// Vaiśeṣika Sūtras — verse-to-concept links overlay.
//
// The raw book files carry translation + commentary but no concept tags,
// which left all 231 sutras and all 12 concepts graph-orphaned (no verse page
// showed concepts, no concept page listed verses, related-verse ranking was empty).
// This id-keyed overlay supplies conceptIds per sutra, merged in
// vaisesika-sutras.ts like the key-points overlay; raw book files are untouched.
// The factory stitches the reverse direction (concept.relatedVerseIds) at runtime.
//
// Derivation, kept here for auditability:
// - PRIMARY: hand-curated topic-to-concept table (67 verse topics reviewed against
//   the sutra translations and commentaries; epistemology topics without a dedicated
//   pramana node sit under guna-karma, since cognition (buddhi) is a guna, and Book 3
//   proof/fallacy topics additionally tag atman, whose existence they establish).
// - UNION: thread step verseIds imply their step conceptId (37 curated refs; 8 verses
//   gain a concept purely from the thread, e.g. manas on 8.1.1/8.1.2/8.1.11).
// - Thin nodes are honest: samavaya has one sutra (7.2.26); padartha and moksha occur
//   chiefly in the programmatic 1.1.4. Enrich only with genuine scholarship, never padding.

export const vaisesikaLinksEn: Record<string, string[]> = {
  // Book 1
  '1.1.1': ['dharma'],
  '1.1.2': ['dharma'],
  '1.1.3': ['dharma'],
  '1.1.4': ['padartha', 'moksha', 'dharma'],
  '1.1.5': ['dravya', 'padartha'],
  '1.1.6': ['guna-karma'],
  '1.1.7': ['guna-karma'],
  '1.1.8': ['dravya', 'guna-karma', 'padartha'],
  '1.1.9': ['dravya', 'guna-karma'],
  '1.1.10': ['dravya', 'guna-karma'],
  '1.1.11': ['dravya', 'guna-karma'],
  '1.1.12': ['dravya', 'guna-karma'],
  '1.1.13': ['dravya', 'guna-karma'],
  '1.1.14': ['dravya', 'guna-karma'],
  '1.1.15': ['dravya'],
  '1.1.16': ['guna-karma'],
  '1.1.17': ['guna-karma'],
  '1.1.18': ['asatkaryavada', 'dravya'],
  '1.1.19': ['asatkaryavada'],
  '1.1.20': ['asatkaryavada'],
  '1.1.21': ['guna-karma', 'asatkaryavada'],
  '1.1.22': ['guna-karma', 'asatkaryavada'],
  '1.1.23': ['guna-karma', 'asatkaryavada'],
  '1.1.24': ['guna-karma', 'asatkaryavada'],
  '1.1.25': ['guna-karma', 'asatkaryavada'],
  '1.1.26': ['guna-karma'],
  '1.1.27': ['dravya', 'asatkaryavada'],
  '1.1.28': ['guna-karma', 'asatkaryavada'],
  '1.1.29': ['guna-karma', 'asatkaryavada'],
  '1.1.30': ['guna-karma'],
  '1.1.31': ['guna-karma'],
  '1.2.1': ['asatkaryavada'],
  '1.2.2': ['asatkaryavada'],
  '1.2.3': ['asatkaryavada', 'samanya-visesa'],
  '1.2.4': ['samanya-visesa'],
  '1.2.5': ['samanya-visesa'],
  '1.2.6': ['samanya-visesa'],
  '1.2.7': ['samanya-visesa', 'padartha'],
  '1.2.8': ['samanya-visesa', 'padartha'],
  '1.2.9': ['samanya-visesa', 'padartha'],
  '1.2.10': ['samanya-visesa', 'padartha'],
  '1.2.11': ['samanya-visesa', 'dravya'],
  '1.2.12': ['samanya-visesa', 'dravya'],
  '1.2.13': ['samanya-visesa', 'guna-karma'],
  '1.2.14': ['samanya-visesa', 'guna-karma'],
  '1.2.15': ['samanya-visesa', 'guna-karma'],
  '1.2.16': ['samanya-visesa', 'guna-karma'],
  '1.2.17': ['samanya-visesa', 'padartha'],
  // Book 3
  '3.1.1': ['atman'],
  '3.1.2': ['atman'],
  '3.1.3': ['atman'],
  '3.1.4': ['atman'],
  '3.1.5': ['atman'],
  '3.1.6': ['atman'],
  '3.1.7': ['atman', 'guna-karma'],
  '3.1.8': ['atman', 'guna-karma'],
  '3.1.9': ['atman', 'guna-karma'],
  '3.1.10': ['atman', 'guna-karma'],
  '3.1.11': ['atman', 'guna-karma'],
  '3.1.12': ['atman', 'guna-karma'],
  '3.1.13': ['atman', 'guna-karma'],
  '3.1.14': ['atman', 'guna-karma'],
  '3.1.15': ['atman', 'guna-karma'],
  '3.1.16': ['atman', 'guna-karma'],
  '3.1.17': ['atman', 'guna-karma'],
  '3.1.18': ['atman', 'guna-karma'],
  '3.1.19': ['atman'],
  '3.1.20': ['atman'],
  '3.2.1': ['manas', 'dravya'],
  '3.2.2': ['manas', 'dravya'],
  '3.2.3': ['manas', 'dravya'],
  '3.2.4': ['atman', 'dravya'],
  '3.2.5': ['atman', 'dravya'],
  '3.2.6': ['atman'],
  '3.2.7': ['atman'],
  '3.2.8': ['atman'],
  '3.2.9': ['atman'],
  '3.2.10': ['atman'],
  '3.2.11': ['atman'],
  '3.2.12': ['atman'],
  '3.2.13': ['atman'],
  '3.2.14': ['atman'],
  '3.2.15': ['atman'],
  '3.2.16': ['atman'],
  '3.2.17': ['atman'],
  '3.2.18': ['atman'],
  '3.2.19': ['atman'],
  '3.2.20': ['atman'],
  '3.2.21': ['atman'],
  // Book 4
  '4.1.1': ['paramanu', 'dravya'],
  '4.1.2': ['paramanu', 'dravya'],
  '4.1.3': ['paramanu', 'dravya'],
  '4.1.4': ['paramanu', 'dravya'],
  '4.1.5': ['paramanu', 'dravya'],
  '4.1.6': ['guna-karma'],
  '4.1.7': ['guna-karma'],
  '4.1.8': ['guna-karma', 'atman'],
  '4.1.9': ['guna-karma', 'atman'],
  '4.1.10': ['guna-karma', 'atman'],
  '4.1.11': ['guna-karma', 'atman'],
  '4.1.12': ['guna-karma', 'atman'],
  '4.1.13': ['guna-karma', 'atman'],
  '4.2.1': ['dravya', 'paramanu'],
  '4.2.2': ['dravya', 'paramanu'],
  '4.2.3': ['dravya', 'paramanu'],
  '4.2.4': ['dravya', 'paramanu'],
  '4.2.5': ['dravya', 'paramanu'],
  '4.2.6': ['dravya', 'paramanu'],
  '4.2.7': ['dravya', 'paramanu'],
  '4.2.8': ['dravya', 'paramanu'],
  '4.2.9': ['dravya', 'paramanu'],
  '4.2.10': ['dravya', 'paramanu'],
  '4.2.11': ['dravya', 'paramanu'],
  '4.2.12': ['dravya', 'paramanu'],
  // Book 5
  '5.1.1': ['guna-karma'],
  '5.1.2': ['guna-karma'],
  '5.1.3': ['guna-karma'],
  '5.1.4': ['guna-karma'],
  '5.1.5': ['guna-karma'],
  '5.1.6': ['guna-karma'],
  '5.1.7': ['guna-karma'],
  '5.1.8': ['guna-karma'],
  '5.1.9': ['guna-karma'],
  '5.1.10': ['guna-karma'],
  '5.1.11': ['guna-karma'],
  '5.1.12': ['guna-karma'],
  '5.1.13': ['guna-karma'],
  '5.1.14': ['guna-karma'],
  '5.1.15': ['guna-karma'],
  '5.1.16': ['guna-karma'],
  '5.1.17': ['guna-karma'],
  '5.1.18': ['guna-karma'],
  '5.2.1': ['guna-karma', 'dravya'],
  '5.2.2': ['guna-karma', 'dravya'],
  '5.2.3': ['guna-karma', 'dravya'],
  '5.2.4': ['guna-karma', 'dravya'],
  '5.2.5': ['guna-karma', 'dravya'],
  '5.2.6': ['guna-karma', 'dravya'],
  '5.2.7': ['guna-karma', 'dravya'],
  '5.2.8': ['guna-karma', 'dravya'],
  '5.2.9': ['guna-karma', 'dravya'],
  '5.2.11': ['guna-karma', 'dravya'],
  '5.2.13': ['guna-karma', 'dravya'],
  '5.2.15': ['guna-karma', 'dravya'],
  '5.2.16': ['guna-karma', 'dravya', 'moksha'],
  '5.2.18': ['guna-karma', 'dravya', 'moksha'],
  '5.2.19': ['guna-karma', 'dravya'],
  '5.2.20': ['guna-karma', 'dravya'],
  '5.2.21': ['guna-karma', 'dravya'],
  // Book 6
  '6.1.1': ['dharma'],
  '6.1.3': ['dharma'],
  '6.1.4': ['dharma'],
  '6.1.6': ['dharma'],
  '6.1.7': ['dharma'],
  '6.2.1': ['dharma'],
  '6.2.2': ['dharma'],
  '6.2.11': ['dharma'],
  '6.2.15': ['dharma'],
  '6.2.17': ['dharma'],
  // Book 7
  '7.1.2': ['guna-karma'],
  '7.1.4': ['guna-karma'],
  '7.1.6': ['guna-karma'],
  '7.1.8': ['paramanu', 'guna-karma'],
  '7.1.20': ['paramanu', 'guna-karma'],
  '7.1.22': ['manas', 'dravya'],
  '7.1.23': ['manas', 'dravya'],
  '7.2.9': ['guna-karma'],
  '7.2.13': ['guna-karma'],
  '7.2.20': ['guna-karma'],
  '7.2.26': ['samavaya'],
  // Book 8
  '8.1.1': ['guna-karma', 'manas'],
  '8.1.2': ['guna-karma', 'manas'],
  '8.1.3': ['guna-karma'],
  '8.1.4': ['guna-karma'],
  '8.1.5': ['guna-karma'],
  '8.1.6': ['guna-karma'],
  '8.1.7': ['guna-karma'],
  '8.1.8': ['guna-karma', 'atman', 'manas'],
  '8.1.9': ['guna-karma', 'atman', 'manas'],
  '8.1.10': ['guna-karma'],
  '8.1.11': ['guna-karma', 'manas'],
  '8.2.1': ['guna-karma'],
  '8.2.2': ['guna-karma'],
  '8.2.3': ['guna-karma'],
  '8.2.4': ['guna-karma'],
  '8.2.5': ['guna-karma'],
  '8.2.6': ['guna-karma'],
  // Book 9
  '9.1.1': ['abhava'],
  '9.1.2': ['abhava'],
  '9.1.3': ['abhava'],
  '9.1.4': ['abhava'],
  '9.1.5': ['abhava'],
  '9.1.6': ['abhava'],
  '9.1.7': ['abhava'],
  '9.1.8': ['abhava'],
  '9.1.9': ['abhava'],
  '9.1.10': ['abhava'],
  '9.1.11': ['atman', 'dravya', 'manas'],
  '9.1.12': ['atman', 'dravya'],
  '9.1.13': ['atman', 'dravya'],
  '9.1.14': ['atman', 'dravya'],
  '9.1.15': ['atman', 'dravya'],
  '9.2.1': ['guna-karma'],
  '9.2.2': ['guna-karma'],
  '9.2.3': ['guna-karma'],
  '9.2.4': ['guna-karma'],
  '9.2.5': ['guna-karma'],
  '9.2.6': ['guna-karma'],
  '9.2.7': ['guna-karma'],
  '9.2.8': ['guna-karma'],
  '9.2.9': ['guna-karma'],
  '9.2.10': ['moksha', 'guna-karma'],
  '9.2.11': ['moksha', 'guna-karma'],
  '9.2.12': ['moksha', 'guna-karma'],
  '9.2.13': ['moksha', 'guna-karma'],
  // Book 10
  '10.1.1': ['guna-karma'],
  '10.1.2': ['guna-karma'],
  '10.1.3': ['guna-karma'],
  '10.1.4': ['guna-karma'],
  '10.1.5': ['guna-karma'],
  '10.1.6': ['guna-karma'],
  '10.1.7': ['guna-karma'],
  '10.2.1': ['asatkaryavada'],
  '10.2.2': ['asatkaryavada'],
  '10.2.3': ['asatkaryavada'],
  '10.2.4': ['asatkaryavada'],
  '10.2.5': ['asatkaryavada'],
  '10.2.6': ['asatkaryavada'],
  '10.2.7': ['asatkaryavada'],
  '10.2.8': ['dharma'],
  '10.2.9': ['dharma'],
};
