export const missingConcepts = [
  {
    id: "atma-pariksha",
    sanskrit: "आत्मपरीक्षा",
    iast: "ātma-parīkṣā",
    english: "Examination of the Soul",
    category: "Metaphysics",
    definition: "The critical investigation into the existence, nature, and eternal status of the self (ātman) as distinct from the body, senses, and mind.",
    significance: "Establishes that the self is the permanent substratum of consciousness, memory, and agency, refuting materialist and Buddhist views of no-self.",
    relatedConcepts: ["atman", "buddhi", "manas"]
  },
  {
    id: "atma-nityatva",
    sanskrit: "आत्मनित्यत्व",
    iast: "ātma-nityatva",
    english: "Eternality of the Soul",
    category: "Metaphysics",
    definition: "The doctrine that the soul (ātman) is uncreated and indestructible, existing continuously across different bodies through transmigration.",
    significance: "A crucial tenet for justifying the laws of karma and moral responsibility; if the soul were destroyed at death, actions would bear no fruit.",
    relatedConcepts: ["atman", "pretyabhava", "karma"]
  },
  {
    id: "prapyakaritva",
    sanskrit: "प्राप्यकारित्व",
    iast: "prāpyakāritva",
    english: "Action by Direct Contact",
    category: "Epistemology",
    definition: "The principle that senses operate by physically reaching or coming into direct contact with their objects (e.g., visual rays traveling to the object).",
    significance: "Explains the mechanism of perception (pratyaksha) and why there are spatial and temporal limits to what can be perceived.",
    relatedConcepts: ["pratyaksha", "sannikarsha", "sharira-indriya-bhuta"]
  },
  {
    id: "buddhi-pariksha",
    sanskrit: "बुद्धिपरीक्षा",
    iast: "buddhi-parīkṣā",
    english: "Examination of Intellect",
    category: "Cognition",
    definition: "The critical investigation of cognition or intellect (buddhi), establishing it as a temporary quality of the soul rather than an eternal substance.",
    significance: "Refutes the Sāmkhya view that intellect is an eternal, independent cosmic principle, reinforcing Nyāya's substance-attribute ontology.",
    relatedConcepts: ["buddhi", "jnana", "atman"]
  },
  {
    id: "kshanabhangavada",
    sanskrit: "क्षणभङ्गवाद",
    iast: "kṣaṇabhaṅgavāda",
    english: "Theory of Momentariness",
    category: "Dialectics",
    definition: "The Buddhist doctrine that all entities exist only for a single instant before ceasing to be, completely replaced by a new entity in the next instant.",
    significance: "Nyāya fiercely refutes this theory to defend the enduring nature of substances (like the soul and material objects) necessary for memory and karma.",
    relatedConcepts: ["vada", "atman", "purvapaksha"]
  },
  {
    id: "adrshta",
    sanskrit: "अदृष्ट",
    iast: "adṛṣṭa",
    english: "The Unseen Force",
    category: "Metaphysics",
    definition: "The invisible moral force or latent potential generated by past actions (karma) that determines future experiences and the initial formation of the universe.",
    significance: "Provides the mechanical link between moral actions and their eventual, often delayed, physical or psychological consequences.",
    relatedConcepts: ["karma", "phala", "apūrva", "pretyabhava"]
  },
  {
    id: "pravrtti",
    sanskrit: "प्रवृत्ति",
    iast: "pravṛtti",
    english: "Activity / Volition",
    category: "Metaphysics",
    definition: "The operation of speech, mind, and body, driven by desire or aversion, which initiates the cycle of karma and rebirth.",
    significance: "Activity is the direct cause of merit and demerit. Stopping ego-driven activity is a prerequisite for liberation.",
    relatedConcepts: ["dosha", "karma", "pravritti-dosha-phala"]
  },
  {
    id: "dosha",
    sanskrit: "दोष",
    iast: "doṣa",
    english: "Psychological Defects",
    category: "Cognition",
    definition: "The underlying psychological flaws—attachment (rāga), aversion (dveṣa), and delusion (moha)—that compel a person to act.",
    significance: "They are the root cause of worldly activity and suffering. Liberation (apavarga) is attained only upon their complete eradication.",
    relatedConcepts: ["raga", "dvesha", "moha", "pravrtti"]
  },
  {
    id: "raga",
    sanskrit: "राग",
    iast: "rāga",
    english: "Attachment / Desire",
    category: "Cognition",
    definition: "The strong attraction or desire for objects that yield pleasure, leading to continued bondage and repeated activity.",
    significance: "One of the three primary doshas; it binds the soul to the cycle of samsara by generating future-oriented desires.",
    relatedConcepts: ["dosha", "pravrtti"]
  },
  {
    id: "dvesha",
    sanskrit: "द्वेष",
    iast: "dveṣa",
    english: "Aversion / Hatred",
    category: "Cognition",
    definition: "The strong repulsion or hatred toward objects or situations that yield pain, driving aggressive or avoidance behaviors.",
    significance: "One of the three primary doshas; equally as binding as attachment, as it forces the soul into reactive karma.",
    relatedConcepts: ["dosha", "pravrtti"]
  },
  {
    id: "moha",
    sanskrit: "मोह",
    iast: "moha",
    english: "Delusion / Ignorance",
    category: "Cognition",
    definition: "The fundamental ignorance or misconception of reality, primarily mistaking the non-self (body/mind) for the self.",
    significance: "The root of all other defects (rāga and dveṣa). Eradicating moha through true knowledge (tattvajñāna) is the ultimate goal of Nyāya.",
    relatedConcepts: ["dosha", "tatva-jnana", "apavarga"]
  },
  {
    id: "pretyabhava",
    sanskrit: "प्रेत्यभाव",
    iast: "pretyabhāva",
    english: "Transmigration / Rebirth",
    category: "Metaphysics",
    definition: "The cycle of dying and being born again in a new physical body, driven by the accumulated merit and demerit of past actions.",
    significance: "Explains the continuity of existence and the disparities in human birth; it is the fundamental problem that Nyāya seeks to escape.",
    relatedConcepts: ["atman", "karma", "phala"]
  },
  {
    id: "karma",
    sanskrit: "कर्म",
    iast: "karma",
    english: "Action / Moral Causation",
    category: "Metaphysics",
    definition: "Any physical, verbal, or mental action that generates an unseen moral consequence (adṛṣṭa) affecting the agent's future.",
    significance: "The mechanism of cosmic justice in Nyāya, ensuring that all experiences of pleasure and pain are earned.",
    relatedConcepts: ["pravrtti", "adrshta", "phala"]
  },
  {
    id: "shunyavada",
    sanskrit: "शून्यवाद",
    iast: "śūnyavāda",
    english: "Doctrine of Emptiness",
    category: "Dialectics",
    definition: "The Buddhist Madhyamaka theory that all things are fundamentally empty (śūnya) of intrinsic nature or independent existence.",
    significance: "Nyāya opposes this by arguing for the absolute reality of objects, categories, and the self, grounded in direct perception and logic.",
    relatedConcepts: ["purvapaksha", "kshanabhangavada", "prameya"]
  },
  {
    id: "ishvara",
    sanskrit: "ईश्वर",
    iast: "īśvara",
    english: "God / Supreme Lord",
    category: "Metaphysics",
    definition: "The supreme, eternal soul who creates, sustains, and destroys the universe, and who dispenses the fruits of karma to individual souls.",
    significance: "While early Nyāya focused on logic, later Nyāya developed sophisticated cosmological arguments to prove the existence of an intelligent creator.",
    relatedConcepts: ["atman", "adrshta", "phala"]
  },
  {
    id: "yadrccha-vada",
    sanskrit: "यदृच्छावाद",
    iast: "yadṛcchā-vāda",
    english: "Doctrine of Chance",
    category: "Dialectics",
    definition: "The materialist view that the universe and living beings emerge purely by random chance without any intelligent cause or moral design.",
    significance: "Nyāya refutes this to defend the necessity of karma and Īśvara, arguing that complex order requires an intelligent agent.",
    relatedConcepts: ["purvapaksha", "ishvara"]
  },
  {
    id: "sarva-anityatva",
    sanskrit: "सर्वानित्यत्व",
    iast: "sarva-anityatva",
    english: "Doctrine of Universal Impermanence",
    category: "Dialectics",
    definition: "The assertion that absolutely everything in existence is temporary and subject to destruction.",
    significance: "Nyāya refutes this by pointing out that certain things, like atoms, space, and the soul, must be eternal to serve as the foundation for the temporary.",
    relatedConcepts: ["nitya", "anitya"]
  },
  {
    id: "nitya",
    sanskrit: "नित्य",
    iast: "nitya",
    english: "Eternal",
    category: "Metaphysics",
    definition: "That which is uncreated, indestructible, and exists forever without modification (e.g., souls, atoms, ether).",
    significance: "Provides the stable ontological ground in Nyāya-Vaiśeṣika upon which the transient universe is built.",
    relatedConcepts: ["anitya", "atman", "paramanu"]
  },
  {
    id: "anitya",
    sanskrit: "अनित्य",
    iast: "anitya",
    english: "Impermanent",
    category: "Metaphysics",
    definition: "That which is produced and eventually destroyed; any composite object made of parts.",
    significance: "Distinguishing between the eternal and impermanent is vital for overcoming attachment to worldly objects.",
    relatedConcepts: ["nitya", "kshanabhangavada"]
  },
  {
    id: "sarva-nityatva",
    sanskrit: "सर्वनित्यत्व",
    iast: "sarva-nityatva",
    english: "Doctrine of Universal Eternality",
    category: "Dialectics",
    definition: "The view that everything that exists is permanent, and change is merely an illusion or a shift in manifestation (often associated with strict Advaita or Sāmkhya).",
    significance: "Nyāya rejects this, affirming the reality of change, creation, and destruction in the physical world.",
    relatedConcepts: ["nitya", "sarva-anityatva"]
  },
  {
    id: "sarva-prthaktva",
    sanskrit: "सर्वपृथक्त्व",
    iast: "sarva-pṛthaktva",
    english: "Doctrine of Universal Separateness",
    category: "Dialectics",
    definition: "The extreme pluralist view that every entity is entirely isolated and distinct, denying any real unifying categories or universals.",
    significance: "Nyāya argues against this to defend the reality of universals (sāmānya) and inherence (samavāya), which link diverse objects.",
    relatedConcepts: ["prameya", "shodasha-padartha"]
  },
  {
    id: "sarva-abhava",
    sanskrit: "सर्वाभाव",
    iast: "sarva-abhāva",
    english: "Doctrine of Universal Non-existence",
    category: "Dialectics",
    definition: "The extreme nihilist view that nothing truly exists at all.",
    significance: "Nyāya dismisses this as self-contradictory, as the very act of asserting non-existence requires the existence of the assertor and the assertion.",
    relatedConcepts: ["shunyavada", "pramana"]
  },
  {
    id: "phala",
    sanskrit: "फल",
    iast: "phala",
    english: "Fruit / Result",
    category: "Metaphysics",
    definition: "The experiential result (pleasure or pain) of one's past actions, representing the fruition of karma.",
    significance: "It is the ultimate driver of the cycle of rebirth. Understanding that all worldly 'fruits' are ultimately tied to suffering motivates the pursuit of liberation.",
    relatedConcepts: ["karma", "adrshta", "duhkha"]
  },
  {
    id: "apūrva",
    sanskrit: "अपूर्व",
    iast: "apūrva",
    english: "The Unprecedented Force",
    category: "Hermeneutics",
    definition: "A concept primarily from Mīmāṃsā, representing the unseen intermediary force generated by a ritual that brings about a future result.",
    significance: "In Nyāya, it is often synthesized with adṛṣṭa to explain how fleeting actions can cause effects long after the action has ceased.",
    relatedConcepts: ["adrshta", "karma"]
  },
  {
    id: "duhkha",
    sanskrit: "दुःख",
    iast: "duḥkha",
    english: "Suffering / Pain",
    category: "Metaphysics",
    definition: "The fundamental nature of worldly existence; the physical and psychological pain inevitably linked to birth and attachment.",
    significance: "The starting point of the Nyāya path. The realization that even worldly pleasure is tainted by pain drives the seeker toward ultimate release.",
    relatedConcepts: ["duhkha-chain-nyaya", "apavarga"]
  },
  {
    id: "moksha",
    sanskrit: "मोक्ष",
    iast: "mokṣa",
    english: "Liberation",
    category: "Metaphysics",
    definition: "The ultimate release from the cycle of rebirth and suffering, synonymous with Apavarga.",
    significance: "The highest goal of human life in Nyāya, achieved when the soul is completely freed from all qualities, including pain, pleasure, and cognition.",
    relatedConcepts: ["apavarga", "tatva-jnana"]
  },
  {
    id: "tatva-jnana",
    sanskrit: "तत्त्वज्ञान",
    iast: "tattva-jñāna",
    english: "Knowledge of Truth",
    category: "Epistemology",
    definition: "The accurate, direct realization of the true nature of the sixteen categories (padārthas) and the distinction between the soul and non-soul.",
    significance: "The sole mechanism that destroys delusion (moha), subsequently eliminating faults, activity, rebirth, and suffering.",
    relatedConcepts: ["apavarga", "duhkha-chain-nyaya", "moha"]
  },
  {
    id: "ahankara",
    sanskrit: "अहङ्कार",
    iast: "ahaṅkāra",
    english: "Ego / I-maker",
    category: "Cognition",
    definition: "The false identification of the true self (ātman) with the physical body, mind, or senses.",
    significance: "A primary manifestation of delusion (moha) that binds the soul to samsara.",
    relatedConcepts: ["moha", "atman"]
  },
  {
    id: "sankalpa",
    sanskrit: "सङ्कल्प",
    iast: "saṅkalpa",
    english: "Volition / Intention",
    category: "Cognition",
    definition: "The mental resolve or intentionality that precedes physical or verbal action.",
    significance: "It is the psychological origin of karma; purifying intentions is necessary to stop the generation of adṛṣṭa.",
    relatedConcepts: ["pravrtti", "manas"]
  },
  {
    id: "paramanu",
    sanskrit: "परमाणु",
    iast: "paramāṇu",
    english: "Atom",
    category: "Metaphysics",
    definition: "The eternal, indivisible, infinitesimal building block of the physical universe in Nyāya-Vaiśeṣika ontology.",
    significance: "Explains the composition and eventual destruction of all material objects without violating the principle that something cannot come from nothing.",
    relatedConcepts: ["nitya", "anitya"]
  },
  {
    id: "samadhi",
    sanskrit: "समाधि",
    iast: "samādhi",
    english: "Meditative Absorption",
    category: "Cognition",
    definition: "The state of deep, undisturbed concentration on the true nature of the soul.",
    significance: "Adopted from Yoga, Nyāya prescribes it as the practical method to internalize philosophical truth and achieve direct realization (tattvajñāna).",
    relatedConcepts: ["yoga", "abhyasa"]
  },
  {
    id: "abhyasa",
    sanskrit: "अभ्यास",
    iast: "abhyāsa",
    english: "Practice / Repetition",
    category: "Cognition",
    definition: "The continuous, disciplined repetition of philosophical reflection and meditation.",
    significance: "Necessary to overcome ingrained habits of false identification and stabilize true knowledge.",
    relatedConcepts: ["samadhi", "yoga"]
  },
  {
    id: "yoga",
    sanskrit: "योग",
    iast: "yoga",
    english: "Spiritual Discipline",
    category: "Cognition",
    definition: "The practical methods of mental and physical control used to focus the mind.",
    significance: "Nyāya explicitly endorses Yogic practices as the necessary complement to logical analysis for achieving liberation.",
    relatedConcepts: ["samadhi", "yama", "niyama"]
  },
  {
    id: "yama",
    sanskrit: "यम",
    iast: "yama",
    english: "Moral Restraints",
    category: "Cognition",
    definition: "The foundational ethical disciplines (like non-violence and truthfulness) required to purify the mind.",
    significance: "A prerequisite for effective meditation and the cessation of negative karma.",
    relatedConcepts: ["yoga", "niyama"]
  },
  {
    id: "niyama",
    sanskrit: "नियम",
    iast: "niyama",
    english: "Positive Observances",
    category: "Cognition",
    definition: "The constructive personal disciplines (like study and purity) that support spiritual growth.",
    significance: "Works alongside Yama to create the mental environment necessary for Tattvajñāna.",
    relatedConcepts: ["yoga", "yama"]
  },
  {
    id: "samvada",
    sanskrit: "संवाद",
    iast: "saṃvāda",
    english: "Constructive Dialogue",
    category: "Dialectics",
    definition: "A sincere discussion with teachers or peers aimed purely at discovering the truth, without the desire to defeat the other.",
    significance: "The preferred mode of philosophical inquiry (Vāda), essential for clarifying doubts and solidifying knowledge.",
    relatedConcepts: ["vada", "tarka"]
  },
  {
    id: "jalpa",
    sanskrit: "जल्प",
    iast: "jalpa",
    english: "Wrangling / Competitive Debate",
    category: "Dialectics",
    definition: "A debate where the primary goal is victory over the opponent rather than the discovery of truth, using any logical means necessary.",
    significance: "While risky, Nyāya permits it for defending the truth against hostile opponents who refuse constructive dialogue.",
    relatedConcepts: ["vada", "vitanda", "chhala"]
  },
  {
    id: "vitanda",
    sanskrit: "वितण्डा",
    iast: "vitaṇḍā",
    english: "Destructive Debate",
    category: "Dialectics",
    definition: "A form of debate where the participant only attacks the opponent's thesis without establishing any thesis of their own.",
    significance: "Viewed as the lowest form of debate, often associated with skeptics or nihilists. Nyāya studies it primarily to know how to counter it.",
    relatedConcepts: ["vada", "jalpa", "shunyavada"]
  }
];
