// Bhagavad Gītā with Sarvatobhadra (Rājānaka Rāmakantha, KSTS LXIV, 1943) — English.
// Devanagari follows the Rāmakantha recension (pāṭhāntara tables pp.421–430); translations/commentaries original to this project.
export const gitaEnPart3: any[] = [
  {
    "id": "7.1",
    "number": "7.1",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Listen how, mind fixed on me and practising yoga taking refuge in me, you shall know me fully without doubt.",
    "commentary": "Plain: Krishna promises complete doubt-free knowledge through attachment and refuge. Ramakantha: refuge is not abandoning action but yoking jnana with karma, both resting in Shiva-self.",
    "keyPoints": ["mad-ashraya as samuccaya", "complete knowing is pratyabhijna"]
  },
  {
    "id": "7.2",
    "number": "7.2",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I shall teach you knowledge together with realisation in full, knowing which nothing further remains to be known.",
    "commentary": "Plain: jnana plus vijnana exhausts the knowable. Ramakantha: vijnana is applied living-through in action, hence jnana alone is incomplete without karma.",
    "keyPoints": ["jnana+vijnana pair", "nothing outside Shiva-knowing"]
  },
  {
    "id": "7.3",
    "number": "7.3",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Among thousands one strives for perfection, and among strivers hardly one knows me in truth.",
    "commentary": "Plain: true knowing is rare. Ramakantha: rarity is due to clinging to intellect or rites alone, not their union in awareness.",
    "keyPoints": ["rarity of samuccaya", "tattvatas as Shiva-recognition"]
  },
  {
    "id": "7.4",
    "number": "7.4",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Earth, water, fire, air, ether, mind, intellect and ego are my eightfold divided nature.",
    "commentary": "Plain: lower prakriti enumerated. Ramakantha: these eight are Shiva's own powers contracted, not alien matter.",
    "keyPoints": ["apara-prakriti as Shiva's contraction", "8-fold"]
  },
  {
    "id": "7.5",
    "number": "7.5",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Beyond this lower nature know my higher nature as the living self by which the world is upheld.",
    "commentary": "Plain: jiva is higher prakriti sustaining cosmos. Ramakantha: jiva is Shiva as experiencer, holding lower through spanda.",
    "keyPoints": ["para-prakriti = jiva", "sustainer not renouncer"]
  },
  {
    "id": "7.6",
    "number": "7.6",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Know all beings spring from these two natures, and I am the origin and dissolution of the whole world.",
    "commentary": "Plain: Krishna is source and end of all. Ramakantha: srishti-samhara are Shiva's projection-withdrawal, known while acting.",
    "keyPoints": ["prabhava-pralaya in one ground", "action as emission"]
  },
  {
    "id": "7.7",
    "number": "7.7",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Nothing higher than me exists, and all this is strung on me like gems on a thread.",
    "commentary": "Plain: Krishna is supreme thread of unity. Ramakantha: threading means karma-world rests on jnana-self without breaking continuity.",
    "keyPoints": ["supremacy without exclusion", "world strung on witness"]
  },
  {
    "id": "7.8",
    "number": "7.8",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I am taste in waters, light in sun and moon, Om in Vedas, sound in ether, manliness in men.",
    "commentary": "Plain: divine essence in sensible qualities. Ramakantha: tasting etc. are modes of perceiving Shiva in activity.",
    "keyPoints": ["essence in sense", "sacramental perception"]
  },
  {
    "id": "7.9",
    "number": "7.9",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I am pure fragrance in earth, brilliance in fire, life in all beings, austerity in ascetics.",
    "commentary": "Plain: sustaining virtue in elements and effort. Ramakantha: tapas includes dutiful karma illumined by knowledge.",
    "keyPoints": ["purity as Shaiva vitality", "tapas = disciplined action"]
  },
  {
    "id": "7.10",
    "number": "7.10",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Know me as the eternal seed of all beings, the intellect of the intelligent and splendour of the splendid.",
    "commentary": "Plain: Krishna is seed-capacity and luminous power. Ramakantha: seed is undivided I-consciousness sprouting as jnana-karma.",
    "keyPoints": ["eternal bija", "buddhi-tejas as Shiva-glow"]
  },
  {
    "id": "7.11",
    "number": "7.11",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I am strength of the strong free from desire and passion, and desire in beings not opposed to dharma.",
    "commentary": "Plain: sanctified power and lawful desire are divine. Ramakantha: desire yoked to dharma exemplifies karma purified by jnana.",
    "keyPoints": ["desireless strength", "dharmic kama allowed"]
  },
  {
    "id": "7.12",
    "number": "7.12",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "All sattvic, rajasic and tamasic states come from me, yet I am not in them, they are in me.",
    "commentary": "Plain: gunas derive from Lord but do not bind him. Ramakantha: Shiva freely assumes gunas without being reduced to them.",
    "keyPoints": ["guna-source yet transcendent", "freedom in manifestation"]
  },
  {
    "id": "7.13",
    "number": "7.13",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Deluded by these three guna-states, the world fails to know me as higher and imperishable beyond them.",
    "commentary": "Plain: guna-delusion hides the imperishable. Ramakantha: delusion lifts only when knowing and doing are held together in witness.",
    "keyPoints": ["moha by gunas", "avyaya beyond"]
  },
  {
    "id": "7.14",
    "number": "7.14",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "This divine guna-made maya of mine is hard to cross, but those who surrender to me cross it.",
    "commentary": "Plain: surrender crosses maya. Ramakantha: explicitly via Spanda Karika 46 — maya is Shiva's own freedom-power, crossed by recognising her as one's own spanda while acting, not by fleeing action.",
    "keyPoints": ["maya as svatantrya", "prapatti + spanda recognition"]
  },
  {
    "id": "7.15",
    "number": "7.15",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Evil-doing fools, lowest men robbed of knowledge by maya, resorting to demonic temper, do not surrender to me.",
    "commentary": "Plain: degraded dispositions block surrender. Ramakantha: loss of knowledge comes from divorcing karma from awareness, falling into inertia.",
    "keyPoints": ["apahrita-jnana", "asura as dissociation"]
  },
  {
    "id": "7.16",
    "number": "7.16",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Four kinds of virtuous people worship me: the distressed, the inquirer, the wealth-seeker, and the knower.",
    "commentary": "Plain: four motives for devotion. Ramakantha: all four are graded approaches to same samuccaya, action gradually ripening into knowledge.",
    "keyPoints": ["four adhikaras", "devotion ripens"]
  },
  {
    "id": "7.17",
    "number": "7.17",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Among them the ever-yoked knower with single devotion excels, for I am dear to him and he to me.",
    "commentary": "Plain: exclusive knower-devotee is highest. Ramakantha: ekabhakti is uninterrupted recognition sustaining all acts.",
    "keyPoints": ["nitya-yukta", "mutual love as recognition"]
  },
  {
    "id": "7.18",
    "number": "7.18",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "All these are noble, but the knower is my very self, abiding yoked to me as the supreme goal.",
    "commentary": "Plain: jnani identified with Lord. Ramakantha: identity is pratyabhijna — self recognised as Shiva while still acting.",
    "keyPoints": ["jnani = atma", "supreme gati in life"]
  },
  {
    "id": "7.19",
    "number": "7.19",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "After many births the knower surrenders to me, seeing Vasudeva as all; such a great soul is very rare.",
    "commentary": "Plain: ripened vision sees all as Vasudeva. Ramakantha: sarvam as Shiva's body, attained through combined path over births.",
    "keyPoints": ["Vasudeva-sarvam", "ripened samuccaya"]
  },
  {
    "id": "7.20",
    "number": "7.20",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Robbed of discernment by various desires, men resort to other deities following particular rites impelled by nature.",
    "commentary": "Plain: fragmented desires lead to lesser gods. Ramakantha: fragmentation is worship without unifying Self-knowledge.",
    "keyPoints": ["hrta-jnana", "partial ends"]
  },
  {
    "id": "7.21",
    "number": "7.21",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Whatever form a devotee seeks to worship with faith, I make that faith steady.",
    "commentary": "Plain: Lord stabilizes all sincere faith. Ramakantha: steadiness comes from Shiva accommodating diverse karmic dispositions.",
    "keyPoints": ["faith stabilized", "inclusivity"]
  },
  {
    "id": "7.22",
    "number": "7.22",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Yoked by that faith he pursues that worship and obtains his desires, ordained by me.",
    "commentary": "Plain: fruits come through divine ordination. Ramakantha: even limited karma bears fruit when grounded in universal consciousness.",
    "keyPoints": ["ordained fruits", "limited yet real"]
  },
  {
    "id": "7.23",
    "number": "7.23",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Finite is the fruit for those of little wit; god-worshippers reach gods, my devotees reach me.",
    "commentary": "Plain: exclusive devotion gives imperishable果. Ramakantha: finite ends follow from dividing knowledge from All-Self; wholeness yields Shiva.",
    "keyPoints": ["anta-vat vs imperishable", "wholeness of end"]
  },
  {
    "id": "7.24",
    "number": "7.24",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "The witless think me, the unmanifest, as become manifest, not knowing my higher imperishable unsurpassed state.",
    "commentary": "Plain: mistaking incarnation for limitation. Ramakantha: avyaya para-bhava is Shiva ever unmanifest even while manifest in act.",
    "keyPoints": ["avyakta in vyakti", "higher bhava"]
  },
  {
    "id": "7.25",
    "number": "7.25",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I am not manifest to all, veiled by yoga-maya; the deluded world knows not my birthless imperishable self.",
    "commentary": "Plain: maya-veil hides birthless Lord. Ramakantha: veil is playful self-concealment lifted by combined knowing-doing.",
    "keyPoints": ["yoga-maya veil", "aja-avyaya"]
  },
  {
    "id": "7.26",
    "number": "7.26",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I know past, present and future beings, but none knows me.",
    "commentary": "Plain: omniscience yet hiddenness. Ramakantha: trikala-knowing is Shiva's citi, unknown until self-recognised.",
    "keyPoints": ["omniscience", "hidden subject"]
  },
  {
    "id": "7.27",
    "number": "7.27",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "By delusion of opposites born of desire and hatred, all beings fall into bewilderment at birth.",
    "commentary": "Plain: dvandva-moha from raga-dvesha. Ramakantha: opposites bind only when action lacks witnessing knowledge.",
    "keyPoints": ["dvandva-moha", "birth-bewilderment"]
  },
  {
    "id": "7.28",
    "number": "7.28",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Those whose sin is ended through virtuous deeds, freed from opposite-delusion, worship me with firm vow.",
    "commentary": "Plain: punya-karma purifies for firm devotion. Ramakantha: textbook samuccaya — pure karma ends papa, freeing jnana.",
    "keyPoints": ["punya-karman purifies", ""]
  },
  {
    "id": "7.29",
    "number": "7.29",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Those who strive for freedom from age and death taking refuge in me know Brahman entire, self-nature and all action.",
    "commentary": "Plain: refuge yields integral knowledge. Ramakantha: akhila-karma known as Brahman — action itself is Brahman-form.",
    "keyPoints": ["refuge-striving", "karma as Brahman"]
  },
  {
    "id": "7.30",
    "number": "7.30",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Those who know me as governing beings, gods and sacrifices know me even at death with yoked mind.",
    "commentary": "Plain: integral theism persists at death. Ramakantha: sacrifice-inclusiveness proves knowledge must accompany rite to the end.",
    "keyPoints": ["adhibhuta-adhidaiva-adhiyajna", "death-yoga"]
  },
  {
    "id": "8.1",
    "number": "8.1",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "What is Brahman, self-nature, action, the ground of beings and of gods?",
    "commentary": "Plain: Arjuna asks seven terms. Ramakantha: questions seek map linking metaphysics to practice.",
    "keyPoints": ["seven questions", "bridge theory-praxis"]
  },
  {
    "id": "8.2",
    "number": "8.2",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Who is sacrifice-lord here in this body, and how are you known at death by self-controlled men?",
    "commentary": "Plain: asks immanent sacrifice and death-knowing. Ramakantha: deha as sacrificial ground where jnana-karma meet.",
    "keyPoints": ["adhiyajna in deha", "death-knowing"]
  },
  {
    "id": "8.3",
    "number": "8.3",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "The imperishable supreme is Brahman, own-being is adhyatma, emission causing birth of beings is action.",
    "commentary": "Plain: definitions of three. Ramakantha: visarga-karma is Shiva's forth-emission, not bondage per se.",
    "keyPoints": ["aksara", "svabhava", "visarga as karma"]
  },
  {
    "id": "8.4",
    "number": "8.4",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "The perishable existence is elemental ground, spirit is divine ground, and I as sacrifice-lord am here in the body.",
    "commentary": "Plain: immanent triad plus indwelling Lord. Ramakantha: deha contains sacrificer and witness together — Shaiva immanence.",
    "keyPoints": ["kshara-purusha", "aham in deha"]
  },
  {
    "id": "8.5",
    "number": "8.5",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Who at death, remembering me alone, leaves the body attains my state without doubt.",
    "commentary": "Plain: final remembrance decides state. Ramakantha: remembrance is fruition of lifelong samuccaya, not momentary trick.",
    "keyPoints": ["anta-smarana", "lifelong ripening"]
  },
  {
    "id": "8.6",
    "number": "8.6",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Whatever state one remembers leaving the body, that alone one attains, ever steeped in that state.",
    "commentary": "Plain: habitual contemplation shapes transit. Ramakantha: bhavita habit is formed by united knowing-doing.",
    "keyPoints": ["habit shapes transit", "continual bhava"]
  },
  {
    "id": "8.7",
    "number": "8.7",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Therefore at all times remember me and fight, with mind-intellect surrendered to me you shall reach me.",
    "commentary": "Plain: classic karma-yoga injunction. Ramakantha: proof-text for samuccaya — smara plus yudhya together.",
    "keyPoints": ["anusmara + yudhya", "arpita-mano-buddhi"]
  },
  {
    "id": "8.8",
    "number": "8.8",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "With practice-yoked unflickering mind, contemplating, one reaches the supreme divine Person.",
    "commentary": "Plain: abhyasa fixes mind on Supreme. Ramakantha: abhyasa is repeated recognition amidst acts.",
    "keyPoints": ["abhyasa-yoga", "ananya-gami mind"]
  },
  {
    "id": "8.9",
    "number": "8.9",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Who contemplates the seer, ancient, ruler, subtler than subtle, supporter of all, unthinkable-form, sun-hued beyond darkness.",
    "commentary": "Plain: cosmic attributes for meditation. Ramakantha: these are Shiva's pervasive light-attributes, darkness-transcending.",
    "keyPoints": ["kavi-purana", "light beyond tamas"]
  },
  {
    "id": "8.10",
    "number": "8.10",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "At death with steady mind, devotion and yoga-power, fixing breath between brows, one reaches that supreme Person.",
    "commentary": "Plain: death-yoga technique. Ramakantha: technique works because prana-mind are Shiva-energies gathered by devotion-action.",
    "keyPoints": ["bhrumadhya", "yoga-bala"]
  },
  {
    "id": "8.11",
    "number": "8.11",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "That imperishable which Veda-knowers declare, passion-free ascetics enter, seeking which they live chastely — that goal I shall briefly tell.",
    "commentary": "Plain: introduces aksara-goal. Ramakantha: aksara sought through disciplined karma as well as detachment.",
    "keyPoints": ["aksara goal", "brahmacharya as discipline"]
  },
  {
    "id": "8.12",
    "number": "8.12",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Restraining all gates, confining mind in heart, fixing life-breath in head, established in yoga-concentration.",
    "commentary": "Plain: interior gathering. Ramakantha: sense-restraint is karma restrained by knowledge, not abandoned.",
    "keyPoints": ["dvara-samyama", "dharana"]
  },
  {
    "id": "8.13",
    "number": "8.13",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Uttering Om, the single-syllable Brahman, remembering me, departing the body, one reaches the supreme goal.",
    "commentary": "Plain: Om plus remembrance at exit. Ramakantha: vac-action and smriti-knowledge fused in one utterance.",
    "keyPoints": ["Om", "remembrance-utterance union"]
  },
  {
    "id": "8.14",
    "number": "8.14",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Who remembers me constantly with undivided mind, to that ever-yoked yogi I am easily attained.",
    "commentary": "Plain: ease through constancy. Ramakantha: satata-smriti sustained amidst duties proves samuccaya's continuity.",
    "keyPoints": ["ananya-cetas", "sulabha"]
  },
  {
    "id": "8.15",
    "number": "8.15",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Reaching me, great souls do not return to rebirth, abode of sorrow impermanent, having attained supreme perfection.",
    "commentary": "Plain: no return after attainment. Ramakantha: non-return is freedom even while living-acting, jivanmukti.",
    "keyPoints": ["no punarjanma", "samsiddhi"]
  },
  {
    "id": "8.16",
    "number": "8.16",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Worlds up to Brahma's realm return again, but reaching me there is no rebirth.",
    "commentary": "Plain: cosmic hierarchy vs finality. Ramakantha: even high karmic heavens return unless illumined by Shiva-knowledge.",
    "keyPoints": ["abrahmabhuvana", "finality in me"]
  },
  {
    "id": "8.17",
    "number": "8.17",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Those who know a day of Brahma lasts a thousand ages and night likewise know day and night.",
    "commentary": "Plain: cosmic time scale. Ramakantha: time-cycles are Shiva's pulsation writ large.",
    "keyPoints": ["Brahma day-night", "cosmic rhythm"]
  },
  {
    "id": "8.18",
    "number": "8.18",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "From the unmanifest all manifest spring at day's advent, and dissolve into the same unmanifest at night.",
    "commentary": "Plain: cyclic emission-dissolution. Ramakantha: avyakta is Shiva's withdrawal state, not void.",
    "keyPoints": ["cyclic vyakta", "avyakta ground"]
  },
  {
    "id": "8.19",
    "number": "8.19",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "This same host of beings helplessly recurs, dissolving at night, emerging at day.",
    "commentary": "Plain: helpless repetition under prakriti. Ramakantha: helplessness ends when emission is recognised as self's freedom.",
    "keyPoints": ["bhutagrama", "avasha repetition"]
  },
  {
    "id": "8.20",
    "number": "8.20",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Rāmakantha pāṭha: Rāmakantha: vyaktāvyaktaḥ sanātanaḥ."}],
    "translation": "Beyond that is another eternal state, manifest-unmanifest, imperishable amid perishing beings.",
    "commentary": "Plain: higher imperishable beyond cycles. Ramakantha variant stresses one reality as both vyakta and avyakta — Shiva as eternal manifest-unmanifest continuum.",
    "keyPoints": ["vyaktavyaktah", "imperishable beyond cycles"]
  },
  {
    "id": "8.21",
    "number": "8.21",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Called unmanifest imperishable, supreme goal, attaining which none return — that is my supreme abode.",
    "commentary": "Plain: aksara as final abode. Ramakantha: dhama is Shiva's luminous abode attained by samuccaya.",
    "keyPoints": ["aksara-gati", "parama-dhama"]
  },
  {
    "id": "8.22",
    "number": "8.22",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "That supreme Person is attained by exclusive devotion, in whom beings abide and in whom all is established.",
    "commentary": "Plain: ananya-bhakti reaches All-ground. Ramakantha: pratishthitam stresses world established in Shiva, known through loving recognition plus duty.",
    "keyPoints": ["ananya-bhakti", "all-established-in-Him"]
  },
  {
    "id": "8.23",
    "number": "8.23",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "The time when yogis departing attain non-return or return, that time I shall tell.",
    "commentary": "Plain: introduces uttarayana lore. Ramakantha: kala-marga symbolic of clarity vs obscurity in consciousness.",
    "keyPoints": ["anavritti-avritti", "death-time lore"]
  },
  {
    "id": "8.24",
    "number": "8.24",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Fire, light, day, bright fortnight, six months northward — departing there Brahman-knowers reach Brahman.",
    "commentary": "Plain: bright path to non-return. Ramakantha: brightness is ascendancy of jnana illumining karma.",
    "keyPoints": ["archiradi path", "light ascendancy"]
  },
  {
    "id": "8.25",
    "number": "8.25",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Smoke, night, dark fortnight, six months southward — the yogi reaching lunar light returns.",
    "commentary": "Plain: dark path returns. Ramakantha: smoke-path is karma without full recognition, hence return.",
    "keyPoints": ["dhuma path", "return"]
  },
  {
    "id": "8.26",
    "number": "8.26",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "These bright and dark courses are deemed eternal; by one goes to non-return, by other returns.",
    "commentary": "Plain: two eternal courses. Ramakantha: two courses are knowledge-lit vs knowledge-dim action.",
    "keyPoints": ["two gatis", "lit vs dim"]
  },
  {
    "id": "8.27",
    "number": "8.27",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Knowing these courses no yogi is deluded; therefore at all times be yoga-yoked.",
    "commentary": "Plain: knowledge prevents delusion. Ramakantha: steady samuccaya transcends concern for transit times.",
    "keyPoints": ["no moha", "constant yoga"]
  },
  {
    "id": "8.28",
    "number": "8.28",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Whatever merit is declared in Vedas, sacrifices, austerities and gifts, the yogi transcends all that knowing this, reaching prime supreme abode.",
    "commentary": "Plain: integral knowledge excels ritual merit. Ramakantha: transcendence includes, not rejects, Vedic karma fulfilled in knowing.",
    "keyPoints": ["transcends punya-phala", "adya-sthana"]
  },
  {
    "id": "9.1",
    "number": "9.1",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "To you ungrudging I shall declare the most secret knowledge with realisation, knowing which you shall be freed from evil.",
    "commentary": "Plain: secret wisdom for the receptive. Ramakantha: guhyatama is Shiva-recognition hidden in plain action.",
    "keyPoints": ["guhyatama", "anasuya adhikara"]
  },
  {
    "id": "9.2",
    "number": "9.2",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "King-science, king-secret, supreme purifier, directly perceivable, righteous, easy to practise, imperishable.",
    "commentary": "Plain: accessible yet supreme. Ramakantha: susukham kartum proves karma included — direct perception while doing.",
    "keyPoints": ["pratyaksha", "easy practice"]
  },
  {
    "id": "9.3",
    "number": "9.3",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Men without faith in this dharma, not reaching me, return to death-transmigration path.",
    "commentary": "Plain: faithless return. Ramakantha: ashraddha is refusal to unite knowing and doing.",
    "keyPoints": ["ashraddha", "return to samsara"]
  },
  {
    "id": "9.4",
    "number": "9.4",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "All this world is pervaded by me in unmanifest form; all beings abide in me, I not in them.",
    "commentary": "Plain: pervasion yet transcendence. Ramakantha: avyakta-murti is Shiva pervading acts without being confined.",
    "keyPoints": ["pervasion", "abiding paradox"]
  },
  {
    "id": "9.5",
    "number": "9.5",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Nor do beings abide in me — behold my lordly yoga — supporting yet not dwelling, my self causes beings.",
    "commentary": "Plain: paradox of support. Ramakantha: aishvara-yoga is svatantrya holding world without clinging.",
    "keyPoints": ["bhutabhrit", "paradox-yoga"]
  },
  {
    "id": "9.6",
    "number": "9.6",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "As mighty all-moving wind ever rests in ether, so all beings rest in me.",
    "commentary": "Plain: ether-wind analogy. Ramakantha: ether is consciousness-space wherein karmic winds move.",
    "keyPoints": ["akasha-vayu", "consciousness-space"]
  },
  {
    "id": "9.7",
    "number": "9.7",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "All beings enter my nature at kalpa's end, and I emit them again at kalpa's dawn.",
    "commentary": "Plain: cyclic withdrawal-emission. Ramakantha: mamika-prakriti is Shiva's own power, emission is worshipful act.",
    "keyPoints": ["kalpa cycle", "emission"]
  },
  {
    "id": "9.8",
    "number": "9.8",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Resting on my nature I emit again and again this helpless host under nature's sway.",
    "commentary": "Plain: compassion despite helplessness. Ramakantha: avashtabhya shows freedom — Shiva creates though beings feel compelled.",
    "keyPoints": ["svam prakritim", "freedom in recurrence"]
  },
  {
    "id": "9.9",
    "number": "9.9",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Nor do those actions bind me, seated as indifferent, unattached to those actions.",
    "commentary": "Plain: unattached creator. Ramakantha: udasina is witness-posture to be adopted while performing karma.",
    "keyPoints": ["non-binding", "udasina model"]
  },
  {
    "id": "9.10",
    "number": "9.10",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Under my overseership nature brings forth moving-unmoving, and for this reason the world revolves.",
    "commentary": "Plain: overseen prakriti creates. Ramakantha: adhyaksha is witnessing Shiva making karma fertile without entanglement.",
    "keyPoints": ["adhyaksha", "prakriti instrument"]
  },
  {
    "id": "9.11",
    "number": "9.11",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Fools despise me dwelling in human form, not knowing my higher state as great lord of beings.",
    "commentary": "Plain: avatar-contempt by ignorant. Ramakantha: bhuta-maheshvara signals Shaiva great-lordship behind human veil.",
    "keyPoints": ["manusim tanum", "maheshvara hidden"]
  },
  {
    "id": "9.12",
    "number": "9.12",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Vain hopes, vain acts, vain knowledge, witless, resorting to deluding demonic nature.",
    "commentary": "Plain: futility of asuric temper. Ramakantha: mogha because jnana and karma divorced.",
    "keyPoints": ["mogha triad", "mohini prakriti"]
  },
  {
    "id": "9.13",
    "number": "9.13",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Great souls resorting to divine nature worship me single-minded, knowing me as origin imperishable.",
    "commentary": "Plain: daivi-nature leads to single devotion. Ramakantha: daivi is Shiva's luminous freedom expressing as unified practice.",
    "keyPoints": ["daivi prakriti", "ananya-manas"]
  },
  {
    "id": "9.14",
    "number": "9.14",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Ever glorifying me, striving firm-vowed, bowing with devotion, ever-yoked they attend.",
    "commentary": "Plain: devotional disciplines. Ramakantha: kirtana-yatna-namasya show karma as worship fused with knowledge.",
    "keyPoints": ["kirtana-yatna", "nitya-yukta"]
  },
  {
    "id": "9.15",
    "number": "9.15",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Others worship tending me through knowledge-sacrifice as one, as distinct, as manifold facing-all.",
    "commentary": "Plain: three modes of jnana-yajna. Ramakantha: ekattva-prithaktva-bahudha are Shaiva modes of unity-in-difference.",
    "keyPoints": ["jnana-yajna", "three visions"]
  },
  {
    "id": "9.16",
    "number": "9.16",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I am rite, sacrifice, ancestral offering, herb, mantra, ghee, fire and oblation.",
    "commentary": "Plain: all sacrificial elements are Lord. Ramakantha: totalizing sacrifice sanctifies outer karma as Shiva.",
    "keyPoints": ["sacrifice identity", "karma sanctified"]
  },
  {
    "id": "9.17",
    "number": "9.17",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I am father, mother, supporter, grandsire of world, knowable, purifier, Om and three Vedas.",
    "commentary": "Plain: familial and Vedic pervasion. Ramakantha: pitamaha includes lineage of teachers transmitting samuccaya.",
    "keyPoints": ["father-mother", "Om-Veda"]
  },
  {
    "id": "9.18",
    "number": "9.18",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Goal, supporter, lord, witness, abode, refuge, friend, origin, dissolution, ground, treasure, imperishable seed.",
    "commentary": "Plain: twelve shelters. Ramakantha: sakshi-sharana pair joins knowing-refuge with active support.",
    "keyPoints": ["gati-bharta-sakshi", "refuge"]
  },
  {
    "id": "9.19",
    "number": "9.19",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I heat, withhold and release rain; I am deathlessness and death, being and non-being.",
    "commentary": "Plain: opposites in Lord. Ramakantha: opposites held by Shiva's inclusive freedom.",
    "keyPoints": ["rain-giver", "sat-asat in one"]
  },
  {
    "id": "9.20",
    "number": "9.20",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Three-Veda soma-drinkers purified of sin, sacrificing, pray for heaven, attaining Indra's world enjoy divine delights.",
    "commentary": "Plain: Vedic heaven-seekers. Ramakantha: legitimate but limited fruit of karma without full recognition.",
    "keyPoints": ["traividya", "heaven fruit"]
  },
  {
    "id": "9.21",
    "number": "9.21",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Enjoying vast heaven when merit exhausts they enter mortal world; thus following triple dharma, desiring desires, they come and go.",
    "commentary": "Plain: exhaustion and return. Ramakantha: gata-agata ends only when karma wedded to knowledge.",
    "keyPoints": ["kshine punye", "coming-going"]
  },
  {
    "id": "9.22",
    "number": "9.22",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Those who attend me exclusively contemplating me — to them ever-devoted I bear acquisition and preservation.",
    "commentary": "Plain: Lord carries burden. Ramakantha: yogakshema is Shiva sustaining both contemplation and worldly duty.",
    "keyPoints": ["ananya contemplation", "borne welfare"]
  },
  {
    "id": "9.23",
    "number": "9.23",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Devotees of other gods sacrificing with faith sacrifice to me alone, though not by true rule.",
    "commentary": "Plain: oblique worship reaches Lord. Ramakantha: avidhi is lack of wholeness-awareness, yet still Shiva-directed.",
    "keyPoints": ["oblique worship", "avidhi"]
  },
  {
    "id": "9.24",
    "number": "9.24",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I am enjoyer and lord of all sacrifices, but they know me not in truth, hence they fall.",
    "commentary": "Plain: ignorance causes fall. Ramakantha: tattvena is samuccaya-recognition; without it, karma drops.",
    "keyPoints": ["bhokta-prabhu", "fall by non-knowing"]
  },
  {
    "id": "9.25",
    "number": "9.25",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "God-vowed reach gods, ancestor-vowed ancestors, being-worshippers beings, my sacrificers reach me.",
    "commentary": "Plain: end matches vow. Ramakantha: vow shapes consciousness-destination.",
    "keyPoints": ["vrata decides gati", "mat-yajin to me"]
  },
  {
    "id": "9.26",
    "number": "9.26",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Leaf, flower, fruit, water — who offers with devotion, that loving gift of striving soul I accept.",
    "commentary": "Plain: simple loving offering accepted. Ramakantha: simplest karma becomes sacrament when charged with knowledge-love.",
    "keyPoints": ["simple gift", "bhakti transfigures karma"]
  },
  {
    "id": "9.27",
    "number": "9.27",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Whatever you do, eat, offer, give, practise as austerity — do that as offering to me.",
    "commentary": "Plain: total offering of life. Ramakantha: central samuccaya verse — every karma made Shiva-offering by awareness.",
    "keyPoints": ["mad-arpanam", "life as offering"]
  },
  {
    "id": "9.28",
    "number": "9.28",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Thus freed from good-evil fruited action-bonds, self yoked by renunciation-yoga, liberated you shall reach me.",
    "commentary": "Plain: offering liberates from bondage. Ramakantha: sannyasa-yoga is not abandonment but offering-attitude in action.",
    "keyPoints": ["shubhashubha release", "offering-renunciation"]
  },
  {
    "id": "9.29",
    "number": "9.29",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Equal am I to all beings, none hateful or dear, but devotees in devotion abide in me and I in them.",
    "commentary": "Plain: impartial yet intimate. Ramakantha: equality is Shiva-sameness, intimacy is recognition-current.",
    "keyPoints": ["sama", "mutual indwelling"]
  },
  {
    "id": "9.30",
    "number": "9.30",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Even gross misconducter worshipping me exclusively is deemed righteous, rightly resolved.",
    "commentary": "Plain: resolve redeems. Ramakantha: ananya-resolve re-orients karma swiftly toward Shiva.",
    "keyPoints": ["redemption by resolve", "ananya-bhak"]
  },
  {
    "id": "9.31",
    "number": "9.31",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Swiftly becomes righteous, attains lasting peace; declare it, my devotee never perishes.",
    "commentary": "Plain: assurance of transformation. Ramakantha: swiftness because united path corrects from within.",
    "keyPoints": ["kshipram dharma", "assurance"]
  },
  {
    "id": "9.32",
    "number": "9.32",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Taking refuge in me even sin-born, women, vaishyas, shudras reach supreme goal.",
    "commentary": "Plain: universal refuge. Ramakantha: adhikara is devotion-awareness, not birth; karma purified in refuge.",
    "keyPoints": ["universal adhikara", "refuge"]
  },
  {
    "id": "9.33",
    "number": "9.33",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "How much more holy brahmins and royal sages; having reached this transient joyless world, worship me.",
    "commentary": "Plain: a fortiori for privileged. Ramakantha: transient world to be used as sacrificial ground, not fled.",
    "keyPoints": ["anitya-asukha", "worship here"]
  },
  {
    "id": "9.34",
    "number": "9.34",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Mind on me, devotee, sacrificer, bow to me — thus yoking self, intent on me, you shall reach me.",
    "commentary": "Plain: fourfold yoking. Ramakantha: manas-bhakti-yajna-namas fuse contemplation and ritual action.",
    "keyPoints": ["fourfold yoga", "mat-parayana"]
  },
];