// Bhagavad Gītā with Sarvatobhadra (Rājānaka Rāmakantha, KSTS LXIV, 1943) — English.
// Devanagari follows the Rāmakantha recension (pāṭhāntara tables pp.421–430); translations/commentaries original to this project.
export const gitaEnPart4: any[] = [
  {
    "id": "10.1",
    "number": "10.1",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Again hear my supreme word, which for your delight seeking your welfare I shall speak.",
    "commentary": "Plain: renewed teaching from love. Ramakantha: welfare is establishment in samuccaya.",
    "keyPoints": ["supreme word", "welfare motive"]
  },
  {
    "id": "10.2",
    "number": "10.2",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Neither gods nor great seers know my origin, for I am source of gods and seers in every way.",
    "commentary": "Plain: transcendence of origin. Ramakantha: adi is Shiva ever-prior subject, not object of deva-mind.",
    "keyPoints": ["unknown prabhava", "adi"]
  },
  {
    "id": "10.3",
    "number": "10.3",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Who knows me birthless beginningless great lord of worlds, undeluded among mortals, freed from all sins.",
    "commentary": "Plain: knowing lordship liberates. Ramakantha: loka-maheshvara is Shaiva title — knowing frees karma.",
    "keyPoints": ["aja-anadi", "maheshvara-knowing"]
  },
  {
    "id": "10.4",
    "number": "10.4",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Intellect, knowledge, undelusion, patience, truth, restraint, calm, pleasure, pain, birth, non-being, fear and fearlessness.",
    "commentary": "Plain: states from Lord (to be completed next). Ramakantha: opposites as Shiva's powers to be recognised in experience.",
    "keyPoints": ["mental states", "divine source"]
  },
  {
    "id": "10.5",
    "number": "10.5",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Non-harm, equanimity, contentment, austerity, gift, fame, infamy — diverse states of beings come from me alone.",
    "commentary": "Plain: ethical opposites from Lord. Ramakantha: even ayashas instructs detachment when seen as Shiva-wave.",
    "keyPoints": ["diverse bhavas", "from me"]
  },
  {
    "id": "10.6",
    "number": "10.6",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Seven ancient seers and four Manus, my-natured mind-born, from whom are these creatures in world.",
    "commentary": "Plain: cosmic progenitors. Ramakantha: manasa creation is consciousness projecting plurality while remaining one.",
    "keyPoints": ["saptarshi-manu", "mind-born"]
  },
  {
    "id": "10.7",
    "number": "10.7",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Who knows in truth this pervasion and yoga of mine is yoked by unwavering yoga without doubt.",
    "commentary": "Plain: knowing vibhuti-yoga steadies. Ramakantha: vibhuti is distributed Shiva-glory seen in acts.",
    "keyPoints": ["vibhuti-yoga knowing", "avikampa"]
  },
  {
    "id": "10.8",
    "number": "10.8",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I am origin of all, from me all proceeds; knowing thus the wise worship me full of feeling.",
    "commentary": "Plain: source-devotion. Ramakantha: pravartate includes karmic activity flowing from Shiva-source.",
    "keyPoints": ["sarva-prabhava", "bhava worship"]
  },
  {
    "id": "10.9",
    "number": "10.9",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Minds on me, lives placed in me, enlightening each other, ever speaking of me, they delight and rejoice.",
    "commentary": "Plain: communal devotion. Ramakantha: kathana-bodhana unite discourse-knowledge with life-energy-action.",
    "keyPoints": ["mat-chitta", "mutual awakening"]
  },
  {
    "id": "10.10",
    "number": "10.10",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "To them ever-yoked worshipping with love I give that buddhi-yoga by which they reach me.",
    "commentary": "Plain: gift of discernment. Ramakantha: buddhi-yoga is discriminative recognition guiding karma.",
    "keyPoints": ["gift buddhi-yoga", "love"]
  },
  {
    "id": "10.11",
    "number": "10.11",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "For compassion I dwelling as their self-state destroy ignorance-born darkness with shining lamp of knowledge.",
    "commentary": "Plain: inner lamp destroys darkness. Ramakantha: atma-bhava lamp shines while lamp-holder still acts in world.",
    "keyPoints": ["compassion", "jnana-dipa"]
  },
  {
    "id": "10.12",
    "number": "10.12",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "You are supreme Brahman, supreme abode, supreme purifier, eternal divine Person, primal god birthless all-pervading.",
    "commentary": "Plain: Arjuna's confession. Ramakantha: titles suit Parama-Shiva as Vasudeva.",
    "keyPoints": ["para-brahman", "confession"]
  },
  {
    "id": "10.13",
    "number": "10.13",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "All seers declare you, divine seer Narada, Asita, Devala, Vyasa, and yourself tell me.",
    "commentary": "Plain: scriptural corroboration. Ramakantha: rishi consensus confirms samuccaya teaching.",
    "keyPoints": ["rishi witness", "tradition"]
  },
  {
    "id": "10.14",
    "number": "10.14",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "All this you speak I deem true; neither gods nor demons know your manifestation.",
    "commentary": "Plain: faith in mystery. Ramakantha: vyakti unknowable as object, knowable as self.",
    "keyPoints": ["ritam", "unknown vyakti"]
  },
  {
    "id": "10.15",
    "number": "10.15",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Yourself by yourself you know, best Person, creator, lord of beings, god of gods, world-lord.",
    "commentary": "Plain: self-known Lord. Ramakantha: atmanatmana is self-recognition, model for pratyabhijna.",
    "keyPoints": ["self-knowing", "bhutesha"]
  },
  {
    "id": "10.16",
    "number": "10.16",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Worthily tell without remainder your divine self-glories by which pervading these worlds you stand.",
    "commentary": "Plain: request for vibhutis. Ramakantha: pervasion to be seen in concrete acts and beings.",
    "keyPoints": ["request", "pervasion-standing"]
  },
  {
    "id": "10.17",
    "number": "10.17",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "How may I know you, O yogi, ever contemplating, and in what states are you to be contemplated by me?",
    "commentary": "Plain: how to contemplate everywhere. Ramakantha: contemplation in bhavas weds meditation to world-action.",
    "keyPoints": ["how to contemplate", "in bhavas"]
  },
  {
    "id": "10.18",
    "number": "10.18",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "In detail tell your yoga and glory again; no satiety in hearing your nectar.",
    "commentary": "Plain: hunger for nectar. Ramakantha: nectar is delight of recognition in multiplicity.",
    "keyPoints": ["vistara", "insatiable nectar"]
  },
  {
    "id": "10.19",
    "number": "10.19",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Lo, I shall tell my divine glories principally, for no end to my detail.",
    "commentary": "Plain: principal selection. Ramakantha: pradhanyatas shows Shiva exemplified in chief activities.",
    "keyPoints": ["principally", "endlessness"]
  },
  {
    "id": "10.20",
    "number": "10.20",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I am self seated in heart of all beings, their beginning middle and end.",
    "commentary": "Plain: indwelling totality. Ramakantha: atma in ashaya proves witness present in every act.",
    "keyPoints": ["atma in heart", "adi-madhya-anta"]
  },
  {
    "id": "10.21",
    "number": "10.21",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Of Adityas I am Vishnu, of lights radiant sun, of Maruts Marichi, of stars moon.",
    "commentary": "Plain: chiefs among luminaries. Ramakantha: chiefs are intensified Shiva-flashes.",
    "keyPoints": ["chief luminaries", "flash-intensity"]
  },
  {
    "id": "10.22",
    "number": "10.22",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Of Vedas I am Sama, of gods Indra, of senses mind, of beings consciousness.",
    "commentary": "Plain: best in each class. Ramakantha: manas-chetanā show inner faculties as Shiva-glory guiding outer karma.",
    "keyPoints": ["Sama", "mind-consciousness"]
  },
  {
    "id": "10.23",
    "number": "10.23",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Of Rudras I am Shankara, of yaksha-rakshas Kubera, of Vasus fire, of peaks Meru.",
    "commentary": "Plain: Shaiva-inclusive hierarchy. Ramakantha: Shankara named openly reveals Shaiva colouring — Shiva as chief Rudra.",
    "keyPoints": ["Shankara", "Meru"]
  },
  {
    "id": "10.24",
    "number": "10.24",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Of priests know me as chief Brihaspati, of generals Skanda, of waters ocean.",
    "commentary": "Plain: priest-warrior-water excellences. Ramakantha: guidance, valour, vastness as powers for righteous action.",
    "keyPoints": ["Brihaspati-Skanda", "ocean"]
  },
  {
    "id": "10.25",
    "number": "10.25",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Of great seers Bhrigu, of speech single syllable Om, of sacrifices muttered repetition, of immovables Himalaya.",
    "commentary": "Plain: contemplative excellences. Ramakantha: japa-yajna praised as karma already fused with knowledge.",
    "keyPoints": ["Bhrigu-Om", "japa-yajna"]
  },
  {
    "id": "10.26",
    "number": "10.26",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Of trees Ashvattha, of divine seers Narada, of gandharvas Chitraratha, of perfected Kapila.",
    "commentary": "Plain: sacred beings. Ramakantha: Kapila honoured yet completed by theistic samuccaya.",
    "keyPoints": ["Ashvattha", "Kapila"]
  },
  {
    "id": "10.27",
    "number": "10.27",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Of horses know me as Uchaishravas nectar-born, of elephants Airavata, of men king.",
    "commentary": "Plain: royal steeds and ruler. Ramakantha: kingship as responsible action-emblem of Shiva.",
    "keyPoints": ["royal emblems", "rulership"]
  },
  {
    "id": "10.28",
    "number": "10.28",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Of weapons thunderbolt, of cows wish-cow, of progenitors love-god, of serpents Vasuki.",
    "commentary": "Plain: power-fertility emblems. Ramakantha: kama as procreation (not lust) sanctified when dharmic.",
    "keyPoints": ["vajra-kamadhuk", "sanctified desire"]
  },
  {
    "id": "10.29",
    "number": "10.29",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Of nagas Ananta, of water-dwellers Varuna, of ancestors Aryaman, of restrainers Yama.",
    "commentary": "Plain: cosmic regulators. Ramakantha: samyama crowned by Shiva-restraint in action.",
    "keyPoints": ["Ananta-Varuna", "Yama restraint"]
  },
  {
    "id": "10.30",
    "number": "10.30",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Of demons Prahlada, of reckoners time, of beasts lion, of birds Garuda.",
    "commentary": "Plain: devotion amid opposition. Ramakantha: Prahlada models bhakti-knowledge amid demonic karma.",
    "keyPoints": ["Prahlada", "kala"]
  },
  {
    "id": "10.31",
    "number": "10.31",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Of purifiers wind, of weapon-bearers Rama, of fishes crocodile, of streams Ganga.",
    "commentary": "Plain: purifying heroic currents. Ramakantha: Rama as dharmic warrior ideal for Arjuna's samuccaya.",
    "keyPoints": ["pavana-Rama", "Jahnavi"]
  },
  {
    "id": "10.32",
    "number": "10.32",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Of creations beginning end and middle am I, of sciences self-science, of debaters dialectic.",
    "commentary": "Plain: temporal and intellectual ground. Ramakantha: adhyatma-vidya crowns yet includes debate-action of mind.",
    "keyPoints": ["adi-anta", "adhyatma-vidya"]
  },
  {
    "id": "10.33",
    "number": "10.33",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Of letters letter A, of compounds dvandva, I imperishable time, ordainer facing all.",
    "commentary": "Plain: grammar-time pervasion. Ramakantha: akara as primal vibration, kala as Shiva's pulsation.",
    "keyPoints": ["akara", "akshaya-kala"]
  },
  {
    "id": "10.34",
    "number": "10.34",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Death all-snatching am I, and birth of future beings; among feminine glories, fame, fortune, speech, memory, insight, resolve, patience.",
    "commentary": "Plain: death-birth and virtues. Ramakantha: feminine powers are Shiva's shaktis operating in knowledge-action.",
    "keyPoints": ["mrityu-udbhava", "shakti virtues"]
  },
  {
    "id": "10.35",
    "number": "10.35",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Of samans Brihat-saman, of metres Gayatri, of months Margashirsha, of seasons flower-maker spring.",
    "commentary": "Plain: liturgical-temporal bests. Ramakantha: song-metre-season show worship rhythm in time-action.",
    "keyPoints": ["Brihat-Gayatri", "sacred time"]
  },
  {
    "id": "10.36",
    "number": "10.36",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Gambling of cheats am I, splendour of splendid, victory, resolve, goodness of good.",
    "commentary": "Plain: even ambiguous powers owned. Ramakantha: dicing owned to show Shiva pervades risky action, to be faced with knowledge.",
    "keyPoints": ["owned opposites", "resolve-victory"]
  },
  {
    "id": "10.37",
    "number": "10.37",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Of Vrishnis Vasudeva, of Pandavas Arjuna, of sages Vyasa, of poets Ushanas.",
    "commentary": "Plain: intimate incarnational hints. Ramakantha: Vasudeva-Dhananjaya pairing shows Lord and devoted actor together.",
    "keyPoints": ["Vasudeva-Arjuna", "Vyasa"]
  },
  {
    "id": "10.38",
    "number": "10.38",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Punishment of subduers, policy of conquer-seekers, silence of secrets, knowledge of knowers.",
    "commentary": "Plain: governance and inwardness. Ramakantha: danda-niti-mauna-jnana balance outer rule and inner silence in one yoga.",
    "keyPoints": ["danda-niti", "mauna-jnana"]
  },
  {
    "id": "10.39",
    "number": "10.39",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Whatever is seed of all beings, that am I; nothing moving-unmoving exists without me.",
    "commentary": "Plain: universal seed, nothing apart. Ramakantha: bija is Shiva-seed present in every karma-germ.",
    "keyPoints": ["sarva-bija", "nothing without"]
  },
  {
    "id": "10.40",
    "number": "10.40",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "No end to my divine glories; this detail is declared by way of illustration.",
    "commentary": "Plain: illustrative limit. Ramakantha: illustration invites seeing Shiva in remaining acts.",
    "keyPoints": ["endless", "illustration"]
  },
  {
    "id": "10.41",
    "number": "10.41",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Whatever glorious, fortunate, mighty being, know it born of a particle of my splendour.",
    "commentary": "Plain: rule for recognition. Ramakantha: tejo-amsha rule trains recognition in daily encounters and duties.",
    "keyPoints": ["rule of glimpse", "amsha"]
  },
  {
    "id": "10.42",
    "number": "10.42",
    "section": "Adhyāya 10 — Vibhūti (Powers)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vibhuti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "What need of much knowing? Supporting this whole world with one fragment, I stand.",
    "commentary": "Plain: whole summed in one support. Ramakantha: ekamsha-sthiti shows Shiva effortlessly holding all karma while transcending.",
    "keyPoints": ["ekamsha support", "summation"]
  },
  {
    "id": "11.1",
    "number": "11.1",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "By your supremely secret self-teaching spoken for grace, this delusion of mine is gone.",
    "commentary": "Plain: grace dispels delusion. Ramakantha: moha-vigama is first recognition dawning through teaching-action.",
    "keyPoints": ["anugraha", "moha gone"]
  },
  {
    "id": "11.2",
    "number": "11.2",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Origin-dissolution of beings heard in detail from you, and imperishable greatness too.",
    "commentary": "Plain: cosmology heard. Ramakantha: bhava-apyaya as Shiva's systole-diastole.",
    "keyPoints": ["heard cosmology", "greatness"]
  },
  {
    "id": "11.3",
    "number": "11.3",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "So it is as you say, supreme Lord, yet I wish to see your lordly form.",
    "commentary": "Plain: request for vision. Ramakantha: seeing crowns hearing — knowledge seeks direct realisation in vision-action.",
    "keyPoints": ["request vision", "aishvara rupa"]
  },
  {
    "id": "11.4",
    "number": "11.4",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "If you think it possible to be seen by me, O lord of yoga, show your imperishable self.",
    "commentary": "Plain: conditional prayer. Ramakantha: capability is ripened samuccaya qualifying for vision.",
    "keyPoints": ["yogyata", "show atman"]
  },
  {
    "id": "11.5",
    "number": "11.5",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Behold my forms by hundreds and thousands, various divine, various colours-shapes.",
    "commentary": "Plain: manifold invitation. Ramakantha: multiplicity is Shiva's free variegation, not division.",
    "keyPoints": ["manifold", "divine variety"]
  },
  {
    "id": "11.6",
    "number": "11.6",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Behold Adityas, Vasus, Rudras, Ashvins, Maruts, and many never-seen wonders.",
    "commentary": "Plain: Vedic hosts in vision. Ramakantha: deva-hosts are Shiva's sense-cosmic powers gathered in one body.",
    "keyPoints": ["deva hosts", "unseen wonders"]
  },
  {
    "id": "11.7",
    "number": "11.7",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Here in one place behold whole world moving-unmoving in my body, and whatever else you wish to see.",
    "commentary": "Plain: whole concentrated in body. Ramakantha: eka-stha shows action-world non-different from consciousness-body.",
    "keyPoints": ["eka-stha jagat", "body cosmos"]
  },
  {
    "id": "11.8",
    "number": "11.8",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "You cannot see me with your own eye; I give divine eye — behold my lordly yoga.",
    "commentary": "Plain: divine eye gifted. Ramakantha: divya-chaksus is grace-opened recognition, not mere organ.",
    "keyPoints": ["gifted eye", "yoga-aishvara"]
  },
  {
    "id": "11.9",
    "number": "11.9",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "So speaking, O king, great yoga-lord Hari showed to Arjuna supreme lordly form.",
    "commentary": "Plain: Sanjaya narrates theophany. Ramakantha: maha-yogeshvara shows yoga includes showing and seeing as acts.",
    "keyPoints": ["narration", "showing"]
  },
  {
    "id": "11.10",
    "number": "11.10",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Many mouths-eyes, many wondrous sights, many divine ornaments, many uplifted divine weapons.",
    "commentary": "Plain: myriad-faced splendour. Ramakantha: weapons-ornaments together signify fierce-gracious Shiva powers in one.",
    "keyPoints": ["many-faced", "weapons-ornaments"]
  },
  {
    "id": "11.11",
    "number": "11.11",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Wearing divine garlands-robes, anointed with divine scent, all-wonder god endless facing-all.",
    "commentary": "Plain: fragrant infinite wonder. Ramakantha: garland-scent show auspiciousness pervading terror.",
    "keyPoints": ["divine dress", "ananta"]
  },
  {
    "id": "11.12",
    "number": "11.12",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "If thousand suns' light rose together in sky, like would be the blaze of that great self.",
    "commentary": "Plain: sun-thousand simile. Ramakantha: blaze is citi-prakasha blinding divisive intellect into unity.",
    "keyPoints": ["thousand suns", "prakasha"]
  },
  {
    "id": "11.13",
    "number": "11.13",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "There in one place Arjuna saw whole world divided manifold in god-of-gods body.",
    "commentary": "Plain: unity holding diversity. Ramakantha: pravibhakta-anekadha yet eka-stha — difference in non-difference, Shaiva bhedabheda.",
    "keyPoints": ["divided yet one", "body"]
  },
  {
    "id": "11.14",
    "number": "11.14",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Then wonder-filled, hair erect, bowing head with folded hands he spoke.",
    "commentary": "Plain: awe-response. Ramakantha: vismaya-hrishta-romata is bodily recognition thrilling through action-organs.",
    "keyPoints": ["vismaya", "anjali"]
  },
  {
    "id": "11.15",
    "number": "11.15",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I see all gods in your body, hosts of varied beings, Brahma lotus-seated, Shiva, seers and divine serpents.",
    "commentary": "Plain: cosmic inventory. Ramakantha: Isham included shows Shiva not outside Vishvarupa but within as its lordship.",
    "keyPoints": ["deva hosts", "Brahma-Isha included"]
  },
  {
    "id": "11.16",
    "number": "11.16",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Many arms-bellies-mouths-eyes, endless all-sided, I see no end middle or beginning of you, world-lord all-formed.",
    "commentary": "Plain: boundless form. Ramakantha: no adi-madhya-anta is Shiva's anadi infinitude.",
    "keyPoints": ["ananta-rupa", "no limits"]
  },
  {
    "id": "11.17",
    "number": "11.17",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Crowned, mace-disc bearing, mass of splendour blazing all round, hard to behold like blazing fire-sun, immeasurable.",
    "commentary": "Plain: dazzling regalia. Ramakantha: kirita-gada-chakra are sovereign powers wielded in righteous war-action.",
    "keyPoints": ["regalia", "durnirikshya"]
  },
  {
    "id": "11.18",
    "number": "11.18",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "You imperishable supreme knowable, supreme ground of universe, undying guardian of sat-tva dharma, eternal Person in my view.",
    "commentary": "Plain: creedal salutation. Ramakantha: reads sāttvata-dharma-goptā — concealer-guardian of esoteric sattvata (truth-being) practice of projecting-withdrawing consciousness, Shaiva appropriation.",
    "keyPoints": ["aksara-nidhana", "sattvata-dharma"]
  },
  {
    "id": "11.19",
    "number": "11.19",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Beginning-middle-endless, infinite valour, infinite arms, moon-sun eyed, fire-mouthed, heating world by own glow.",
    "commentary": "Plain: fiery cosmic ascetic. Ramakantha: heating is tapas of consciousness purifying karma.",
    "keyPoints": ["anadi", "tapantam"]
  },
  {
    "id": "11.20",
    "number": "11.20",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Heaven-earth interval and all quarters pervaded by you alone; seeing this wondrous fierce form three worlds tremble.",
    "commentary": "Plain: pervasion causes trembling. Ramakantha: trembling is limited ego confronting all-inclusive freedom.",
    "keyPoints": ["pervasion", "trembling"]
  },
  {
    "id": "11.21",
    "number": "11.21",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Rudras, Adityas, Vasus, Sadhyas, Vishvas, Ashvins, Maruts, ancestors, gandharva-yaksha-asura-perfected hosts gaze astonished, great seer-hosts crying hail.",
    "commentary": "Plain: awed cosmic audience. Ramakantha variant cry svasti shows even seers take refuge in all-form while continuing praise-action.",
    "keyPoints": ["astonished hosts", "svasti cry"]
  },
  {
    "id": "11.22",
    "number": "11.22",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Seeing your vast many-mouthed-eyed, many-armed-thighed-footed, many-bellied terrible-tusked form, worlds tremble and I too.",
    "commentary": "Plain: terror shared. Ramakantha: karala teaches fierce aspect of same gracious Shiva, to be faced in battle-duty.",
    "keyPoints": ["mahat-rupa", "shared terror"]
  },
  {
    "id": "11.23",
    "number": "11.23",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Sky-touching, blazing multicoloured, gaping-mouthed blazing-eyed, seeing you my inner self trembles, I find no steadiness or peace.",
    "commentary": "Plain: overwhelmed steadiness lost. Ramakantha: loss of dhriti precedes higher steadiness rooted in recognition.",
    "keyPoints": ["sky-touching", "overwhelmed"]
  },
  {
    "id": "11.24",
    "number": "11.24",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Seeing tusk-terrible mouths like world-fire, I know not directions nor find shelter — be gracious, god-lord world-abode.",
    "commentary": "Plain: plea for grace. Ramakantha: plea is prapatti turning terror into samuccaya-courage.",
    "keyPoints": ["kala-anala", "prasida plea"]
  },
  {
    "id": "11.25",
    "number": "11.25",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "These sons of Dhritarashtra with prince-hosts, Bhishma, Drona, Karna, with our chief warriors rush into you.",
    "commentary": "Plain: warriors entering maw (intro). Ramakantha: foreseen destruction authorizes detached yet strenuous action.",
    "keyPoints": ["hosts rushing", "foreseen fate"]
  },
  {
    "id": "11.26",
    "number": "11.26",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Swiftly they enter your tusk-terrible dreadful mouths, some stuck between teeth seen with crushed heads.",
    "commentary": "Plain: crushing vision. Ramakantha: crushing is time-Svatantrya withdrawing projections.",
    "keyPoints": ["entering mouths", "crushed"]
  },
  {
    "id": "11.27",
    "number": "11.27",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "As river torrents rush facing ocean, so these heroes enter your blazing mouths.",
    "commentary": "Plain: river-ocean simile. Ramakantha: inevitability seen by knower-actor breeds nimittamatra humility.",
    "keyPoints": ["river simile", "inevitability"]
  },
  {
    "id": "11.28",
    "number": "11.28",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "As moths enter blazing fire to perish with gathering speed, so worlds enter your mouths to perish.",
    "commentary": "Plain: moth-flame simile. Ramakantha: moth-image warns against karma blind to Self; illumined karma escapes delusion.",
    "keyPoints": ["moth simile", "blind karma"]
  },
  {
    "id": "11.29",
    "number": "11.29",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Licking, swallowing all worlds with flaming mouths on every side, filling world with rays your fierce glows scorch.",
    "commentary": "Plain: all-devouring licking. Ramakantha: licking is samhara relish — Shiva tasting his own emission.",
    "keyPoints": ["lelihyase", "scorching"]
  },
  {
    "id": "11.30",
    "number": "11.30",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Tell who are you fierce-formed, homage, be gracious, I wish to know you primal, I grasp not your working.",
    "commentary": "Plain: identity question. Ramakantha: pravritti-question seeks meaning of fierce action for Arjuna's duty.",
    "keyPoints": ["ko bhavan", "pravritti query"]
  },
  {
    "id": "11.31",
    "number": "11.31",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I am time, world-destroying matured, engaged to gather worlds; without you all opposing warriors shall not survive.",
    "commentary": "Plain: kala proclamation. Ramakantha: kala is Shiva as time-power, already-decided outcome grounding fearless action.",
    "keyPoints": ["kalo'smi", "already decided"]
  },
  {
    "id": "11.32",
    "number": "11.32",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Therefore rise, gain glory, conquering foes enjoy rich kingdom; by me already slain, be mere instrument.",
    "commentary": "Plain: instrument-call. Ramakantha with pravriddhan lokan echo: matured worlds already withdrawn by Shiva; warrior's karma is instrumental participation, crown of samuccaya.",
    "keyPoints": ["uttishtha", "nimitta-matra"]
  },
  {
    "id": "11.33",
    "number": "11.33",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Rāmakantha pāṭha: Rāmakantha: pravṛddhāṁllokān."}],
    "translation": "Drona, Bhishma, Jayadratha, Karna and other heroes already killed by me — kill them, grieve not, fight, you shall conquer foes.",
    "commentary": "Plain: named assurance. Ramakantha: naming shows universal consciousness particularizes responsibility without anxiety.",
    "keyPoints": ["already killed", "ma vyathishtha"]
  },
  {
    "id": "11.34",
    "number": "11.34",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Hearing this, crowned Arjuna trembling folded hands, bowing again spoke choked, fearful, prostrate.",
    "commentary": "Plain: trembling praise prelude. Ramakantha: vepamana devotion shows feeling-knowledge shaking body yet steadying resolve.",
    "keyPoints": ["trembling", "folded hands"]
  },
  {
    "id": "11.35",
    "number": "11.35",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Rightly in your glory world rejoices and loves, rakshasas flee fearful, perfected hosts bow.",
    "commentary": "Plain: cosmic joy-fear split. Ramakantha: joy vs flight reflect recognition vs non-recognition of same Shiva.",
    "keyPoints": ["rejoice-flee", "sthane"]
  },
  {
    "id": "11.36",
    "number": "11.36",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Why should they not bow to you, greater than Brahma first-maker, endless god-lord world-abode, imperishable, being-nonbeing-beyond?",
    "commentary": "Plain: fitting homage. Ramakantha: gariyase Brahmano'pi asserts Shiva-Vasudeva beyond creator Brahma.",
    "keyPoints": ["greater than Brahma", "aksara"]
  },
  {
    "id": "11.37",
    "number": "11.37",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "You primal god ancient Person, supreme ground, knower and knowable, supreme abode, by you world pervaded, endless-formed.",
    "commentary": "Plain: total pervasion. Ramakantha: vetta-vedya unity is subject-object non-duality.",
    "keyPoints": ["vetta-vedya", "pervasion"]
  },
  {
    "id": "11.38",
    "number": "11.38",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Wind, death, fire, water, moon, creator, great-grandsire are you; homage thousandfold, again homage.",
    "commentary": "Plain: elemental homage. Ramakantha: elemental identities authorize seeing Shiva in natural forces while fighting.",
    "keyPoints": ["elements as you", "thousand homage"]
  },
  {
    "id": "11.39",
    "number": "11.39",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Homage before, behind, on every side, O All; endless valour, boundless stride, you pervade all, hence you are All.",
    "commentary": "Plain: all-sided homage. Ramakantha: sarva epithet is Shaiva All-Self appropriating Vishvarupa as Shiva's body.",
    "keyPoints": ["all-sided", "sarva"]
  },
  {
    "id": "11.40",
    "number": "11.40",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "(Traditional Kashmir extra brilliance half amplifying thousand-sun blaze abiding in vision.)",
    "commentary": "Plain: intensification. Ramakantha: extra stresses uninterrupted blaze of recognition.",
    "keyPoints": ["intensification", "blaze"]
  },
  {
    "id": "11.41",
    "number": "11.41",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Taking as friend, whatever I rashly said — O Krishna, Yadava, friend — unknowing your greatness through negligence or love.",
    "commentary": "Plain: apology for familiarity. Ramakantha: familiarity itself was germ of recognition maturing through vision-action.",
    "keyPoints": ["apology", "love-negligence"]
  },
  {
    "id": "11.42",
    "number": "11.42",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Whatever jest-disrespect in play, rest, seat, meals, alone or before others, I beg pardon, immeasurable one.",
    "commentary": "Plain: pardon for jests. Ramakantha: daily acts listed show karma-field where disrespect turns to reverence via knowledge.",
    "keyPoints": ["daily acts", "pardon"]
  },
  {
    "id": "11.43",
    "number": "11.43",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Father of moving-unmoving world, worshipful weighty guru, none equal, how another greater in three worlds, matchless power?",
    "commentary": "Plain: father-guru supremacy. Ramakantha: guru epithet validates teaching-action lineage of Pratyabhijna masters.",
    "keyPoints": ["pita-guru", "matchless"]
  },
  {
    "id": "11.44",
    "number": "11.44",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Bowing, laying body down, I propitiate you praiseworthy lord; as father to son, friend to friend, lover to loved, bear with me.",
    "commentary": "Plain: triple forgiveness simile. Ramakantha: three loves model jnana-kinship sustaining karma-forgiveness.",
    "keyPoints": ["triple simile", "prasada plea"]
  },
  {
    "id": "11.45",
    "number": "11.45",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Unseen before, delighted seeing, yet mind trembles with fear — show that same dear form, be gracious.",
    "commentary": "Plain: delight-fear requests gentle form. Ramakantha: both affects are Shiva-touches; gentle form integrates them for duty.",
    "keyPoints": ["delight-fear", "gentle form plea"]
  },
  {
    "id": "11.46",
    "number": "11.46",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Crowned, mace-bearing, disc-handed I wish to see as before; assume that four-armed form, thousand-armed all-formed.",
    "commentary": "Plain: return to four arms. Ramakantha: four arms are gracious contraction of infinite for actionable devotion.",
    "keyPoints": ["four-armed", "contraction for worship"]
  },
  {
    "id": "11.47",
    "number": "11.47",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "By me gracious this supreme form shown through self-yoga, luminous endless primal, never seen by other than you.",
    "commentary": "Plain: grace-exclusive vision. Ramakantha: atma-yoga is Shiva's self-display through own power, not external aid.",
    "keyPoints": ["prasanna", "exclusive grace"]
  },
  {
    "id": "11.48",
    "number": "11.48",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Not by Veda-sacrifice-study, gifts, rites, fierce austerities can I thus be seen by another in mortal world.",
    "commentary": "Plain: vision beyond mere rites. Ramakantha upodghata cites “You are maker of all by yourself, O pervader, hence all this is you” — rites avail only when known as Shiva's self-making, i.e., samuccaya.",
    "keyPoints": ["beyond mere rite", "self-maker gloss"]
  },
  {
    "id": "11.49",
    "number": "11.49",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Fear not nor bewilderment seeing this dread form; fear gone, gladdened, behold again this same gentle form of mine.",
    "commentary": "Plain: fear removed, gentle return. Ramakantha: vyapeta-bhih is fruit of recognition stabilizing warrior for action.",
    "keyPoints": ["ma vyatha", "gentle return"]
  },
  {
    "id": "11.50",
    "number": "11.50",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "So speaking Vasudeva showed again his own form, consoling the frightened, resuming gentle body.",
    "commentary": "Plain: consolation. Ramakantha: saumya-vapus is Shiva's grace-contraction comforting actor for duty.",
    "keyPoints": ["consolation", "saumya"]
  },
  {
    "id": "11.51",
    "number": "11.51",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Seeing this human gentle form, now I am composed, mind restored, returned to nature.",
    "commentary": "Plain: composure regained. Ramakantha: prakriti-gata is settled in own balanced nature ready for samuccaya-action.",
    "keyPoints": ["composed", "nature regained"]
  },
  {
    "id": "11.52",
    "number": "11.52",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Hard to behold this form you have seen; even gods ever long to see it.",
    "commentary": "Plain: rarity extolled. Ramakantha: gods long because human actor-knower is privileged locus of recognition.",
    "keyPoints": ["sudurdarsha", "gods long"]
  },
  {
    "id": "11.53",
    "number": "11.53",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Not by Vedas, austerity, gift, or worship can I be seen as you have seen.",
    "commentary": "Plain: means-insufficiency. Ramakantha: isolated means fail; united devotion-knowledge-action succeeds.",
    "keyPoints": ["insufficiency of isolated means"]
  },
  {
    "id": "11.54",
    "number": "11.54",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "By exclusive devotion can I thus be known, seen in truth, and entered.",
    "commentary": "Plain: ananya-bhakti triad. Ramakantha: jnatum-drashtum-praveshtum are knowledge-vision-entry — recognition lived, seen, merged while acting.",
    "keyPoints": ["ananya-bhakti", "triple fruition"]
  },
  {
    "id": "11.55",
    "number": "11.55",
    "section": "Adhyāya 11 — Viśvarūpa (Cosmic Form)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-vishvarupa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Who acts for me, supreme in me, devoted, detached, enmity-free toward all beings reaches me.",
    "commentary": "Plain: fivefold conduct. Ramakantha: crown samuccaya verse — mat-karma-krit weds action to devotion-knowledge, non-enmity as Shiva-sameness.",
    "keyPoints": ["mat-karma", "nirvaira"]
  },
  {
    "id": "12.1",
    "number": "12.1",
    "section": "Adhyāya 12 — Bhakti (Devotion)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-bhakti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Ever-yoked devotees attending you thus, and those tending imperishable unmanifest — who are best yoga-knowers?",
    "commentary": "Plain: personal vs impersonal query. Ramakantha: question tests whether path abandons action or embraces it.",
    "keyPoints": ["two tendencies", "best yogi query"]
  },
  {
    "id": "12.2",
    "number": "12.2",
    "section": "Adhyāya 12 — Bhakti (Devotion)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-bhakti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Fixing mind on me, ever-yoked attending me endowed with supreme faith — deemed most yoked.",
    "commentary": "Plain: personal devotees excel. Ramakantha: avesya-manas amidst duties proves samuccaya superior to abstraction.",
    "keyPoints": ["mind-fixed", "para-shraddha"]
  },
  {
    "id": "12.3",
    "number": "12.3",
    "section": "Adhyāya 12 — Bhakti (Devotion)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-bhakti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Those tending imperishable indefinable unmanifest, all-pervading unthinkable, peak-seated immovable firm.",
    "commentary": "Plain: impersonal discipline described. Ramakantha: valid but arduous, lacking sweet concreteness for action.",
    "keyPoints": ["aksara discipline", "arduous"]
  },
  {
    "id": "12.4",
    "number": "12.4",
    "section": "Adhyāya 12 — Bhakti (Devotion)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-bhakti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Restraining sense-host, equal-minded everywhere, delighting in welfare of all beings, they reach me.",
    "commentary": "Plain: impersonal reaches Lord via welfare. Ramakantha: sarva-bhuta-hite-rati is karma retained even in abstract path.",
    "keyPoints": ["sense-restraint", "welfare delight"]
  },
  {
    "id": "12.5",
    "number": "12.5",
    "section": "Adhyāya 12 — Bhakti (Devotion)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-bhakti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Greater toil for mind-attached to unmanifest, for unmanifest goal is painfully won by embodied.",
    "commentary": "Plain: embodied hardship. Ramakantha: dehavadbhir stresses actor needs embodied support — devotion-action eases.",
    "keyPoints": ["greater klesha", "embodied hardship"]
  },
  {
    "id": "12.6",
    "number": "12.6",
    "section": "Adhyāya 12 — Bhakti (Devotion)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-bhakti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Those surrendering all actions to me, supreme in me, meditating attend with exclusive yoga.",
    "commentary": "Plain: surrender of all karma. Ramakantha: sarva-karmani mayi sannyasya is samuccaya formula — not cessation but dedication.",
    "keyPoints": ["karma-sannyasa as dedication", "mat-para"]
  },
  {
    "id": "12.7",
    "number": "12.7",
    "section": "Adhyāya 12 — Bhakti (Devotion)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-bhakti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "For them mind-fixed on me I become swift uplifter from death-transmigration ocean.",
    "commentary": "Plain: swift rescue. Ramakantha: swiftness due to Shiva's grace responding to united offering.",
    "keyPoints": ["swift uplift", "ocean"]
  },
  {
    "id": "12.8",
    "number": "12.8",
    "section": "Adhyāya 12 — Bhakti (Devotion)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-bhakti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Place mind on me alone, settle intellect in me; hereafter you shall dwell in me alone without doubt.",
    "commentary": "Plain: mind-intellect placement. Ramakantha: adhatsva-niveshaya join feeling and discrimination while hands act.",
    "keyPoints": ["mano-buddhi in me", "dwelling"]
  },
  {
    "id": "12.9",
    "number": "12.9",
    "section": "Adhyāya 12 — Bhakti (Devotion)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-bhakti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "If unable to fix mind steadily on me, then seek to reach me by practice-yoga.",
    "commentary": "Plain: fallback to practice. Ramakantha: abhyasa is repeated remembrance between acts, gradually steadying.",
    "keyPoints": ["abhyasa fallback", "gradual"]
  },
  {
    "id": "12.10",
    "number": "12.10",
    "section": "Adhyāya 12 — Bhakti (Devotion)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-bhakti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "If incapable even of practice, be intent on action for me; doing acts for my sake you shall win perfection.",
    "commentary": "Plain: service as path. Ramakantha: mat-karma-paramo explicitly saves karma-yogi — perfection via dedicated acts.",
    "keyPoints": ["mat-karma", "sake-service"]
  },
  {
    "id": "12.11",
    "number": "12.11",
    "section": "Adhyāya 12 — Bhakti (Devotion)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-bhakti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "If unable even this, resorting to my yoga, then renounce fruit of all actions self-restrained.",
    "commentary": "Plain: fruit-renunciation. Ramakantha: phala-tyaga is minimal samuccaya — act with restrained self, leave result to Shiva.",
    "keyPoints": ["phala-tyaga", "minimal yoga"]
  },
  {
    "id": "12.12",
    "number": "12.12",
    "section": "Adhyāya 12 — Bhakti (Devotion)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-bhakti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Better than practice is knowledge, better than knowledge meditation, better than meditation fruit-renunciation, from renunciation peace 바로.",
    "commentary": "Plain: graded excellences. Ramakantha: hierarchy shows each includes prior, culminating in peace sustaining further action.",
    "keyPoints": ["graded ladder", "peace"]
  },
  {
    "id": "12.13",
    "number": "12.13",
    "section": "Adhyāya 12 — Bhakti (Devotion)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-bhakti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Hater of none, friendly, compassionate, mine-free, ego-free, same in pain-pleasure, forbearing.",
    "commentary": "Plain: devotee virtues begin. Ramakantha: advesta-maitra are Shiva-sameness expressed socially while acting.",
    "keyPoints": ["adveshta", "sama"]
  },
  {
    "id": "12.14",
    "number": "12.14",
    "section": "Adhyāya 12 — Bhakti (Devotion)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-bhakti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Content ever, yogi self-restrained firm-resolved, mind-intellect surrendered to me — such devotee is dear.",
    "commentary": "Plain: content resolve dear. Ramakantha: arpita-mano-buddhi repeats samuccaya seal on bhakti.",
    "keyPoints": ["santushta", "dear"]
  },
  {
    "id": "12.15",
    "number": "12.15",
    "section": "Adhyāya 12 — Bhakti (Devotion)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-bhakti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Whom world does not dread, who dreads not world, free from joy-impatience-fear-agitation — dear to me.",
    "commentary": "Plain: mutual non-disturbance. Ramakantha: non-agitation is even pulse of spanda amid social karma.",
    "keyPoints": ["non-disturbance", "even pulse"]
  },
  {
    "id": "12.16",
    "number": "12.16",
    "section": "Adhyāya 12 — Bhakti (Devotion)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-bhakti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Expectation-free, pure, skilled, indifferent, pain-gone, renouncing all undertakings' selfishness — dear devotee.",
    "commentary": "Plain: skilled indifference. Ramakantha: daksha-udasina pair — skill in karma with witness poise, sarvarambha-tyaga as ego-tyaga not work-tyaga.",
    "keyPoints": ["daksha-udasina", "skilful detachment"]
  },
  {
    "id": "12.17",
    "number": "12.17",
    "section": "Adhyāya 12 — Bhakti (Devotion)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-bhakti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Who neither rejoices, hates, grieves, craves, renouncing good-evil — devout, dear.",
    "commentary": "Plain: equanimity beyond opposites. Ramakantha: shubhashubha-tyaga is offering both to Shiva, not inertia.",
    "keyPoints": ["no h-dvesha", "offering opposites"]
  },
  {
    "id": "12.18",
    "number": "12.18",
    "section": "Adhyāya 12 — Bhakti (Devotion)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-bhakti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Equal to foe and friend, honour-dishonour, cold-heat pleasure-pain, attachment-free.",
    "commentary": "Plain: equalities. Ramakantha: samatva is recognition-sameness steadying varied karmic encounters.",
    "keyPoints": ["sama", "sanga-free"]
  },
  {
    "id": "12.19",
    "number": "12.19",
    "section": "Adhyāya 12 — Bhakti (Devotion)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-bhakti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Same in blame-praise, silent, content with whatever, homeless, steady-minded, devout — dear.",
    "commentary": "Plain: praise-blame silence. Ramakantha: mauna-aniketa are inner freedom compatible with dutiful residence-action.",
    "keyPoints": ["tulya-ninda", "sthira-mati"]
  },
  {
    "id": "12.20",
    "number": "12.20",
    "section": "Adhyāya 12 — Bhakti (Devotion)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-bhakti"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Those attending this righteous nectar as declared, faithful, supreme in me — exceedingly dear devotees.",
    "commentary": "Plain: nectar-closing. Ramakantha: dharmya-amrita is samuccaya-dharma as deathless nectar — faith plus supremacy in Shiva-action crowns VII-XII.",
    "keyPoints": ["dharmya-amrita", "exceedingly dear  </task_result> </task>"]
  },
];