// Bhagavad Gītā with Sarvatobhadra (Rājānaka Rāmakantha, KSTS LXIV, 1943) — English.
// Devanagari follows the Rāmakantha recension (pāṭhāntara tables pp.421–430); translations/commentaries original to this project.
export const gitaEnPart3: any[] = [
  {
    "id": "7.1",
    "number": "7.1",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "श्रीभगवानुवाच — मय्यासक्तमनाः पार्थ योगं युञ्जन्मदाश्रयः । असंशयं समग्रं मां यथा ज्ञास्यसि तच्छृणु ॥7.1॥",
    "iast": "śrībhagavānuvāca mayyāsaktamanāḥ pārtha yogṃ yuñjanmadāśrayḥ asṃśayṃ samagrṃ māṃ yathā jñāsyasi tacchṛṇu",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Listen how, mind fixed on me and practising yoga taking refuge in me, you shall know me fully without doubt.",
    "commentary": "Plain: Krishna promises complete doubt-free knowledge through attachment and refuge. Ramakantha: refuge is not abandoning action but yoking jnana with karma, both resting in Shiva-self.",
    "keyPoints": ["mad-ashraya as samuccaya", "complete knowing is pratyabhijna"]
  },
  {
    "id": "7.2",
    "number": "7.2",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "ज्ञानं तेऽहं सविज्ञानमिदं वक्ष्याम्यशेषतः । यज्ज्ञात्वा नेह भूयोऽन्यज्ज्ञातव्यमवशिष्यते ॥7.2॥",
    "iast": "jñānṃ tehṃ savijñānamidṃ vakṣyāmyaśeṣatḥ yajjñātvā neha bhūyonyajjñātavyamavaśiṣyate",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I shall teach you knowledge together with realisation in full, knowing which nothing further remains to be known.",
    "commentary": "Plain: jnana plus vijnana exhausts the knowable. Ramakantha: vijnana is applied living-through in action, hence jnana alone is incomplete without karma.",
    "keyPoints": ["jnana+vijnana pair", "nothing outside Shiva-knowing"]
  },
  {
    "id": "7.3",
    "number": "7.3",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "मनुष्याणां सहस्रेषु कश्चिद्यतति सिद्धये । यततामपि सिद्धानां कश्चिन्मां वेत्ति तत्त्वतः ॥7.3॥",
    "iast": "manuṣyāṇāṃ sahasreṣu kaścidyatati siddhaye yatatāmapi siddhānāṃ kaścinmāṃ vetti tattvatḥ",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Among thousands one strives for perfection, and among strivers hardly one knows me in truth.",
    "commentary": "Plain: true knowing is rare. Ramakantha: rarity is due to clinging to intellect or rites alone, not their union in awareness.",
    "keyPoints": ["rarity of samuccaya", "tattvatas as Shiva-recognition"]
  },
  {
    "id": "7.4",
    "number": "7.4",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "भूमिरापोऽनलो वायुः खं मनो बुद्धिरेव च । अहङ्कार इतीयं मे भिन्ना प्रकृतिरष्टधा ॥7.4॥",
    "iast": "bhūmirāponalo vāyuḥ khṃ mano buddhireva ca ahaṅkāra itīyṃ me bhinnā prakṛtiraṣṭadhā",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Earth, water, fire, air, ether, mind, intellect and ego are my eightfold divided nature.",
    "commentary": "Plain: lower prakriti enumerated. Ramakantha: these eight are Shiva's own powers contracted, not alien matter.",
    "keyPoints": ["apara-prakriti as Shiva's contraction", "8-fold"]
  },
  {
    "id": "7.5",
    "number": "7.5",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "अपरेयमितस्त्वन्यां प्रकृतिं विद्धि मे पराम् । जीवभूतां महाबाहो ययेदं धार्यते जगत् ॥7.5॥",
    "iast": "apareyamitastvanyāṃ prakṛtiṃ viddhi me parām jīvabhūtāṃ mahābāho yayedṃ dhāryate jagat",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Beyond this lower nature know my higher nature as the living self by which the world is upheld.",
    "commentary": "Plain: jiva is higher prakriti sustaining cosmos. Ramakantha: jiva is Shiva as experiencer, holding lower through spanda.",
    "keyPoints": ["para-prakriti = jiva", "sustainer not renouncer"]
  },
  {
    "id": "7.6",
    "number": "7.6",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "एतद्योनीनि भूतानि सर्वाणीत्युपधारय । अहं कृत्स्नस्य जगतः प्रभवः प्रलयस्तथा ॥7.6॥",
    "iast": "etadyonīni bhūtāni sarvāṇītyupadhāraya ahṃ kṛtsnasya jagatḥ prabhavḥ pralayastathā",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Know all beings spring from these two natures, and I am the origin and dissolution of the whole world.",
    "commentary": "Plain: Krishna is source and end of all. Ramakantha: srishti-samhara are Shiva's projection-withdrawal, known while acting.",
    "keyPoints": ["prabhava-pralaya in one ground", "action as emission"]
  },
  {
    "id": "7.7",
    "number": "7.7",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "मत्तः परतरं नान्यत्किञ्चिदस्ति धनञ्जय । मयि सर्वमिदं प्रोतं सूत्रे मणिगणा इव ॥7.7॥",
    "iast": "mattḥ paratarṃ nānyatkiñcidasti dhanañjaya mayi sarvamidṃ protṃ sūtre maṇigaṇā iva",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Nothing higher than me exists, and all this is strung on me like gems on a thread.",
    "commentary": "Plain: Krishna is supreme thread of unity. Ramakantha: threading means karma-world rests on jnana-self without breaking continuity.",
    "keyPoints": ["supremacy without exclusion", "world strung on witness"]
  },
  {
    "id": "7.8",
    "number": "7.8",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "रसोऽहमप्सु कौन्तेय प्रभास्मि शशिसूर्ययोः । प्रणवः सर्ववेदेषु शब्दः खे पौरुषं नृषु ॥7.8॥",
    "iast": "rasohamapsu kaunteya prabhāsmi śaśisūryayoḥ praṇavḥ sarvavedeṣu śabdḥ khe pauruṣṃ nṛṣu",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I am taste in waters, light in sun and moon, Om in Vedas, sound in ether, manliness in men.",
    "commentary": "Plain: divine essence in sensible qualities. Ramakantha: tasting etc. are modes of perceiving Shiva in activity.",
    "keyPoints": ["essence in sense", "sacramental perception"]
  },
  {
    "id": "7.9",
    "number": "7.9",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "पुण्यो गन्धः पृथिव्यां च तेजश्चास्मि विभावसौ । जीवनं सर्वभूतेषु तपश्चास्मि तपस्विषु ॥7.9॥",
    "iast": "puṇyo gandhḥ pṛthivyāṃ ca tejaścāsmi vibhāvasau jīvanṃ sarvabhūteṣu tapaścāsmi tapasviṣu",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I am pure fragrance in earth, brilliance in fire, life in all beings, austerity in ascetics.",
    "commentary": "Plain: sustaining virtue in elements and effort. Ramakantha: tapas includes dutiful karma illumined by knowledge.",
    "keyPoints": ["purity as Shaiva vitality", "tapas = disciplined action"]
  },
  {
    "id": "7.10",
    "number": "7.10",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "बीजं मां सर्वभूतानां विद्धि पार्थ सनातनम् । बुद्धिर्बुद्धिमतामस्मि तेजस्तेजस्विनामहम् ॥7.10॥",
    "iast": "bījṃ māṃ sarvabhūtānāṃ viddhi pārtha sanātanam buddhirbuddhimatāmasmi tejastejasvināmaham",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Know me as the eternal seed of all beings, the intellect of the intelligent and splendour of the splendid.",
    "commentary": "Plain: Krishna is seed-capacity and luminous power. Ramakantha: seed is undivided I-consciousness sprouting as jnana-karma.",
    "keyPoints": ["eternal bija", "buddhi-tejas as Shiva-glow"]
  },
  {
    "id": "7.11",
    "number": "7.11",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "बलं बलवतां चाहं कामरागविवर्जितम् । धर्माविरुद्धो भूतेषु कामोऽस्मि भरतर्षभ ॥7.11॥",
    "iast": "balṃ balavatāṃ cāhṃ kāmarāgavivarjitam dharmāviruddho bhūteṣu kāmosmi bharatarṣabha",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I am strength of the strong free from desire and passion, and desire in beings not opposed to dharma.",
    "commentary": "Plain: sanctified power and lawful desire are divine. Ramakantha: desire yoked to dharma exemplifies karma purified by jnana.",
    "keyPoints": ["desireless strength", "dharmic kama allowed"]
  },
  {
    "id": "7.12",
    "number": "7.12",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "ये चैव सात्त्विका भावा राजसास्तामसाश्च ये । मत्त एवेति तान्विद्धि न त्वहं तेषु ते मयि ॥7.12॥",
    "iast": "ye caiva sāttvikā bhāvā rājasāstāmasāśca ye matta eveti tānviddhi na tvahṃ teṣu te mayi",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "All sattvic, rajasic and tamasic states come from me, yet I am not in them, they are in me.",
    "commentary": "Plain: gunas derive from Lord but do not bind him. Ramakantha: Shiva freely assumes gunas without being reduced to them.",
    "keyPoints": ["guna-source yet transcendent", "freedom in manifestation"]
  },
  {
    "id": "7.13",
    "number": "7.13",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "त्रिभिर्गुणमयैर्भावैरेभिः सर्वमिदं जगत् । मोहितं नाभिजानाति मामेभ्यः परमव्ययम् ॥7.13॥",
    "iast": "tribhirguṇamayairbhāvairebhiḥ sarvamidṃ jagat mohitṃ nābhijānāti māmebhyḥ paramavyayam",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Deluded by these three guna-states, the world fails to know me as higher and imperishable beyond them.",
    "commentary": "Plain: guna-delusion hides the imperishable. Ramakantha: delusion lifts only when knowing and doing are held together in witness.",
    "keyPoints": ["moha by gunas", "avyaya beyond"]
  },
  {
    "id": "7.14",
    "number": "7.14",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "दैवी ह्येषा गुणमयी मम माया दुरत्यया । मामेव ये प्रपद्यन्ते मायामेतां तरन्ति ते ॥7.14॥",
    "iast": "daivī hyeṣā guṇamayī mama māyā duratyayā māmeva ye prapadyante māyāmetāṃ taranti te",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "This divine guna-made maya of mine is hard to cross, but those who surrender to me cross it.",
    "commentary": "Plain: surrender crosses maya. Ramakantha: explicitly via Spanda Karika 46 — maya is Shiva's own freedom-power, crossed by recognising her as one's own spanda while acting, not by fleeing action.",
    "keyPoints": ["maya as svatantrya", "prapatti + spanda recognition"]
  },
  {
    "id": "7.15",
    "number": "7.15",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "न मां दुष्कृतिनो मूढाः प्रपद्यन्ते नराधमाः । माययापहृतज्ञाना आसुरं भावमाश्रिताः ॥7.15॥",
    "iast": "na māṃ duṣkṛtino mūḍhāḥ prapadyante narādhamāḥ māyayāpahṛtajñānā āsurṃ bhāvamāśritāḥ",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Evil-doing fools, lowest men robbed of knowledge by maya, resorting to demonic temper, do not surrender to me.",
    "commentary": "Plain: degraded dispositions block surrender. Ramakantha: loss of knowledge comes from divorcing karma from awareness, falling into inertia.",
    "keyPoints": ["apahrita-jnana", "asura as dissociation"]
  },
  {
    "id": "7.16",
    "number": "7.16",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "चतुर्विधा भजन्ते मां जनाः सुकृतिनोऽर्जुन । आर्तो जिज्ञासुरर्थार्थी ज्ञानी च भरतर्षभ ॥7.16॥",
    "iast": "caturvidhā bhajante māṃ janāḥ sukṛtinorjuna ārto jijñāsurarthārthī jñānī ca bharatarṣabha",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Four kinds of virtuous people worship me: the distressed, the inquirer, the wealth-seeker, and the knower.",
    "commentary": "Plain: four motives for devotion. Ramakantha: all four are graded approaches to same samuccaya, action gradually ripening into knowledge.",
    "keyPoints": ["four adhikaras", "devotion ripens"]
  },
  {
    "id": "7.17",
    "number": "7.17",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "तेषां ज्ञानी नित्ययुक्त एकभक्तिर्विशिष्यते । प्रियो हि ज्ञानिनोऽत्यर्थमाहं स च मम प्रियः ॥7.17॥",
    "iast": "teṣāṃ jñānī nityayukta ekabhaktirviśiṣyate priyo hi jñāninotyarthamāhṃ sa ca mama priyḥ",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Among them the ever-yoked knower with single devotion excels, for I am dear to him and he to me.",
    "commentary": "Plain: exclusive knower-devotee is highest. Ramakantha: ekabhakti is uninterrupted recognition sustaining all acts.",
    "keyPoints": ["nitya-yukta", "mutual love as recognition"]
  },
  {
    "id": "7.18",
    "number": "7.18",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "उदाराः सर्व एवैते ज्ञानी त्वात्मैव मे मतम् । आस्थितः स हि युक्तात्मा मामेवानुत्तमां गतिम् ॥7.18॥",
    "iast": "udārāḥ sarva evaite jñānī tvātmaiva me matam āsthitḥ sa hi yuktātmā māmevānuttamāṃ gatim",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "All these are noble, but the knower is my very self, abiding yoked to me as the supreme goal.",
    "commentary": "Plain: jnani identified with Lord. Ramakantha: identity is pratyabhijna — self recognised as Shiva while still acting.",
    "keyPoints": ["jnani = atma", "supreme gati in life"]
  },
  {
    "id": "7.19",
    "number": "7.19",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "बहूनां जन्मनामन्ते ज्ञानवान्मां प्रपद्यते । वासुदेवः सर्वमिति स महात्मा सुदुर्लभः ॥7.19॥",
    "iast": "bahūnāṃ janmanāmante jñānavānmāṃ prapadyate vāsudevḥ sarvamiti sa mahātmā sudurlabhḥ",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "After many births the knower surrenders to me, seeing Vasudeva as all; such a great soul is very rare.",
    "commentary": "Plain: ripened vision sees all as Vasudeva. Ramakantha: sarvam as Shiva's body, attained through combined path over births.",
    "keyPoints": ["Vasudeva-sarvam", "ripened samuccaya"]
  },
  {
    "id": "7.20",
    "number": "7.20",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "कामैस्तैस्तैर्हृतज्ञानाः प्रपद्यन्तेऽन्यदेवताः । तं तं नियममास्थाय प्रकृत्या नियताः स्वया ॥7.20॥",
    "iast": "kāmaistaistairhṛtajñānāḥ prapadyantenyadevatāḥ tṃ tṃ niyamamāsthāya prakṛtyā niyatāḥ svayā",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Robbed of discernment by various desires, men resort to other deities following particular rites impelled by nature.",
    "commentary": "Plain: fragmented desires lead to lesser gods. Ramakantha: fragmentation is worship without unifying Self-knowledge.",
    "keyPoints": ["hrta-jnana", "partial ends"]
  },
  {
    "id": "7.21",
    "number": "7.21",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "यो यो यां यां तनुं भक्तः श्रद्धयार्चितुमिच्छति । तस्य तस्याचलां श्रद्धां तामेव विदधाम्यहम् ॥7.21॥",
    "iast": "yo yo yāṃ yāṃ tanuṃ bhaktḥ śraddhayārcitumicchati tasya tasyācalāṃ śraddhāṃ tāmeva vidadhāmyaham",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Whatever form a devotee seeks to worship with faith, I make that faith steady.",
    "commentary": "Plain: Lord stabilizes all sincere faith. Ramakantha: steadiness comes from Shiva accommodating diverse karmic dispositions.",
    "keyPoints": ["faith stabilized", "inclusivity"]
  },
  {
    "id": "7.22",
    "number": "7.22",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "स तया श्रद्धया युक्तस्तस्याराधनमीहते । लभते च ततः कामान्मयैव विहितान्हि तान् ॥7.22॥",
    "iast": "sa tayā śraddhayā yuktastasyārādhanamīhate labhate ca tatḥ kāmānmayaiva vihitānhi tān",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Yoked by that faith he pursues that worship and obtains his desires, ordained by me.",
    "commentary": "Plain: fruits come through divine ordination. Ramakantha: even limited karma bears fruit when grounded in universal consciousness.",
    "keyPoints": ["ordained fruits", "limited yet real"]
  },
  {
    "id": "7.23",
    "number": "7.23",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "अन्तवत्तु फलं तेषां तद्भवत्यल्पमेधसाम् । देवान्देवयजो यान्ति मद्भक्ता यान्ति मामपि ॥7.23॥",
    "iast": "antavattu phalṃ teṣāṃ tadbhavatyalpamedhasām devāndevayajo yānti madbhaktā yānti māmapi",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Finite is the fruit for those of little wit; god-worshippers reach gods, my devotees reach me.",
    "commentary": "Plain: exclusive devotion gives imperishable果. Ramakantha: finite ends follow from dividing knowledge from All-Self; wholeness yields Shiva.",
    "keyPoints": ["anta-vat vs imperishable", "wholeness of end"]
  },
  {
    "id": "7.24",
    "number": "7.24",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "अव्यक्तं व्यक्तिमापन्नं मन्यन्ते मामबुद्धयः । परं भावमजानन्तो ममाव्ययमनुत्तमम् ॥7.24॥",
    "iast": "avyaktṃ vyaktimāpannṃ manyante māmabuddhayḥ parṃ bhāvamajānanto mamāvyayamanuttamam",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "The witless think me, the unmanifest, as become manifest, not knowing my higher imperishable unsurpassed state.",
    "commentary": "Plain: mistaking incarnation for limitation. Ramakantha: avyaya para-bhava is Shiva ever unmanifest even while manifest in act.",
    "keyPoints": ["avyakta in vyakti", "higher bhava"]
  },
  {
    "id": "7.25",
    "number": "7.25",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "नाहं प्रकाशः सर्वस्य योगमायासमावृतः । मूढोऽयं नाभिजानाति लोको मामजमव्ययम् ॥7.25॥",
    "iast": "nāhṃ prakāśḥ sarvasya yogamāyāsamāvṛtḥ mūḍhoyṃ nābhijānāti loko māmajamavyayam",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I am not manifest to all, veiled by yoga-maya; the deluded world knows not my birthless imperishable self.",
    "commentary": "Plain: maya-veil hides birthless Lord. Ramakantha: veil is playful self-concealment lifted by combined knowing-doing.",
    "keyPoints": ["yoga-maya veil", "aja-avyaya"]
  },
  {
    "id": "7.26",
    "number": "7.26",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "वेदाहं समतीतानि वर्तमानानि चार्जुन । भविष्याणि च भूतानि मां तु वेद न कश्चन ॥7.26॥",
    "iast": "vedāhṃ samatītāni vartamānāni cārjuna bhaviṣyāṇi ca bhūtāni māṃ tu veda na kaścana",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I know past, present and future beings, but none knows me.",
    "commentary": "Plain: omniscience yet hiddenness. Ramakantha: trikala-knowing is Shiva's citi, unknown until self-recognised.",
    "keyPoints": ["omniscience", "hidden subject"]
  },
  {
    "id": "7.27",
    "number": "7.27",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "इच्छाद्वेषसमुत्थेन द्वन्द्वमोहेन भारत । सर्वभूतानि सम्मोहं सर्गे यान्ति परन्तप ॥7.27॥",
    "iast": "icchādveṣasamutthena dvandvamohena bhārata sarvabhūtāni sammohṃ sarge yānti parantapa",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "By delusion of opposites born of desire and hatred, all beings fall into bewilderment at birth.",
    "commentary": "Plain: dvandva-moha from raga-dvesha. Ramakantha: opposites bind only when action lacks witnessing knowledge.",
    "keyPoints": ["dvandva-moha", "birth-bewilderment"]
  },
  {
    "id": "7.28",
    "number": "7.28",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "येषां त्वन्तगतं पापं जनानां पुण्यकर्मणाम् । ते द्वन्द्वमोहनिर्मुक्ता भजन्ते मां दृढव्रताः ॥7.28॥",
    "iast": "yeṣāṃ tvantagatṃ pāpṃ janānāṃ puṇyakarmaṇām te dvandvamohanirmuktā bhajante māṃ dṛḍhavratāḥ",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Those whose sin is ended through virtuous deeds, freed from opposite-delusion, worship me with firm vow.",
    "commentary": "Plain: punya-karma purifies for firm devotion. Ramakantha: textbook samuccaya — pure karma ends papa, freeing jnana.",
    "keyPoints": ["punya-karman purifies", "दृढव्रता"]
  },
  {
    "id": "7.29",
    "number": "7.29",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "जरामरणमोक्षाय मामाश्रित्य यतन्ति ये । ते ब्रह्म तद्विदुः कृत्स्नमध्यात्मं कर्म चाखिलम् ॥7.29॥",
    "iast": "jarāmaraṇamokṣāya māmāśritya yatanti ye te brahma tadviduḥ kṛtsnamadhyātmṃ karma cākhilam",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Those who strive for freedom from age and death taking refuge in me know Brahman entire, self-nature and all action.",
    "commentary": "Plain: refuge yields integral knowledge. Ramakantha: akhila-karma known as Brahman — action itself is Brahman-form.",
    "keyPoints": ["refuge-striving", "karma as Brahman"]
  },
  {
    "id": "7.30",
    "number": "7.30",
    "section": "Adhyāya 7 — Jñāna-vijñāna (Knowledge & Realisation)",
    "devanagari": "साधिभूताधिदैवं मां साधियज्ञं च ये विदुः । प्रयाणकालेऽपि च मां ते विदुर्युक्तचेतसः ॥7.30॥",
    "iast": "sādhibhūtādhidaivṃ māṃ sādhiyajñṃ ca ye viduḥ prayāṇakālepi ca māṃ te viduryuktacetasḥ",
    "conceptIds": ["gita-vijnana"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Those who know me as governing beings, gods and sacrifices know me even at death with yoked mind.",
    "commentary": "Plain: integral theism persists at death. Ramakantha: sacrifice-inclusiveness proves knowledge must accompany rite to the end.",
    "keyPoints": ["adhibhuta-adhidaiva-adhiyajna", "death-yoga"]
  },
  {
    "id": "8.1",
    "number": "8.1",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "अर्जुन उवाच — किं तद्ब्रह्म किमध्यात्मं किं कर्म पुरुषोत्तम । अधिभूतं च किं प्रोक्तमधिदैवं किमुच्यते ॥8.1॥",
    "iast": "arjuna uvāca kiṃ tadbrahma kimadhyātmṃ kiṃ karma puruṣottama adhibhūtṃ ca kiṃ proktamadhidaivṃ kimucyate",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "What is Brahman, self-nature, action, the ground of beings and of gods?",
    "commentary": "Plain: Arjuna asks seven terms. Ramakantha: questions seek map linking metaphysics to practice.",
    "keyPoints": ["seven questions", "bridge theory-praxis"]
  },
  {
    "id": "8.2",
    "number": "8.2",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "अधियज्ञः कथं कोऽत्र देहेऽस्मिन्मधुसूदन । प्रयाणकाले च कथं ज्ञेयोऽसि नियतात्मभिः ॥8.2॥",
    "iast": "adhiyajñḥ kathṃ kotra dehesminmadhusūdana prayāṇakāle ca kathṃ jñeyosi niyatātmabhiḥ",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Who is sacrifice-lord here in this body, and how are you known at death by self-controlled men?",
    "commentary": "Plain: asks immanent sacrifice and death-knowing. Ramakantha: deha as sacrificial ground where jnana-karma meet.",
    "keyPoints": ["adhiyajna in deha", "death-knowing"]
  },
  {
    "id": "8.3",
    "number": "8.3",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "श्रीभगवानुवाच — अक्षरं ब्रह्म परमं स्वभावोऽध्यात्ममुच्यते । भूतभावोद्भवकरो विसर्गः कर्मसंज्ञितः ॥8.3॥",
    "iast": "śrībhagavānuvāca akṣarṃ brahma paramṃ svabhāvodhyātmamucyate bhūtabhāvodbhavakaro visargḥ karmasṃjñitḥ",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "The imperishable supreme is Brahman, own-being is adhyatma, emission causing birth of beings is action.",
    "commentary": "Plain: definitions of three. Ramakantha: visarga-karma is Shiva's forth-emission, not bondage per se.",
    "keyPoints": ["aksara", "svabhava", "visarga as karma"]
  },
  {
    "id": "8.4",
    "number": "8.4",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "अधिभूतं क्षरो भावः पुरुषश्चाधिदैवतम् । अधियज्ञोऽहमेवात्र देहे देहभृतां वर ॥8.4॥",
    "iast": "adhibhūtṃ kṣaro bhāvḥ puruṣaścādhidaivatam adhiyajñohamevātra dehe dehabhṛtāṃ vara",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "The perishable existence is elemental ground, spirit is divine ground, and I as sacrifice-lord am here in the body.",
    "commentary": "Plain: immanent triad plus indwelling Lord. Ramakantha: deha contains sacrificer and witness together — Shaiva immanence.",
    "keyPoints": ["kshara-purusha", "aham in deha"]
  },
  {
    "id": "8.5",
    "number": "8.5",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "अन्तकाले च मामेव स्मरन्मुक्त्वा कलेवरम् । यः प्रयाति स मद्भावं याति नास्त्यत्र संशयः ॥8.5॥",
    "iast": "antakāle ca māmeva smaranmuktvā kalevaram yḥ prayāti sa madbhāvṃ yāti nāstyatra sṃśayḥ",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Who at death, remembering me alone, leaves the body attains my state without doubt.",
    "commentary": "Plain: final remembrance decides state. Ramakantha: remembrance is fruition of lifelong samuccaya, not momentary trick.",
    "keyPoints": ["anta-smarana", "lifelong ripening"]
  },
  {
    "id": "8.6",
    "number": "8.6",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "यं यं वापि स्मरन्भावं त्यजत्यन्ते कलेवरम् । तं तमेवैति कौन्तेय सदा तद्भावभावितः ॥8.6॥",
    "iast": "yṃ yṃ vāpi smaranbhāvṃ tyajatyante kalevaram tṃ tamevaiti kaunteya sadā tadbhāvabhāvitḥ",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Whatever state one remembers leaving the body, that alone one attains, ever steeped in that state.",
    "commentary": "Plain: habitual contemplation shapes transit. Ramakantha: bhavita habit is formed by united knowing-doing.",
    "keyPoints": ["habit shapes transit", "continual bhava"]
  },
  {
    "id": "8.7",
    "number": "8.7",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "तस्मात्सर्वेषु कालेषु मामनुस्मर युध्य च । मय्यर्पितमनोबुद्धिर्मामेवैष्यस्यसंशयम् ॥8.7॥",
    "iast": "tasmātsarveṣu kāleṣu māmanusmara yudhya ca mayyarpitamanobuddhirmāmevaiṣyasyasṃśayam",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Therefore at all times remember me and fight, with mind-intellect surrendered to me you shall reach me.",
    "commentary": "Plain: classic karma-yoga injunction. Ramakantha: proof-text for samuccaya — smara plus yudhya together.",
    "keyPoints": ["anusmara + yudhya", "arpita-mano-buddhi"]
  },
  {
    "id": "8.8",
    "number": "8.8",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "अभ्यासयोगयुक्तेन चेतसा नान्यगामिना । परमं पुरुषं दिव्यं याति पार्थानुचिन्तयन् ॥8.8॥",
    "iast": "abhyāsayogayuktena cetasā nānyagāminā paramṃ puruṣṃ divyṃ yāti pārthānucintayan",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "With practice-yoked unflickering mind, contemplating, one reaches the supreme divine Person.",
    "commentary": "Plain: abhyasa fixes mind on Supreme. Ramakantha: abhyasa is repeated recognition amidst acts.",
    "keyPoints": ["abhyasa-yoga", "ananya-gami mind"]
  },
  {
    "id": "8.9",
    "number": "8.9",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "कविं पुराणमनुशासितारमणोरणीयांसमनुस्मरेद्यः । सर्वस्य धातारमचिन्त्यरूपमादित्यवर्णं तमसः परस्तात् ॥8.9॥",
    "iast": "kaviṃ purāṇamanuśāsitāramaṇoraṇīyāṃsamanusmaredyḥ sarvasya dhātāramacintyarūpamādityavarṇṃ tamasḥ parastāt",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Who contemplates the seer, ancient, ruler, subtler than subtle, supporter of all, unthinkable-form, sun-hued beyond darkness.",
    "commentary": "Plain: cosmic attributes for meditation. Ramakantha: these are Shiva's pervasive light-attributes, darkness-transcending.",
    "keyPoints": ["kavi-purana", "light beyond tamas"]
  },
  {
    "id": "8.10",
    "number": "8.10",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "प्रयाणकाले मनसाचलेन भक्त्या युक्तो योगबलेन चैव । भ्रुवोर्मध्ये प्राणमावेश्य सम्यक् स तं परं पुरुषमुपैति दिव्यम् ॥8.10॥",
    "iast": "prayāṇakāle manasācalena bhaktyā yukto yogabalena caiva bhruvormadhye prāṇamāveśya samyak sa tṃ parṃ puruṣamupaiti divyam",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "At death with steady mind, devotion and yoga-power, fixing breath between brows, one reaches that supreme Person.",
    "commentary": "Plain: death-yoga technique. Ramakantha: technique works because prana-mind are Shiva-energies gathered by devotion-action.",
    "keyPoints": ["bhrumadhya", "yoga-bala"]
  },
  {
    "id": "8.11",
    "number": "8.11",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "यदक्षरं वेदविदो वदन्ति विशन्ति यद्यतयो वीतरागाः । यदिच्छन्तो ब्रह्मचर्यं चरन्ति तत्ते पदं सङ्ग्रहेण प्रवक्ष्ये ॥8.11॥",
    "iast": "yadakṣarṃ vedavido vadanti viśanti yadyatayo vītarāgāḥ yadicchanto brahmacaryṃ caranti tatte padṃ saṅgraheṇa pravakṣye",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "That imperishable which Veda-knowers declare, passion-free ascetics enter, seeking which they live chastely — that goal I shall briefly tell.",
    "commentary": "Plain: introduces aksara-goal. Ramakantha: aksara sought through disciplined karma as well as detachment.",
    "keyPoints": ["aksara goal", "brahmacharya as discipline"]
  },
  {
    "id": "8.12",
    "number": "8.12",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "सर्वद्वाराणि संयम्य मनो हृदि निरुध्य च । मूर्ध्न्याधायात्मनः प्राणमास्थितो योगधारणाम् ॥8.12॥",
    "iast": "sarvadvārāṇi sṃyamya mano hṛdi nirudhya ca mūrdhnyādhāyātmanḥ prāṇamāsthito yogadhāraṇām",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Restraining all gates, confining mind in heart, fixing life-breath in head, established in yoga-concentration.",
    "commentary": "Plain: interior gathering. Ramakantha: sense-restraint is karma restrained by knowledge, not abandoned.",
    "keyPoints": ["dvara-samyama", "dharana"]
  },
  {
    "id": "8.13",
    "number": "8.13",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "ओमित्येकाक्षरं ब्रह्म व्याहरन्मामनुस्मरन् । यः प्रयाति त्यजन्देहं स याति परमां गतिम् ॥8.13॥",
    "iast": "omityekākṣarṃ brahma vyāharanmāmanusmaran yḥ prayāti tyajandehṃ sa yāti paramāṃ gatim",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Uttering Om, the single-syllable Brahman, remembering me, departing the body, one reaches the supreme goal.",
    "commentary": "Plain: Om plus remembrance at exit. Ramakantha: vac-action and smriti-knowledge fused in one utterance.",
    "keyPoints": ["Om", "remembrance-utterance union"]
  },
  {
    "id": "8.14",
    "number": "8.14",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "अनन्यचेताः सततं यो मां स्मरति नित्यशः । तस्याहं सुलभः पार्थ नित्ययुक्तस्य योगिनः ॥8.14॥",
    "iast": "ananyacetāḥ satatṃ yo māṃ smarati nityaśḥ tasyāhṃ sulabhḥ pārtha nityayuktasya yoginḥ",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Who remembers me constantly with undivided mind, to that ever-yoked yogi I am easily attained.",
    "commentary": "Plain: ease through constancy. Ramakantha: satata-smriti sustained amidst duties proves samuccaya's continuity.",
    "keyPoints": ["ananya-cetas", "sulabha"]
  },
  {
    "id": "8.15",
    "number": "8.15",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "मामुपेत्य पुनर्जन्म दुःखालयमशाश्वतम् । नाप्नुवन्ति महात्मानः संसिद्धिं परमां गताः ॥8.15॥",
    "iast": "māmupetya punarjanma duḥkhālayamaśāśvatam nāpnuvanti mahātmānḥ sṃsiddhiṃ paramāṃ gatāḥ",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Reaching me, great souls do not return to rebirth, abode of sorrow impermanent, having attained supreme perfection.",
    "commentary": "Plain: no return after attainment. Ramakantha: non-return is freedom even while living-acting, jivanmukti.",
    "keyPoints": ["no punarjanma", "samsiddhi"]
  },
  {
    "id": "8.16",
    "number": "8.16",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "आब्रह्मभुवनाल्लोकाः पुनरावर्तिनोऽर्जुन । मामुपेत्य तु कौन्तेय पुनर्जन्म न विद्यते ॥8.16॥",
    "iast": "ābrahmabhuvanāllokāḥ punarāvartinorjuna māmupetya tu kaunteya punarjanma na vidyate",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Worlds up to Brahma's realm return again, but reaching me there is no rebirth.",
    "commentary": "Plain: cosmic hierarchy vs finality. Ramakantha: even high karmic heavens return unless illumined by Shiva-knowledge.",
    "keyPoints": ["abrahmabhuvana", "finality in me"]
  },
  {
    "id": "8.17",
    "number": "8.17",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "सहस्रयुगपर्यन्तमहर्यद्ब्रह्मणो विदुः । रात्रिं युगसहस्रान्तां तेऽहोरात्रविदो जनाः ॥8.17॥",
    "iast": "sahasrayugaparyantamaharyadbrahmaṇo viduḥ rātriṃ yugasahasrāntāṃ tehorātravido janāḥ",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Those who know a day of Brahma lasts a thousand ages and night likewise know day and night.",
    "commentary": "Plain: cosmic time scale. Ramakantha: time-cycles are Shiva's pulsation writ large.",
    "keyPoints": ["Brahma day-night", "cosmic rhythm"]
  },
  {
    "id": "8.18",
    "number": "8.18",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "अव्यक्ताद्व्यक्तयः सर्वाः प्रभवन्त्यहरागमे । रात्र्यागमे प्रलीयन्ते तत्रैवाव्यक्तसंज्ञके ॥8.18॥",
    "iast": "avyaktādvyaktayḥ sarvāḥ prabhavantyaharāgame rātryāgame pralīyante tatraivāvyaktasṃjñake",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "From the unmanifest all manifest spring at day's advent, and dissolve into the same unmanifest at night.",
    "commentary": "Plain: cyclic emission-dissolution. Ramakantha: avyakta is Shiva's withdrawal state, not void.",
    "keyPoints": ["cyclic vyakta", "avyakta ground"]
  },
  {
    "id": "8.19",
    "number": "8.19",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "भूतग्रामः स एवायं भूत्वा भूत्वा प्रलीयते । रात्र्यागमेऽवशः पार्थ प्रभवत्यहरागमे ॥8.19॥",
    "iast": "bhūtagrāmḥ sa evāyṃ bhūtvā bhūtvā pralīyate rātryāgamevaśḥ pārtha prabhavatyaharāgame",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "This same host of beings helplessly recurs, dissolving at night, emerging at day.",
    "commentary": "Plain: helpless repetition under prakriti. Ramakantha: helplessness ends when emission is recognised as self's freedom.",
    "keyPoints": ["bhutagrama", "avasha repetition"]
  },
  {
    "id": "8.20",
    "number": "8.20",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "परस्तस्मात्तु भावोऽन्यो व्यक्ताव्यक्तः सनातनः । यः स सर्वेषु भूतेषु नश्यत्सु न विनश्यति ॥8.20॥ [K: व्यक्ताव्यक्तः सनातनः]",
    "iast": "parastasmāttu bhāvonyo vyaktāvyaktḥ sanātanḥ yḥ sa sarveṣu bhūteṣu naśyatsu na vinaśyati vyaktāvyaktḥ sanātanḥ",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Rāmakantha pāṭha: Rāmakantha: vyaktāvyaktaḥ sanātanaḥ."}],
    "translation": "Beyond that is another eternal state, manifest-unmanifest, imperishable amid perishing beings.",
    "commentary": "Plain: higher imperishable beyond cycles. Ramakantha variant stresses one reality as both vyakta and avyakta — Shiva as eternal manifest-unmanifest continuum.",
    "keyPoints": ["vyaktavyaktah", "imperishable beyond cycles"]
  },
  {
    "id": "8.21",
    "number": "8.21",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "अव्यक्तोऽक्षर इत्युक्तस्तमाहुः परमां गतिम् । यं प्राप्य न निवर्तन्ते तद्धाम परमं मम ॥8.21॥",
    "iast": "avyaktokṣara ityuktastamāhuḥ paramāṃ gatim yṃ prāpya na nivartante taddhāma paramṃ mama",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Called unmanifest imperishable, supreme goal, attaining which none return — that is my supreme abode.",
    "commentary": "Plain: aksara as final abode. Ramakantha: dhama is Shiva's luminous abode attained by samuccaya.",
    "keyPoints": ["aksara-gati", "parama-dhama"]
  },
  {
    "id": "8.22",
    "number": "8.22",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "पुरुषः स परः पार्थ भक्त्या लभ्यस्त्वनन्यया । यत्र सर्वं प्रतिष्ठितम् [K variant for येन सर्वमिदं ततम्] ॥8.22॥ — पूरा: यस्यान्तःस्थानि भूतानि यत्र सर्वं प्रतिष्ठितम् ॥8.22॥",
    "iast": "puruṣḥ sa parḥ pārtha bhaktyā labhyastvananyayā yatra sarvṃ pratiṣṭhitam yena sarvamidṃ tatam pūrā yasyāntḥsthāni bhūtāni yatra sarvṃ pratiṣṭhitam",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "That supreme Person is attained by exclusive devotion, in whom beings abide and in whom all is established.",
    "commentary": "Plain: ananya-bhakti reaches All-ground. Ramakantha: pratishthitam stresses world established in Shiva, known through loving recognition plus duty.",
    "keyPoints": ["ananya-bhakti", "all-established-in-Him"]
  },
  {
    "id": "8.23",
    "number": "8.23",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "यत्र काले त्वनावृत्तिमावृत्तिं चैव योगिनः । प्रयाता यान्ति तं कालं वक्ष्यामि भरतर्षभ ॥8.23॥",
    "iast": "yatra kāle tvanāvṛttimāvṛttiṃ caiva yoginḥ prayātā yānti tṃ kālṃ vakṣyāmi bharatarṣabha",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "The time when yogis departing attain non-return or return, that time I shall tell.",
    "commentary": "Plain: introduces uttarayana lore. Ramakantha: kala-marga symbolic of clarity vs obscurity in consciousness.",
    "keyPoints": ["anavritti-avritti", "death-time lore"]
  },
  {
    "id": "8.24",
    "number": "8.24",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "अग्निर्ज्योतिरहः शुक्लः षण्मासा उत्तरायणम् । तत्र प्रयाता गच्छन्ति ब्रह्म ब्रह्मविदो जनाः ॥8.24॥",
    "iast": "agnirjyotirahḥ śuklḥ ṣaṇmāsā uttarāyaṇam tatra prayātā gacchanti brahma brahmavido janāḥ",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Fire, light, day, bright fortnight, six months northward — departing there Brahman-knowers reach Brahman.",
    "commentary": "Plain: bright path to non-return. Ramakantha: brightness is ascendancy of jnana illumining karma.",
    "keyPoints": ["archiradi path", "light ascendancy"]
  },
  {
    "id": "8.25",
    "number": "8.25",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "धूमो रात्रिस्तथा कृष्णः षण्मासा दक्षिणायनम् । तत्र चान्द्रमसं ज्योतिर्योगी प्राप्य निवर्तते ॥8.25॥",
    "iast": "dhūmo rātristathā kṛṣṇḥ ṣaṇmāsā dakṣiṇāyanam tatra cāndramasṃ jyotiryogī prāpya nivartate",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Smoke, night, dark fortnight, six months southward — the yogi reaching lunar light returns.",
    "commentary": "Plain: dark path returns. Ramakantha: smoke-path is karma without full recognition, hence return.",
    "keyPoints": ["dhuma path", "return"]
  },
  {
    "id": "8.26",
    "number": "8.26",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "शुक्लकृष्णे गती ह्येते जगतः शाश्वते मते । एकया यात्यनावृत्तिमन्ययावर्तते पुनः ॥8.26॥",
    "iast": "śuklakṛṣṇe gatī hyete jagatḥ śāśvate mate ekayā yātyanāvṛttimanyayāvartate punḥ",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "These bright and dark courses are deemed eternal; by one goes to non-return, by other returns.",
    "commentary": "Plain: two eternal courses. Ramakantha: two courses are knowledge-lit vs knowledge-dim action.",
    "keyPoints": ["two gatis", "lit vs dim"]
  },
  {
    "id": "8.27",
    "number": "8.27",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "नैते सृती पार्थ जानन्योगी मुह्यति कश्चन । तस्मात्सर्वेषु कालेषु योगयुक्तो भवार्जुन ॥8.27॥",
    "iast": "naite sṛtī pārtha jānanyogī muhyati kaścana tasmātsarveṣu kāleṣu yogayukto bhavārjuna",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Knowing these courses no yogi is deluded; therefore at all times be yoga-yoked.",
    "commentary": "Plain: knowledge prevents delusion. Ramakantha: steady samuccaya transcends concern for transit times.",
    "keyPoints": ["no moha", "constant yoga"]
  },
  {
    "id": "8.28",
    "number": "8.28",
    "section": "Adhyāya 8 — Akṣara-brahma (Imperishable)",
    "devanagari": "वेदेषु यज्ञेषु तपःसु चैव दानेषु यत्पुण्यफलं प्रदिष्टम् । अत्येति तत्सर्वमिदं विदित्वा योगी परं स्थानमुपैति चाद्यम् ॥8.28॥",
    "iast": "vedeṣu yajñeṣu tapḥsu caiva dāneṣu yatpuṇyaphalṃ pradiṣṭam atyeti tatsarvamidṃ viditvā yogī parṃ sthānamupaiti cādyam",
    "conceptIds": ["gita-aksara"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Whatever merit is declared in Vedas, sacrifices, austerities and gifts, the yogi transcends all that knowing this, reaching prime supreme abode.",
    "commentary": "Plain: integral knowledge excels ritual merit. Ramakantha: transcendence includes, not rejects, Vedic karma fulfilled in knowing.",
    "keyPoints": ["transcends punya-phala", "adya-sthana"]
  },
  {
    "id": "9.1",
    "number": "9.1",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "श्रीभगवानुवाच — इदं तु ते गुह्यतमं प्रवक्ष्याम्यनसूयवे । ज्ञानं विज्ञानसहितं यज्ज्ञात्वा मोक्ष्यसेऽशुभात् ॥9.1॥",
    "iast": "śrībhagavānuvāca idṃ tu te guhyatamṃ pravakṣyāmyanasūyave jñānṃ vijñānasahitṃ yajjñātvā mokṣyaseśubhāt",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "To you ungrudging I shall declare the most secret knowledge with realisation, knowing which you shall be freed from evil.",
    "commentary": "Plain: secret wisdom for the receptive. Ramakantha: guhyatama is Shiva-recognition hidden in plain action.",
    "keyPoints": ["guhyatama", "anasuya adhikara"]
  },
  {
    "id": "9.2",
    "number": "9.2",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "राजविद्या राजगुह्यं पवित्रमिदमुत्तमम् । प्रत्यक्षावगमं धर्म्यं सुसुखं कर्तुमव्ययम् ॥9.2॥",
    "iast": "rājavidyā rājaguhyṃ pavitramidamuttamam pratyakṣāvagamṃ dharmyṃ susukhṃ kartumavyayam",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "King-science, king-secret, supreme purifier, directly perceivable, righteous, easy to practise, imperishable.",
    "commentary": "Plain: accessible yet supreme. Ramakantha: susukham kartum proves karma included — direct perception while doing.",
    "keyPoints": ["pratyaksha", "easy practice"]
  },
  {
    "id": "9.3",
    "number": "9.3",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "अश्रद्दधानाः पुरुषा धर्मस्यास्य परन्तप । अप्राप्य मां निवर्तन्ते मृत्युसंसारवर्त्मनि ॥9.3॥",
    "iast": "aśraddadhānāḥ puruṣā dharmasyāsya parantapa aprāpya māṃ nivartante mṛtyusṃsāravartmani",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Men without faith in this dharma, not reaching me, return to death-transmigration path.",
    "commentary": "Plain: faithless return. Ramakantha: ashraddha is refusal to unite knowing and doing.",
    "keyPoints": ["ashraddha", "return to samsara"]
  },
  {
    "id": "9.4",
    "number": "9.4",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "मया ततमिदं सर्वं जगदव्यक्तमूर्तिना । मत्स्थानि सर्वभूतानि न चाहं तेष्ववस्थितः ॥9.4॥",
    "iast": "mayā tatamidṃ sarvṃ jagadavyaktamūrtinā matsthāni sarvabhūtāni na cāhṃ teṣvavasthitḥ",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "All this world is pervaded by me in unmanifest form; all beings abide in me, I not in them.",
    "commentary": "Plain: pervasion yet transcendence. Ramakantha: avyakta-murti is Shiva pervading acts without being confined.",
    "keyPoints": ["pervasion", "abiding paradox"]
  },
  {
    "id": "9.5",
    "number": "9.5",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "न च मत्स्थानि भूतानि पश्य मे योगमैश्वरम् । भूतभृन्न च भूतस्थो ममात्मा भूतभावनः ॥9.5॥",
    "iast": "na ca matsthāni bhūtāni paśya me yogamaiśvaram bhūtabhṛnna ca bhūtastho mamātmā bhūtabhāvanḥ",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Nor do beings abide in me — behold my lordly yoga — supporting yet not dwelling, my self causes beings.",
    "commentary": "Plain: paradox of support. Ramakantha: aishvara-yoga is svatantrya holding world without clinging.",
    "keyPoints": ["bhutabhrit", "paradox-yoga"]
  },
  {
    "id": "9.6",
    "number": "9.6",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "यथाकाशस्थितो नित्यं वायुः सर्वत्रगो महान् । तथा सर्वाणि भूतानि मत्स्थानीत्युपधारय ॥9.6॥",
    "iast": "yathākāśasthito nityṃ vāyuḥ sarvatrago mahān tathā sarvāṇi bhūtāni matsthānītyupadhāraya",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "As mighty all-moving wind ever rests in ether, so all beings rest in me.",
    "commentary": "Plain: ether-wind analogy. Ramakantha: ether is consciousness-space wherein karmic winds move.",
    "keyPoints": ["akasha-vayu", "consciousness-space"]
  },
  {
    "id": "9.7",
    "number": "9.7",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "सर्वभूतानि कौन्तेय प्रकृतिं यान्ति मामिकाम् । कल्पक्षये पुनस्तानि कल्पादौ विसृजाम्यहम् ॥9.7॥",
    "iast": "sarvabhūtāni kaunteya prakṛtiṃ yānti māmikām kalpakṣaye punastāni kalpādau visṛjāmyaham",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "All beings enter my nature at kalpa's end, and I emit them again at kalpa's dawn.",
    "commentary": "Plain: cyclic withdrawal-emission. Ramakantha: mamika-prakriti is Shiva's own power, emission is worshipful act.",
    "keyPoints": ["kalpa cycle", "emission"]
  },
  {
    "id": "9.8",
    "number": "9.8",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "प्रकृतिं स्वामवष्टभ्य विसृजामि पुनः पुनः । भूतग्राममिमं कृत्स्नमवशं प्रकृतेर्वशात् ॥9.8॥",
    "iast": "prakṛtiṃ svāmavaṣṭabhya visṛjāmi punḥ punḥ bhūtagrāmamimṃ kṛtsnamavaśṃ prakṛtervaśāt",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Resting on my nature I emit again and again this helpless host under nature's sway.",
    "commentary": "Plain: compassion despite helplessness. Ramakantha: avashtabhya shows freedom — Shiva creates though beings feel compelled.",
    "keyPoints": ["svam prakritim", "freedom in recurrence"]
  },
  {
    "id": "9.9",
    "number": "9.9",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "न च मां तानि कर्माणि निबध्नन्ति धनञ्जय । उदासीनवदासीनमसक्तं तेषु कर्मसु ॥9.9॥",
    "iast": "na ca māṃ tāni karmāṇi nibadhnanti dhanañjaya udāsīnavadāsīnamasaktṃ teṣu karmasu",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Nor do those actions bind me, seated as indifferent, unattached to those actions.",
    "commentary": "Plain: unattached creator. Ramakantha: udasina is witness-posture to be adopted while performing karma.",
    "keyPoints": ["non-binding", "udasina model"]
  },
  {
    "id": "9.10",
    "number": "9.10",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "मयाध्यक्षेण प्रकृतिः सूयते सचराचरम् । हेतुनानेन कौन्तेय जगद्विपरिवर्तते ॥9.10॥",
    "iast": "mayādhyakṣeṇa prakṛtiḥ sūyate sacarācaram hetunānena kaunteya jagadviparivartate",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Under my overseership nature brings forth moving-unmoving, and for this reason the world revolves.",
    "commentary": "Plain: overseen prakriti creates. Ramakantha: adhyaksha is witnessing Shiva making karma fertile without entanglement.",
    "keyPoints": ["adhyaksha", "prakriti instrument"]
  },
  {
    "id": "9.11",
    "number": "9.11",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "अवजानन्ति मां मूढा मानुषीं तनुमाश्रितम् । परं भावमजानन्तो मम भूतमहेश्वरम् ॥9.11॥",
    "iast": "avajānanti māṃ mūḍhā mānuṣīṃ tanumāśritam parṃ bhāvamajānanto mama bhūtamaheśvaram",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Fools despise me dwelling in human form, not knowing my higher state as great lord of beings.",
    "commentary": "Plain: avatar-contempt by ignorant. Ramakantha: bhuta-maheshvara signals Shaiva great-lordship behind human veil.",
    "keyPoints": ["manusim tanum", "maheshvara hidden"]
  },
  {
    "id": "9.12",
    "number": "9.12",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "मोघाशा मोघकर्माणो मोघज्ञाना विचेतसः । राक्षसीमासुरीं चैव प्रकृतिं मोहिनीं श्रिताः ॥9.12॥",
    "iast": "moghāśā moghakarmāṇo moghajñānā vicetasḥ rākṣasīmāsurīṃ caiva prakṛtiṃ mohinīṃ śritāḥ",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Vain hopes, vain acts, vain knowledge, witless, resorting to deluding demonic nature.",
    "commentary": "Plain: futility of asuric temper. Ramakantha: mogha because jnana and karma divorced.",
    "keyPoints": ["mogha triad", "mohini prakriti"]
  },
  {
    "id": "9.13",
    "number": "9.13",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "महात्मानस्तु मां पार्थ दैवीं प्रकृतिमाश्रिताः । भजन्त्यनन्यमनसो ज्ञात्वा भूतादिमव्ययम् ॥9.13॥",
    "iast": "mahātmānastu māṃ pārtha daivīṃ prakṛtimāśritāḥ bhajantyananyamanaso jñātvā bhūtādimavyayam",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Great souls resorting to divine nature worship me single-minded, knowing me as origin imperishable.",
    "commentary": "Plain: daivi-nature leads to single devotion. Ramakantha: daivi is Shiva's luminous freedom expressing as unified practice.",
    "keyPoints": ["daivi prakriti", "ananya-manas"]
  },
  {
    "id": "9.14",
    "number": "9.14",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "सततं कीर्तयन्तो मां यतन्तश्च दृढव्रताः । नमस्यन्तश्च मां भक्त्या नित्ययुक्ता उपासते ॥9.14॥",
    "iast": "satatṃ kīrtayanto māṃ yatantaśca dṛḍhavratāḥ namasyantaśca māṃ bhaktyā nityayuktā upāsate",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Ever glorifying me, striving firm-vowed, bowing with devotion, ever-yoked they attend.",
    "commentary": "Plain: devotional disciplines. Ramakantha: kirtana-yatna-namasya show karma as worship fused with knowledge.",
    "keyPoints": ["kirtana-yatna", "nitya-yukta"]
  },
  {
    "id": "9.15",
    "number": "9.15",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "ज्ञानयज्ञेन चाप्यन्ये यजन्तो मामुपासते । एकत्वेन पृथक्त्वेन बहुधा विश्वतोमुखम् ॥9.15॥",
    "iast": "jñānayajñena cāpyanye yajanto māmupāsate ekatvena pṛthaktvena bahudhā viśvatomukham",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Others worship tending me through knowledge-sacrifice as one, as distinct, as manifold facing-all.",
    "commentary": "Plain: three modes of jnana-yajna. Ramakantha: ekattva-prithaktva-bahudha are Shaiva modes of unity-in-difference.",
    "keyPoints": ["jnana-yajna", "three visions"]
  },
  {
    "id": "9.16",
    "number": "9.16",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "अहं क्रतुरहं यज्ञः स्वधाहमहमौषधम् । मन्त्रोऽहमहमेवाज्यमहमग्निरहं हुतम् ॥9.16॥",
    "iast": "ahṃ kraturahṃ yajñḥ svadhāhamahamauṣadham mantrohamahamevājyamahamagnirahṃ hutam",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I am rite, sacrifice, ancestral offering, herb, mantra, ghee, fire and oblation.",
    "commentary": "Plain: all sacrificial elements are Lord. Ramakantha: totalizing sacrifice sanctifies outer karma as Shiva.",
    "keyPoints": ["sacrifice identity", "karma sanctified"]
  },
  {
    "id": "9.17",
    "number": "9.17",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "पिताहमस्य जगतो माता धाता पितामहः । वेद्यं पवित्रमोङ्कार ऋक्साम यजुरेव च ॥9.17॥",
    "iast": "pitāhamasya jagato mātā dhātā pitāmahḥ vedyṃ pavitramoṅkāra ṛksāma yajureva ca",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I am father, mother, supporter, grandsire of world, knowable, purifier, Om and three Vedas.",
    "commentary": "Plain: familial and Vedic pervasion. Ramakantha: pitamaha includes lineage of teachers transmitting samuccaya.",
    "keyPoints": ["father-mother", "Om-Veda"]
  },
  {
    "id": "9.18",
    "number": "9.18",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "गतिर्भर्ता प्रभुः साक्षी निवासः शरणं सुहृत् । प्रभवः प्रलयः स्थानं निधानं बीजमव्ययम् ॥9.18॥",
    "iast": "gatirbhartā prabhuḥ sākṣī nivāsḥ śaraṇṃ suhṛt prabhavḥ pralayḥ sthānṃ nidhānṃ bījamavyayam",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Goal, supporter, lord, witness, abode, refuge, friend, origin, dissolution, ground, treasure, imperishable seed.",
    "commentary": "Plain: twelve shelters. Ramakantha: sakshi-sharana pair joins knowing-refuge with active support.",
    "keyPoints": ["gati-bharta-sakshi", "refuge"]
  },
  {
    "id": "9.19",
    "number": "9.19",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "तपाम्यहमहं वर्षं निगृह्णाम्युत्सृजामि च । अमृतं चैव मृत्युश्च सदसच्चाहमर्जुन ॥9.19॥",
    "iast": "tapāmyahamahṃ varṣṃ nigṛhṇāmyutsṛjāmi ca amṛtṃ caiva mṛtyuśca sadasaccāhamarjuna",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I heat, withhold and release rain; I am deathlessness and death, being and non-being.",
    "commentary": "Plain: opposites in Lord. Ramakantha: opposites held by Shiva's inclusive freedom.",
    "keyPoints": ["rain-giver", "sat-asat in one"]
  },
  {
    "id": "9.20",
    "number": "9.20",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "त्रैविद्या मां सोमपाः पूतपापा यज्ञैरिष्ट्वा स्वर्गतिं प्रार्थयन्ते । ते पुण्यमासाद्य सुरेन्द्रलोकमश्नन्ति दिव्यान्दिवि देवभोगान् ॥9.20॥",
    "iast": "traividyā māṃ somapāḥ pūtapāpā yajñairiṣṭvā svargatiṃ prārthayante te puṇyamāsādya surendralokamaśnanti divyāndivi devabhogān",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Three-Veda soma-drinkers purified of sin, sacrificing, pray for heaven, attaining Indra's world enjoy divine delights.",
    "commentary": "Plain: Vedic heaven-seekers. Ramakantha: legitimate but limited fruit of karma without full recognition.",
    "keyPoints": ["traividya", "heaven fruit"]
  },
  {
    "id": "9.21",
    "number": "9.21",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "ते तं भुक्त्वा स्वर्गलोकं विशालं क्षीणे पुण्ये मर्त्यलोकं विशन्ति । एवं त्रयीधर्ममनुप्रपन्ना गतागतं कामकामा लभन्ते ॥9.21॥",
    "iast": "te tṃ bhuktvā svargalokṃ viśālṃ kṣīṇe puṇye martyalokṃ viśanti evṃ trayīdharmamanuprapannā gatāgatṃ kāmakāmā labhante",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Enjoying vast heaven when merit exhausts they enter mortal world; thus following triple dharma, desiring desires, they come and go.",
    "commentary": "Plain: exhaustion and return. Ramakantha: gata-agata ends only when karma wedded to knowledge.",
    "keyPoints": ["kshine punye", "coming-going"]
  },
  {
    "id": "9.22",
    "number": "9.22",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "अनन्याश्चिन्तयन्तो मां ये जनाः पर्युपासते । तेषां नित्याभियुक्तानां योगक्षेमं वहाम्यहम् ॥9.22॥",
    "iast": "ananyāścintayanto māṃ ye janāḥ paryupāsate teṣāṃ nityābhiyuktānāṃ yogakṣemṃ vahāmyaham",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Those who attend me exclusively contemplating me — to them ever-devoted I bear acquisition and preservation.",
    "commentary": "Plain: Lord carries burden. Ramakantha: yogakshema is Shiva sustaining both contemplation and worldly duty.",
    "keyPoints": ["ananya contemplation", "borne welfare"]
  },
  {
    "id": "9.23",
    "number": "9.23",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "येऽप्यन्यदेवता भक्ता यजन्ते श्रद्धयान्विताः । तेऽपि मामेव कौन्तेय यजन्त्यविधिपूर्वकम् ॥9.23॥",
    "iast": "yepyanyadevatā bhaktā yajante śraddhayānvitāḥ tepi māmeva kaunteya yajantyavidhipūrvakam",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Devotees of other gods sacrificing with faith sacrifice to me alone, though not by true rule.",
    "commentary": "Plain: oblique worship reaches Lord. Ramakantha: avidhi is lack of wholeness-awareness, yet still Shiva-directed.",
    "keyPoints": ["oblique worship", "avidhi"]
  },
  {
    "id": "9.24",
    "number": "9.24",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "अहं हि सर्वयज्ञानां भोक्ता च प्रभुरेव च । न तु मामभिजानन्ति तत्त्वेनातश्च्यवन्ति ते ॥9.24॥",
    "iast": "ahṃ hi sarvayajñānāṃ bhoktā ca prabhureva ca na tu māmabhijānanti tattvenātaścyavanti te",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I am enjoyer and lord of all sacrifices, but they know me not in truth, hence they fall.",
    "commentary": "Plain: ignorance causes fall. Ramakantha: tattvena is samuccaya-recognition; without it, karma drops.",
    "keyPoints": ["bhokta-prabhu", "fall by non-knowing"]
  },
  {
    "id": "9.25",
    "number": "9.25",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "यान्ति देवव्रता देवान्पितॄन्यान्ति पितृव्रताः । भूतानि यान्ति भूतेज्या यान्ति मद्याजिनोऽपि माम् ॥9.25॥",
    "iast": "yānti devavratā devānpitṝnyānti pitṛvratāḥ bhūtāni yānti bhūtejyā yānti madyājinopi mām",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "God-vowed reach gods, ancestor-vowed ancestors, being-worshippers beings, my sacrificers reach me.",
    "commentary": "Plain: end matches vow. Ramakantha: vow shapes consciousness-destination.",
    "keyPoints": ["vrata decides gati", "mat-yajin to me"]
  },
  {
    "id": "9.26",
    "number": "9.26",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "पत्रं पुष्पं फलं तोयं यो मे भक्त्या प्रयच्छति । तदहं भक्त्युपहृतमश्नामि प्रयतात्मनः ॥9.26॥",
    "iast": "patrṃ puṣpṃ phalṃ toyṃ yo me bhaktyā prayacchati tadahṃ bhaktyupahṛtamaśnāmi prayatātmanḥ",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Leaf, flower, fruit, water — who offers with devotion, that loving gift of striving soul I accept.",
    "commentary": "Plain: simple loving offering accepted. Ramakantha: simplest karma becomes sacrament when charged with knowledge-love.",
    "keyPoints": ["simple gift", "bhakti transfigures karma"]
  },
  {
    "id": "9.27",
    "number": "9.27",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "यत्करोषि यदश्नासि यज्जुहोषि ददासि यत् । यत्तपस्यसि कौन्तेय तत्कुरुष्व मदर्पणम् ॥9.27॥",
    "iast": "yatkaroṣi yadaśnāsi yajjuhoṣi dadāsi yat yattapasyasi kaunteya tatkuruṣva madarpaṇam",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Whatever you do, eat, offer, give, practise as austerity — do that as offering to me.",
    "commentary": "Plain: total offering of life. Ramakantha: central samuccaya verse — every karma made Shiva-offering by awareness.",
    "keyPoints": ["mad-arpanam", "life as offering"]
  },
  {
    "id": "9.28",
    "number": "9.28",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "शुभाशुभफलैरेवं मोक्ष्यसे कर्मबन्धनैः । संन्यासयोगयुक्तात्मा विमुक्तो मामुपैष्यसि ॥9.28॥",
    "iast": "śubhāśubhaphalairevṃ mokṣyase karmabandhanaiḥ sṃnyāsayogayuktātmā vimukto māmupaiṣyasi",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Thus freed from good-evil fruited action-bonds, self yoked by renunciation-yoga, liberated you shall reach me.",
    "commentary": "Plain: offering liberates from bondage. Ramakantha: sannyasa-yoga is not abandonment but offering-attitude in action.",
    "keyPoints": ["shubhashubha release", "offering-renunciation"]
  },
  {
    "id": "9.29",
    "number": "9.29",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "समोऽहं सर्वभूतेषु न मे द्वेष्योऽस्ति न प्रियः । ये भजन्ति तु मां भक्त्या मयि ते तेषु चाप्यहम् ॥9.29॥",
    "iast": "samohṃ sarvabhūteṣu na me dveṣyosti na priyḥ ye bhajanti tu māṃ bhaktyā mayi te teṣu cāpyaham",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Equal am I to all beings, none hateful or dear, but devotees in devotion abide in me and I in them.",
    "commentary": "Plain: impartial yet intimate. Ramakantha: equality is Shiva-sameness, intimacy is recognition-current.",
    "keyPoints": ["sama", "mutual indwelling"]
  },
  {
    "id": "9.30",
    "number": "9.30",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "अपि चेत्सुदुराचारो भजते मामनन्यभाक् । साधुरेव स मन्तव्यः सम्यग्व्यवसितो हि सः ॥9.30॥",
    "iast": "api cetsudurācāro bhajate māmananyabhāk sādhureva sa mantavyḥ samyagvyavasito hi sḥ",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Even gross misconducter worshipping me exclusively is deemed righteous, rightly resolved.",
    "commentary": "Plain: resolve redeems. Ramakantha: ananya-resolve re-orients karma swiftly toward Shiva.",
    "keyPoints": ["redemption by resolve", "ananya-bhak"]
  },
  {
    "id": "9.31",
    "number": "9.31",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "क्षिप्रं भवति धर्मात्मा शश्वच्छान्तिं निगच्छति । कौन्तेय प्रतिजानीहि न मे भक्तः प्रणश्यति ॥9.31॥",
    "iast": "kṣiprṃ bhavati dharmātmā śaśvacchāntiṃ nigacchati kaunteya pratijānīhi na me bhaktḥ praṇaśyati",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Swiftly becomes righteous, attains lasting peace; declare it, my devotee never perishes.",
    "commentary": "Plain: assurance of transformation. Ramakantha: swiftness because united path corrects from within.",
    "keyPoints": ["kshipram dharma", "assurance"]
  },
  {
    "id": "9.32",
    "number": "9.32",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "मां हि पार्थ व्यपाश्रित्य येऽपि स्युः पापयोनयः । स्त्रियो वैश्यास्तथा शूद्रास्तेऽपि यान्ति परां गतिम् ॥9.32॥",
    "iast": "māṃ hi pārtha vyapāśritya yepi syuḥ pāpayonayḥ striyo vaiśyāstathā śūdrāstepi yānti parāṃ gatim",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Taking refuge in me even sin-born, women, vaishyas, shudras reach supreme goal.",
    "commentary": "Plain: universal refuge. Ramakantha: adhikara is devotion-awareness, not birth; karma purified in refuge.",
    "keyPoints": ["universal adhikara", "refuge"]
  },
  {
    "id": "9.33",
    "number": "9.33",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "किं पुनर्ब्राह्मणाः पुण्या भक्ता राजर्षयस्तथा । अनित्यमसुखं लोकमिमं प्राप्य भजस्व माम् ॥9.33॥",
    "iast": "kiṃ punarbrāhmaṇāḥ puṇyā bhaktā rājarṣayastathā anityamasukhṃ lokamimṃ prāpya bhajasva mām",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "How much more holy brahmins and royal sages; having reached this transient joyless world, worship me.",
    "commentary": "Plain: a fortiori for privileged. Ramakantha: transient world to be used as sacrificial ground, not fled.",
    "keyPoints": ["anitya-asukha", "worship here"]
  },
  {
    "id": "9.34",
    "number": "9.34",
    "section": "Adhyāya 9 — Rāja-guhya (Royal Secret)",
    "devanagari": "मन्मना भव मद्भक्तो मद्याजी मां नमस्कुरु । मामेवैष्यसि युक्त्वैवमात्मानं मत्परायणः ॥9.34॥",
    "iast": "manmanā bhava madbhakto madyājī māṃ namaskuru māmevaiṣyasi yuktvaivamātmānṃ matparāyaṇḥ",
    "conceptIds": ["gita-rajaguhya"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Mind on me, devotee, sacrificer, bow to me — thus yoking self, intent on me, you shall reach me.",
    "commentary": "Plain: fourfold yoking. Ramakantha: manas-bhakti-yajna-namas fuse contemplation and ritual action.",
    "keyPoints": ["fourfold yoga", "mat-parayana"]
  },
];