// Bhagavad Gītā with Sarvatobhadra (Rājānaka Rāmakantha, KSTS LXIV, 1943) — English.
// Devanagari follows the Rāmakantha recension (pāṭhāntara tables pp.421–430); translations/commentaries original to this project.
export const gitaEnPart5: any[] = [
  {
    "id": "13.1",
    "number": "13.1",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "अर्जुन उवाच। प्रकृतिं पुरुषं चैव क्षेत्रं क्षेत्रज्ञमेव च। एतद्वेदितुमिच्छामि ज्ञानं ज्ञेयं च केशव।",
    "iast": "arjuna uvāca prakṛtiṃ puruṣṃ caiva kṣetrṃ kṣetrajñameva ca etadveditumicchāmi jñānṃ jñeyṃ ca keśava",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Kashmir-only opening question; absent in Śaṅkara vulgate."}],
    "translation": "Arjuna asks to know prakriti, purusha, kshetra, kshetrajna, jnana and jneya.",
    "commentary": "This introductory question is absent in vulgate Shankara but present in Kashmir recension. Ramakantha uses it to frame Ch.13 as jnana-karma-samuccaya bhumika.",
    "keyPoints": ["Kashmir extra prccha", "frames kshetra-vicara"]
  },
  {
    "id": "13.2",
    "number": "13.2",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "श्रीभगवानुवाच। इदं शरीरं कौन्तेय क्षेत्रमित्यभिधीयते। एतद्यो वेत्ति तं प्राहुः क्षेत्रज्ञ इति तद्विदः।",
    "iast": "śrībhagavānuvāca idṃ śarīrṃ kaunteya kṣetramityabhidhīyate etadyo vetti tṃ prāhuḥ kṣetrajña iti tadvidḥ",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.2 = vulgate 13.1."}],
    "translation": "This body is called kshetra, and one who knows it is called kshetrajna.",
    "commentary": "Kshetra is the objective field, kshetrajna the knower. Ramakantha stresses kshetrajna as Shiva-svarupa sakshin, not mere jiva.",
    "keyPoints": ["deha=kshetra", "jnata=kshetrajna"]
  },
  {
    "id": "13.3",
    "number": "13.3",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "क्षेत्रज्ञं चापि मां विद्धि सर्वक्षेत्रेषु भारत। क्षेत्रक्षेत्रज्ञयोर्ज्ञानं यत्तज्ज्ञानं मतं मम।",
    "iast": "kṣetrajñṃ cāpi māṃ viddhi sarvakṣetreṣu bhārata kṣetrakṣetrajñayorjñānṃ yattajjñānṃ matṃ mama",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.3 = vulgate 13.2."}],
    "translation": "Know Me as kshetrajna in all kshetras; knowledge of both is true jnana.",
    "commentary": "Universalizes the knower as Ishvara. Ramakantha reads this as advaya Shaiva atman, witnessing all fields without division.",
    "keyPoints": ["sarva-kshetra eka jnata", "jnana-lakshana"]
  },
  {
    "id": "13.4",
    "number": "13.4",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "तत्क्षेत्रं यच्च यादृक्च यद्विकारि यतश्च यत्। स च यो यत्प्रभावश्च तत्समासेन मे शृणु।",
    "iast": "tatkṣetrṃ yacca yādṛkca yadvikāri yataśca yat sa ca yo yatprabhāvaśca tatsamāsena me śṛṇu",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.4 = vulgate 13.3."}],
    "translation": "Hear briefly what the field is, its nature, modifications, origin, and the knower's power.",
    "commentary": "Programmatic verse for six questions. Ramakantha divides exposition into kshetra-svarupa, vikara, and kshetrajna-mahima.",
    "keyPoints": ["shad-prashna", "samasena exposition"]
  },
  {
    "id": "13.5",
    "number": "13.5",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "ऋषिभिर्बहुधा गीतं छन्दोभिर्विविधैः पृथक्। ब्रह्मसूत्रपदैश्चैव हेतुमद्भिर्विनिश्चितैः।",
    "iast": "ṛṣibhirbahudhā gītṃ chandobhirvividhaiḥ pṛthak brahmasūtrapadaiścaiva hetumadbhirviniścitaiḥ",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.5 = vulgate 13.4."}],
    "translation": "It has been sung by rishis in various hymns and settled Brahmasutra aphorisms.",
    "commentary": "Authority is shruti and yukti. Ramakantha cites Shaiva agamas alongside Vedanta-sutras as pramana.",
    "keyPoints": ["rishi-vacana", "hetumad Brahma-sutra"]
  },
  {
    "id": "13.6",
    "number": "13.6",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "महाभूतान्यहङ्कारो बुद्धिरव्यक्तमेव च। इन्द्रियाणि दशैकं च पञ्च चेन्द्रियगोचराः।",
    "iast": "mahābhūtānyahaṅkāro buddhiravyaktameva ca indriyāṇi daśaikṃ ca pañca cendriyagocarāḥ",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.6 = vulgate 13.5."}],
    "translation": "The field comprises great elements, ahankara, buddhi, avyakta, ten senses plus mind, and five sense-objects.",
    "commentary": "Samkhya 24-tattva enumeration adapted. Ramakantha maps avyakta to maya-shakti, not independent prakriti.",
    "keyPoints": ["24-tattva kshetra", "Samkhya frame"]
  },
  {
    "id": "13.7",
    "number": "13.7",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "इच्छा द्वेषः सुखं दुःखं सङ्घातश्चेतना धृतिः। एतत्क्षेत्रं समासेन सविकारमुदाहृतम्।",
    "iast": "icchā dveṣḥ sukhṃ duḥkhṃ saṅghātaścetanā dhṛtiḥ etatkṣetrṃ samāsena savikāramudāhṛtam",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.7 = vulgate 13.6."}],
    "translation": "Desire, hatred, pleasure, pain, the aggregate, consciousness-signs, and resolve are modifications of the field.",
    "commentary": "Vikaras are dharmas of kshetra, not of atman. Ramakantha insists cetana here is anta-karana-vritti, not pure caitanya.",
    "keyPoints": ["vikara=kshetra-dharma", "cetana as vritti"]
  },
  {
    "id": "13.8",
    "number": "13.8",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "अमानित्वमदम्भित्वमहिंसा क्षान्तिरार्जवम्। आचार्योपासनं शौचं स्थैर्यमात्मविनिग्रहः।",
    "iast": "amānitvamadambhitvamahiṃsā kṣāntirārjavam ācāryopāsanṃ śaucṃ sthairyamātmavinigrahḥ",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.8 = vulgate 13.7."}],
    "translation": "Humility, pridelessness, nonviolence, patience, honesty, teacher-service, purity, steadfastness and self-control constitute jnana.",
    "commentary": "First of jnana-sadhana virtues. Ramakantha treats them as karma-shuddhi preparing samuccaya.",
    "keyPoints": ["amanitya etc.", "jnana-sadhana"]
  },
  {
    "id": "13.9",
    "number": "13.9",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "इन्द्रियार्थेषु वैराग्यमनहङ्कार एव च। जन्ममृत्युजराव्याधिदुःखदोषानुदर्शनम्। [पाठा: क्षेत्रज्ञमिति ज्ञेय-प्रकरणे]",
    "iast": "indriyārtheṣu vairāgyamanahaṅkāra eva ca janmamṛtyujarāvyādhiduḥkhadoṣānudarśanam pāṭhā kṣetrajñamiti jñeya prakaraṇe",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.9 = vulgate 13.8."}],
    "translation": "Dispassion toward sense-objects, egolessness, and constant perception of suffering in birth, death, age and disease.",
    "commentary": "Vairagya and dosha-darshana detach from kshetra. Ramakantha pathantara links this discipline directly to kshetrajna-avabodha, hence क्षेत्रज्ञमिति gloss.",
    "keyPoints": ["vairagya", "janma-duhkha-darshana"]
  },
  {
    "id": "13.10",
    "number": "13.10",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "असक्तिरनभिष्वङ्गः पुत्रदारगृहादिषु। नित्यं च समचित्तत्वमिष्टानिष्टोपपत्तिषु।",
    "iast": "asaktiranabhiṣvaṅgḥ putradāragṛhādiṣu nityṃ ca samacittatvamiṣṭāniṣṭopapattiṣu",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.10 = vulgate 13.9."}],
    "translation": "Non-attachment without clinging to son, wife and home, and constant equanimity in pleasant and unpleasant events.",
    "commentary": "Asakti is inner freedom while acting. Ramakantha allows grihastha-karma with samuccaya, not forced sannyasa.",
    "keyPoints": ["asakti", "sama-cittatva"]
  },
  {
    "id": "13.11",
    "number": "13.11",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "मयि चानन्ययोगेन भक्तिरव्यभिचारिणी। विविक्तदेशसेवित्वमरतिर्जनसंसदि।",
    "iast": "mayi cānanyayogena bhaktiravyabhicāriṇī viviktadeśasevitvamaratirjanasṃsadi",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.11 = vulgate 13.10."}],
    "translation": "Unswerving devotion to Me through exclusive yoga, resort to solitude, and distaste for crowds.",
    "commentary": "Bhakti stabilizes jnana. Ramakantha reads ananya-bhakti as Shivaika-bhakti, support for karma-jnana unity.",
    "keyPoints": ["ananya-bhakti", "vivikta-seva"]
  },
  {
    "id": "13.12",
    "number": "13.12",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "अध्यात्मज्ञाननित्यत्वं तत्त्वज्ञानार्थदर्शनम्। एतज्ज्ञानमिति प्रोक्तमज्ञानं यदतोऽन्यथा।",
    "iast": "adhyātmajñānanityatvṃ tattvajñānārthadarśanam etajjñānamiti proktamajñānṃ yadatonyathā",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.12 = vulgate 13.11."}],
    "translation": "Constancy in self-knowledge and insight into the goal of truth-knowledge is called jnana, all else is ajnana.",
    "commentary": "Closes the 20-fold jnana list. Ramakantha: these are means, not end; jneya follows.",
    "keyPoints": ["adhyatma-nityatva", "jnana/ajnana divide"]
  },
  {
    "id": "13.13",
    "number": "13.13",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "ज्ञेयं यत्तत्प्रवक्ष्यामि यज्ज्ञात्वामृतमश्नुते। अनादिमत्परं ब्रह्म न सन्नासत्तदुच्यते।",
    "iast": "jñeyṃ yattatpravakṣyāmi yajjñātvāmṛtamaśnute anādimatparṃ brahma na sannāsattaducyate",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Rāmakantha pāṭha: Rāmakantha: na sannāsat tad ucyate."}, {"note": "Concordance: Kashmir 13.13 = vulgate 13.12."}],
    "translation": "I shall teach the knowable by which immortality is gained, beginningless supreme Brahman called neither being nor non-being.",
    "commentary": "Jneya transcends sat/asat categories. Ramakantha: न सन्नासत् emphasizes anubhava-avyapadesya Shiva-tattva beyond affirmation-negation.",
    "keyPoints": ["anadi para Brahman", "na san-na-asat"]
  },
  {
    "id": "13.14",
    "number": "13.14",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "सर्वतः पाणिपादं तत्सर्वतोऽक्षिशिरोमुखम्। सर्वतः श्रुतिमल्लोके सर्वमावृत्य तिष्ठति।",
    "iast": "sarvatḥ pāṇipādṃ tatsarvatokṣiśiromukham sarvatḥ śrutimalloke sarvamāvṛtya tiṣṭhati",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.14 = vulgate 13.13."}],
    "translation": "Everywhere hands and feet, everywhere eyes, heads, mouths and ears, it abides enveloping all.",
    "commentary": "Omnipresence through borrowed organs. Ramakantha: Shakti-vyapti, not physical limbs.",
    "keyPoints": ["sarvatah-pani", "vyapti"]
  },
  {
    "id": "13.15",
    "number": "13.15",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "सर्वेन्द्रियगुणाभासं सर्वेन्द्रियविवर्जितम्। असक्तं सर्वभृच्चैव निर्गुणं गुणभोक्तृ च।",
    "iast": "sarvendriyaguṇābhāsṃ sarvendriyavivarjitam asaktṃ sarvabhṛccaiva nirguṇṃ guṇabhoktṛ ca",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.15 = vulgate 13.14."}],
    "translation": "Shining through all sense-qualities yet devoid of senses, detached yet sustaining all, attributeless yet experiencing gunas.",
    "commentary": "Paradox of nirguna-saguna. Ramakantha resolves via svatantrya: Shiva reveals through instruments without bondage.",
    "keyPoints": ["nirguna yet bhoktri", "svatantrya"]
  },
  {
    "id": "13.16",
    "number": "13.16",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "बहिरन्तश्च भूतानामचरं चरमेव च। सूक्ष्मत्वात्तदविज्ञेयं दूरस्थं चान्तिके च तत्।",
    "iast": "bahirantaśca bhūtānāmacarṃ carameva ca sūkṣmatvāttadavijñeyṃ dūrasthṃ cāntike ca tat",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.16 = vulgate 13.15."}],
    "translation": "Outside and inside beings, moving and unmoving, subtle hence unknowable, yet far and near.",
    "commentary": "Proximity is epistemic, not spatial. Ramakantha: subtlety requires diksha-shuddha buddhi.",
    "keyPoints": ["bahir-antah", "suksmatva"]
  },
  {
    "id": "13.17",
    "number": "13.17",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "अविभक्तं च भूतेषु विभक्तमिव च स्थितम्। भूतभर्तृ च तज्ज्ञेयं ग्रसिष्णु प्रभविष्णु च।",
    "iast": "avibhaktṃ ca bhūteṣu vibhaktamiva ca sthitam bhūtabhartṛ ca tajjñeyṃ grasiṣṇu prabhaviṣṇu ca",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.17 = vulgate 13.16."}],
    "translation": "Undivided yet standing as if divided among beings, the knowable sustains, devours and creates beings.",
    "commentary": "One sustainer appearing manifold. Ramakantha: srishti-samhara as Shiva-kritya.",
    "keyPoints": ["avibhakta-vibhakta", "bharta-prabhavishnu"]
  },
  {
    "id": "13.18",
    "number": "13.18",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "ज्योतिषामपि तज्ज्योतिस्तमसः परमुच्यते। ज्ञानं ज्ञेयं ज्ञानगम्यं हृदि सर्वस्य विष्ठितम्।",
    "iast": "jyotiṣāmapi tajjyotistamasḥ paramucyate jñānṃ jñeyṃ jñānagamyṃ hṛdi sarvasya viṣṭhitam",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.18 = vulgate 13.17."}],
    "translation": "Light of lights beyond darkness, knowledge itself, the knowable and goal of knowledge, seated in every heart.",
    "commentary": "Hridaya-stha jyotis is directly realisable. Ramakantha: heart is samvit-pitha.",
    "keyPoints": ["jyotir-jyotis", "hridi-sthita"]
  },
  {
    "id": "13.19",
    "number": "13.19",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "इति क्षेत्रं तथा ज्ञानं ज्ञेयं चोक्तं समासतः। मद्भक्त एतद्विज्ञाय मद्भावायोपपद्यते।",
    "iast": "iti kṣetrṃ tathā jñānṃ jñeyṃ coktṃ samāsatḥ madbhakta etadvijñāya madbhāvāyopapadyate",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.19 = vulgate 13.18."}],
    "translation": "Thus field, knowledge and knowable are briefly told; knowing this My devotee attains My state.",
    "commentary": "Phala-shruti for jnana-prakarana. Ramakantha: mad-bhava is Shivatva-patti through samuccaya.",
    "keyPoints": ["samasa-upasamhara", "mad-bhava"]
  },
  {
    "id": "13.20",
    "number": "13.20",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "प्रकृतिं पुरुषं चैव विद्ध्यनादी उभावपि। विकारांश्च गुणांश्चैव विद्धि प्रकृतिसम्भवान्।",
    "iast": "prakṛtiṃ puruṣṃ caiva viddhyanādī ubhāvapi vikārāṃśca guṇāṃścaiva viddhi prakṛtisambhavān",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.20 = vulgate 13.19."}],
    "translation": "Know prakriti and purusha both as beginningless; modifications and gunas arise from prakriti.",
    "commentary": "Dual beginningless principles for vyavahara. Ramakantha subordinates both to Parama-Shiva as prakasha-vimarsha.",
    "keyPoints": ["ubhau anadi", "vikara from prakriti"]
  },
  {
    "id": "13.21",
    "number": "13.21",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "कार्यकारणकर्तृत्वे हेतुः प्रकृतिरुच्यते। पुरुषः सुखदुःखानां भोक्तृत्वे हेतुरुच्यते।",
    "iast": "kāryakāraṇakartṛtve hetuḥ prakṛtirucyate puruṣḥ sukhaduḥkhānāṃ bhoktṛtve heturucyate",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Rāmakantha pāṭha: Rāmakantha: kārya-kāraṇa (vs kārya-karaṇa)."}, {"note": "Concordance: Kashmir 13.21 = vulgate 13.20."}],
    "translation": "Prakriti is declared the cause of effect-instrument-agency, purusha of experiencing pleasure and pain.",
    "commentary": "Division of kartrtva and bhoktrtva. Ramakantha patha कार्यकारण (karya-karana, effect-cause) stresses sharira-indriya as karya-karana, correcting कार्यकरण.",
    "keyPoints": ["prakriti=kartrtva-hetu", "purusha=bhokta"]
  },
  {
    "id": "13.22",
    "number": "13.22",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "पुरुषः प्रकृतिस्थो हि भुङ्क्ते प्रकृतिजान्गुणान्। कारणं गुणसङ्गोऽस्य सदसद्योनिजन्मसु।",
    "iast": "puruṣḥ prakṛtistho hi bhuṅkte prakṛtijānguṇān kāraṇṃ guṇasaṅgosya sadasadyonijanmasu",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.22 = vulgate 13.21."}],
    "translation": "Purusha seated in prakriti enjoys prakriti-born gunas; attachment to gunas causes good and evil births.",
    "commentary": "Bondage is sanga, not svarupa. Ramakantha: guna-sanga is mala, removable by jnana-karma-shuddhi.",
    "keyPoints": ["guna-sanga", "yoni-karana"]
  },
  {
    "id": "13.23",
    "number": "13.23",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "उपद्रष्टानुमन्ता च भर्ता भोक्ता महेश्वरः। परमात्मेति चाप्युक्तो देहेऽस्मिन्पुरुषः परः।",
    "iast": "upadraṣṭānumantā ca bhartā bhoktā maheśvarḥ paramātmeti cāpyukto dehesminpuruṣḥ parḥ",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.23 = vulgate 13.22."}],
    "translation": "In this body the supreme Purusha is witness, approver, supporter, enjoyer, great Lord and supreme Self.",
    "commentary": "Sixfold maheshvara-linga. Ramakantha highlights Maheshvara nama as Shaiva pratyabhijna.",
    "keyPoints": ["upadrashtri etc.", "Maheshvara"]
  },
  {
    "id": "13.24",
    "number": "13.24",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "य एवं वेत्ति पुरुषं प्रकृतिं च गुणैः सह। सर्वथा वर्तमानोऽपि न स भूयोऽभिजायते।",
    "iast": "ya evṃ vetti puruṣṃ prakṛtiṃ ca guṇaiḥ saha sarvathā vartamānopi na sa bhūyobhijāyate",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.24 = vulgate 13.23."}],
    "translation": "Who knows purusha and prakriti with gunas is not reborn however he lives.",
    "commentary": "Jivanmukti assurance. Ramakantha: sarvatha vartamano'pi = samuccaya-yukta grihastha also liberated.",
    "keyPoints": ["tattva-viveka", "apunarjanma"]
  },
  {
    "id": "13.25",
    "number": "13.25",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "ध्यानेनात्मनि पश्यन्ति केचिदात्मानमात्मना। अन्ये साङ्ख्येन योगेन कर्मयोगेन चापरे।",
    "iast": "dhyānenātmani paśyanti kecidātmānamātmanā anye sāṅkhyena yogena karmayogena cāpare",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.25 = vulgate 13.24."}],
    "translation": "Some see the Self by meditation, others by Samkhya-yoga, others by karma-yoga.",
    "commentary": "Adhikari-bheda with same lakshya. Ramakantha harmonizes them as samuccaya stages, not exclusive alternatives.",
    "keyPoints": ["dhyana-samkhya-karma", "adhikari-bheda"]
  },
  {
    "id": "13.26",
    "number": "13.26",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "अन्ये त्वेवमजानन्तः श्रुत्वान्येभ्य उपासते। तेऽपि चातितरन्त्येव मृत्युं श्रुतिपरायणाः।",
    "iast": "anye tvevamajānantḥ śrutvānyebhya upāsate tepi cātitarantyeva mṛtyuṃ śrutiparāyaṇāḥ",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.26 = vulgate 13.25."}],
    "translation": "Others unknowing worship after hearing from others; they too cross death through devotion to hearing.",
    "commentary": "Shruti-parayana as valid path for manda. Ramakantha validates agama-shravana for unlettered.",
    "keyPoints": ["shrutva-upasana", "manda-adhikara"]
  },
  {
    "id": "13.27",
    "number": "13.27",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "यावत्सञ्जायते किञ्चित्सत्त्वं स्थावरजङ्गमम्। क्षेत्रक्षेत्रज्ञसंयोगात्तद्विद्धि भरतर्षभ।",
    "iast": "yāvatsañjāyate kiñcitsattvṃ sthāvarajaṅgamam kṣetrakṣetrajñasṃyogāttadviddhi bharatarṣabha",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.27 = vulgate 13.26."}],
    "translation": "Whatever existent, moving or unmoving, arises from union of kshetra and kshetrajna.",
    "commentary": "All srishti is samyoga. Ramakantha: samyoga is Shakti-sparsha, not real mixture.",
    "keyPoints": ["kshetra-kshetrajna-samyoga", "sarva-utpatti"]
  },
  {
    "id": "13.28",
    "number": "13.28",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "समं सर्वेषु भूतेषु तिष्ठन्तं परमेश्वरम्। विनश्यत्स्वविनश्यन्तं यः पश्यति स पश्यति।",
    "iast": "samṃ sarveṣu bhūteṣu tiṣṭhantṃ parameśvaram vinaśyatsvavinaśyantṃ yḥ paśyati sa paśyati",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.28 = vulgate 13.27."}],
    "translation": "Who sees the supreme Lord equally abiding in all beings, imperishable in the perishing, truly sees.",
    "commentary": "Sama-darshana is true vision. Ramakantha: Parameshvara-darshana dissolves bheda-buddhi.",
    "keyPoints": ["sama-darshana", "avinashyan"]
  },
  {
    "id": "13.29",
    "number": "13.29",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "समं पश्यन्हि सर्वत्र समवस्थितमीश्वरम्। न हिनस्त्यात्मनात्मानं ततो याति परां गतिम्।",
    "iast": "samṃ paśyanhi sarvatra samavasthitamīśvaram na hinastyātmanātmānṃ tato yāti parāṃ gatim",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.29 = vulgate 13.28."}],
    "translation": "Seeing the Lord equally everywhere, one does not injure the self by the self and attains the supreme goal.",
    "commentary": "Non-himsa follows from equality. Ramakantha: atma-himsa is guna-sanga; avoidance is moksha-marga.",
    "keyPoints": ["a-himsa", "param gati"]
  },
  {
    "id": "13.30",
    "number": "13.30",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "प्रकृत्यैव च कर्माणि क्रियमाणानि सर्वशः। यः पश्यति तथात्मानमकर्तारं स पश्यति।",
    "iast": "prakṛtyaiva ca karmāṇi kriyamāṇāni sarvaśḥ yḥ paśyati tathātmānamakartārṃ sa paśyati",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.30 = vulgate 13.29."}],
    "translation": "Who sees all actions done by prakriti alone and the Self as non-doer truly sees.",
    "commentary": "Akartrtva-darshana. Ramakantha: Shiva as akarta witnesses maya-karma; jnana-karma union preserves this.",
    "keyPoints": ["prakriti-kartrtva", "atma-akartrtva"]
  },
  {
    "id": "13.31",
    "number": "13.31",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "यदा भूतपृथग्भावमेकस्थमनुपश्यति। तत एव च विस्तारं ब्रह्म सम्पद्यते तदा।",
    "iast": "yadā bhūtapṛthagbhāvamekasthamanupaśyati tata eva ca vistārṃ brahma sampadyate tadā",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.31 = vulgate 13.30."}],
    "translation": "When one sees manifold beings grounded in One and expanding from It, one attains Brahman.",
    "commentary": "Ekastha-darshana leads to Brahma-sampatti. Ramakantha: eka is samvit, vistara its sphuratta.",
    "keyPoints": ["eka-stha", "Brahma-sampatti"]
  },
  {
    "id": "13.32",
    "number": "13.32",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "अनादित्वान्निर्गुणत्वात्परमात्मायमव्ययः। शरीरस्थोऽपि कौन्तेय न करोति न लिप्यते।",
    "iast": "anāditvānnirguṇatvātparamātmāyamavyayḥ śarīrasthopi kaunteya na karoti na lipyate",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.32 = vulgate 13.31."}],
    "translation": "Beginningless and attributeless, this imperishable supreme Self though in body neither acts nor is tainted.",
    "commentary": "Asanga despite deha-sthiti. Ramakantha: nirgunatva does not deny svatantrya-shakti.",
    "keyPoints": ["anadi-nirguna", "a-lipyamana"]
  },
  {
    "id": "13.33",
    "number": "13.33",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "यथा सर्वगतं सौक्ष्म्यादाकाशं नोपलिप्यते। सर्वत्रावस्थितो देहे तथात्मा नोपलिप्यते।",
    "iast": "yathā sarvagatṃ saukṣmyādākāśṃ nopalipyate sarvatrāvasthito dehe tathātmā nopalipyate",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.33 = vulgate 13.32."}],
    "translation": "As all-pervading ether is unstained by subtlety, so the Self everywhere in body is unstained.",
    "commentary": "Akasha-drishtanta for asanga. Ramakantha uses it to defend embodied liberation.",
    "keyPoints": ["akasha-drishtanta", "asanga"]
  },
  {
    "id": "13.34",
    "number": "13.34",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "यथा प्रकाशयत्येकः कृत्स्नं लोकमिमं रविः। क्षेत्रं क्षेत्री तथा कृत्स्नं प्रकाशयति भारत।",
    "iast": "yathā prakāśayatyekḥ kṛtsnṃ lokamimṃ raviḥ kṣetrṃ kṣetrī tathā kṛtsnṃ prakāśayati bhārata",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.34 = vulgate 13.33."}],
    "translation": "As one sun illumines this whole world, so the field-knower illumines the whole field.",
    "commentary": "Prakasha is bodha. Ramakantha: kshetri as prakasha, kshetra as prakashya-vimarsha.",
    "keyPoints": ["surya-drishtanta", "prakasha"]
  },
  {
    "id": "13.35",
    "number": "13.35",
    "section": "Adhyāya 13 — Kṣetra-kṣetrajña (Field & Knower)",
    "devanagari": "क्षेत्रक्षेत्रज्ञयोरेवमन्तरं ज्ञानचक्षुषा। भूतप्रकृतिमोक्षं च ये विदुर्यान्ति ते परम्।",
    "iast": "kṣetrakṣetrajñayorevamantarṃ jñānacakṣuṣā bhūtaprakṛtimokṣṃ ca ye viduryānti te param",
    "conceptIds": ["gita-ksetra"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Concordance: Kashmir 13.35 = vulgate 13.34."}],
    "translation": "Those who know by wisdom-eye the distinction of field and knower and liberation from elemental prakriti reach the Supreme.",
    "commentary": "Phala: jnana-cakshu gives moksha. Ramakantha closes kshetra-adhyaya as samuccaya-purva.",
    "keyPoints": ["jnana-cakshu", "prakriti-moksha"]
  },
  {
    "id": "14.1",
    "number": "14.1",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "श्रीभगवानुवाच। परं भूयः प्रवक्ष्यामि ज्ञानानां ज्ञानमुत्तमम्। यज्ज्ञात्वा मुनयः सर्वे परां सिद्धिमितो गताः।",
    "iast": "śrībhagavānuvāca parṃ bhūyḥ pravakṣyāmi jñānānāṃ jñānamuttamam yajjñātvā munayḥ sarve parāṃ siddhimito gatāḥ",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I shall again teach the supreme knowledge among knowledges by which sages attained perfection.",
    "commentary": "Para-jnana is guna-viveka. Ramakantha: beyond kshetra-vicara, guna-knowledge enables samuccaya-siddhi.",
    "keyPoints": ["para-jnana", "siddhi-hetu"]
  },
  {
    "id": "14.2",
    "number": "14.2",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "इदं ज्ञानमुपाश्रित्य मम साधर्म्यमागताः। सर्गेऽपि नोपजायन्ते प्रलये न व्यथन्ति च।",
    "iast": "idṃ jñānamupāśritya mama sādharmyamāgatāḥ sargepi nopajāyante pralaye na vyathanti ca",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Resorting to this knowledge and attaining My likeness, they are not born at creation nor troubled at dissolution.",
    "commentary": "Sadharmya is similarity, not annihilation. Ramakantha: Shaiva samya, retaining svatantrya.",
    "keyPoints": ["sadharmya", "sarga-pralaya-mukta"]
  },
  {
    "id": "14.3",
    "number": "14.3",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "मम योनिर्महद्ब्रह्म तस्मिन्गर्भं दधाम्यहम्। सम्भवः सर्वभूतानां ततो भवति भारत।",
    "iast": "mama yonirmahadbrahma tasmingarbhṃ dadhāmyaham sambhavḥ sarvabhūtānāṃ tato bhavati bhārata",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "My womb is great Brahman; in it I place the seed, whence all beings arise.",
    "commentary": "Mahad-Brahma is maya-yoni. Ramakantha: garbhadhana is Shakti-sankalpa by Shiva.",
    "keyPoints": ["mahad-brahma yoni", "sarva-sambhava"]
  },
  {
    "id": "14.4",
    "number": "14.4",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "सर्वयोनिषु कौन्तेय मूर्तयः सम्भवन्ति याः। तासां ब्रह्म महद्योनिरहं बीजप्रदः पिता।",
    "iast": "sarvayoniṣu kaunteya mūrtayḥ sambhavanti yāḥ tāsāṃ brahma mahadyonirahṃ bījapradḥ pitā",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "In all wombs whatever forms arise, great Brahman is womb and I the seed-giving father.",
    "commentary": "Dual parenthood of manifestation. Ramakantha: pitritva is prakasha, yonitva vimarsha.",
    "keyPoints": ["yoni-bija", "pita-putra nyaya"]
  },
  {
    "id": "14.5",
    "number": "14.5",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "सत्त्वं रजस्तम इति गुणाः प्रकृतिसम्भवाः। निबध्नन्ति महाबाहो देहे देहिनमव्ययम्।",
    "iast": "sattvṃ rajastama iti guṇāḥ prakṛtisambhavāḥ nibadhnanti mahābāho dehe dehinamavyayam",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Sattva, rajas, tamas born of prakriti bind the imperishable embodied self in body.",
    "commentary": "Bandha mechanism introduced. Ramakantha: gunas are pasha, body the bandha-sthana.",
    "keyPoints": ["tri-guna", "bandha-hetu"]
  },
  {
    "id": "14.6",
    "number": "14.6",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "तत्र सत्त्वं निर्मलत्वात्प्रकाशकमनामयम्। सुखसङ्गेन बध्नाति ज्ञानसङ्गेन चानघ।",
    "iast": "tatra sattvṃ nirmalatvātprakāśakamanāmayam sukhasaṅgena badhnāti jñānasaṅgena cānagha",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Sattva being stainless, luminous and healthy binds by attachment to pleasure and knowledge.",
    "commentary": "Even sattva binds subtly. Ramakantha warns samuccaya must transcend jnana-abhimana.",
    "keyPoints": ["sattva-nirmala", "sukha-jnana-sanga"]
  },
  {
    "id": "14.7",
    "number": "14.7",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "रजो रागात्मकं विद्धि तृष्णासङ्गसमुद्भवम्। तन्निबध्नाति कौन्तेय कर्मसङ्गेन देहिनम्।",
    "iast": "rajo rāgātmakṃ viddhi tṛṣṇāsaṅgasamudbhavam tannibadhnāti kaunteya karmasaṅgena dehinam",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Know rajas as passion-born, springing from thirst and attachment; it binds by attachment to action.",
    "commentary": "Rajas drives pravritti. Ramakantha: karma-sanga must be purified into nishkama-karma.",
    "keyPoints": ["rago-rajah", "karma-sanga"]
  },
  {
    "id": "14.8",
    "number": "14.8",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "तमस्त्वज्ञानजं विद्धि मोहनं सर्वदेहिनाम्। प्रमादालस्यनिद्राभिस्तन्निबध्नाति भारत।",
    "iast": "tamastvajñānajṃ viddhi mohanṃ sarvadehinām pramādālasyanidrābhistannibadhnāti bhārata",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Know tamas born of ignorance deluding all embodied beings, binding by negligence, sloth and sleep.",
    "commentary": "Tamas veils viveka. Ramakantha: pramada is Shaiva apratyavamarsha.",
    "keyPoints": ["ajnana-ja tamas", "pramada-bandha"]
  },
  {
    "id": "14.9",
    "number": "14.9",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "सत्त्वं सुखे सञ्जयति रजः कर्मणि भारत। ज्ञानमावृत्य तु तमः प्रमादे सञ्जयत्युत।",
    "iast": "sattvṃ sukhe sañjayati rajḥ karmaṇi bhārata jñānamāvṛtya tu tamḥ pramāde sañjayatyuta",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Sattva attaches to pleasure, rajas to action, tamas covering knowledge attaches to negligence.",
    "commentary": "Summary of guna-functions. Ramakantha uses it for daily self-pariksha.",
    "keyPoints": ["sukha-karma-pramada", "guna-karya"]
  },
  {
    "id": "14.10",
    "number": "14.10",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "रजस्तमश्चाभिभूय सत्त्वं भवति भारत। रजः सत्त्वं तमश्चैव तमः सत्त्वं रजस्तथा।",
    "iast": "rajastamaścābhibhūya sattvṃ bhavati bhārata rajḥ sattvṃ tamaścaiva tamḥ sattvṃ rajastathā",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Sattva prevails overpowering rajas and tamas, and each in turn overpowers the others.",
    "commentary": "Mutual struggle of gunas. Ramakantha: kshana-parinama requires constant sadhana vigilance.",
    "keyPoints": ["anyonya-abhibhava", "guna-parinama"]
  },
  {
    "id": "14.11",
    "number": "14.11",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "सर्वद्वारेषु देहेऽस्मिन्प्रकाश उपजायते। ज्ञानं यदा तदा विद्याद्विवृद्धं सत्त्वमित्युत।",
    "iast": "sarvadvāreṣu dehesminprakāśa upajāyate jñānṃ yadā tadā vidyādvivṛddhṃ sattvamityuta",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "When light of knowledge arises in all gates of body, know sattva increased.",
    "commentary": "Linga of sattva-vriddhi. Ramakantha: dvAras are indriyas illumined by samvit.",
    "keyPoints": ["prakasha-linga", "sattva-vriddhi"]
  },
  {
    "id": "14.12",
    "number": "14.12",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "लोभः प्रवृत्तिरारम्भः कर्मणामशमः स्पृहा। रजस्येतानि जायन्ते विवृद्धे भरतर्षभ।",
    "iast": "lobhḥ pravṛttirārambhḥ karmaṇāmaśamḥ spṛhā rajasyetāni jāyante vivṛddhe bharatarṣabha",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Greed, activity, undertaking of works, restlessness and craving arise when rajas increases.",
    "commentary": "Rajas-lingas. Ramakantha: arambha without shastra is bandhaka.",
    "keyPoints": ["lobha-pravritti", "rajo-linga"]
  },
  {
    "id": "14.13",
    "number": "14.13",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "अप्रकाशोऽप्रवृत्तिश्च प्रमादो मोह एव च। तमस्येतानि जायन्ते विवृद्धे कुरुनन्दन।",
    "iast": "aprakāśopravṛttiśca pramādo moha eva ca tamasyetāni jāyante vivṛddhe kurunandana",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Darkness, inactivity, negligence and delusion arise when tamas increases.",
    "commentary": "Tamas-lingas. Ramakantha prescribes karma-yoga and japa to pierce aprakasha.",
    "keyPoints": ["aprakasha-pramada", "tamo-linga"]
  },
  {
    "id": "14.14",
    "number": "14.14",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "यदा सत्त्वे प्रवृद्धे तु प्रलयं याति देहभृत्। तदोत्तमविदां लोकानमलान्प्रतिपद्यते।",
    "iast": "yadā sattve pravṛddhe tu pralayṃ yāti dehabhṛt tadottamavidāṃ lokānamalānpratipadyate",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Dying in increased sattva, the embodied attains pure worlds of knowers.",
    "commentary": "Sattva-mrityu-phala. Ramakantha: loka is citta-bhumika, not mere svarga.",
    "keyPoints": ["sattva-pralaya", "amala-loka"]
  },
  {
    "id": "14.15",
    "number": "14.15",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "रजसि प्रलयं गत्वा कर्मसङ्गिषु जायते। तथा प्रलीनस्तमसि मूढयोनिषु जायते।",
    "iast": "rajasi pralayṃ gatvā karmasaṅgiṣu jāyate tathā pralīnastamasi mūḍhayoniṣu jāyate",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Dying in rajas one is born among action-attached, dying in tamas among deluded wombs.",
    "commentary": "Gati according to guna. Ramakantha stresses anta-kala guna determines dehantara.",
    "keyPoints": ["rajas-karma-sangi", "tamas-mudha-yoni"]
  },
  {
    "id": "14.16",
    "number": "14.16",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "कर्मणः सुकृतस्याहुः सात्त्विकं निर्मलं फलम्। रजसस्तु फलं दुःखमज्ञानं तमसः फलम्।",
    "iast": "karmaṇḥ sukṛtasyāhuḥ sāttvikṃ nirmalṃ phalam rajasastu phalṃ duḥkhamajñānṃ tamasḥ phalam",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Fruit of good action is sattvic and pure, of rajasic is suffering, of tamasic is ignorance.",
    "commentary": "Karma-phala triad. Ramakantha: sukrita is shastra-vihita nishkama karma.",
    "keyPoints": ["sukrita-phala", "guna-phala"]
  },
  {
    "id": "14.17",
    "number": "14.17",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "सत्त्वात्सञ्जायते ज्ञानं रजसो लोभ एव च। प्रमादमोहौ तमसो भवतोऽज्ञानमेव च।",
    "iast": "sattvātsañjāyate jñānṃ rajaso lobha eva ca pramādamohau tamaso bhavatojñānameva ca",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "From sattva arises knowledge, from rajas greed, from tamas negligence, delusion and ignorance.",
    "commentary": "Epistemic effects. Ramakantha: jnana here is viveka, to be united with karma.",
    "keyPoints": ["jnana-lobha-moha", "guna-janya"]
  },
  {
    "id": "14.18",
    "number": "14.18",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "ऊर्ध्वं गच्छन्ति सत्त्वस्था मध्ये तिष्ठन्ति राजसाः। जघन्यगुणवृत्तिस्था अधो गच्छन्ति तामसाः।",
    "iast": "ūrdhvṃ gacchanti sattvasthā madhye tiṣṭhanti rājasāḥ jaghanyaguṇavṛttisthā adho gacchanti tāmasāḥ",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Sattva-dwellers go upward, rajasic stay in middle, tamasic sunk in lowest guna go down.",
    "commentary": "Tri-gati. Ramakantha maps urdhva to Shivatva-unmukha.",
    "keyPoints": ["urdhva-madhya-adho", "tri-gati"]
  },
  {
    "id": "14.19",
    "number": "14.19",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "नान्यं गुणेभ्यः कर्तारं यदा द्रष्टानुपश्यति। गुणेभ्यश्च परं वेत्ति मद्भावं सोऽधिगच्छति।",
    "iast": "nānyṃ guṇebhyḥ kartārṃ yadā draṣṭānupaśyati guṇebhyaśca parṃ vetti madbhāvṃ sodhigacchati",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "When the seer sees no agent beyond gunas and knows what is beyond them, he attains My state.",
    "commentary": "Guna-kartrtva darshana and guna-para bodha. Ramakantha: para is fourth, turya Shiva.",
    "keyPoints": ["guna-kartrtva", "guna-para"]
  },
  {
    "id": "14.20",
    "number": "14.20",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "गुणानेतानतीत्य त्रीन्देही देहसमुद्भवान्। जन्ममृत्युजरादुःखैर्विमुक्तोऽमृतमश्नुते।",
    "iast": "guṇānetānatītya trīndehī dehasamudbhavān janmamṛtyujarāduḥkhairvimuktomṛtamaśnute",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Transcending these three gunas born of body, the embodied freed from birth-death-age-suffering enjoys immortality.",
    "commentary": "Gunatita is jivanmukta. Ramakantha: atityA is not rejection but samuccaya-adhiroha.",
    "keyPoints": ["gunatita", "amrita"]
  },
  {
    "id": "14.21",
    "number": "14.21",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "अर्जुन उवाच। कैर्लिङ्गैस्त्रीन्गुणानेतानतीतो भवति प्रभो। किमाचारः कथं चैतांस्त्रीन्गुणानतिवर्तते।",
    "iast": "arjuna uvāca kairliṅgaistrīnguṇānetānatīto bhavati prabho kimācārḥ kathṃ caitāṃstrīnguṇānativartate",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Arjuna asks the marks, conduct, and means of one who transcends the three gunas.",
    "commentary": "Practical inquiry. Ramakantha frames answer as samuccaya-lakshana.",
    "keyPoints": ["gunatita-prashna", "linga-acara-upaya"]
  },
  {
    "id": "14.22",
    "number": "14.22",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "श्रीभगवानुवाच। प्रकाशं च प्रवृत्तिं च मोहमेव च पाण्डव। न द्वेष्टि सम्प्रवृत्तानि न निवृत्तानि काङ्क्षति।",
    "iast": "śrībhagavānuvāca prakāśṃ ca pravṛttiṃ ca mohameva ca pāṇḍava na dveṣṭi sampravṛttāni na nivṛttāni kāṅkṣati",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "One who neither hates nor craves light, activity, or delusion when present or absent.",
    "commentary": "Sama-buddhi toward guna-vrittis. Ramakantha: advEsha is Shaiva upeksha.",
    "keyPoints": ["a-dvesha-a-kanksha", "sama"]
  },
  {
    "id": "14.23",
    "number": "14.23",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "उदासीनवदासीनो गुणैर्यो न विचाल्यते। गुणा वर्तन्त इत्येव योऽवतिष्ठति नेङ्गते।",
    "iast": "udāsīnavadāsīno guṇairyo na vicālyate guṇā vartanta ityeva yovatiṣṭhati neṅgate",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Seated as neutral, unmoved by gunas, knowing gunas operate, who stays firm and unshaken.",
    "commentary": "Udasina is sakshi-sthiti. Ramakantha: gunA vartante = maya-krida darshana.",
    "keyPoints": ["udasina", "a-vicalya"]
  },
  {
    "id": "14.24",
    "number": "14.24",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "समदुःखसुखः स्वस्थः समलोष्टाश्मकाञ्चनः। तुल्यप्रियाप्रियो धीरस्तुल्यनिन्दात्मसंस्तुतिः।",
    "iast": "samaduḥkhasukhḥ svasthḥ samaloṣṭāśmakāñcanḥ tulyapriyāpriyo dhīrastulyanindātmasṃstutiḥ",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Equal in pain-pleasure, self-abiding, equal toward clod-stone-gold, equal toward dear-undesired, blame-praise, steady.",
    "commentary": "External samatva signs. Ramakantha: svastha = Shiva-svarupa-stha.",
    "keyPoints": ["sama-duhkha-sukha", "svastha"]
  },
  {
    "id": "14.25",
    "number": "14.25",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "मानापमानयोस्तुल्यस्तुल्यो मित्रारिपक्षयोः। सर्वारम्भपरित्यागी गुणातीतः स उच्यते।",
    "iast": "mānāpamānayostulyastulyo mitrāripakṣayoḥ sarvārambhaparityāgī guṇātītḥ sa ucyate",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Equal in honour-dishonour, friend-foe, renouncing all undertakings, is called beyond gunas.",
    "commentary": "Sarvarambha-tyaga is phala-tyaga, not karma-tyaga. Ramakantha: crucial for samuccaya.",
    "keyPoints": ["mana-apamana-sama", "arambha-tyaga"]
  },
  {
    "id": "14.26",
    "number": "14.26",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "मां च योऽव्यभिचारेण भक्तियोगेन सेवते। स गुणान्समतीत्यैतान्ब्रह्मभूयाय कल्पते।",
    "iast": "māṃ ca yovyabhicāreṇa bhaktiyogena sevate sa guṇānsamatītyaitānbrahmabhūyāya kalpate",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Who serves Me with unfailing devotion transcends gunas and becomes fit for Brahman-becoming.",
    "commentary": "Bhakti as gunatita-upaya. Ramakantha: avyabhicara-bhakti is means to Shivatva.",
    "keyPoints": ["avyabhicara-bhakti", "Brahma-bhuya"]
  },
  {
    "id": "14.27",
    "number": "14.27",
    "section": "Adhyāya 14 — Guṇatraya (Three Guṇas)",
    "devanagari": "ब्रह्मणो हि प्रतिष्ठाहममृतस्याव्ययस्य च। शाश्वतस्य च धर्मस्य सुखस्यैकान्तिकस्य च।",
    "iast": "brahmaṇo hi pratiṣṭhāhamamṛtasyāvyayasya ca śāśvatasya ca dharmasya sukhasyaikāntikasya ca",
    "conceptIds": ["gita-guna"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "I am the foundation of Brahman, of imperishable immortality, eternal dharma and absolute bliss.",
    "commentary": "Krishna as pratishtha of Brahman. Ramakantha: Para-Shiva as adhishthana of para-Brahman.",
    "keyPoints": ["Brahmano pratishtha", "ekantika-sukha"]
  },
  {
    "id": "15.1",
    "number": "15.1",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "श्रीभगवानुवाच। ऊर्ध्वमूलमधःशाखमश्वत्थं प्राहुरव्ययम्। छन्दांसि यस्य पर्णानि यस्तं वेद स वेदवित्।",
    "iast": "śrībhagavānuvāca ūrdhvamūlamadhḥśākhamaśvatthṃ prāhuravyayam chandāṃsi yasya parṇāni yastṃ veda sa vedavit",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "They speak of imperishable ashvattha with roots above, branches below, Vedas as leaves; knower thereof knows Vedas.",
    "commentary": "Samsara-vriksha inverted. Ramakantha: urdhva-mula is Para-Shiva, shakhas tattva-prapanca.",
    "keyPoints": ["urdhva-mula ashvattha", "Veda-patra"]
  },
  {
    "id": "15.2",
    "number": "15.2",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "अधश्चोर्ध्वं प्रसृतास्तस्य शाखा गुणप्रवृद्धा विषयप्रवालाः। अधश्च मूलान्यनुसन्ततानि कर्मानुबन्धीनि मनुष्यलोके।",
    "iast": "adhaścordhvṃ prasṛtāstasya śākhā guṇapravṛddhā viṣayapravālāḥ adhaśca mūlānyanusantatāni karmānubandhīni manuṣyaloke",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Branches spread below and above, nourished by gunas with sense-object sprouts, and roots binding action in human world.",
    "commentary": "Guna-poshita vistara. Ramakantha: karma-anubandhi roots are vasana-jala.",
    "keyPoints": ["guna-pravriddha", "karma-anubandha"]
  },
  {
    "id": "15.3",
    "number": "15.3",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "न रूपमस्येह तथोपलभ्यते नान्तो न चादिर्न च सम्प्रतिष्ठा। अश्वत्थमेनं सुविरूढमूलमसङ्गशस्त्रेण दृढेन छित्त्वा।",
    "iast": "na rūpamasyeha tathopalabhyate nānto na cādirna ca sampratiṣṭhā aśvatthamenṃ suvirūḍhamūlamasaṅgaśastreṇa dṛḍhena chittvā",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Its form, end, beginning or support is not perceived; cutting this deep-rooted tree with strong non-attachment sword.",
    "commentary": "Asanga-shastra is viveka-vairagya. Ramakantha: दृढ asanga from samuccaya-abhyasa.",
    "keyPoints": ["a-rupa", "asanga-shastra"]
  },
  {
    "id": "15.4",
    "number": "15.4",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "ततः पदं तत्परिमार्गितव्यं यस्मिन्गता न निवर्तन्ति भूयः। तमेव चाद्यं पुरुषं प्रपद्ये यतः प्रवृत्तिः प्रसृता पुराणी।",
    "iast": "tatḥ padṃ tatparimārgitavyṃ yasmingatā na nivartanti bhūyḥ tameva cādyṃ puruṣṃ prapadye yatḥ pravṛttiḥ prasṛtā purāṇī",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Then seek the state of no return, surrendering to the primal Purusha whence ancient activity issued.",
    "commentary": "Pada-marga and prapatti. Ramakantha: adya Purusha is Adi-Shiva, prapatti is samuccaya-nishtha.",
    "keyPoints": ["a-nivritti pada", "adya-prapatti"]
  },
  {
    "id": "15.5",
    "number": "15.5",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "निर्मानमोहा जितसङ्गदोषा अध्यात्मनित्या विनिवृत्तकामाः। द्वन्द्वैर्विमुक्ताः सुखदुःखसंज्ञैर्गच्छन्त्यमूढाः पदमव्ययं तत्।",
    "iast": "nirmānamohā jitasaṅgadoṣā adhyātmanityā vinivṛttakāmāḥ dvandvairvimuktāḥ sukhaduḥkhasṃjñairgacchantyamūḍhāḥ padamavyayṃ tat",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Free from pride-delusion, conquering attachment, ever in Self, desires ceased, freed from pleasure-pain dualities, the undeluded reach that imperishable state.",
    "commentary": "Qualifications for pada. Ramakantha: nirmana-moha is mala-kshaya.",
    "keyPoints": ["nirmana-moha", "avyaya-pada"]
  },
  {
    "id": "15.6",
    "number": "15.6",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "न तद्भासयते सूर्यो न शशाङ्को न पावकः। यद्गत्वा न निवर्तन्ते तद्धाम परमं मम।",
    "iast": "na tadbhāsayate sūryo na śaśāṅko na pāvakḥ yadgatvā na nivartante taddhāma paramṃ mama",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Neither sun, moon nor fire illumines it; reaching it none return; that is My supreme abode.",
    "commentary": "Svayam-prakasha dhama. Ramakantha: parama dhama is Chid-vyoman, beyond jyotir-mandala.",
    "keyPoints": ["a-bhasya", "parama dhama"]
  },
  {
    "id": "15.7",
    "number": "15.7",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "ममैवांशो जीवलोके जीवभूतः सनातनः। मनःषष्ठानीन्द्रियाणि प्रकृतिस्थानि कर्षति।",
    "iast": "mamaivāṃśo jīvaloke jīvabhūtḥ sanātanḥ manḥṣaṣṭhānīndriyāṇi prakṛtisthāni karṣati",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "My eternal portion becomes jiva in life-world, drawing the mind-sixth senses abiding in prakriti.",
    "commentary": "Jiva as amsha. Ramakantha: amsha is pratibimba, not khanda; non-dual Shaiva amsha-vada.",
    "keyPoints": ["mama-amsha", "mana-shashtha-karshana"]
  },
  {
    "id": "15.8",
    "number": "15.8",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "शरीरं यदवाप्नोति यच्चाप्युत्क्रामतीश्वरः। गृहीत्वैतानि संयाति वायुर्गन्धानिवाशयात्।",
    "iast": "śarīrṃ yadavāpnoti yaccāpyutkrāmatīśvarḥ gṛhītvaitāni sṃyāti vāyurgandhānivāśayāt",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "When the lord takes or leaves a body, he carries these senses as wind carries scents.",
    "commentary": "Dehantara-sankranti. Ramakantha: ishvara here is jiva-bhokta with anava-mala.",
    "keyPoints": ["dehantara", "vayu-gandha nyaya"]
  },
  {
    "id": "15.9",
    "number": "15.9",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "श्रोत्रं चक्षुः स्पर्शनं च रसनं घ्राणमेव च। अधिष्ठाय मनश्चायं विषयानुपसेवते।",
    "iast": "śrotrṃ cakṣuḥ sparśanṃ ca rasanṃ ghrāṇameva ca adhiṣṭhāya manaścāyṃ viṣayānupasevate",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Presiding over ear, eye, touch, taste, smell and mind, it enjoys sense-objects.",
    "commentary": "Bhoga through adhishthana. Ramakantha: manas-adhiṣṭhana shows bhoktrtva is aupadhika.",
    "keyPoints": ["shad-indriya-adhishthana", "vishaya-seva"]
  },
  {
    "id": "15.10",
    "number": "15.10",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "उत्क्रामन्तं स्थितं वापि भुञ्जानं वा गुणान्वितम्। विमूढा नानुपश्यन्ति पश्यन्ति ज्ञानचक्षुषः।",
    "iast": "utkrāmantṃ sthitṃ vāpi bhuñjānṃ vā guṇānvitam vimūḍhā nānupaśyanti paśyanti jñānacakṣuṣḥ",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "The deluded do not see it departing, staying or enjoying with gunas; wisdom-eyed see.",
    "commentary": "Jnana-cakshu requirement. Ramakantha links to Ch.13 jnana-cakshu.",
    "keyPoints": ["vimudha-a-darshana", "jnana-cakshu"]
  },
  {
    "id": "15.11",
    "number": "15.11",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "यतन्तो योगिनश्चैनं पश्यन्त्यात्मन्यवस्थितम्। यतन्तोऽप्यकृतात्मानो नैनं पश्यन्त्यचेतसः।",
    "iast": "yatanto yoginaścainṃ paśyantyātmanyavasthitam yatantopyakṛtātmāno nainṃ paśyantyacetasḥ",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Striving yogis see it abiding in self; striving yet impure-souled senseless do not see.",
    "commentary": "Yatna plus atma-shuddhi. Ramakantha: akritatman = asamucita-karma-jnana.",
    "keyPoints": ["yatna-darshana", "akritatman"]
  },
  {
    "id": "15.12",
    "number": "15.12",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "यदादित्यगतं तेजो जगद्भासयतेऽखिलम्। यच्चन्द्रमसि यच्चाग्नौ तत्तेजो विद्धि मामकम्।",
    "iast": "yadādityagatṃ tejo jagadbhāsayatekhilam yaccandramasi yaccāgnau tattejo viddhi māmakam",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Know the radiance in sun illumining world, in moon and fire, as Mine.",
    "commentary": "Tejas as vibhuti. Ramakantha: sarva-tejas is Shiva-prakasha-amsha.",
    "keyPoints": ["aditya-tejas", "mat-tejas"]
  },
  {
    "id": "15.13",
    "number": "15.13",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "गामाविश्य च भूतानि धारयाम्यहमोजसा। पुष्णामि चौषधीः सर्वाः सोमो भूत्वा रसात्मकः।",
    "iast": "gāmāviśya ca bhūtāni dhārayāmyahamojasā puṣṇāmi cauṣadhīḥ sarvāḥ somo bhūtvā rasātmakḥ",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Entering earth I support beings by power, and as sapful moon nourish all herbs.",
    "commentary": "Dharana-poshana kritya. Ramakantha: ojas is dharika-shakti.",
    "keyPoints": ["bhu-dharana", "soma-poshana"]
  },
  {
    "id": "15.14",
    "number": "15.14",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "अहं वैश्वानरो भूत्वा प्राणिनां देहमाश्रितः। प्राणापानसमायुक्तः पचाम्यन्नं चतुर्विधम्।",
    "iast": "ahṃ vaiśvānaro bhūtvā prāṇināṃ dehamāśritḥ prāṇāpānasamāyuktḥ pacāmyannṃ caturvidham",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Becoming Vaishvanara fire in bodies, united with in-out breaths, I digest fourfold food.",
    "commentary": "Antaryami as pachaka. Ramakantha: vaishvanara is jathara-Shakti of Parameshvara.",
    "keyPoints": ["vaishvanara", "caturvidha-anna-paka"]
  },
  {
    "id": "15.15",
    "number": "15.15",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "सर्वस्य चाहं हृदि संनिविष्टो मत्तः स्मृतिर्ज्ञानमपोहनं च। वेदैश्च सर्वैरहमेव वेद्यो वेदान्तकृद्वेदविदेव चाहम्।",
    "iast": "sarvasya cāhṃ hṛdi sṃniviṣṭo mattḥ smṛtirjñānamapohanṃ ca vedaiśca sarvairahameva vedyo vedāntakṛdvedavideva cāham",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Seated in every heart, from Me come memory, knowledge and forgetting; by all Vedas I am knowable, author and knower of Vedanta.",
    "commentary": "Hridaya-antaryami and Veda-vedya. Ramakantha: smriti-jnana-apohana are vimarsha-shaktis; Vedanta-krit is Agama-praneta.",
    "keyPoints": ["hridi-sannivishta", "smriti-apohana"]
  },
  {
    "id": "15.16",
    "number": "15.16",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "द्वाविमौ पुरुषौ लोके क्षरश्चाक्षर एव च। क्षरः सर्वाणि भूतानि कूटस्थोऽक्षर उच्यते।",
    "iast": "dvāvimau puruṣau loke kṣaraścākṣara eva ca kṣarḥ sarvāṇi bhūtāni kūṭasthokṣara ucyate",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Two purushas in world, perishable and imperishable; perishable all beings, immutable the kutastha.",
    "commentary": "Kshara-akshara vibhaga. Ramakantha: kshara = maya-karya, akshara = maya-shuddha purusha.",
    "keyPoints": ["kshara-akshara", "kutastha"]
  },
  {
    "id": "15.17",
    "number": "15.17",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "उत्तमः पुरुषस्त्वन्यः परमात्मेत्युदाहृतः। यो लोकत्रयमाविश्य बिभर्त्यव्यय ईश्वरः।",
    "iast": "uttamḥ puruṣastvanyḥ paramātmetyudāhṛtḥ yo lokatrayamāviśya bibhartyavyaya īśvarḥ",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "The supreme Purusha is other, called supreme Self, imperishable Lord pervading and sustaining three worlds.",
    "commentary": "Uttama beyond duality. Ramakantha: anya means vilakshana Para-Shiva, Purusottama.",
    "keyPoints": ["uttama-anya", "loka-bhartri"]
  },
  {
    "id": "15.18",
    "number": "15.18",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "यस्मात्क्षरमतीतोऽहमक्षरादपि चोत्तमः। अतोऽस्मि लोके वेदे च प्रथितः पुरुषोत्तमः।",
    "iast": "yasmātkṣaramatītohamakṣarādapi cottamḥ atosmi loke vede ca prathitḥ puruṣottamḥ",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Since I transcend perishable and excel imperishable, I am famed as Purushottama in world and Veda.",
    "commentary": "Nirvacana of Purushottama. Ramakantha: atita-uttama shows samuccaya-phala is Purusottama-patti.",
    "keyPoints": ["ksharatita", "Purushottama-prathita"]
  },
  {
    "id": "15.19",
    "number": "15.19",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "यो मामेवमसम्मूढो जानाति पुरुषोत्तमम्। स सर्वविद्भजति मां सर्वभावेन भारत।",
    "iast": "yo māmevamasammūḍho jānāti puruṣottamam sa sarvavidbhajati māṃ sarvabhāvena bhārata",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Undeluded knower of Me as Purushottama knows all and worships Me with whole being.",
    "commentary": "Sarvavit-phala of Purusottama-jnana. Ramakantha: sarva-bhava-bhajana is jnana-karma-aikya.",
    "keyPoints": ["asammudha", "sarvavit"]
  },
  {
    "id": "15.20",
    "number": "15.20",
    "section": "Adhyāya 15 — Puruṣottama (Supreme Person)",
    "devanagari": "इति गुह्यतमं शास्त्रमिदमुक्तं मयानघ। एतद्बुद्ध्वा बुद्धिमान्स्यात्कृतकृत्यश्च भारत।",
    "iast": "iti guhyatamṃ śāstramidamuktṃ mayānagha etadbuddhvā buddhimānsyātkṛtakṛtyaśca bhārata",
    "conceptIds": ["gita-purusottama"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Thus this most secret teaching is spoken; understanding it one becomes wise and fulfilled.",
    "commentary": "Shastra-upasamhara. Ramakantha: guhyatama because samuccaya-rahasya revealed.",
    "keyPoints": ["guhyatama-shastra", "kritakritya"]
  },
];