// Bhagavad Gītā with Sarvatobhadra (Rājānaka Rāmakantha, KSTS LXIV, 1943) — English.
// Devanagari follows the Rāmakantha recension (pāṭhāntara tables pp.421–430); translations/commentaries original to this project.
export const gitaEnPart6: any[] = [
  {
    "id": "16.1",
    "number": "16.1",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Fearlessness, sattva-purity, steadiness in knowledge-yoga, charity, restraint, sacrifice, study, austerity, honesty mark divine wealth.",
    "commentary": "Daivi list begins. Ramakantha: abhaya is Shiva-smarana-phala, basis for samuccaya.",
    "keyPoints": ["abhaya", "sattva-shuddhi"]
  },
  {
    "id": "16.2",
    "number": "16.2",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Nonviolence, truth, angerlessness, renunciation, peace, non-slander, compassion, non-greed, gentleness, modesty, steadiness.",
    "commentary": "Ethical daivi virtues. Ramakantha: tyaga here is phala-tyaga precursor to Ch.18.",
    "keyPoints": ["ahimsa-satya", "tyaga-shanti"]
  },
  {
    "id": "16.3",
    "number": "16.3",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Radiance, forgiveness, fortitude, purity, harmlessness, non-pride belong to divine-born.",
    "commentary": "Closing daivi enumeration. Ramakantha notes  /  variant (tushti contentment vs adroha harmlessness) both indicating santosha-ahara for samuccaya.",
    "keyPoints": ["tejas-kshama", "adroha-amanita"]
  },
  {
    "id": "16.4",
    "number": "16.4",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Hypocrisy, arrogance, conceit, anger, harshness and ignorance belong to demonic-born.",
    "commentary": "Asuri vipaksha. Ramakantha: ajnana-mula asuri as mala-prabalya.",
    "keyPoints": ["dambha-darpa", "ajnana"]
  },
  {
    "id": "16.5",
    "number": "16.5",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Divine wealth leads to liberation, demonic to bondage; grieve not, you are divine-born.",
    "commentary": "Phala-bheda and ashvasa. Ramakantha: Arjuna adhikari for samuccaya hence daivi.",
    "keyPoints": ["vimoksha-nibandha", "ma shucah"]
  },
  {
    "id": "16.6",
    "number": "16.6",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Two creature-orders, divine and demonic; divine expounded, now hear demonic.",
    "commentary": "Dvaira-shya vibhaga. Ramakantha: sarga is bhava-sarga, not jati.",
    "keyPoints": ["dvau sargau", "asura-shravana"]
  },
  {
    "id": "16.7",
    "number": "16.7",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Demonic know not activity nor withdrawal; no purity, conduct, or truth in them.",
    "commentary": "Pravritti-nivritti viveka lacking. Ramakantha: shastra-anadara is asura-linga.",
    "keyPoints": ["a-pravritti-viveka", "a-shauca"]
  },
  {
    "id": "16.8",
    "number": "16.8",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "They call world unreal, foundationless, lordless, born of mutual union, nothing but lust-caused.",
    "commentary": "Nastika-drishti. Ramakantha refutes Carvaka-Bauddha paksha; Ishvara is adhyaksha.",
    "keyPoints": ["a-satya-jagat", "a-nishvara-vada"]
  },
  {
    "id": "16.9",
    "number": "16.9",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Holding this view, lost-souled, small-minded, cruel-doers arise as world-ruiners.",
    "commentary": "Social phala of mithya-drishti. Ramakantha: ugra-karma from krodha-kama.",
    "keyPoints": ["nashtatman", "jagat-kshaya"]
  },
  {
    "id": "16.10",
    "number": "16.10",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Resorting to insatiable desire, full of hypocrisy-pride-arrogance, deludedly holding false dogmas, they act impurely.",
    "commentary": "Kama-ashraya. Ramakantha: duspura-kama is Shaiva hrdaya-granthi.",
    "keyPoints": ["duspura-kama", "asad-graha"]
  },
  {
    "id": "16.11",
    "number": "16.11",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Clinging to endless anxiety ending with death, holding enjoyment as highest, convinced this is all.",
    "commentary": "Cinta as samsara. Ramakantha: pralayanta cinta blocks samuccaya.",
    "keyPoints": ["aparimeya-cinta", "bhoga-parama"]
  },
  {
    "id": "16.12",
    "number": "16.12",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Bound by hundred hope-nooses, devoted to lust-anger, they seek wealth unjustly for enjoyment.",
    "commentary": "Artha-anyaya. Ramakantha: asha-pasha is bandha-dridhata.",
    "keyPoints": ["asha-pasha", "anyaya-artha"]
  },
  {
    "id": "16.13",
    "number": "16.13",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "This gained today, this desire I shall get, this wealth mine and more shall be mine.",
    "commentary": "Aham-vada monologue 13-15. Ramakantha showsaha nkara-vriddhi as asura-pushti.",
    "keyPoints": ["labdha-manoratha", "dhana-trishna"]
  },
  {
    "id": "16.14",
    "number": "16.14",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "This foe slain, others I shall slay; I am lord, enjoyer, perfect, strong, happy.",
    "commentary": "Ishvara-abhimana viparyaya. Ramakantha: mithya-ishvaratva vs true Maheshvaratva.",
    "keyPoints": ["hatah-shatru", "mithya-ishvara"]
  },
  {
    "id": "16.15",
    "number": "16.15",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Rich, well-born, who equals me? I shall sacrifice, give, rejoice, deluded by ignorance.",
    "commentary": "Dana-yajna with ahankara is asura. Ramakantha contrasts with sattvika tyaga in Ch.17-18.",
    "keyPoints": ["adhya-abhimana", "ajnana-mohita"]
  },
  {
    "id": "16.16",
    "number": "16.16",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Bewildered by manifold thoughts, enmeshed in delusion, attached to enjoyments, they fall into foul hell.",
    "commentary": "Naraka as citta-avastha and gati. Ramakantha: moha-jala is maya-avarana.",
    "keyPoints": ["aneka-citta", "naraka-patana"]
  },
  {
    "id": "16.17",
    "number": "16.17",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Self-conceited, stubborn, drunk with wealth-pride, they sacrifice nominally with hypocrisy against ordinance.",
    "commentary": "Nama-yajna critique. Ramakantha: avidhi is shastra-agama-viruddha.",
    "keyPoints": ["atma-sambhavita", "nama-yajna"]
  },
  {
    "id": "16.18",
    "number": "16.18",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Resorting to ego, force, pride, lust, anger, envying Me in own and others' bodies, they hate.",
    "commentary": "Dvesha toward Antaryami. Ramakantha: atma-para-deha-dvesha is Shiva-dvesha.",
    "keyPoints": ["ahankara-ashraya", "mat-dvesha"]
  },
  {
    "id": "16.19",
    "number": "16.19",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Those hating cruel lowest men I cast ever into demonic wombs in samsara.",
    "commentary": "Ishvara-vaishamya parihara: karma-anurupa kshepa. Ramakantha: kshipami is niyati-shakti.",
    "keyPoints": ["dvishat-kshipana", "asuri-yoni"]
  },
  {
    "id": "16.20",
    "number": "16.20",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Attaining demonic wombs deluded birth after birth, never reaching Me, they go to lowest state.",
    "commentary": "Adhama-gati as apr apti. Ramakantha urges early samuccaya to reverse.",
    "keyPoints": ["janmani-janmani", "adhama-gati"]
  },
  {
    "id": "16.21",
    "number": "16.21",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Threefold gate of hell destroying self: lust, anger, greed; abandon these three.",
    "commentary": "Dvara-traya tyaga. Ramakantha: traya-tyaga is sannyasa-bija leading to Ch.18 tyaga.",
    "keyPoints": ["kama-krodha-lobha", "nara ka-dvara"]
  },
  {
    "id": "16.22",
    "number": "16.22",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Freed from these three darkness-gates, one practices self-good and reaches supreme goal.",
    "commentary": "Shreya-acarana. Ramakantha: atmana shreyas = jnana-karma-samuccaya.",
    "keyPoints": ["tamodvara-mukta", "shreya-acarana"]
  },
  {
    "id": "16.23",
    "number": "16.23",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Who discards scriptural ordinance acting wilfully attains neither perfection, happiness nor supreme goal.",
    "commentary": "Shastra-vidhi pramanya. Ramakantha: shastra includes Shaiva agama vidhi.",
    "keyPoints": ["shastra-utsarga", "a-siddhi"]
  },
  {
    "id": "16.24",
    "number": "16.24",
    "section": "Adhyāya 16 — Daivāsura-sampad (Divine & Demonic)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-daivasura"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Therefore scripture is authority for what to do and avoid; knowing ordinance, act here.",
    "commentary": "Upasamhara: shastra-pramana leads to Ch.17 shraddha and Ch.18 nirnaya. Ramakantha: karya-akarya viveka is samuccaya-adhikara.",
    "keyPoints": ["shastra-pramana", "karya-akarya"]
  },
  {
    "id": "17.1",
    "number": "17.1",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Those worshipping with faith yet discarding ordinance, what is their standing, sattva, rajas or tamas?",
    "commentary": "Shraddha without vidhi question. Ramakantha: shraddha-matra determines gati but needs shastra-samskara.",
    "keyPoints": ["shraddha-nishtha", "guna-prashna"]
  },
  {
    "id": "17.2",
    "number": "17.2",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Threefold faith of embodied, born of nature: sattvic, rajasic, tamasic; hear it.",
    "commentary": "Svabhava-ja shraddha. Ramakantha: svabhava is vasana-sancita guna.",
    "keyPoints": ["trividha-shraddha", "svabhava-ja"]
  },
  {
    "id": "17.3",
    "number": "17.3",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Faith accords with inner being; man is made of faith, whatever his faith that he is.",
    "commentary": "Shraddhamaya Purusha. Ramakantha: antahkarana-sattva shapes shraddha; hence shuddhi needed.",
    "keyPoints": ["sattvanurupa", "shraddhamaya"]
  },
  {
    "id": "17.4",
    "number": "17.4",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Sattvic worship gods, rajasic yaksha-rakshas, tamasic ghosts and spirits.",
    "commentary": "Upasya-linga. Ramakantha: deva = prakasha-shakti, bhuta-preta = tamas-avarana.",
    "keyPoints": ["deva-yaksha-preta", "upasya-bheda"]
  },
  {
    "id": "17.5",
    "number": "17.5",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Those performing dreadful non-scriptural austerity with hypocrisy-egotism, lust-passion-force.",
    "commentary": "Asura-tapas. Ramakantha: ashastra-tapas binds though painful.",
    "keyPoints": ["ashastra-tapas", "dambha-ahamkara"]
  },
  {
    "id": "17.6",
    "number": "17.6",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Tormenting elements in body and Me within, senseless; know them demonic-resolved.",
    "commentary": "Deha-shoshana ninda. Ramakantha: antah-sharira Ishvara-dvesha is Shiva-aparadha.",
    "keyPoints": ["bhuta-karshana", "asura-nishcaya"]
  },
  {
    "id": "17.7",
    "number": "17.7",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Food dear to each is threefold, as are sacrifice, austerity, charity; hear their distinctions.",
    "commentary": "Ahara-yajna-tapo-dana vibhaga programme. Ramakantha: ahara-shuddhi is samuccaya-mula.",
    "keyPoints": ["ahara-trividha", "yajna-bheda"]
  },
  {
    "id": "17.8",
    "number": "17.8",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Life-sattva-strength-health-pleasure increasing, juicy, smooth, stable, hearty foods dear to sattvic.",
    "commentary": "Sattvika-ahara lakshana. Ramakantha prescribes for jnana-karma sadhaka.",
    "keyPoints": ["ayuh-sattva-vardhana", "hridya"]
  },
  {
    "id": "17.9",
    "number": "17.9",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Bitter-sour-salty-overhot-pungent-dry-burning foods dear to rajasic give pain-grief-disease.",
    "commentary": "Rajasika-ahara. Ramakantha: tejas-udvejaka ahara agitates karma.",
    "keyPoints": ["katu-amla", "duhkha-prada"]
  },
  {
    "id": "17.10",
    "number": "17.10",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Stale, tasteless, putrid, leftover, impure food dear to tamasic.",
    "commentary": "Tamasika-ahara. Ramakantha: amedhya blocks viveka.",
    "keyPoints": ["yatayama", "amedhya"]
  },
  {
    "id": "17.11",
    "number": "17.11",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Sacrifice offered as duty without fruit-desire according to ordinance with collected mind is sattvic.",
    "commentary": "Sattvika-yajna = nishkama-vidhi-yukta. Ramakantha model for samuccaya-karma.",
    "keyPoints": ["aphala-kanksha", "yashtavya-buddhi"]
  },
  {
    "id": "17.12",
    "number": "17.12",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Offered aiming at fruit or for ostentation, know that as rajasic.",
    "commentary": "Phala-dambha mixture. Ramakantha: dambha contaminates even vidhi.",
    "keyPoints": ["phala-sandhana", "dambha"]
  },
  {
    "id": "17.13",
    "number": "17.13",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Devoid of ordinance, food-gift, mantra, fee, and faith is called tamasic.",
    "commentary": "Tamasa-yajna. Ramakantha: shraddha-virahita nullifies.",
    "keyPoints": ["vidhi-hina", "shraddha-hina"]
  },
  {
    "id": "17.14",
    "number": "17.14",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Worship of gods, twice-born, teachers, wise, purity, honesty, celibacy, nonviolence is bodily austerity.",
    "commentary": "Sharira-tapas. Ramakantha: pujana includes Shiva-guru-archana.",
    "keyPoints": ["deva-guru-pujana", "sharira-tapas"]
  },
  {
    "id": "17.15",
    "number": "17.15",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Inoffensive, true, pleasant-beneficial speech and study-practice is vocal austerity.",
    "commentary": "Vanmaya-tapas. Ramakantha: satya-priya-hita as mantra-shuddhi.",
    "keyPoints": ["anudvega-vakya", "svadhyaya"]
  },
  {
    "id": "17.16",
    "number": "17.16",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Cheerfulness, gentleness, silence, self-control, purity of motive is mental austerity.",
    "commentary": "Manasa-tapas. Ramakantha: bhava-samshuddhi is vimarsha-nirmalatva.",
    "keyPoints": ["manah-prasada", "mauna"]
  },
  {
    "id": "17.17",
    "number": "17.17",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "This threefold austerity practiced with supreme faith by balanced non-fruit-seekers is sattvic.",
    "commentary": "Sattvika-tapas. Ramakantha: yukta = samuccaya-yukta.",
    "keyPoints": ["paraya-shraddha", "aphala"]
  },
  {
    "id": "17.18",
    "number": "17.18",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Done for honour-respect-worship with hypocrisy is rajasic, unstable, impermanent.",
    "commentary": "Rajasa-tapas. Ramakantha: cala-adhruva phala warns karma-sanga.",
    "keyPoints": ["satkara-artha", "cala"]
  },
  {
    "id": "17.19",
    "number": "17.19",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Done with deluded obstinacy tormenting self or to harm others is tamasic.",
    "commentary": "Tamasa-tapas. Ramakantha: mudha-graha is duragraha-mala.",
    "keyPoints": ["mudha-graha", "para-utsadana"]
  },
  {
    "id": "17.20",
    "number": "17.20",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Gift given as duty to non-returning worthy at place-time is sattvic.",
    "commentary": "Sattvika-dana. Ramakantha: datavyam-buddhi is samuccaya-dana.",
    "keyPoints": ["datavya-buddhi", "desha-kala-patra"]
  },
  {
    "id": "17.21",
    "number": "17.21",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Given for return or aiming fruit, grudgingly, is rajasic.",
    "commentary": "Rajasa-dana. Ramakantha: pariklishta contaminates.",
    "keyPoints": ["pratyupakara", "pariklishta"]
  },
  {
    "id": "17.22",
    "number": "17.22",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Given at wrong place-time to unworthy, disrespectfully-contemptuously is tamasic.",
    "commentary": "Tamasa-dana. Ramakantha: apatra-dana vardhayati moha.",
    "keyPoints": ["adesha-kala", "avajnata"]
  },
  {
    "id": "17.23",
    "number": "17.23",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Om Tat Sat is threefold designation of Brahman; thereby Brahmanas, Vedas, sacrifices ordained of old.",
    "commentary": "Brahma-nirdesha. Ramakantha: Om = Para-nada, Tat = Para, Sat = Sattva-sphurana.",
    "keyPoints": ["Om-Tat-Sat", "Brahma-nirdesha"]
  },
  {
    "id": "17.24",
    "number": "17.24",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Hence uttering Om, sacrifices-charities-austerities proceed per ordinance for Brahman-seekers.",
    "commentary": "Om-purvaka karma. Ramakantha: Omkarapranidhana shuddhaye.",
    "keyPoints": ["Om-uccarana", "vidhi-pravritti"]
  },
  {
    "id": "17.25",
    "number": "17.25",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Uttering Tat without aiming fruit, varied sacrifices-austerities-charities done by liberation-seekers.",
    "commentary": "Tat = nishkama-mudra. Ramakantha: moksha-kanksha is samuccaya-iccha.",
    "keyPoints": ["Tat", "a-nabhisandhaya"]
  },
  {
    "id": "17.26",
    "number": "17.26",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Sat is used for existence and goodness, and for praiseworthy action.",
    "commentary": "Sad-artha. Ramakantha: Sat = satta-sphurana Shiva.",
    "keyPoints": ["sadbhava", "prashasta-karma"]
  },
  {
    "id": "17.27",
    "number": "17.27",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Steadfastness in sacrifice-austerity-charity is called Sat, and action for That is Sat.",
    "commentary": "Sthiti as Sat. Ramakantha: tad-arthiya karma = Ishvararpana.",
    "keyPoints": ["sthiti-Sat", "tad-arthiya"]
  },
  {
    "id": "17.28",
    "number": "17.28",
    "section": "Adhyāya 17 — Śraddhātraya (Three Faiths)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-shraddha"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Offered-given-austered-done without faith is Asat, naught here or hereafter.",
    "commentary": "Ashraddha = Asat. Ramakantha closes shraddha-adhyaya: shraddha is samuccaya-prana.",
    "keyPoints": ["ashraddha-Asat", "ubhaya-nash"]
  },
  {
    "id": "18.1",
    "number": "18.1",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Arjuna seeks truth of sannyasa and tyaga distinctly.",
    "commentary": "Question distinguishes sannyasa (svarupa-tyaga) and tyaga (phala-tyaga). Ramakantha promises samuccaya-nirnaya.",
    "keyPoints": ["sannyasa-prashna", "tyaga-bheda"]
  },
  {
    "id": "18.2",
    "number": "18.2",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Sages know sannyasa as laying down kamya acts, the wise call tyaga abandonment of all action-fruits.",
    "commentary": "Classical bheda. Ramakantha: kamya-nyasa is sannyasa, phala-tyaga allows nitya-karma-samuccaya.",
    "keyPoints": ["kamya-nyasa", "phala-tyaga"]
  },
  {
    "id": "18.3",
    "number": "18.3",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Some say all action faulty to be abandoned, others say sacrifice-charity-austerity never to be abandoned.",
    "commentary": "Purva-paksha dvaya. Ramakantha notes Shaiva paksha retains pavana-karma.",
    "keyPoints": ["tyajya-vada", "a-tyajya-vada"]
  },
  {
    "id": "18.4",
    "number": "18.4",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Hear My conclusion on tyaga, threefold proclaimed.",
    "commentary": "Pratijna for trividha-tyaga. Ramakantha: nishcaya is samuccaya-siddhanta.",
    "keyPoints": ["nishcaya", "trividha-tyaga"]
  },
  {
    "id": "18.5",
    "number": "18.5",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Sacrifice-charity-austerity never to be abandoned but done; they purify the wise.",
    "commentary": "Pavana-karma doctrine. Ramakantha: pavana = mala-shodhana for jnana-yogyata.",
    "keyPoints": ["na tyajyam", "pavanani"]
  },
  {
    "id": "18.6",
    "number": "18.6",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Even these acts done abandoning attachment and fruits is My settled supreme view.",
    "commentary": "Sangaphala-tyaga is samuccaya formula. Ramakantha: uttamam matam = Shaiva siddhanta.",
    "keyPoints": ["sanga-phala-tyaga", "nishcita-mata"]
  },
  {
    "id": "18.7",
    "number": "18.7",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Renunciation of obligatory act is improper; abandoning from delusion is tamasic.",
    "commentary": "Niyata-tyaga nishedha. Ramakantha: mohat-tyaga is tamas-sannyasa-abhasa.",
    "keyPoints": ["niyata-a-tyajya", "moha-tamasa"]
  },
  {
    "id": "18.8",
    "number": "18.8",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Abandoning act fearing bodily pain from sorrow gets rajasic tyaga, no fruit.",
    "commentary": "Kaya-klesha-bhaya tyaga. Ramakantha: rajasatyaga fails samuccaya.",
    "keyPoints": ["duhkha-bhaya", "rajasa-tyaga"]
  },
  {
    "id": "18.9",
    "number": "18.9",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Obligatory act done as duty abandoning attachment-fruit is sattvic tyaga.",
    "commentary": "Karya-buddhi tyaga ideal. Ramakantha: this is samuccaya-tyaga svarupa.",
    "keyPoints": ["karya-buddhi", "sattvika-tyaga"]
  },
  {
    "id": "18.10",
    "number": "18.10",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Hating not unskilled, clinging not to skilled, sattva-filled wise doubt-cut is true renouncer.",
    "commentary": "Tyagi-lakshana. Ramakantha: medhavi = viveki samuccayi.",
    "keyPoints": ["a-dvesha-a-sanga", "chinna-samshaya"]
  },
  {
    "id": "18.11",
    "number": "18.11",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Embodied cannot wholly abandon acts; abandoner of fruits is called tyagi.",
    "commentary": "Asheshata-asambhava hetu. Ramakantha: dehabhrit must do pavana-karma with phala-tyaga.",
    "keyPoints": ["a-shakya-ashesha", "phala-tyagi"]
  },
  {
    "id": "18.12",
    "number": "18.12",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Threefold fruit unpleasant-pleasant-mixed accrues hereafter to non-renouncers, never to renouncers.",
    "commentary": "Phala-traya vibhaga. Ramakantha: sannyasin here = phala-sannyasi samuccayi.",
    "keyPoints": ["trividha-phala", "a-tyagin"]
  },
  {
    "id": "18.13",
    "number": "18.13",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Learn five causes for all action-accomplishment declared in Samkhya-kritanta.",
    "commentary": "Pancakarana. Ramakantha: Samkhya-kritanta = siddhanta including Shaiva karana-pancaka.",
    "keyPoints": ["panca-karana", "sarva-siddhi"]
  },
  {
    "id": "18.14",
    "number": "18.14",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Base, agent, varied instruments, distinct efforts, and fifth providence.",
    "commentary": "Karana list. Ramakantha: daiva = Ishvara-shakti, not blind fate.",
    "keyPoints": ["adhishthana-karta", "daiva-pancama"]
  },
  {
    "id": "18.15",
    "number": "18.15",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Whatever just or unjust begun by body-speech-mind has these five as causes.",
    "commentary": "Sarva-karma vyapti. Ramakantha: nyayya-viparita both need shuddhi.",
    "keyPoints": ["kaya-van-manah", "nyayya-viparita"]
  },
  {
    "id": "18.16",
    "number": "18.16",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Seeing only Self as agent thus, from unrefined intellect, that fool sees not.",
    "commentary": "Kevala-kartrtva ninda. Ramakantha: akritabuddhi = asamucita-buddhi.",
    "keyPoints": ["kevala-akartrtva", "durmati"]
  },
  {
    "id": "18.17",
    "number": "18.17",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Whose ego-sense and intellect unstained, slaying worlds neither slays nor is bound.",
    "commentary": "Al epa-jnana. Ramakantha: nahankrita is Shiva-bodha, allowing samuccayi action without bandha.",
    "keyPoints": ["nahankrita", "a-lipyamana"]
  },
  {
    "id": "18.18",
    "number": "18.18",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Knowledge, knowable, knower impel action; instrument, act, agent comprise action.",
    "commentary": "Karma-codana-sangraha. Ramakantha links to Ch.13 triad.",
    "keyPoints": ["jnana-jneya", "karana-karma"]
  },
  {
    "id": "18.19",
    "number": "18.19",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Knowledge, action, agent are threefold by guna; hear as taught in guna-shastra.",
    "commentary": "Guna-traya application. Ramakantha: guna-sankhyana = Ch.14 extension.",
    "keyPoints": ["guna-bheda", "yathavat-shravana"]
  },
  {
    "id": "18.20",
    "number": "18.20",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "By which one imperishable being is seen undivided in divided beings, know as sattvic knowledge.",
    "commentary": "Ekatva-jnana. Ramakantha: avyaya-bhava = Shiva-satta.",
    "keyPoints": ["eka-avyaya", "sattvika-jnana"]
  },
  {
    "id": "18.21",
    "number": "18.21",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Knowledge seeing manifold distinct beings separately is rajasic.",
    "commentary": "Prithaktva-jnana. Ramakantha: bheda-graha from rajas.",
    "keyPoints": ["prithaktva", "rajasa-jnana"]
  },
  {
    "id": "18.22",
    "number": "18.22",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Clinging to one act as whole without reason, untrue, trivial is tamasic.",
    "commentary": "Kritsna-vad ekasmin. Ramakantha: ahaituka-mudha.",
    "keyPoints": ["ekasakti", "tamasa-jnana"]
  },
  {
    "id": "18.23",
    "number": "18.23",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Ordained, attachmentless, without love-hate, by fruit-undesiring is sattvic action.",
    "commentary": "Sattvika-karma = samuccaya-karma. Ramakantha core definition.",
    "keyPoints": ["niyata-sangarahita", "aphala"]
  },
  {
    "id": "18.24",
    "number": "18.24",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Done by desire-seeker with ego and great effort is rajasic.",
    "commentary": "Kamepsu-sahankara. Ramakantha: bahulayasa is rajas-linga.",
    "keyPoints": ["kamepsu", "bahulayasa"]
  },
  {
    "id": "18.25",
    "number": "18.25",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Begun deludedly ignoring consequence, loss, harm, capacity is tamasic.",
    "commentary": "Anubandha-anapeksha. Ramakantha: mohat-arambha.",
    "keyPoints": ["anubandha", "tamasa"]
  },
  {
    "id": "18.26",
    "number": "18.26",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Freed from attachment, egoless speech, firm-zealous, unmoved in success-failure is sattvic agent.",
    "commentary": "Sattvika-karta. Ramakantha ideal samuccayi.",
    "keyPoints": ["mukta-sanga", "siddhi-nirvikara"]
  },
  {
    "id": "18.27",
    "number": "18.27",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Passionate, fruit-craving, greedy, harmful, impure, joy-sorrowed is rajasic agent.",
    "commentary": "Rajasa-karta. Ramakantha: lubdha-himsatmaka.",
    "keyPoints": ["ragi-lubdha", "harshashoka"]
  },
  {
    "id": "18.28",
    "number": "18.28",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Unyoked, vulgar, stubborn, deceitful, idle, despondent, procrastinating is tamasic agent.",
    "commentary": "Tamasa-karta. Ramakantha: ayukta = asamahita.",
    "keyPoints": ["ayukta-alasa", "vishadi"]
  },
  {
    "id": "18.29",
    "number": "18.29",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Hear fully distinct threefold intellect and resolve by guna.",
    "commentary": "Buddhi-dhriti vibhaga pratijna. Ramakantha: buddhi-shuddhi is samuccaya-dvara.",
    "keyPoints": ["buddhi-dhriti", "guna-trividha"]
  },
  {
    "id": "18.30",
    "number": "18.30",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Knowing activity-withdrawal, duty-unduty, fear-fearlessness, bondage-liberation is sattvic intellect.",
    "commentary": "Sattvika-buddhi viveka. Ramakantha: bandha-moksha-viveka is samuccaya-phala.",
    "keyPoints": ["pravritti-nivritti", "bandha-moksha"]
  },
  {
    "id": "18.31",
    "number": "18.31",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "By which dharma-adharma, duty-unduty are wrongly known is rajasic intellect.",
    "commentary": "Ayathavat. Ramakantha: viparyaya from rajas.",
    "keyPoints": ["ayathavat", "rajasi-buddhi"]
  },
  {
    "id": "18.32",
    "number": "18.32",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Covered by darkness, taking adharma as dharma and all reversed is tamasic intellect.",
    "commentary": "Viparita. Ramakantha: tamasavrta = mala-avrta.",
    "keyPoints": ["adharma-dharma", "tamasi"]
  },
  {
    "id": "18.33",
    "number": "18.33",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "By which mind-breath-sense acts are held with unfailing yoga is sattvic resolve.",
    "commentary": "Sattvika-dhriti. Ramakantha: avyabhicari-yoga = samuccaya-dhriti.",
    "keyPoints": ["mana-prana-dharana", "avyabhicari"]
  },
  {
    "id": "18.34",
    "number": "18.34",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Holding dharma-pleasure-wealth with attachment, fruit-craving is rajasic resolve.",
    "commentary": "Rajasi-dhriti. Ramakantha: prasanga = sanga.",
    "keyPoints": ["dharma-kamartha", "phala-kanksha"]
  },
  {
    "id": "18.35",
    "number": "18.35",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "By which sleep, fear, grief, despair, intoxication not abandoned by dull is tamasic resolve.",
    "commentary": "Tamasi-dhriti. Ramakantha: durmedha = viveka-hina.",
    "keyPoints": ["svapna-bhaya", "durmedha"]
  },
  {
    "id": "18.36",
    "number": "18.36",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Now hear threefold happiness where one delights by practice and reaches sorrow-end.",
    "commentary": "Sukha-traya pratijna. Ramakantha: abhyasa-ramati is samuccaya-ananda.",
    "keyPoints": ["trividha-sukha", "duhkhanta"]
  },
  {
    "id": "18.37",
    "number": "18.37",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "First like poison, end like nectar, born of self-intellect clarity is sattvic happiness.",
    "commentary": "Atma-buddhi-prasada. Ramakantha: agre visha = sadhana-klesha, pariname amrita = Shiva-vishranti.",
    "keyPoints": ["agre-visha", "atmabuddhi-prasada"]
  },
  {
    "id": "18.38",
    "number": "18.38",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "From sense-object contact, first nectar-like, end poison-like is rajasic happiness.",
    "commentary": "Vishayendriya. Ramakantha warns samuccayi to transcend.",
    "keyPoints": ["vishaya-samyoga", "pariname-visha"]
  },
  {
    "id": "18.39",
    "number": "18.39",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Deluding self first and after, born of sleep-sloth-negligence is tamasic happiness.",
    "commentary": "Mohana-sukha. Ramakantha: nidra-sukha is tamas-ananda-abhasa.",
    "keyPoints": ["mohana", "nidra-pramada"]
  },
  {
    "id": "18.40",
    "number": "18.40",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "No being on earth or among gods free from these three prakriti-born gunas exists.",
    "commentary": "Guna-vyapti. Ramakantha: hence gunatita requires Shakti-prasada.",
    "keyPoints": ["sarva-guna-vyapta", "na mukta"]
  },
  {
    "id": "18.41",
    "number": "18.41",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Brahmin-kshatriya-vaishya-shudra duties distributed by nature-born gunas.",
    "commentary": "Svabhava-guna varna. Ramakantha: svabhava = samskara-guna, not birth alone; supports adhikara for samuccaya.",
    "keyPoints": ["svabhava-guna", "karma-vibhaga"]
  },
  {
    "id": "18.42",
    "number": "18.42",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Calm, restraint, austerity, purity, patience, honesty, knowledge, realisation, faith is brahmin nature-duty.",
    "commentary": "Brahma-karma. Ramakantha: jnana-vijnana is agama-viveka.",
    "keyPoints": ["shama-dama", "jnana-vijnana"]
  },
  {
    "id": "18.43",
    "number": "18.43",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Valour, radiance, resolve, skill, non-flight in battle, charity, lordliness is kshatra nature-duty.",
    "commentary": "Kshatra-karma. Ramakantha: Arjuna sva-dharma hence yuddha as samuccaya-karma.",
    "keyPoints": ["shaurya-tejas", "apalayana"]
  },
  {
    "id": "18.44",
    "number": "18.44",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Agriculture-cattle-trade is vaishya, service-natured is shudra duty.",
    "commentary": "Vaishya-shudra. Ramakantha defends all as pavana when Ishvararpita.",
    "keyPoints": ["krishi-vanijya", "paricarya"]
  },
  {
    "id": "18.45",
    "number": "18.45",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Devoted to own duty one attains perfection; hear how duty-devoted gains perfection.",
    "commentary": "Sve-sve-karmani siddhi. Ramakantha: sva-karma is samuccaya-dvara, not kevala-karma.",
    "keyPoints": ["sva-karma-abhirati", "samsiddhi"]
  },
  {
    "id": "18.46",
    "number": "18.46",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Worshipping with own duty Him from whom beings issue and all pervaded, one gains perfection.",
    "commentary": "Sva-karma-abhyarcana. Ramakantha: abhyarcya = Shiva-puja-buddhi, samuccaya-sara.",
    "keyPoints": ["yatah-pravritti", "abhyarcya-siddhi"]
  },
  {
    "id": "18.47",
    "number": "18.47",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Better own duty deficient than alien well-done; doing nature-fixed act incurs no sin.",
    "commentary": "Sva-dharma shreyas. Ramakantha: svabhava-niyata = adhikara-anurupa samuccaya-karma.",
    "keyPoints": ["svadharmo-vigunah", "a-kilbisha"]
  },
  {
    "id": "18.48",
    "number": "18.48",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Inborn act though faulty abandon not; all undertakings veiled by fault as fire by smoke.",
    "commentary": "Sahaja-a-tyaga. Ramakantha: dosha is guna-avas esha, shuddhya by phala-tyaga.",
    "keyPoints": ["sahaja-a-tyaga", "dhumagni nyaya"]
  },
  {
    "id": "18.49",
    "number": "18.49",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Unattached intellect everywhere, conquered self, cravings gone, attains supreme actionlessness perfection through renunciation.",
    "commentary": "Naishkarmya-siddhi via sannyasa (phala-sannyasa). Ramakantha: asakta-buddhi is samuccaya-nishtha phala.",
    "keyPoints": ["asakta-buddhi", "naishkarmya-siddhi"]
  },
  {
    "id": "18.50",
    "number": "18.50",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "How perfection-gainer attains Brahman, learn briefly, supreme consummation of knowledge.",
    "commentary": "Brahma-prapti krama pratijna. Ramakantha: para jnana-nishtha is samuccaya-para.",
    "keyPoints": ["siddhi-Brahma", "para-nishtha"]
  },
  {
    "id": "18.51",
    "number": "18.51",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Yoked with pure intellect, restraining self by resolve, abandoning sound-objects, casting love-hate.",
    "commentary": "Brahma-yogyata-sadhana. Ramakantha: vishuddha-buddhi from pavana-karma.",
    "keyPoints": ["vishuddha-buddhi", "raga-dvesha-tyaga"]
  },
  {
    "id": "18.52",
    "number": "18.52",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Resorting solitude, light-eating, restrained speech-body-mind, ever meditation-yoked, resorting dispassion.",
    "commentary": "Bahir-anga. Ramakantha: vivikta-seva supports antarmukha samuccaya.",
    "keyPoints": ["vivikta-laghvashi", "dhyana-para"]
  },
  {
    "id": "18.53",
    "number": "18.53",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Shedding ego, force, pride, lust, anger, grasping, egoless, peaceful, fit for Brahman-becoming.",
    "commentary": "Antar-shuddhi. Ramakantha: parigraha-tyaga is aparigraha-sannyasa.",
    "keyPoints": ["ahankara-tyaga", "nirmama-shanta"]
  },
  {
    "id": "18.54",
    "number": "18.54",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Brahman-become, serene, grieves not, craves not, equal to all, attains supreme devotion to Me.",
    "commentary": "Brahmabhuta-para-bhakti. Ramakantha: para-bhakti is fruit of samuccaya, not means only.",
    "keyPoints": ["brahmabhuta", "para-bhakti"]
  },
  {
    "id": "18.55",
    "number": "18.55",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "By devotion one knows Me as I am in truth; knowing thus truly enters thereafter.",
    "commentary": "Bhakti-jnana-pravesha. Ramakantha: vishate = tanmayibhava, Shaiva samavesha.",
    "keyPoints": ["tattvato-jnana", "tad-vishate"]
  },
  {
    "id": "18.56",
    "number": "18.56",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Ever doing all acts sheltered in Me, by My grace attains eternal imperishable state.",
    "commentary": "Mad-vyapashraya samuccaya. Ramakantha: mat-prasada is Shakti-anugraha.",
    "keyPoints": ["mad-vyapashraya", "mat-prasada"]
  },
  {
    "id": "18.57",
    "number": "18.57",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Mentally resigning all acts to Me, intent on Me, resorting to buddhi-yoga, be ever mind-fixed on Me.",
    "commentary": "Cetasa-sannyasa vidhi. Ramakantha: manasa-sannyasa preserves bahya-karma with samuccaya.",
    "keyPoints": ["cetasa-sannyasa", "mat-citta"]
  },
  {
    "id": "18.58",
    "number": "18.58",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Mind-fixed on Me, by My grace cross all straits; if egotistically hear not, perish.",
    "commentary": "Prasada-tarana vs vinasha. Ramakantha: ahankara-ashravana breaks samuccaya.",
    "keyPoints": ["durga-tarana", "a-shravana-vinasha"]
  },
  {
    "id": "18.59",
    "number": "18.59",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Clinging to ego thinking I shall not fight, vain resolve; nature will compel you.",
    "commentary": "Ahankara-vyavasaya mithya. Ramakantha patha    (you shall not escape the act) stresses svabhava-niyojana over Shankara reading.",
    "keyPoints": ["ahankara-mithya", "prakriti-niyojana"]
  },
  {
    "id": "18.60",
    "number": "18.60",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Bound by own nature-born act, what deludedly you wish not to do, helplessly you shall do.",
    "commentary": "Svabhava-nibandha. Ramakantha: avasha-kartrtva shows karma unavoidable, hence samuccaya necessary.",
    "keyPoints": ["svabhava-nibaddha", "avasha-karana"]
  },
  {
    "id": "18.61",
    "number": "18.61",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Rāmakantha pāṭha: Rāmakantha: hṛdyeṣa vasateʼrjuna (vs hṛd-deśeʼrjuna tiṣṭhati)."}],
    "translation": "The Lord dwells in hearts of all beings, whirling all as if machine-mounted by maya.",
    "commentary": "Hridaya-Ishvara. Ramakantha patha   for   emphasizes indwelling residence (vasa) as Shakti-vilasa.",
    "keyPoints": ["hridi-Ishvara", "yantra-maya"]
  },
  {
    "id": "18.62",
    "number": "18.62",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Surrender to Him alone with whole being; by His grace attain supreme peace and eternal abode.",
    "commentary": "Sharanagati. Ramakantha reads tat-prasada as mat-prasada, Shiva-anugraha granting shanti-siddhi; variant recorded at 18.63  .",
    "keyPoints": ["sarvabhava-sharana", "tat-prasada-shanti"]
  },
  {
    "id": "18.63",
    "number": "18.63",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}, {"note": "Rāmakantha pāṭha: Rāmakantha: mat-prasādāt parāṃ siddhiṃ (vs tat-prasādāt parāṃ śāntim)."}],
    "translation": "Thus knowledge more secret than secret taught; reflecting fully, act as you wish.",
    "commentary": "Vimrishya-adhikara. Ramakantha: yath ecchasi preserves svatantrya; siddhi is mat-prasada, not kevala-purusha prayatna.",
    "keyPoints": ["guhyatara", "vimrishya-kuru"]
  },
  {
    "id": "18.64",
    "number": "18.64",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Hear again My supreme most-secret word; dear you are firmly, hence I speak welfare.",
    "commentary": "Sarva-guhyatama pratijna. Ramakantha: ishta-adhikari Arjuna fit for samuccaya-upadesha.",
    "keyPoints": ["guhyatama", "ishta-hita"]
  },
  {
    "id": "18.65",
    "number": "18.65",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Be mind-fixed on Me, devotee, sacrificer, bow to Me; you shall reach Me, truly I promise, dear you are.",
    "commentary": "Manmana-madbhakta caturvidha. Ramakantha: mad-yaji includes bahya-karma samarpita.",
    "keyPoints": ["manmana", "satya-pratijna"]
  },
  {
    "id": "18.66",
    "number": "18.66",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Abandoning all dharmas, surrender to Me alone; I shall free you from all sins, grieve not.",
    "commentary": "Sarva-dharma-tyaga is phala-sanga-tyaga, not svarupa-tyaga of pavana-karma. Ramakantha harmonizes with 18.5-6 samuccaya.",
    "keyPoints": ["sarvadharma-tyaga", "eka-sharana"]
  },
  {
    "id": "18.67",
    "number": "18.67",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Never speak this to non-austere, non-devotee, non-listener, or hater of Me.",
    "commentary": "Gopyatva niyama. Ramakantha: adhikari is tapas-bhakti-shushrusha-yukta samuccayi.",
    "keyPoints": ["a-tapaska-varjana", "gopya"]
  },
  {
    "id": "18.68",
    "number": "18.68",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Who teaches this supreme secret among My devotees, with supreme devotion, shall reach Me doubtless.",
    "commentary": "Acarya-phala. Ramakantha: sampradaya-raksha is Shaiva seva.",
    "keyPoints": ["guhya-pracara", "para-bhakti"]
  },
  {
    "id": "18.69",
    "number": "18.69",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "None among men dearer doer to Me than he, nor dearer shall be on earth.",
    "commentary": "Priyakrit-tama. Ramakantha: jnana-dana is para-seva.",
    "keyPoints": ["priyakrit", "priyatara"]
  },
  {
    "id": "18.70",
    "number": "18.70",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Who studies this righteous dialogue worships Me by knowledge-sacrifice, is My view.",
    "commentary": "Jnana-yajna. Ramakantha: adhyayana is manasa-samuccaya.",
    "keyPoints": ["adhyayana", "jnana-yajna"]
  },
  {
    "id": "18.71",
    "number": "18.71",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Faithful, non-cavilling hearer even is freed and attains auspicious worlds of virtuous.",
    "commentary": "Shravana-phala. Ramakantha validates shruta-parayana as in 13.26.",
    "keyPoints": ["shraddha-shravana", "shubha-loka"]
  },
  {
    "id": "18.72",
    "number": "18.72",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Has this been heard one-pointedly? Is ignorance-delusion destroyed?",
    "commentary": "Prashna for shishya-nishcaya. Ramakantha: ekagra-shravana is samuccaya-siddhi pariksha.",
    "keyPoints": ["ekagra-shravana", "moha-pranasha"]
  },
  {
    "id": "18.73",
    "number": "18.73",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Delusion destroyed, memory gained by Your grace; fixed, doubt-gone, I shall do Your word.",
    "commentary": "Shishya-pratyaya. Ramakantha: smriti-labha is pratyabhijna; karishye vacanam is samuccaya-angikara (fight as duty).",
    "keyPoints": ["nashto-mohah", "karishye-vacanam"]
  },
  {
    "id": "18.74",
    "number": "18.74",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Thus I heard this wondrous hair-raising dialogue of Vasudeva and great-souled Partha.",
    "commentary": "Sanjaya-sakshya. Ramakantha accepts itihasa-pramanya.",
    "keyPoints": ["adbhuta-samvada", "romaharshana"]
  },
  {
    "id": "18.75",
    "number": "18.75",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "By Vyasa grace I heard this supreme secret yoga from Yogeshvara Krishna himself.",
    "commentary": "Vyasa-prasada divya-shravana. Ramakantha: guru-prasada parampara.",
    "keyPoints": ["Vyasa-prasada", "Yogeshvara"]
  },
  {
    "id": "18.76",
    "number": "18.76",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "O king, remembering this holy wondrous dialogue again and again I rejoice.",
    "commentary": "Samsmritya-harsha. Ramakantha: punah-smarana is dhyana.",
    "keyPoints": ["samsmritya", "muhur-hrishyami"]
  },
  {
    "id": "18.77",
    "number": "18.77",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Remembering Hari's most wondrous form, great amazement, I rejoice again and again.",
    "commentary": "Vishvarupa-smarana. Ramakantha links Ch.11 to samuccaya-bhakti phala.",
    "keyPoints": ["rupa-smarana", "vismaya"]
  },
  {
    "id": "18.78",
    "number": "18.78",
    "section": "Adhyāya 18 — Mokṣa-sannyāsa (Release)",
    "devanagari": "",
    "iast": "",
    "conceptIds": ["gita-moksa"],
    "interpretiveNotes": [{"note": "Kashmir Series of Texts and Studies No. LXIV (1943): Bhagavadgītā with Sarvatobhadra of Rājānaka Rāmakantha, ed. Madhusudan Kaul Shastri; Sanskrit-only source, English rendering original to this project."}],
    "translation": "Where Yogeshvara Krishna and bowman Partha are, there fortune, victory, prosperity, firm policy, is my conviction.",
    "commentary": "Upasamhara: samuccaya of Ishvara-yoga and nara-paurusha gives shri-vijaya. Ramakantha: this is jnana-karma-samuccaya phala-shloka.",
    "keyPoints": ["Yogeshvara-dhanurdhara", "shri-vijaya"]
  },
];