export const mimamsaConceptsEn = [
  {
    id: 'dharma-jijnasa',
    sanskrit: 'धर्मजिज्ञासा',
    iast: 'dharmajijñāsā',
    english: 'Inquiry into Dharma',
    category: 'Epistemology',
    definition: 'The systematic philosophical inquiry into the nature of duty and righteousness, necessary because the Vedas are complex and require interpretation.',
    significance: 'Sets the entire foundation of the Mimamsa system: mere recitation is insufficient; comprehension is required.'
  },
  {
    id: 'codana',
    sanskrit: 'चोदना',
    iast: 'codanā',
    english: 'Vedic Injunction',
    category: 'Epistemology',
    definition: 'A prescriptive command found in the Vedas that urges one to perform a specific action.',
    significance: 'The sole and exclusive means of knowing Dharma according to Mimamsa.'
  },
  {
    id: 'dharma',
    sanskrit: 'धर्म',
    iast: 'dharma',
    english: 'Duty / Righteousness',
    category: 'Ethics / Ontology',
    definition: 'That objective which is indicated by a Vedic injunction and is conducive to the highest good.',
    significance: 'The central focus of Mimamsa, entirely un-knowable through sensory perception or logic.'
  },
  {
    id: 'pramana',
    sanskrit: 'प्रमाण',
    iast: 'pramāṇa',
    english: 'Means of Valid Knowledge',
    category: 'Epistemology',
    definition: 'The instruments through which valid knowledge is acquired. Mimamsa rigorously examines these to prove only the Veda can reveal Dharma.',
    significance: 'Establishes the epistemological boundaries of what can and cannot be known through human faculties.'
  },
  {
    id: 'pratyaksha',
    sanskrit: 'प्रत्यक्ष',
    iast: 'pratyakṣa',
    english: 'Sensory Perception',
    category: 'Epistemology',
    definition: 'Knowledge arising from the direct contact of sense organs with existing objects.',
    significance: 'Explicitly rejected as a means to know Dharma, because Dharma deals with future, unseen outcomes.'
  },
  {
    id: 'apurva',
    sanskrit: 'अपूर्व',
    iast: 'apūrva',
    english: 'Unseen Force',
    category: 'Ontology',
    definition: 'The unseen, future outcome or spiritual merit generated by an action that bridges the temporal gap between a ritual and its future result (e.g., heaven).',
    significance: 'Explains causality in ritual action and necessitates Vedic authority.'
  },
  {
    id: 'autpattika',
    sanskrit: 'औत्पत्तिक',
    iast: 'autpattika',
    english: 'Innate / Eternal Connection',
    category: 'Linguistics / Epistemology',
    definition: 'The doctrine that the relationship between a word and its meaning is structural, uncreated, and eternal.',
    significance: 'The central dogma of Mimamsa that guarantees the infallibility of the Veda.'
  },
  {
    id: 'apaurusheya',
    sanskrit: 'अपौरुषेय',
    iast: 'apauruṣeya',
    english: 'Authorless',
    category: 'Theology / Epistemology',
    definition: 'Not authored by any human or divine agency. The Veda is considered Apaurusheya.',
    significance: 'Removes the possibility of human error, deceit, or ignorance from Vedic commands.'
  },
  {
    id: 'sabda-anityatva',
    sanskrit: 'शब्दानित्यत्व',
    iast: 'śabdānityatva',
    english: 'Non-eternality of Sound',
    category: 'Linguistics (Purvapaksha)',
    definition: 'The opponent\'s view (Nyaya) that sound is a produced, transient physical wave that ceases to exist after utterance.',
    significance: 'The primary objection Jaimini must overcome to establish the eternality of the Veda.'
  },
  {
    id: 'sabda-nityatva',
    sanskrit: 'शब्ददित्यत्व',
    iast: 'śabdanityatva',
    english: 'Eternality of Sound',
    category: 'Linguistics (Siddhanta)',
    definition: 'The Mimamsa conclusion that the Word (Sabda) is eternal, and human utterance merely manifests it through physical sound waves (Nada).',
    significance: 'Proves the eternal nature of language, ensuring the eternal validity of the Vedas.'
  },
  {
    "id": "arthavada",
    "sanskrit": "अर्थवाद",
    "iast": "arthavāda",
    "english": "Corroborative Statement",
    "category": "Hermeneutics",
    "definition": "Vedic passages that do not command an action directly, but consist of stories, myths, or descriptions.",
    "significance": "Though not commands themselves, they are vital as they provide psychological motivation (Prarocana) for performing the enjoined actions."
  },
  {
    "id": "ekavakyata",
    "sanskrit": "एकवाक्यता",
    "iast": "ekavākyatā",
    "english": "Syntactical Unity",
    "category": "Hermeneutics",
    "definition": "The principle that a descriptive sentence (Arthavada) forms a single, unified syntactical whole with a prescriptive command (Vidhi).",
    "significance": "Resolves the objection that descriptive Vedic texts are useless, proving they serve the central ritual action."
  },
  {
    "id": "gunavada",
    "sanskrit": "गुणवाद",
    "iast": "guṇavāda",
    "english": "Figurative Expression",
    "category": "Hermeneutics",
    "definition": "Interpreting a statement metaphorically based on secondary qualities when its literal meaning contradicts empirical perception or reality.",
    "significance": "Ensures that seemingly absurd or contradictory Vedic statements are understood logically and poetically."
  },
  {
    "id": "prarocana",
    "sanskrit": "प्ररोचना",
    "iast": "prarocanā",
    "english": "Psychological Motivation",
    "category": "Psychology / Hermeneutics",
    "definition": "The praising or glorification of an action to entice and motivate the human agent to perform difficult rituals.",
    "significance": "The primary function of Arthavada texts, recognizing human psychological needs within duty."
  },
  {
    "id": "hetu",
    "sanskrit": "हेतु",
    "iast": "hetu",
    "english": "Reason / Logical Justification",
    "category": "Epistemology",
    "definition": "A stated reason within the Veda (e.g., \"because...\"). In Mimamsa, these are never treated as true logical proofs, but merely as rhetorical praise (Stuti).",
    "significance": "Prevents human logic from superseding the absolute authority of the Vedic command. If logic were supreme, the command could be ignored."
  },
  {
    "id": "mantra",
    "sanskrit": "मन्त्र",
    "iast": "mantra",
    "english": "Sacred Chant",
    "category": "Ritual / Linguistics",
    "definition": "Vedic verses recited during a ritual. Opponents claim they are magical, meaningless noise, but Jaimini proves they possess exact semantic meaning.",
    "significance": "Ensures that the Veda is entirely a semantic, meaningful text, not just a collection of phonetic vibrations."
  },
  {
    "id": "adrishta",
    "sanskrit": "अदृष्ट",
    "iast": "adṛṣṭa",
    "english": "Unseen Spiritual Result",
    "category": "Ontology",
    "definition": "The invisible metaphysical potency generated by the exact, flawless performance of a ritual (including the strict phonetic sequence of Mantras).",
    "significance": "Explains why synonyms cannot be used in Mantras even though their meaning is the same; the exact sound generates Adrishta."
  },
  {
    "id": "smarana",
    "sanskrit": "स्मरण",
    "iast": "smaraṇa",
    "english": "Recollection / Mental Focus",
    "category": "Psychology / Ritual",
    "definition": "The primary function of reciting a Mantra during a ritual: to mentally recall the specific deity, material, and action precisely at the required moment.",
    "significance": "Proves that Mantras have a profound psychological and cognitive purpose, demanding the full attention of the priest."
  },
  {
    "id": "smriti",
    "sanskrit": "स्मृति",
    "iast": "smṛti",
    "english": "Remembered Tradition",
    "category": "Epistemology",
    "definition": "Human-authored texts on Dharma (e.g., Manusmriti). They hold derivative authority by allowing us to infer the existence of a lost Vedic text.",
    "significance": "Incorporates traditional human law into the Vedic system, but firmly subordinates it to the eternal Sruti."
  },
  {
    "id": "sadachara",
    "sanskrit": "सदाचार",
    "iast": "sadācāra",
    "english": "Customs of the Good",
    "category": "Epistemology / Ethics",
    "definition": "Unwritten customs practiced by virtuous people (Śiṣṭas) who know the Veda. Valid as a source of Dharma if they do not contradict the Veda.",
    "significance": "Creates flexibility in Dharma, recognizing lived cultural traditions as authoritative extensions of scripture."
  },
  {
    "id": "akriti",
    "sanskrit": "आकृति",
    "iast": "ākṛti",
    "english": "The Universal / Form",
    "category": "Linguistics / Ontology",
    "definition": "The eternal, abstract class or universal (e.g., \"cow-ness\"). Mimamsa asserts that words strictly denote Universals, not physical individuals.",
    "significance": "The ultimate philosophical defense of the eternal Word; since individuals die but Universals do not, the word-meaning connection remains unbroken."
  },
  {
    "id": "vyakti",
    "sanskrit": "व्यक्ति",
    "iast": "vyakti",
    "english": "The Particular / Individual",
    "category": "Linguistics / Ontology",
    "definition": "A specific, physical entity. Words do not denote these; they are only implied because actions require physical objects.",
    "significance": "Subordinates the physical world to the conceptual/eternal realm of language."
  },
  {
    "id": "apabhramsa",
    "sanskrit": "अपभ्रंश",
    "iast": "apabhraṃśa",
    "english": "Corrupt Language / Slang",
    "category": "Linguistics",
    "definition": "Grammatically incorrect speech. While it can convey meaning, it is banned in Vedic rituals because it fails to generate spiritual merit (Adrishta).",
    "significance": "Elevates grammar (Vyakarana) to a spiritual science, not just a communicative tool."
  },
  {
    "id": "namadheya",
    "sanskrit": "नामधेय",
    "iast": "nāmadheya",
    "english": "Proper Name",
    "category": "Linguistics / Hermeneutics",
    "definition": "A word in the Veda that serves as the title of a specific ritual (like Udbhid or Agnihotra), rather than enjoining a material accessory.",
    "significance": "Prevents the Veda from being misinterpreted as commanding unnecessary objects, keeping the ritual syntax clean and distinct."
  },
  {
    "id": "vakyabheda",
    "sanskrit": "वाक्यभेद",
    "iast": "vākyabheda",
    "english": "Syntactical Split",
    "category": "Hermeneutics (Fallacy)",
    "definition": "The logical fallacy of making a single sentence command two entirely different things simultaneously (e.g., commanding both a sacrifice and a specific material).",
    "significance": "A central rule of Mimamsa interpretation: a single injunction can only have one primary objective to maintain clear authority."
  },
  {
    "id": "rudhi",
    "sanskrit": "रूढि",
    "iast": "rūḍhi",
    "english": "Conventional Meaning",
    "category": "Linguistics",
    "definition": "The fixed, widely accepted meaning of a noun denoting a specific class or genus (e.g., \"Barhis\" means Kusha grass).",
    "significance": "Overrides functional interpretations. You cannot substitute any grass and still call it Barhis just because it serves the same function."
  },
  {
    "id": "yaugika",
    "sanskrit": "यौगिक",
    "iast": "yaugika",
    "english": "Derivative Meaning",
    "category": "Linguistics",
    "definition": "A word whose meaning is derived purely from its verbal root and functional action (e.g., \"Prokshani\" means anything used for sprinkling).",
    "significance": "Contrasts with Rudhi; allows for functional flexibility when a word is inherently action-based."
  },
  {
    "id": "matvartha-lakshana",
    "sanskrit": "मत्वर्थलक्षणा",
    "iast": "matvarthalakṣaṇā",
    "english": "Secondary Implication of Possession",
    "category": "Hermeneutics (Fallacy)",
    "definition": "Twisting the direct meaning of a word to mean \"possessing X\" rather than just \"X\".",
    "significance": "Mimamsa heavily avoids this. If a word can be simply read as a proper name (Namadheya) without twisting its grammar, that interpretation wins."
  },
  {
    "id": "bhavana",
    "sanskrit": "भावना",
    "iast": "bhāvanā",
    "english": "Productive Energy / Verbal Action",
    "category": "Linguistics / Ontology",
    "definition": "The active, productive force denoted by a verb. It is the core engine of a Vedic sentence, drawing in all nouns and materials to accomplish an action.",
    "significance": "Establishes that the Veda is fundamentally about doing and becoming, not just knowing static facts."
  },
  {
    "id": "pradhana-karma",
    "sanskrit": "प्रधानकर्म",
    "iast": "pradhānakarma",
    "english": "Primary Action",
    "category": "Ritual Mechanics",
    "definition": "An action where the material is consumed or disposed of (e.g., offering ghee into fire), performed solely to generate the transcendent Apurva.",
    "significance": "The core ritual act that directly leads to the promised heavenly result."
  },
  {
    "id": "guna-karma",
    "sanskrit": "गुणकर्म",
    "iast": "guṇakarma",
    "english": "Secondary Action",
    "category": "Ritual Mechanics",
    "definition": "A preparatory action that physically modifies or improves a substance (e.g., washing rice) so it can be used in the Primary Action.",
    "significance": "Creates a strict hierarchical dependency of actions, preventing ritual chaos."
  },
  {
    "id": "brahmana",
    "sanskrit": "ब्राह्मण",
    "iast": "brāhmaṇa",
    "english": "Prose Injunctions and Explanations",
    "category": "Textual Classification",
    "definition": "The portion of the Veda that contains the actual commands (Vidhi) and their explanatory stories (Arthavada), defined as everything that is not a Mantra.",
    "significance": "The true source of Dharma, where the authoritative rules are found."
  },
  {
    "id": "rc",
    "sanskrit": "ऋच्",
    "iast": "ṛc",
    "english": "Metrical Verse",
    "category": "Textual Classification",
    "definition": "A Mantra that is highly structured into specific metrical feet (pādas) according to its meaning.",
    "significance": "Defines the structural basis of the Rig Veda based purely on metrical utility."
  },
  {
    "id": "saman",
    "sanskrit": "सामन्",
    "iast": "sāman",
    "english": "Musical Chant",
    "category": "Textual Classification",
    "definition": "A Mantra that is stretched and set to complex musical notation and melody.",
    "significance": "Defines the Sama Veda based on its musical ritual application."
  },
  {
    "id": "yajus",
    "sanskrit": "यजुस्",
    "iast": "yajuṣ",
    "english": "Prose Formula",
    "category": "Textual Classification",
    "definition": "A Mantra that is neither strictly metrical (Ṛc) nor musically chanted (Sāman); a prose formula.",
    "significance": "Defines the Yajur Veda through an exclusionary classification."
  },
  {
    "id": "karmabheda",
    "sanskrit": "कर्मभेद",
    "iast": "karmabheda",
    "english": "Differentiation of Action",
    "category": "Ritual Mechanics",
    "definition": "The logical process of determining whether Vedic sentences command one single action or multiple distinct actions. Jaimini establishes six strict proofs (Pramanas) to differentiate actions.",
    "significance": "Prevents the conflation of rituals, ensuring that every command is executed with its exact intended structure and distinct Apurva."
  },
  {
    "id": "sabdantara",
    "sanskrit": "शब्दान्तर",
    "iast": "śabdāntara",
    "english": "Difference of Verbs",
    "category": "Ritual Mechanics (Proof)",
    "definition": "The first proof of Karma-bheda: If the Veda uses completely different verb roots (e.g., sacrificing vs. giving), they command fundamentally different actions.",
    "significance": "Ensures that the physical mechanics of an act (like burning vs. transferring ownership) are not confused."
  },
  {
    "id": "abhyasa",
    "sanskrit": "अभ्यास",
    "iast": "abhyāsa",
    "english": "Repetition",
    "category": "Ritual Mechanics (Proof)",
    "definition": "The second proof: The deliberate repetition of the same verb without a new accessory proves it is a sequence of separate actions, not one continuous act.",
    "significance": "Establishes that the Veda is never redundant; every repetition has a distinct mathematical and spiritual purpose."
  },
  {
    "id": "sankhya",
    "sanskrit": "सङ्ख्या",
    "iast": "saṅkhyā",
    "english": "Number",
    "category": "Ritual Mechanics (Proof)",
    "definition": "The third proof: The explicit use of a number (e.g., \"three libations\") logically divides the action into that exact number of distinct events.",
    "significance": "Brings mathematical precision to the ritual syntax."
  },
  {
    "id": "samjna",
    "sanskrit": "संज्ञा",
    "iast": "saṃjñā",
    "english": "Proper Name (As a Proof)",
    "category": "Ritual Mechanics (Proof)",
    "definition": "The fourth proof: Differing proper titles (e.g., Jyotishtoma vs. Ashvamedha) indicate completely different primary rituals.",
    "significance": "Treats titles as rigid boundaries between massive ritual systems."
  },
  {
    "id": "guna-proof",
    "sanskrit": "गुण",
    "iast": "guṇa",
    "english": "Incompatible Accessory",
    "category": "Ritual Mechanics (Proof)",
    "definition": "The fifth proof: If two sentences command completely incompatible primary materials (like solid curds vs. liquid whey) at the origin of the act, they must be two distinct acts.",
    "significance": "Prevents logistical paradoxes in ritual execution."
  },
  {
    "id": "prakaranantara",
    "sanskrit": "प्रकरणान्तर",
    "iast": "prakaraṇāntara",
    "english": "Difference of Context",
    "category": "Ritual Mechanics (Proof)",
    "definition": "The sixth proof: A ritual described in one chapter is distinct from a similarly named ritual in a completely different, walled-off chapter.",
    "significance": "Uses the architectural structure of the Veda itself to isolate actions."
  },
  {
    "id": "anuvada",
    "sanskrit": "अनुवाद",
    "iast": "anuvāda",
    "english": "Restatement / Corroboration",
    "category": "Hermeneutics",
    "definition": "The restatement of an already established injunction. It is not a new command; it serves merely as a reference point to attach a new accessory (Guṇa) or a specific reward to a known action.",
    "significance": "Prevents the unnecessary multiplication of rituals by recognizing when the Veda is just adding details to an existing act."
  },
  {
    "id": "guna-vikara",
    "sanskrit": "गुणविकार",
    "iast": "guṇavikāra",
    "english": "Accessory Modification",
    "category": "Ritual Mechanics",
    "definition": "A variation in the method or materials of a standard sacrifice (like the Dakshayana). It receives a specific name but remains fundamentally the same primary ritual.",
    "significance": "Demonstrates that a new proper name does not always mean a new primary act if the core mechanics are identical."
  },
  {
    "id": "adhikara-bheda",
    "sanskrit": "अधिकारभेद",
    "iast": "adhikārabheda",
    "english": "Difference in Eligibility",
    "category": "Ritual Mechanics",
    "definition": "A proof of independence. If an embedded ritual (like the Aveshti) allows participants (like Brahmanas) who are strictly forbidden from the main overarching ritual (like the Kshatriya-only Rajasuya), the embedded ritual must be an independent act.",
    "significance": "Shows how social/caste eligibility rules are used as logical proofs to untangle ritual syntax."
  },
  {
    "id": "prakarana-subordination",
    "sanskrit": "प्रकरण",
    "iast": "prakaraṇa",
    "english": "Contextual Gravitation",
    "category": "Hermeneutics",
    "definition": "The rule that any action mentioned inside a specific chapter (Prakaraṇa) without its own stated reward is automatically sucked in as a subordinate act serving the main sacrifice of that chapter.",
    "significance": "Creates a neat, hierarchical dependency tree where minor acts logically support the primary objective."
  }
];
