// Brahma Sutras — verse-to-concept links overlay.
//
// The raw Adhyaya files carry translation + commentary but no concept tags,
// which left all 552 sutras and all 27 concepts graph-orphaned (no verse page
// showed concepts, no concept page listed verses, related-verse ranking was empty).
// This id-keyed overlay supplies conceptIds per sutra, merged in brahma-sutras.ts
// like the key-points overlay; raw Adhyaya files are untouched.
// The factory stitches the reverse direction (concept.relatedVerseIds) at runtime.
//
// Derivation, kept here for auditability:
// - PRIMARY: one or two standard adhikarana subjects per pada (16 padas; e.g. 1.1
//   is Brahman, 2.2 is the defence of Brahman, 3.3 is the vidyas). Deliberately
//   narrow: rival doctrines, pramana, sadhana and maya ride on precise paraphrase
//   keywords, never on pada-wide defaults (an earlier draft tagged every 2.2 verse
//   with all five rival schools and was rejected on sample review).
// - KEYWORDS: English paraphrase vocabulary of the Sankara commentaries, which rarely
//   use Sanskrit terms (atman:0, maya:0, moksha:0 in the corpus) but say soul/self/lord,
//   dream/deep sleep, superimposition, atoms, momentariness. Each pattern was
//   frequency-probed and sample-verified; scoped exceptions: insentient only in the
//   cause-debate padas, void only in 2.2 (elsewhere it is a verb), prana/breath/vital
//   only in the genesis/departure padas (elsewhere prana is Brahman or the upasya),
//   liberation vocabulary routes to jivanmukti except in 4.2/4.3 (krama-mukti).
// - UNION: thread step verseIds imply their step conceptId (16 refs; all already
//   covered, kept as an independent curation signal).
// - Manual overrides: 1.1.1 gains sadhana_chatushtaya (its atha marks the fourfold fitness;
//   thread step-1 agrees but carries no verseIds) and drops jivanmukti; 1.2.11 drops jiva (supreme soul).
// - Thin nodes are honest: anirvacaniya (1 sutra), satta_traya, syadvada and the
//   Samkhya triad occur rarely in the sutra text. Enrich only with genuine
//   scholarship, never padding.

export const brahmaSutrasLinksEn: Record<string, string[]> = {
  // Adhyaya 1
  '1.1.1': ['concept_brahman', 'concept_sadhana_chatushtaya'],
  '1.1.2': ['concept_brahman', 'concept_pramana'],
  '1.1.3': ['concept_brahman', 'concept_pramana'],
  '1.1.4': ['concept_brahman', 'concept_maya', 'concept_pramana'],
  '1.1.5': ['concept_brahman', 'concept_atman', 'concept_pradhana', 'concept_samkhya_gunas'],
  '1.1.6': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_jivanmukti', 'concept_pradhana'],
  '1.1.7': ['concept_brahman', 'concept_atman', 'concept_maya', 'concept_jivanmukti', 'concept_nididhyasana', 'concept_pradhana'],
  '1.1.8': ['concept_brahman', 'concept_satkaryavada', 'concept_pradhana'],
  '1.1.9': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_avastha_traya', 'concept_turiya', 'concept_pradhana'],
  '1.1.10': ['concept_brahman', 'concept_atman'],
  '1.1.11': ['concept_brahman', 'concept_ishvara', 'concept_pramana', 'concept_pradhana'],
  '1.1.12': ['concept_brahman', 'concept_atman', 'concept_pancha_kosha', 'concept_sadhana_chatushtaya', 'concept_nididhyasana'],
  '1.1.13': ['concept_brahman', 'concept_jiva', 'concept_pancha_kosha'],
  '1.1.14': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_pancha_kosha'],
  '1.1.15': ['concept_brahman', 'concept_atman', 'concept_pancha_kosha'],
  '1.1.16': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara'],
  '1.1.17': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_pancha_kosha'],
  '1.1.18': ['concept_brahman', 'concept_atman', 'concept_pancha_kosha', 'concept_pradhana'],
  '1.1.19': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_pancha_kosha'],
  '1.1.20': ['concept_brahman', 'concept_ishvara', 'concept_nididhyasana'],
  '1.1.21': ['concept_brahman', 'concept_jiva', 'concept_ishvara'],
  '1.1.22': ['concept_brahman', 'concept_atman'],
  '1.1.23': ['concept_brahman', 'concept_jiva', 'concept_avastha_traya', 'concept_turiya'],
  '1.1.24': ['concept_brahman', 'concept_atman', 'concept_nididhyasana'],
  '1.1.25': ['concept_brahman', 'concept_nididhyasana'],
  '1.1.26': ['concept_brahman'],
  '1.1.27': ['concept_brahman'],
  '1.1.28': ['concept_brahman', 'concept_atman', 'concept_nididhyasana'],
  '1.1.29': ['concept_brahman', 'concept_atman', 'concept_ishvara'],
  '1.1.30': ['concept_brahman', 'concept_atman', 'concept_pramana'],
  '1.1.31': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_satta_traya', 'concept_nididhyasana'],
  '1.2.1': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_nididhyasana'],
  '1.2.2': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_nididhyasana'],
  '1.2.3': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara'],
  '1.2.4': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_nididhyasana'],
  '1.2.5': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_nididhyasana'],
  '1.2.6': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara', 'concept_satkaryavada', 'concept_satta_traya'],
  '1.2.7': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_sadhana_chatushtaya', 'concept_nididhyasana'],
  '1.2.8': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara', 'concept_maya', 'concept_karma_traya'],
  '1.2.9': ['concept_brahman', 'concept_atman', 'concept_jiva'],
  '1.2.10': ['concept_brahman', 'concept_atman', 'concept_jiva'],
  '1.2.11': ['concept_brahman', 'concept_atman', 'concept_ishvara'],
  '1.2.12': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara', 'concept_adhyasa', 'concept_nididhyasana', 'concept_samkhya_gunas'],
  '1.2.13': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_sadhana_chatushtaya', 'concept_jivanmukti', 'concept_nididhyasana'],
  '1.2.14': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_nididhyasana'],
  '1.2.15': ['concept_brahman', 'concept_atman'],
  '1.2.16': ['concept_brahman', 'concept_atman', 'concept_ishvara'],
  '1.2.17': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_adhyasa', 'concept_sadhana_chatushtaya', 'concept_nididhyasana'],
  '1.2.18': ['concept_brahman', 'concept_atman', 'concept_satta_traya'],
  '1.2.19': ['concept_brahman', 'concept_atman', 'concept_pradhana'],
  '1.2.20': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_maya', 'concept_satkaryavada', 'concept_karma_traya'],
  '1.2.21': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara', 'concept_karma_traya', 'concept_jivanmukti'],
  '1.2.22': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_adhyasa', 'concept_pradhana'],
  '1.2.23': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara'],
  '1.2.24': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara'],
  '1.2.25': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara', 'concept_pramana'],
  '1.2.26': ['concept_brahman', 'concept_atman', 'concept_ishvara', 'concept_nididhyasana'],
  '1.2.27': ['concept_brahman', 'concept_atman'],
  '1.2.28': ['concept_brahman', 'concept_atman', 'concept_nididhyasana'],
  '1.2.29': ['concept_brahman', 'concept_atman', 'concept_ishvara'],
  '1.2.30': ['concept_brahman', 'concept_atman', 'concept_ishvara', 'concept_nididhyasana'],
  '1.2.31': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara', 'concept_adhyasa', 'concept_nididhyasana'],
  '1.2.32': ['concept_brahman', 'concept_atman'],
  '1.3.1': ['concept_brahman', 'concept_atman', 'concept_jiva'],
  '1.3.2': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_jivanmukti'],
  '1.3.3': ['concept_brahman', 'concept_atman', 'concept_pradhana'],
  '1.3.4': ['concept_brahman', 'concept_atman', 'concept_jiva'],
  '1.3.5': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_jivanmukti'],
  '1.3.6': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_satkaryavada'],
  '1.3.7': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara'],
  '1.3.8': ['concept_brahman', 'concept_atman', 'concept_avastha_traya', 'concept_turiya'],
  '1.3.9': ['concept_brahman', 'concept_atman', 'concept_avastha_traya', 'concept_turiya'],
  '1.3.10': ['concept_brahman', 'concept_atman', 'concept_nididhyasana'],
  '1.3.11': ['concept_brahman', 'concept_atman', 'concept_ishvara', 'concept_satkaryavada'],
  '1.3.12': ['concept_brahman', 'concept_atman', 'concept_jiva'],
  '1.3.13': ['concept_brahman', 'concept_atman', 'concept_vivartavada', 'concept_jivanmukti', 'concept_krama_mukti', 'concept_nididhyasana'],
  '1.3.14': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara'],
  '1.3.15': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_avastha_traya', 'concept_turiya', 'concept_krama_mukti'],
  '1.3.16': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara'],
  '1.3.17': ['concept_brahman', 'concept_atman', 'concept_jiva'],
  '1.3.18': ['concept_brahman', 'concept_atman', 'concept_jiva'],
  '1.3.19': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_vivartavada', 'concept_avastha_traya', 'concept_turiya'],
  '1.3.20': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara', 'concept_avastha_traya', 'concept_turiya', 'concept_nididhyasana'],
  '1.3.21': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara', 'concept_satkaryavada', 'concept_sadhana_chatushtaya', 'concept_nididhyasana'],
  '1.3.22': ['concept_brahman', 'concept_atman', 'concept_pancha_kosha'],
  '1.3.23': ['concept_brahman', 'concept_atman', 'concept_ishvara'],
  '1.3.24': ['concept_brahman', 'concept_atman', 'concept_ishvara'],
  '1.3.25': ['concept_brahman', 'concept_atman', 'concept_jiva'],
  '1.3.26': ['concept_brahman', 'concept_atman', 'concept_ishvara'],
  '1.3.27': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara'],
  '1.3.28': ['concept_brahman', 'concept_atman', 'concept_ishvara', 'concept_pramana'],
  '1.3.29': ['concept_brahman', 'concept_atman', 'concept_ishvara', 'concept_satkaryavada', 'concept_karma_traya'],
  '1.3.30': ['concept_brahman', 'concept_atman', 'concept_ishvara', 'concept_avastha_traya', 'concept_turiya'],
  '1.3.31': ['concept_brahman', 'concept_atman', 'concept_ishvara', 'concept_sadhana_chatushtaya', 'concept_nididhyasana'],
  '1.3.32': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara'],
  '1.3.33': ['concept_brahman', 'concept_atman', 'concept_ishvara', 'concept_pramana'],
  '1.3.34': ['concept_brahman', 'concept_atman', 'concept_sadhana_chatushtaya', 'concept_nididhyasana'],
  '1.3.35': ['concept_brahman', 'concept_atman'],
  '1.3.36': ['concept_brahman', 'concept_atman'],
  '1.3.37': ['concept_brahman', 'concept_atman'],
  '1.3.38': ['concept_brahman', 'concept_atman', 'concept_sadhana_chatushtaya', 'concept_nididhyasana'],
  '1.3.39': ['concept_brahman', 'concept_atman'],
  '1.3.40': ['concept_brahman', 'concept_atman', 'concept_jivanmukti'],
  '1.3.41': ['concept_brahman', 'concept_atman', 'concept_jiva'],
  '1.3.42': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara', 'concept_avastha_traya', 'concept_turiya', 'concept_karma_traya', 'concept_jivanmukti'],
  '1.3.43': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara'],
  '1.4.1': ['concept_pradhana', 'concept_brahman', 'concept_atman', 'concept_abhinna_nimitta_upadana'],
  '1.4.2': ['concept_pradhana', 'concept_brahman'],
  '1.4.3': ['concept_pradhana', 'concept_brahman', 'concept_jiva', 'concept_ishvara', 'concept_maya'],
  '1.4.4': ['concept_pradhana', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_jivanmukti'],
  '1.4.5': ['concept_pradhana', 'concept_brahman', 'concept_atman', 'concept_jivanmukti'],
  '1.4.6': ['concept_pradhana', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara'],
  '1.4.7': ['concept_pradhana', 'concept_brahman', 'concept_atman', 'concept_jivanmukti', 'concept_nididhyasana', 'concept_samkhya_gunas'],
  '1.4.8': ['concept_pradhana', 'concept_brahman', 'concept_samkhya_gunas'],
  '1.4.9': ['concept_pradhana', 'concept_brahman', 'concept_ishvara'],
  '1.4.10': ['concept_pradhana', 'concept_brahman', 'concept_jiva', 'concept_maya', 'concept_jivanmukti', 'concept_nididhyasana'],
  '1.4.11': ['concept_pradhana', 'concept_brahman', 'concept_atman'],
  '1.4.12': ['concept_pradhana', 'concept_brahman'],
  '1.4.13': ['concept_pradhana', 'concept_brahman', 'concept_nididhyasana'],
  '1.4.14': ['concept_pradhana', 'concept_brahman', 'concept_atman', 'concept_ishvara', 'concept_satkaryavada'],
  '1.4.15': ['concept_pradhana', 'concept_brahman', 'concept_atman', 'concept_pancha_kosha'],
  '1.4.16': ['concept_pradhana', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara', 'concept_karma_traya'],
  '1.4.17': ['concept_pradhana', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_avastha_traya', 'concept_turiya', 'concept_nididhyasana'],
  '1.4.18': ['concept_pradhana', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara', 'concept_avastha_traya', 'concept_turiya'],
  '1.4.19': ['concept_pradhana', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_nididhyasana'],
  '1.4.20': ['concept_pradhana', 'concept_brahman', 'concept_atman', 'concept_jiva'],
  '1.4.21': ['concept_pradhana', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_nididhyasana'],
  '1.4.22': ['concept_pradhana', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_maya'],
  '1.4.23': ['concept_pradhana', 'concept_brahman', 'concept_atman', 'concept_abhinna_nimitta_upadana', 'concept_satkaryavada', 'concept_vivartavada'],
  '1.4.24': ['concept_pradhana', 'concept_brahman', 'concept_atman', 'concept_abhinna_nimitta_upadana', 'concept_sadhana_chatushtaya', 'concept_nididhyasana'],
  '1.4.25': ['concept_pradhana', 'concept_brahman', 'concept_abhinna_nimitta_upadana', 'concept_satkaryavada'],
  '1.4.26': ['concept_pradhana', 'concept_brahman', 'concept_atman', 'concept_abhinna_nimitta_upadana'],
  '1.4.27': ['concept_pradhana', 'concept_brahman', 'concept_jiva', 'concept_ishvara', 'concept_satkaryavada'],
  '1.4.28': ['concept_pradhana', 'concept_brahman', 'concept_adhyasa', 'concept_sadhana_chatushtaya', 'concept_nididhyasana'],
  // Adhyaya 2
  '2.1.1': ['concept_brahman', 'concept_atman'],
  '2.1.2': ['concept_brahman', 'concept_pradhana'],
  '2.1.3': ['concept_brahman', 'concept_sadhana_chatushtaya', 'concept_jivanmukti', 'concept_nididhyasana'],
  '2.1.4': ['concept_brahman', 'concept_vivartavada', 'concept_pradhana'],
  '2.1.5': ['concept_brahman', 'concept_pradhana'],
  '2.1.6': ['concept_brahman', 'concept_pradhana'],
  '2.1.7': ['concept_brahman'],
  '2.1.8': ['concept_brahman'],
  '2.1.9': ['concept_brahman', 'concept_avastha_traya', 'concept_turiya'],
  '2.1.10': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_pradhana'],
  '2.1.11': ['concept_brahman', 'concept_jivanmukti'],
  '2.1.12': ['concept_brahman', 'concept_ishvara', 'concept_pradhana', 'concept_paramanuvada', 'concept_kshanikavada', 'concept_syadvada'],
  '2.1.13': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_avastha_traya', 'concept_turiya'],
  '2.1.14': ['concept_brahman', 'concept_atman', 'concept_satkaryavada', 'concept_adhyasa'],
  '2.1.15': ['concept_brahman', 'concept_satkaryavada'],
  '2.1.16': ['concept_brahman', 'concept_satkaryavada'],
  '2.1.17': ['concept_brahman'],
  '2.1.18': ['concept_brahman', 'concept_satkaryavada', 'concept_pramana'],
  '2.1.19': ['concept_brahman', 'concept_jiva', 'concept_avastha_traya', 'concept_turiya', 'concept_jivanmukti'],
  '2.1.20': ['concept_brahman', 'concept_avastha_traya', 'concept_turiya'],
  '2.1.21': ['concept_brahman', 'concept_jiva'],
  '2.1.22': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_satkaryavada'],
  '2.1.23': ['concept_brahman'],
  '2.1.24': ['concept_brahman'],
  '2.1.25': ['concept_brahman', 'concept_ishvara', 'concept_nididhyasana'],
  '2.1.26': ['concept_brahman'],
  '2.1.27': ['concept_brahman', 'concept_atman', 'concept_maya'],
  '2.1.28': ['concept_brahman', 'concept_atman', 'concept_ishvara', 'concept_avastha_traya', 'concept_turiya'],
  '2.1.29': ['concept_brahman', 'concept_pradhana'],
  '2.1.30': ['concept_brahman'],
  '2.1.31': ['concept_brahman', 'concept_sadhana_chatushtaya', 'concept_nididhyasana'],
  '2.1.32': ['concept_brahman', 'concept_ishvara'],
  '2.1.33': ['concept_brahman', 'concept_ishvara'],
  '2.1.34': ['concept_brahman', 'concept_jiva', 'concept_ishvara', 'concept_karma_traya'],
  '2.1.35': ['concept_brahman', 'concept_ishvara', 'concept_karma_traya'],
  '2.1.36': ['concept_brahman', 'concept_ishvara', 'concept_karma_traya'],
  '2.1.37': ['concept_brahman', 'concept_ishvara', 'concept_abhinna_nimitta_upadana'],
  '2.2.1': ['concept_brahman', 'concept_pramana', 'concept_pradhana'],
  '2.2.2': ['concept_brahman', 'concept_atman', 'concept_samkhya_gunas'],
  '2.2.3': ['concept_brahman', 'concept_atman', 'concept_pradhana'],
  '2.2.4': ['concept_brahman', 'concept_pradhana'],
  '2.2.5': ['concept_brahman', 'concept_pradhana'],
  '2.2.6': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_jivanmukti', 'concept_pradhana', 'concept_samkhya_purusha'],
  '2.2.7': ['concept_brahman', 'concept_pradhana', 'concept_samkhya_purusha'],
  '2.2.8': ['concept_brahman', 'concept_pradhana', 'concept_samkhya_gunas'],
  '2.2.9': ['concept_brahman', 'concept_pramana'],
  '2.2.10': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_maya', 'concept_jivanmukti', 'concept_pradhana', 'concept_samkhya_purusha', 'concept_samkhya_gunas'],
  '2.2.11': ['concept_brahman', 'concept_paramanuvada'],
  '2.2.12': ['concept_brahman', 'concept_jiva', 'concept_karma_traya', 'concept_pradhana', 'concept_paramanuvada'],
  '2.2.13': ['concept_brahman', 'concept_paramanuvada'],
  '2.2.14': ['concept_brahman', 'concept_paramanuvada'],
  '2.2.15': ['concept_brahman', 'concept_paramanuvada'],
  '2.2.16': ['concept_brahman', 'concept_paramanuvada'],
  '2.2.17': ['concept_brahman', 'concept_paramanuvada'],
  '2.2.18': ['concept_brahman', 'concept_pradhana', 'concept_paramanuvada', 'concept_kshanikavada'],
  '2.2.19': ['concept_brahman', 'concept_atman', 'concept_maya'],
  '2.2.20': ['concept_brahman'],
  '2.2.21': ['concept_brahman', 'concept_kshanikavada'],
  '2.2.22': ['concept_brahman', 'concept_atman', 'concept_kshanikavada'],
  '2.2.23': ['concept_brahman'],
  '2.2.24': ['concept_brahman', 'concept_kshanikavada'],
  '2.2.25': ['concept_brahman', 'concept_kshanikavada'],
  '2.2.26': ['concept_brahman'],
  '2.2.27': ['concept_brahman', 'concept_samkhya_purusha', 'concept_kshanikavada'],
  '2.2.28': ['concept_brahman', 'concept_atman', 'concept_satkaryavada', 'concept_pramana'],
  '2.2.29': ['concept_brahman', 'concept_atman', 'concept_avastha_traya', 'concept_turiya'],
  '2.2.30': ['concept_brahman', 'concept_pramana'],
  '2.2.31': ['concept_brahman', 'concept_kshanikavada'],
  '2.2.32': ['concept_brahman', 'concept_atman', 'concept_kshanikavada'],
  '2.2.33': ['concept_brahman', 'concept_syadvada'],
  '2.2.34': ['concept_brahman', 'concept_jiva', 'concept_syadvada'],
  '2.2.35': ['concept_brahman', 'concept_jiva'],
  '2.2.36': ['concept_brahman', 'concept_jiva', 'concept_karma_traya', 'concept_jivanmukti', 'concept_paramanuvada', 'concept_kshanikavada', 'concept_syadvada'],
  '2.2.37': ['concept_brahman', 'concept_jiva', 'concept_ishvara', 'concept_abhinna_nimitta_upadana'],
  '2.2.38': ['concept_brahman', 'concept_jiva', 'concept_ishvara', 'concept_pradhana', 'concept_kshanikavada'],
  '2.2.39': ['concept_brahman', 'concept_jiva', 'concept_ishvara', 'concept_pradhana', 'concept_paramanuvada'],
  '2.2.40': ['concept_brahman', 'concept_jiva', 'concept_ishvara', 'concept_pradhana'],
  '2.2.41': ['concept_brahman', 'concept_ishvara'],
  '2.2.42': ['concept_brahman', 'concept_jiva', 'concept_ishvara', 'concept_jivanmukti'],
  '2.2.43': ['concept_brahman', 'concept_jiva'],
  '2.2.44': ['concept_brahman'],
  '2.2.45': ['concept_brahman', 'concept_ishvara'],
  '2.3.1': ['concept_jiva', 'concept_atman'],
  '2.3.2': ['concept_jiva', 'concept_atman', 'concept_brahman'],
  '2.3.3': ['concept_jiva', 'concept_atman', 'concept_satkaryavada'],
  '2.3.4': ['concept_jiva', 'concept_atman', 'concept_brahman'],
  '2.3.5': ['concept_jiva', 'concept_atman', 'concept_brahman', 'concept_satkaryavada'],
  '2.3.6': ['concept_jiva', 'concept_atman', 'concept_brahman', 'concept_satkaryavada'],
  '2.3.7': ['concept_jiva', 'concept_atman', 'concept_vivartavada', 'concept_satkaryavada'],
  '2.3.8': ['concept_jiva', 'concept_atman'],
  '2.3.9': ['concept_jiva', 'concept_atman', 'concept_brahman'],
  '2.3.10': ['concept_jiva', 'concept_atman', 'concept_brahman'],
  '2.3.11': ['concept_jiva', 'concept_atman'],
  '2.3.12': ['concept_jiva', 'concept_atman'],
  '2.3.13': ['concept_jiva', 'concept_atman', 'concept_ishvara'],
  '2.3.14': ['concept_jiva', 'concept_atman', 'concept_brahman'],
  '2.3.15': ['concept_jiva', 'concept_atman', 'concept_brahman'],
  '2.3.16': ['concept_jiva', 'concept_atman'],
  '2.3.17': ['concept_jiva', 'concept_atman'],
  '2.3.18': ['concept_jiva', 'concept_atman'],
  '2.3.19': ['concept_jiva', 'concept_atman', 'concept_syadvada'],
  '2.3.20': ['concept_jiva', 'concept_atman'],
  '2.3.21': ['concept_jiva', 'concept_atman', 'concept_brahman', 'concept_vivartavada', 'concept_jivanmukti'],
  '2.3.22': ['concept_jiva', 'concept_atman'],
  '2.3.23': ['concept_jiva', 'concept_atman'],
  '2.3.24': ['concept_jiva', 'concept_atman'],
  '2.3.25': ['concept_jiva', 'concept_atman'],
  '2.3.26': ['concept_jiva', 'concept_atman'],
  '2.3.27': ['concept_jiva', 'concept_atman', 'concept_pramana', 'concept_avastha_traya', 'concept_turiya'],
  '2.3.28': ['concept_jiva', 'concept_atman'],
  '2.3.29': ['concept_jiva', 'concept_atman', 'concept_brahman', 'concept_maya'],
  '2.3.30': ['concept_jiva', 'concept_atman', 'concept_maya', 'concept_karma_traya', 'concept_jivanmukti'],
  '2.3.31': ['concept_jiva', 'concept_atman'],
  '2.3.32': ['concept_jiva', 'concept_atman', 'concept_pramana'],
  '2.3.33': ['concept_jiva', 'concept_atman'],
  '2.3.34': ['concept_jiva', 'concept_atman', 'concept_avastha_traya', 'concept_turiya'],
  '2.3.35': ['concept_jiva', 'concept_atman'],
  '2.3.36': ['concept_jiva', 'concept_atman'],
  '2.3.37': ['concept_jiva', 'concept_atman', 'concept_pramana'],
  '2.3.38': ['concept_jiva', 'concept_atman', 'concept_samkhya_purusha'],
  '2.3.39': ['concept_jiva', 'concept_atman', 'concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_samkhya_purusha'],
  '2.3.40': ['concept_jiva', 'concept_atman', 'concept_jivanmukti'],
  '2.3.41': ['concept_jiva', 'concept_atman', 'concept_ishvara'],
  '2.3.42': ['concept_jiva', 'concept_atman', 'concept_ishvara'],
  '2.3.43': ['concept_jiva', 'concept_atman', 'concept_brahman', 'concept_ishvara'],
  '2.3.44': ['concept_jiva', 'concept_atman'],
  '2.3.45': ['concept_jiva', 'concept_atman', 'concept_ishvara'],
  '2.3.46': ['concept_jiva', 'concept_atman', 'concept_ishvara', 'concept_satkaryavada'],
  '2.3.47': ['concept_jiva', 'concept_atman'],
  '2.3.48': ['concept_jiva', 'concept_atman', 'concept_jivanmukti'],
  '2.3.49': ['concept_jiva', 'concept_atman', 'concept_karma_traya'],
  '2.3.50': ['concept_jiva', 'concept_atman', 'concept_ishvara'],
  '2.3.51': ['concept_jiva', 'concept_atman', 'concept_karma_traya', 'concept_pradhana'],
  '2.3.52': ['concept_jiva', 'concept_atman', 'concept_ishvara'],
  '2.3.53': ['concept_jiva', 'concept_atman', 'concept_ishvara'],
  '2.4.1': ['concept_antahkarana', 'concept_jiva', 'concept_brahman', 'concept_atman'],
  '2.4.2': ['concept_antahkarana', 'concept_jiva', 'concept_abhinna_nimitta_upadana', 'concept_karma_traya'],
  '2.4.3': ['concept_antahkarana', 'concept_jiva'],
  '2.4.4': ['concept_antahkarana', 'concept_jiva'],
  '2.4.5': ['concept_antahkarana', 'concept_jiva'],
  '2.4.6': ['concept_antahkarana', 'concept_jiva', 'concept_pramana'],
  '2.4.7': ['concept_antahkarana', 'concept_jiva', 'concept_paramanuvada'],
  '2.4.8': ['concept_antahkarana', 'concept_jiva'],
  '2.4.9': ['concept_antahkarana', 'concept_jiva'],
  '2.4.10': ['concept_antahkarana', 'concept_jiva'],
  '2.4.11': ['concept_antahkarana', 'concept_jiva'],
  '2.4.12': ['concept_antahkarana', 'concept_jiva'],
  '2.4.13': ['concept_antahkarana', 'concept_jiva', 'concept_paramanuvada'],
  '2.4.14': ['concept_antahkarana', 'concept_jiva', 'concept_ishvara', 'concept_sadhana_chatushtaya', 'concept_nididhyasana'],
  '2.4.15': ['concept_antahkarana', 'concept_jiva', 'concept_atman'],
  '2.4.16': ['concept_antahkarana', 'concept_jiva', 'concept_karma_traya', 'concept_jivanmukti'],
  '2.4.17': ['concept_antahkarana', 'concept_jiva', 'concept_sadhana_chatushtaya', 'concept_nididhyasana'],
  '2.4.18': ['concept_antahkarana', 'concept_jiva'],
  '2.4.19': ['concept_antahkarana', 'concept_jiva'],
  '2.4.20': ['concept_antahkarana', 'concept_jiva'],
  '2.4.21': ['concept_antahkarana', 'concept_jiva', 'concept_brahman', 'concept_sadhana_chatushtaya', 'concept_nididhyasana'],
  // Adhyaya 3
  '3.1.1': ['concept_karma_traya', 'concept_jiva', 'concept_ishvara'],
  '3.1.2': ['concept_karma_traya', 'concept_jiva'],
  '3.1.3': ['concept_karma_traya', 'concept_jiva'],
  '3.1.4': ['concept_karma_traya', 'concept_jiva'],
  '3.1.5': ['concept_karma_traya', 'concept_jiva'],
  '3.1.6': ['concept_karma_traya', 'concept_jiva'],
  '3.1.7': ['concept_karma_traya', 'concept_jiva', 'concept_atman'],
  '3.1.8': ['concept_karma_traya', 'concept_jiva'],
  '3.1.9': ['concept_karma_traya', 'concept_jiva'],
  '3.1.10': ['concept_karma_traya', 'concept_jiva'],
  '3.1.11': ['concept_karma_traya', 'concept_jiva'],
  '3.1.12': ['concept_karma_traya', 'concept_jiva'],
  '3.1.13': ['concept_karma_traya', 'concept_jiva', 'concept_atman'],
  '3.1.14': ['concept_karma_traya', 'concept_jiva'],
  '3.1.15': ['concept_karma_traya', 'concept_jiva'],
  '3.1.16': ['concept_karma_traya', 'concept_jiva', 'concept_atman', 'concept_jivanmukti'],
  '3.1.17': ['concept_karma_traya', 'concept_jiva'],
  '3.1.18': ['concept_karma_traya', 'concept_jiva'],
  '3.1.19': ['concept_karma_traya', 'concept_jiva'],
  '3.1.20': ['concept_karma_traya', 'concept_jiva'],
  '3.1.21': ['concept_karma_traya', 'concept_jiva'],
  '3.1.22': ['concept_karma_traya', 'concept_jiva'],
  '3.1.23': ['concept_karma_traya', 'concept_jiva'],
  '3.1.24': ['concept_karma_traya', 'concept_jiva'],
  '3.1.25': ['concept_karma_traya', 'concept_jiva'],
  '3.1.26': ['concept_karma_traya', 'concept_jiva'],
  '3.1.27': ['concept_karma_traya', 'concept_jiva'],
  '3.2.1': ['concept_brahman', 'concept_atman', 'concept_avastha_traya', 'concept_turiya', 'concept_jiva'],
  '3.2.2': ['concept_brahman', 'concept_atman', 'concept_ishvara', 'concept_avastha_traya', 'concept_turiya'],
  '3.2.3': ['concept_brahman', 'concept_atman', 'concept_maya', 'concept_avastha_traya', 'concept_turiya'],
  '3.2.4': ['concept_brahman', 'concept_avastha_traya', 'concept_turiya'],
  '3.2.5': ['concept_brahman', 'concept_jiva', 'concept_ishvara', 'concept_maya', 'concept_jivanmukti', 'concept_nididhyasana'],
  '3.2.6': ['concept_brahman', 'concept_jiva'],
  '3.2.7': ['concept_brahman', 'concept_atman', 'concept_avastha_traya', 'concept_turiya'],
  '3.2.8': ['concept_brahman', 'concept_atman', 'concept_avastha_traya', 'concept_turiya'],
  '3.2.9': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_avastha_traya', 'concept_turiya'],
  '3.2.10': ['concept_brahman', 'concept_jiva', 'concept_avastha_traya', 'concept_turiya'],
  '3.2.11': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_avastha_traya', 'concept_turiya', 'concept_karma_traya'],
  '3.2.12': ['concept_brahman', 'concept_atman', 'concept_nididhyasana'],
  '3.2.13': ['concept_brahman'],
  '3.2.14': ['concept_brahman', 'concept_atman', 'concept_nididhyasana'],
  '3.2.15': ['concept_brahman', 'concept_nididhyasana'],
  '3.2.16': ['concept_brahman', 'concept_atman'],
  '3.2.17': ['concept_brahman'],
  '3.2.18': ['concept_brahman', 'concept_atman', 'concept_satkaryavada', 'concept_jivanmukti'],
  '3.2.19': ['concept_brahman', 'concept_atman', 'concept_sadhana_chatushtaya', 'concept_nididhyasana'],
  '3.2.20': ['concept_brahman'],
  '3.2.21': ['concept_brahman', 'concept_atman', 'concept_sadhana_chatushtaya', 'concept_nididhyasana'],
  '3.2.22': ['concept_brahman', 'concept_vivartavada'],
  '3.2.23': ['concept_brahman', 'concept_atman', 'concept_anirvacaniya_khyati'],
  '3.2.24': ['concept_brahman', 'concept_atman', 'concept_sadhana_chatushtaya', 'concept_nididhyasana'],
  '3.2.25': ['concept_brahman', 'concept_atman', 'concept_nididhyasana'],
  '3.2.26': ['concept_brahman', 'concept_atman', 'concept_jiva', 'concept_maya'],
  '3.2.27': ['concept_brahman', 'concept_atman', 'concept_vivartavada'],
  '3.2.28': ['concept_brahman', 'concept_atman'],
  '3.2.29': ['concept_brahman', 'concept_atman', 'concept_maya', 'concept_vivartavada', 'concept_jivanmukti'],
  '3.2.30': ['concept_brahman', 'concept_atman'],
  '3.2.31': ['concept_brahman', 'concept_atman', 'concept_jiva'],
  '3.2.32': ['concept_brahman', 'concept_atman'],
  '3.2.33': ['concept_brahman', 'concept_nididhyasana'],
  '3.2.34': ['concept_brahman', 'concept_atman'],
  '3.2.35': ['concept_brahman', 'concept_atman'],
  '3.2.36': ['concept_brahman', 'concept_atman'],
  '3.2.37': ['concept_brahman'],
  '3.2.38': ['concept_brahman', 'concept_ishvara', 'concept_karma_traya', 'concept_kshanikavada'],
  '3.2.39': ['concept_brahman', 'concept_atman', 'concept_ishvara', 'concept_pramana'],
  '3.2.40': ['concept_brahman', 'concept_ishvara', 'concept_karma_traya', 'concept_kshanikavada'],
  '3.2.41': ['concept_brahman', 'concept_ishvara', 'concept_karma_traya'],
  '3.3.1': ['concept_nididhyasana', 'concept_brahman', 'concept_atman'],
  '3.3.2': ['concept_nididhyasana', 'concept_brahman', 'concept_atman'],
  '3.3.3': ['concept_nididhyasana', 'concept_brahman'],
  '3.3.4': ['concept_nididhyasana', 'concept_brahman'],
  '3.3.5': ['concept_nididhyasana', 'concept_brahman', 'concept_atman'],
  '3.3.6': ['concept_nididhyasana', 'concept_brahman', 'concept_atman', 'concept_ishvara'],
  '3.3.7': ['concept_nididhyasana', 'concept_brahman', 'concept_adhyasa'],
  '3.3.8': ['concept_nididhyasana', 'concept_brahman', 'concept_atman'],
  '3.3.9': ['concept_nididhyasana', 'concept_brahman', 'concept_atman', 'concept_adhyasa'],
  '3.3.10': ['concept_nididhyasana', 'concept_brahman', 'concept_atman'],
  '3.3.11': ['concept_nididhyasana', 'concept_brahman', 'concept_atman'],
  '3.3.12': ['concept_nididhyasana', 'concept_brahman', 'concept_pancha_kosha'],
  '3.3.13': ['concept_nididhyasana', 'concept_brahman', 'concept_atman'],
  '3.3.14': ['concept_nididhyasana', 'concept_brahman', 'concept_jivanmukti'],
  '3.3.15': ['concept_nididhyasana', 'concept_brahman', 'concept_atman', 'concept_pancha_kosha'],
  '3.3.16': ['concept_nididhyasana', 'concept_brahman', 'concept_atman', 'concept_ishvara'],
  '3.3.17': ['concept_nididhyasana', 'concept_brahman', 'concept_atman', 'concept_ishvara'],
  '3.3.18': ['concept_nididhyasana', 'concept_brahman'],
  '3.3.19': ['concept_nididhyasana', 'concept_brahman', 'concept_atman', 'concept_ishvara', 'concept_sadhana_chatushtaya'],
  '3.3.20': ['concept_nididhyasana', 'concept_brahman'],
  '3.3.21': ['concept_nididhyasana', 'concept_brahman'],
  '3.3.22': ['concept_nididhyasana', 'concept_brahman'],
  '3.3.23': ['concept_nididhyasana', 'concept_brahman', 'concept_satkaryavada'],
  '3.3.24': ['concept_nididhyasana', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_samkhya_purusha'],
  '3.3.25': ['concept_nididhyasana', 'concept_brahman'],
  '3.3.26': ['concept_nididhyasana', 'concept_brahman', 'concept_karma_traya'],
  '3.3.27': ['concept_nididhyasana', 'concept_brahman', 'concept_jiva', 'concept_ishvara', 'concept_karma_traya'],
  '3.3.28': ['concept_nididhyasana', 'concept_brahman', 'concept_atman'],
  '3.3.29': ['concept_nididhyasana', 'concept_brahman', 'concept_ishvara'],
  '3.3.30': ['concept_nididhyasana', 'concept_brahman'],
  '3.3.31': ['concept_nididhyasana', 'concept_brahman', 'concept_ishvara', 'concept_sadhana_chatushtaya'],
  '3.3.32': ['concept_nididhyasana', 'concept_brahman', 'concept_karma_traya', 'concept_jivanmukti'],
  '3.3.33': ['concept_nididhyasana', 'concept_brahman', 'concept_atman', 'concept_jiva'],
  '3.3.34': ['concept_nididhyasana', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara'],
  '3.3.35': ['concept_nididhyasana', 'concept_brahman', 'concept_atman', 'concept_sadhana_chatushtaya'],
  '3.3.36': ['concept_nididhyasana', 'concept_brahman', 'concept_atman', 'concept_ishvara'],
  '3.3.37': ['concept_nididhyasana', 'concept_brahman', 'concept_atman'],
  '3.3.38': ['concept_nididhyasana', 'concept_brahman', 'concept_jiva', 'concept_ishvara'],
  '3.3.39': ['concept_nididhyasana', 'concept_brahman'],
  '3.3.40': ['concept_nididhyasana', 'concept_brahman', 'concept_jiva'],
  '3.3.41': ['concept_nididhyasana', 'concept_brahman', 'concept_satkaryavada'],
  '3.3.42': ['concept_nididhyasana', 'concept_brahman', 'concept_ishvara'],
  '3.3.43': ['concept_nididhyasana', 'concept_brahman', 'concept_atman', 'concept_avastha_traya', 'concept_turiya'],
  '3.3.44': ['concept_nididhyasana', 'concept_brahman', 'concept_adhyasa'],
  '3.3.45': ['concept_nididhyasana', 'concept_brahman'],
  '3.3.46': ['concept_nididhyasana', 'concept_brahman'],
  '3.3.47': ['concept_nididhyasana', 'concept_brahman', 'concept_avastha_traya', 'concept_turiya'],
  '3.3.48': ['concept_nididhyasana', 'concept_brahman'],
  '3.3.49': ['concept_nididhyasana', 'concept_brahman'],
  '3.3.50': ['concept_nididhyasana', 'concept_brahman', 'concept_atman'],
  '3.3.51': ['concept_nididhyasana', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_jivanmukti'],
  '3.3.52': ['concept_nididhyasana', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_pramana', 'concept_avastha_traya', 'concept_turiya', 'concept_samkhya_purusha'],
  '3.3.53': ['concept_nididhyasana', 'concept_brahman'],
  '3.3.54': ['concept_nididhyasana', 'concept_brahman'],
  '3.3.55': ['concept_nididhyasana', 'concept_brahman', 'concept_atman'],
  '3.3.56': ['concept_nididhyasana', 'concept_brahman', 'concept_atman', 'concept_ishvara'],
  '3.3.57': ['concept_nididhyasana', 'concept_brahman', 'concept_atman', 'concept_ishvara', 'concept_pramana', 'concept_karma_traya'],
  '3.3.58': ['concept_nididhyasana', 'concept_brahman', 'concept_pramana', 'concept_karma_traya'],
  '3.3.59': ['concept_nididhyasana', 'concept_brahman'],
  '3.3.60': ['concept_nididhyasana', 'concept_brahman'],
  '3.3.61': ['concept_nididhyasana', 'concept_brahman'],
  '3.3.62': ['concept_nididhyasana', 'concept_brahman'],
  '3.3.63': ['concept_nididhyasana', 'concept_brahman', 'concept_satkaryavada'],
  '3.3.64': ['concept_nididhyasana', 'concept_brahman'],
  '3.4.1': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_brahman', 'concept_atman', 'concept_jivanmukti'],
  '3.4.2': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_atman'],
  '3.4.3': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya'],
  '3.4.4': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti'],
  '3.4.5': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_jiva', 'concept_jivanmukti'],
  '3.4.6': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_brahman'],
  '3.4.7': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya'],
  '3.4.8': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_atman', 'concept_jiva', 'concept_ishvara'],
  '3.4.9': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_atman'],
  '3.4.10': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_atman'],
  '3.4.11': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_jiva'],
  '3.4.12': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_atman', 'concept_jivanmukti'],
  '3.4.13': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_atman', 'concept_jivanmukti'],
  '3.4.14': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_atman'],
  '3.4.15': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_atman'],
  '3.4.16': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_atman'],
  '3.4.17': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_brahman', 'concept_atman'],
  '3.4.18': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_brahman', 'concept_atman', 'concept_ishvara'],
  '3.4.19': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_atman'],
  '3.4.20': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_brahman'],
  '3.4.21': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya'],
  '3.4.22': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya'],
  '3.4.23': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya'],
  '3.4.24': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_atman'],
  '3.4.25': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti'],
  '3.4.26': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_atman'],
  '3.4.27': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_atman'],
  '3.4.28': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya'],
  '3.4.29': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya'],
  '3.4.30': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya'],
  '3.4.31': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya'],
  '3.4.32': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti'],
  '3.4.33': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya'],
  '3.4.34': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_atman'],
  '3.4.35': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_atman'],
  '3.4.36': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_brahman'],
  '3.4.37': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya'],
  '3.4.38': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya'],
  '3.4.39': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya'],
  '3.4.40': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya'],
  '3.4.41': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_atman', 'concept_pramana'],
  '3.4.42': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya'],
  '3.4.43': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya'],
  '3.4.44': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_atman'],
  '3.4.45': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya'],
  '3.4.46': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya'],
  '3.4.47': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya'],
  '3.4.48': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_brahman'],
  '3.4.49': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya'],
  '3.4.50': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya'],
  '3.4.51': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_atman'],
  '3.4.52': ['concept_sadhana_chatushtaya', 'concept_nididhyasana', 'concept_karma_traya', 'concept_brahman', 'concept_jiva', 'concept_jivanmukti'],
  // Adhyaya 4
  '4.1.1': ['concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_sadhana_chatushtaya'],
  '4.1.2': ['concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti', 'concept_brahman', 'concept_sadhana_chatushtaya'],
  '4.1.3': ['concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara', 'concept_pramana'],
  '4.1.4': ['concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti', 'concept_brahman', 'concept_atman'],
  '4.1.5': ['concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti', 'concept_brahman', 'concept_adhyasa'],
  '4.1.6': ['concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti', 'concept_satkaryavada', 'concept_adhyasa'],
  '4.1.7': ['concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti', 'concept_avastha_traya', 'concept_turiya'],
  '4.1.8': ['concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti'],
  '4.1.9': ['concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti'],
  '4.1.10': ['concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti'],
  '4.1.11': ['concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti'],
  '4.1.12': ['concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti', 'concept_atman'],
  '4.1.13': ['concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti', 'concept_brahman'],
  '4.1.14': ['concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti', 'concept_maya'],
  '4.1.15': ['concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti', 'concept_maya'],
  '4.1.16': ['concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti'],
  '4.1.17': ['concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti'],
  '4.1.18': ['concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti'],
  '4.1.19': ['concept_nididhyasana', 'concept_karma_traya', 'concept_jivanmukti', 'concept_brahman', 'concept_maya'],
  '4.2.1': ['concept_jiva', 'concept_krama_mukti', 'concept_antahkarana', 'concept_atman', 'concept_abhinna_nimitta_upadana'],
  '4.2.2': ['concept_jiva', 'concept_krama_mukti', 'concept_antahkarana'],
  '4.2.3': ['concept_jiva', 'concept_krama_mukti', 'concept_antahkarana', 'concept_atman', 'concept_avastha_traya', 'concept_turiya'],
  '4.2.4': ['concept_jiva', 'concept_krama_mukti', 'concept_antahkarana', 'concept_atman', 'concept_maya', 'concept_karma_traya'],
  '4.2.5': ['concept_jiva', 'concept_krama_mukti', 'concept_antahkarana'],
  '4.2.6': ['concept_jiva', 'concept_krama_mukti', 'concept_antahkarana', 'concept_atman', 'concept_karma_traya'],
  '4.2.7': ['concept_jiva', 'concept_krama_mukti', 'concept_antahkarana', 'concept_brahman', 'concept_maya', 'concept_karma_traya', 'concept_nididhyasana'],
  '4.2.8': ['concept_jiva', 'concept_krama_mukti', 'concept_antahkarana', 'concept_brahman', 'concept_maya', 'concept_abhinna_nimitta_upadana', 'concept_avastha_traya', 'concept_turiya', 'concept_karma_traya'],
  '4.2.9': ['concept_jiva', 'concept_krama_mukti', 'concept_antahkarana'],
  '4.2.10': ['concept_jiva', 'concept_krama_mukti', 'concept_antahkarana'],
  '4.2.11': ['concept_jiva', 'concept_krama_mukti', 'concept_antahkarana', 'concept_pramana', 'concept_jivanmukti'],
  '4.2.12': ['concept_jiva', 'concept_krama_mukti', 'concept_antahkarana', 'concept_brahman'],
  '4.2.13': ['concept_jiva', 'concept_krama_mukti', 'concept_antahkarana', 'concept_karma_traya'],
  '4.2.14': ['concept_jiva', 'concept_krama_mukti', 'concept_antahkarana', 'concept_atman', 'concept_ishvara', 'concept_jivanmukti'],
  '4.2.15': ['concept_jiva', 'concept_krama_mukti', 'concept_antahkarana', 'concept_brahman', 'concept_atman'],
  '4.2.16': ['concept_jiva', 'concept_krama_mukti', 'concept_antahkarana', 'concept_maya', 'concept_paramanuvada'],
  '4.2.17': ['concept_jiva', 'concept_krama_mukti', 'concept_antahkarana', 'concept_brahman', 'concept_nididhyasana'],
  '4.2.18': ['concept_jiva', 'concept_krama_mukti', 'concept_antahkarana', 'concept_nididhyasana'],
  '4.2.19': ['concept_jiva', 'concept_krama_mukti', 'concept_antahkarana'],
  '4.2.20': ['concept_jiva', 'concept_krama_mukti', 'concept_antahkarana'],
  '4.2.21': ['concept_jiva', 'concept_krama_mukti', 'concept_antahkarana', 'concept_ishvara', 'concept_nididhyasana', 'concept_pradhana'],
  '4.3.1': ['concept_krama_mukti', 'concept_ishvara', 'concept_brahman', 'concept_jiva', 'concept_nididhyasana'],
  '4.3.2': ['concept_krama_mukti', 'concept_ishvara', 'concept_atman', 'concept_jiva'],
  '4.3.3': ['concept_krama_mukti', 'concept_ishvara'],
  '4.3.4': ['concept_krama_mukti', 'concept_ishvara', 'concept_brahman', 'concept_jiva'],
  '4.3.5': ['concept_krama_mukti', 'concept_ishvara', 'concept_atman'],
  '4.3.6': ['concept_krama_mukti', 'concept_ishvara', 'concept_brahman', 'concept_jiva'],
  '4.3.7': ['concept_krama_mukti', 'concept_ishvara', 'concept_brahman', 'concept_atman', 'concept_jiva'],
  '4.3.8': ['concept_krama_mukti', 'concept_ishvara', 'concept_brahman'],
  '4.3.9': ['concept_krama_mukti', 'concept_ishvara', 'concept_brahman', 'concept_atman', 'concept_nididhyasana'],
  '4.3.10': ['concept_krama_mukti', 'concept_ishvara', 'concept_brahman', 'concept_jiva'],
  '4.3.11': ['concept_krama_mukti', 'concept_ishvara', 'concept_brahman', 'concept_nididhyasana'],
  '4.3.12': ['concept_krama_mukti', 'concept_ishvara', 'concept_brahman', 'concept_vivartavada'],
  '4.3.13': ['concept_krama_mukti', 'concept_ishvara', 'concept_brahman'],
  '4.3.14': ['concept_krama_mukti', 'concept_ishvara', 'concept_brahman', 'concept_satkaryavada', 'concept_nididhyasana', 'concept_paramanuvada'],
  '4.3.15': ['concept_krama_mukti', 'concept_ishvara', 'concept_brahman', 'concept_nididhyasana'],
  '4.3.16': ['concept_krama_mukti', 'concept_ishvara', 'concept_brahman', 'concept_nididhyasana'],
  '4.4.1': ['concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_jiva'],
  '4.4.2': ['concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_maya', 'concept_avastha_traya', 'concept_turiya'],
  '4.4.3': ['concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara', 'concept_nididhyasana'],
  '4.4.4': ['concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_jiva'],
  '4.4.5': ['concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_jiva'],
  '4.4.6': ['concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_jiva'],
  '4.4.7': ['concept_jivanmukti', 'concept_brahman', 'concept_atman'],
  '4.4.8': ['concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_satta_traya'],
  '4.4.9': ['concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara'],
  '4.4.10': ['concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_krama_mukti'],
  '4.4.11': ['concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_nididhyasana'],
  '4.4.12': ['concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_jiva'],
  '4.4.13': ['concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_avastha_traya', 'concept_turiya'],
  '4.4.14': ['concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_avastha_traya', 'concept_turiya'],
  '4.4.15': ['concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_jiva'],
  '4.4.16': ['concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_avastha_traya', 'concept_turiya'],
  '4.4.17': ['concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara', 'concept_paramanuvada'],
  '4.4.18': ['concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara'],
  '4.4.19': ['concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_ishvara'],
  '4.4.20': ['concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_pramana'],
  '4.4.21': ['concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_ishvara'],
  '4.4.22': ['concept_jivanmukti', 'concept_brahman', 'concept_atman', 'concept_jiva', 'concept_ishvara', 'concept_sadhana_chatushtaya', 'concept_krama_mukti', 'concept_nididhyasana'],
};
