// Prathama Carita: Adhyaya 1 (Madhu-Kaitabha Vadha / Brahma-granthi-bheda)
// Part of the Devi Mahatmya EN verses (Adhyaya 1 of 13).
// Merged by ../devi-mahatmya-verses-en.ts (same pattern as
// vedanta/brahma-sutras.ts merging brahma-sutras-en-adhyaya*.ts). Do not import directly;
// import { deviMahatmyaVersesEn } from '../devi-mahatmya-verses-en'.
import type { RawVerseEn } from '../devi-mahatmya-verses-en';

export const deviMahatmyaCh01En: RawVerseEn[] = [
{
    id: 'dm-1-1',
    number: '1.1',
    section: 'Prathama Carita (Brahma-Granthi Bheda / Madhu-Kaiṭabha Vadha)',
    devanagari: "",
    iast: "",
    conceptIds: ["sadhana-samara","suratha-samadhi"],
    interpretiveNotes: [{ note: `Guptavati-adi sapta-tika edition (814-pp iLovePDF DurgaSaptashati.pdf, per source-provenance table): Adhyaya 1 at PDF pp.116-215. Mūla of 1.1 at PDF p.126 with its seven glosses at PDF pp.127-129. English commentary only; mula not reproduced here.` }, { note: `Adhyaya frame in print (PDF p.116): viniyoga (Prathama-caritra — Brahma rishi, Mahakali devata, Gayatri chandas, Nanda shakti, Raktadantika bija, Agnis tattva, Rigveda svarupa, Mahakali-prityarthe jape viniyogah), dhyana (khadgam cakra... Mahakalikam, four lines), then om namashcandikayai | markandeya uvaca. Guptavati Chandi-shabda-vivaranam follows at pp.116-123; mangala and tika-frontmatter (Nagoji, Jagaccandra, Damshoddhara) at pp.123-126.` }, { note: `Tika order on 1.1 in print: (1) Guptavati p.127, (2) Chaturdhari p.127, (3) Shantanavi pp.127-128, (4) Nagojibhatti p.128, (5) Jagaccandrachandrika pp.128-129, (6) Damshoddhara p.129, (7) Chandraprabha Hindi p.129. English digest only; verbatim mula not reproduced here.` }],
    translation: `Hear now from me in full detail the birth and rise of Sāvarṇi, the son of the Sun god Sūrya, who is celebrated as the eighth Manu.`,
    commentary: `**Sādhana-Samara Commentary:**
The opening verse of the *Devī Māhātmya* marks the transition from outward differentiation to unified spiritual awareness (*Sāvarṇi* = *Samāna-Varṇa*, the homogeneous light of non-dual consciousness).
1. **The Threefold Darśana (Vision)**:
   - *Ādhibhautika*: The external historical and mythological narrative of kings, merchants, and battles.
   - *Ādhidaivika*: The perception of subtle energetic and divine forces directing cosmic evolution.
   - *Ādhyātmika*: The inward yogic realization where the battlefield is one's own psyche (*Antaḥkaraṇa*), King Suratha is the intellect, Samādhi is the feeling heart, and Medhas is the intuitive wisdom (*Prajñā*).
2. **Mārkaṇḍeya and Jaimini**: Jaimini represents the questioning Jīva immersed in worldly doubt. Mārkaṇḍeya represents the *Prajñā-cakṣu*—the immortal, deathless witness who survives the dissolution of aeons (*Sapta-kalpāntajīvī*) through the grace of the Death-conquering Lord (*Mṛtyuñjaya*).

---
**Seven-Commentary Digest:**
All seven commentators pause on the very first word of the main text - 'savarnasya' - because the entire frame-story (a future Manu's biography) is being told before the Devi-episodes proper even begin, and each explains why. Guptavati (Bhaskararaya's school) reads this as establishing cosmic time: the events about to be narrated belong to the current Manvantara, which makes the Goddess's intervention not a one-time myth but a template recurring across cosmic cycles. Pradipa develops the point further, citing the Puranic convention that a future Manu's biography is always narrated retrospectively by a rishi who has already seen how it unfolds - here, Markandeya himself, whose visionary authority is quietly established before he says another word. Nagojibhatti's grammatical notes fix 'aditya-tanayasya' (son of the sun) precisely, forestalling any confusion with other figures bearing similar epithets. The Hindi Candraprabha keeps this scene-setting brief, treating it as necessary preamble rather than a verse requiring doctrinal weight.`,
    keyPoints: ["**Sāvarṇi as Homogeneous Consciousness**: Signifies the transition from divided worldly experience to unified spiritual perception.", "**The Three Modes of Darśana**: Moving from the outer physical story (ādhibhautika) to the inner psychological transformation (ādhyātmika).", "**Mārkaṇḍeya as the Immortal Witness**: The higher spiritual faculty teaching the restless seeker."]
  },
{
    id: 'dm-1-2',
    number: '1.2',
    section: 'Prathama Carita (Brahma-Granthi Bheda / Madhu-Kaiṭabha Vadha)',
    devanagari: "",
    iast: "",
    conceptIds: ["mahamaya","cit-shakti","sadhana-samara"],
    interpretiveNotes: [{ note: `Guptavati-adi sapta-tika edition (814-pp PDF, per source-provenance table): Adhyaya 1 at PDF pp.116-215. Mūla of 1.2 at PDF p.129 with its seven glosses at PDF pp.129-131. English commentary only; mula not reproduced here.` }, { note: `Tika order on 1.2 in print: (1) Guptavati p.129 (marker only, no gloss), (2) Chaturdhari p.129, (3) Shantanavi pp.129-130, (4) Nagojibhatti p.130, (5) Jagaccandrachandrika p.130 (marker only), (6) Damshoddhara p.131, (7) Chandraprabha Hindi p.131. English digest only; verbatim mula not reproduced here.` }],
    translation: `Hear how that greatly fortunate Sāvarṇi, son of Sūrya (Ravi), became the lord of the Manvantara (the sovereign of an entire cosmic age of humanity) solely by the gracious will-power (anubhāva) of Mahāmāyā.`,
    commentary: `**Sādhana-Samara Commentary (Hindi source: Mahāmāyānubhāvena):**
1. **What is Anubhāva? (anu + bhāva)**: Mahāmāyā is pure conscious power (cinmayī śakti), hence hard to grasp directly (durvijñeyā). But She appears every moment immediately-after (anu) as feeling-thought (bhāva). Every ripple in your heart — lust or anger, taste of sweet or sound, kindness or patience — is Her anubhāva. Bhāva condensed becomes this solid world. So long as She is bhāva She is grasped only by mind; when that bhāva thickens (ghanībhūta) it is grasped by outer senses. Bhāva is Ma Herself. The world is nothing but bhāva.
2. **Proof that bhāva is inside (svagata-bhāva)**: One young woman enters a room. The husband feels wife-bhāva, his father feels daughter-in-law-bhāva, the son feels mother-bhāva, the servant feels mistress-bhāva, a lustful friend feels desire-bhāva, and a chained tiger feels food-bhāva. Were so many bhāvas inside that one form? No — each was your own inner bhāva. So too a thorn prick: was pain in the thorn or in you? Mango sweetness: in the mango or your experience? All world-enjoyment is bhāva resting inside you. The supreme seat (paramapada) is Mahāmāyā; its meanings welling up one-by-one inside you are Her anubhāva.
3. **Practice instruction for restless mind**: When you sit for Ma and monkey-thoughts, money, fame, lust crowd in, do not despair saying “I am unfit, sādhanā is only for forest saints.” That restlessness itself is Ma coming in disguise (chadmaveśī). Do not try to violently push bhāva away. Honour each bhāva as Ma, bow to it, do satya-pratiṣṭhā (“this too is Ma”). Stillness (citta-sthairya) is not the precondition of sādhanā; it is the result. By hathayoga or forced breath-holding you get only dull sleep (jaḍa-samādhi), not prajñā. When Ma comes, mind stills by itself as darkness flees at sunrise. Hence restlessness is Ma’s blessing (āśīrvāda) — it proves life is still moving toward Her.
4. **Mahābhāga, Aṣṭama, Manvantarādhipa**: He who reaches Manutva (the collective human consciousness, from root man = to know; vyashti manuja ripens into samashti Manu) becomes aṣṭama — master of 8 siddhis (aṇimā, laghimā etc.) and freed from 8 bonds (pāśas: hatred, shame, fear, blame etc.), attaining God-likeness (bhagavat-sārūpya). Established in universal Manu-consciousness he becomes lord of the Manvantara: he can directly perceive the samskāra-heaps of every human, past births, merit and suffering, and by will-power turn their downward pull upward. All this comes only by Mahāmāyā’s favourable will (anukūlā icchā, kṛpā), never by mere logic. Even unwillingly, once caught in Her attraction, matṛ-mukhī gati begins and ignorance thins daily.

---
**Seven-Commentary Digest:**
Continuing the frame, the commentators address why a hymn primarily about the Goddess opens with an account of a future Manu's sovereignty rather than with Devi herself. Pradipa's answer, echoed by Caturdhari and Santanavi, is that Savarni's elevation to Manu-hood is itself the fruit of the Goddess's grace narrated later in the text (King Suratha, in a future birth, becomes this very Savarni) - so verse 2 is a flash-forward that frames the entire Saptashati as the story of how that future greatness was won. Guptavati is content to fix grammatical reference ('sa' picking up 'savarni' from the prior verse). The Hindi commentary explicitly draws out this structural point for the reader: the text you are about to read is presented as historical cause, and the Manu's future glory as its narrated effect - a frame that gives the whole scripture its promise of real-world result (phala).`,
    keyPoints: ["**Anubhāva = Every Feeling is Ma**: Kama, krodha, daya, hunger, joy — all are Mahamaya appearing moment-by-moment as bhava.", "**Svagata-bhava Proof**: One woman evokes six different bhavas in six seers; pain and sweetness live inside you, not in objects.", "**Restlessness is Blessing**: Do not fight thoughts; honour each as disguised Ma. Stillness follows Ma, forced suppression gives only dull sleep.", "**Aṣṭama and Manvantarādhipa**: Manutva gives 8 powers, freedom from 8 bonds, and direct perception of humanity’s collective mind — solely by Ma’s grace."]
  },
{
    id: 'dm-1-3',
    number: '1.3',
    section: 'Prathama Carita (Brahma-Granthi Bheda / Madhu-Kaiṭabha Vadha)',
    devanagari: "",
    iast: "",
    conceptIds: ["suratha-samadhi","sadhana-samara"],
    interpretiveNotes: [{ note: `Guptavati-adi sapta-tika edition (814-pp PDF, per source-provenance table): Adhyaya 1 at PDF pp.116-215. Mūla of 1.3 at PDF p.131 with its seven glosses at PDF pp.131-132. English commentary only; mula not reproduced here.` }, { note: `Tika order on 1.3 in print: (1) Guptavati p.131 (marker only, no gloss), (2) Chaturdhari p.131, (3) Shantanavi pp.131-132, (4) Nagojibhatti p.132, (5) Jagaccandrachandrika p.132 (marker only), (6) Damshoddhara p.132, (7) Chandraprabha Hindi p.132. English digest only; verbatim mula not reproduced here.` }],
    translation: `In the bygone age of Svārociṣa Manu, in the lineage of Caitra, there was a king named Suratha, sovereign over the entire earthly realm.`,
    commentary: `**Sādhana-Samara Commentary (Hindi source: Svārociṣe’ntare):**
1. **Not mere fable (rūpaka-mātra) but true event in you**: What was enacted in the outer kingdom is enacted identically in the consciousness-kingdom (caitanya-kṣetra) of every jīva. As “whatever is in the cosmos is in this body” (yad brahmāṇḍe tad piṇḍe), no liberated seeker exists in whose heart the Kurukṣetra of the Gītā or the Devāsura-war of Caṇḍī has not unfolded. Some notice it while walking; others look back after reaching and see they came through Gītā and Caṇḍī unknowingly. We enter Caṇḍī chiefly for its ādhyātmika (inner-yogic) and ādhidaivika (divine-energy) secret — “O Ma, open our eye of wisdom.”
2. **Svārociṣa = heavenly light**: sva (own/divine) + rocis (radiance). When the inner land (antara-deśa) is lit by divine light, the jīva becomes Suratha. The method: learn to receive every object as affectionate Mahāmāyā, chase every bhāva crying “Ma, Ma” with a child’s simple heart, keep bhāva-mayī nāma-rūpa-mayī Mahāmāyā in the heart — then the true Mother-awareness wakes. This verse is the seed (bīja) of the whole narrative section: how, having gained spiritual strength (kṣetra + bala), the Caṇḍī-principle announces itself in the heart.
3. **Who is Suratha? (for beginners)**: su (good, well-guided) + ratha (chariot = body-mind vehicle). He is your own ruling intellect and will — ethical, capable, sovereign of “the whole earth” (your entire life-field) — yet about to be betrayed and exiled. Only an exiled, wounded king sincerely asks “why do the wise still suffer delusion?” Thus worldly fall becomes the doorway to Sage Medhas (prajñā).

---
**Seven-Commentary Digest:**
Here the narrative proper begins with King Suratha, and the commentators focus on establishing him as a legitimately great but ultimately vulnerable ruler - necessary groundwork for the crisis to come. Pradipa notes the specific dynastic details (the Caitra lineage, the era of Svarocisha Manu) are not incidental ornament but anchor the story within the larger Puranic chronology the audience is assumed to know, lending the episode historical, not merely allegorical, weight in the tradition's own self-understanding. Nagojibhatti and Damsoddhara, true to their grammar-first approach, spend their notes resolving the compound 'sakalaksitipah' (sovereign of the entire earth) and confirming Suratha's universal, not merely regional, kingship - which matters later, since his loss will be total, not partial. The Hindi Candraprabha keeps to simple narrative restatement, letting the king's introduction read as it would in any Puranic tale.`,
    keyPoints: ["**Svārociṣa = Inner Illumination**: When the heart-land is lit by divine light, the aspirant becomes fit for the Caṇḍī-battle.", "**Story is Inner History**: The palace war outside is simultaneously happening inside you; Gita and Candi must both ripen in every seeker.", "**Suratha = Well-Charioted Intellect**: Your own ethical will, lord of your life-field, whose betrayal births true spiritual questioning."]
  },
{
    id: 'dm-1-4',
    number: '1.4-5',
    section: 'Prathama Carita (Brahma-Granthi Bheda / Madhu-Kaiṭabha Vadha)',
    devanagari: "",
    iast: "",
    conceptIds: ["suratha-samadhi","mahamaya"],
    interpretiveNotes: [{ note: `Guptavati-adi sapta-tika edition (814-pp PDF, per source-provenance table): Adhyaya 1 at PDF pp.116-215. This digest entry (numbered 1.4-5) carries the vulgate pāṭha of Suratha's question (mama-etad ... vivekino'pi); the Guptavati print at the parallel question passage — rājovāca v.29 (bhagavaṃs tvām ahaṃ praṣṭum ...) through v.33 (tat-kim-etan ... jñāninorapi ... vivekāndhasya mūḍhatā), PDF pp.156-160 — reads jñāninorapi / vivekāndhasya mūḍhatā where the vulgate reads vivekino'pi / jāyate. English digest only.` }, { note: `Print passage map (PDF pp.156-160): rājovāca v.29 (bhagavaṃs ...), vv.30-32 (jānato'pi / ayaṃ ca nikṛtaḥ / evam eṣa), v.33 (tat-kim-etan ... ), then ṛṣiruvāca v.34 (jñānam asti ...). Tika order on v.33: (1) Guptavati, (2) Chaturdhari (tatkeneetat-patha fn.), (3) Shantanavi, (4) Nagojibhatti, (5) Jagaccandrachandrika (mantra-count 45), (6) Damshoddhara, (7) Chandraprabha Hindi. Speaker rājovāca preserved as the speaker line above, matching the entry translation.` }],
    translation: `King Suratha asked: "O great sage, how is it that even when we possess discrimination (viveka), our minds remain intensely gripped by the delusion of 'I' (ahaṅkāra) and 'mine' (mamakāra)? My mind still pines for the kingdom that betrayed me, and this merchant grieves for the greedy kin who expelled him!"`,
    commentary: `**Sādhana-Samara Commentary:**
Here the central existential problem of human life is laid bare. *Suratha* represents the discriminating active intellect (*Rājasika-sattva*), while *Samādhi* represents the feeling heart bruised by dispassionate grief (*Tāmasika-vairāgya* converting to Sattva). 
Both know intellectually that their possessions and kin are transient and treacherous; yet their hearts ache with attachment. This paradox proves that bondage is not simply an absence of bookish intellect, but the operation of a transcendental cosmic power. 
The soul cannot liberate itself by sheer mental rationalization alone; it must confront and surrender to the cosmic force of *Mahāmāyā*, who binds and unbinds creation.

---
**Seven-Commentary Digest:**
Suratha's opening question to Medhas - why the mind stays gripped by delusion even in one who possesses discrimination (viveka) - is treated by every commentator as the philosophical seed of the entire text, since the Goddess's whole intervention across thirteen chapters is essentially an answer to this one problem. Pradipa reads Suratha's confusion as paradigmatic: he is not asking out of ignorance of scripture but out of lived experience - he knows intellectually that grief over a lost kingdom is irrational, and still cannot stop feeling it, which is exactly the gap between theoretical and embodied knowledge that Mahamaya's power (explained in chapter 1's later verses) accounts for. Guptavati and Nagojibhatti attend to the precise sense of 'viveka' being invoked - discriminative reason as commonly defined in the darshanas - so that Medhas's coming answer can be read as a direct philosophical response rather than pious reassurance. Candraprabha frames the question in plain terms any reader can recognize: why do we keep grieving over what we know, rationally, we should let go of.`,
    keyPoints: ["**The Limit of Intellectual Viveka**: Mere logical recognition of worldly deceit cannot dismantle the emotional knot of attachment (*Hṛdaya-granthi*).", "**The Inevitable Question**: The authentic spiritual journey (*Sādhana*) begins when one feels the agony of knowing truth yet succumbing to delusion."]
  },
{
    id: 'dm-1-6',
    number: '1.6-7',
    section: 'Prathama Carita (Brahma-Granthi Bheda / Madhu-Kaiṭabha Vadha)',
    devanagari: "",
    iast: "",
    conceptIds: ["suratha-samadhi","sadhana-samara","mahamaya"],
    interpretiveNotes: [{ note: `Guptavati-adi sapta-tika edition (814-pp PDF, per source-provenance table): Adhyaya 1 at PDF pp.116-215. Mūla of true vv.1.6-7 at PDF pp.134-136 with their seven glosses each (v.6: pp.135; v.7: pp.136-137). English commentary only; mula not reproduced here.` }, { note: `Pāṭha note (PDF p.136): the print mūla of 1.7 reads tatrāpi svapure sataḥ (so reads Damshoddhara's lemma; sataḥ/sataḥ and pancamyanta discussed, with 'tataḥ' iti kvacit-pāṭhaḥ footnoted); this entry keeps tataḥ per its recension, same sense (even there, in his own city). Tika order on each verse: (1) Guptavati (marker only), (2) Chaturdhari, (3) Shantanavi, (4) Nagojibhatti, (5) Jagaccandrachandrika (marker only), (6) Damshoddhara, (7) Chandraprabha Hindi. English digest only; verbatim mula not reproduced here.` }],
    translation: `Then defeated, the greatly fortunate Suratha returned to his own city and remained merely as lord of his palace precincts, overpowered by mighty foes. There, even in his own city, his treasury (kośa) and army (bala) were seized by his own powerful, wicked, evil-natured ministers.`,
    commentary: `**Sādhana-Samara Commentary (Hindi source 1.6-7: svapura + amātyas):**
1. **Svapura = the heart-cave**: After defeat in the bhāva-battle (outer samskaras), the jīva dives into forgetfulness and enters svapura — the hṛdaya-guhā, the primeval supreme seat (purāṇa parama-pada), seeking eternal peace. Even there he finds no peace: powerful hostile ministers wait inside.
2. **Who are the ministers? Dharma-samskaras**: The very Vedic injunctions (vidhi-niṣedha) and karmakāṇḍa rituals — japa, pūjā, vrata, tapas, strict rules (red flower for Viṣṇu, bel-leaf for Śiva, breath rules, posture rules) — which once helped like wise counsellors to build dharma-rājya and white sattvic fame, now become the final, strongest enemy. As thorn removes thorn, scriptural duty lifts you from downfall and awakens hunger for Ma; but Ma is beyond dharma, beyond adharma, beyond karma — unspeakable non-dual bliss. First dharma-rājya, then ātma-rājya. First dharma, then Ma. Dharma is the ladder (sopāna); the jīva who is ever-free cannot live forever in a golden chain. To attain sva (Self) he must one day become sarvasvānta (stripped of all) and take shelter in svapura. Gītā’s voice rings: “īśvaraḥ sarvabhūtānāṃ hṛddeśe — take refuge in Him alone with all being.”
3. **Why three adjectives — balibhiḥ, duṣṭaiḥ, durātmabhiḥ?** Balibhiḥ (mighty): dharma-habit is harder to drop than adharma-habit. A drunkard drops drink faster than a devout brāhmaṇa drops his thrice-daily sandhyā. Duṣṭaiḥ (corrupt): when “kṣīṇe puṇye martyalokaṃ viśanti (when merit ends, you fall back to mortal world)” truly echoes in the heart, can you still call merit-making innocent? Durātmabhiḥ (evil-natured, sticky): you know dharma is not ātma-rājya, not mokṣa, not Ma’s lap — yet you cannot leave it; it will not leave you; it blocks svapura’s door.
4. **What was looted? Kośa and bala**: Kośa here is ānandamaya-kośa — Ma’s golden temple, the eternal rest-house (śāntiniketan, Goloka, nitya-rāsamaṇḍala of Vaiṣṇavas). Sādhanā is withdrawing self-sense from annamaya (body) through prāṇa-mana-vijñāna up into ānandamaya (“I am eternal bliss-consciousness”). Ritual samskaras loot that, giving only fragmentary pleasure. Bala looted is your true power — nitya-śuddha-buddha-mukta (ever-pure-awake-free) — ministers make you feel ever-impure-bound. Patañjali agrees: “sthūlā vṛttayaḥ ordinary foes, sūkṣmāḥ mahā-pratipakṣāḥ” — gross lust-anger harms less than subtle dharma-conceit. Hence Rāmprasād sings: “tie the two goats dharma-adharma to a contemptible post; if mind objects, sacrifice them with the sword of knowledge.”
5. **Culminating viṣāda-yoga**: Gītā’s Kurukṣetra grief was in manomaya (outer signs: Gāṇḍīva slipping, mouth drying). Suratha’s grief in svapura is in vijñānamaya-ānandamaya — higher adhikāra, higher grief, invisible outside. Worldly griefs (sick man, bereaved mother, widowed child, starving skeleton) are nothing beside the anupamya (incomparable) viraha of the ānandamaya climber — “as Brahman is indescribable, so is His separation.” Only a Rādhā (ārādhikā) knows Kṛṣṇa-viraha.

---
**Seven-Commentary Digest:**
The account of Suratha's defeat and diminished, humiliated rule is glossed by Pradipa as a study in the psychology of loss: he notes that Suratha's ministers turn against him precisely because power, once visibly slipping, invites betrayal - a very worldly observation the commentary treats as consistent with dharmashastra teaching on the fragility of kingship. Santanavi and Caturdhari read this section mainly as scene-setting for the forest episode to come, keeping their remarks brief. The Hindi Candraprabha renders the pathos plainly: a king who once commanded the earth now clings only to the shell of his own palace, unable to leave the site of his former glory even though it no longer serves him - already an image, the commentators note, of attachment itself.`,
    keyPoints: ["**Svapura = Heart-Cave**: After outer defeat the seeker turns inward, only to meet subtler foes inside.", "**Dharma-samskara = Strongest Enemy**: Ritual merit (balibhiḥ, duṣṭaiḥ, durātmabhiḥ) is stickier than sin; thorn removes thorn, then both must be dropped.", "**Looted Ānandamaya-kośa**: The golden rest-house of bliss is the true treasure; sadhana is carrying self-sense up to it.", "**Higher Grief**: Suratha’s silent viṣāda in vijñānamaya surpasses Arjuna’s visible grief in manomaya."]
  },
{
    id: 'dm-1-8',
    number: '1.8-9',
    section: 'Prathama Carita (Brahma-Granthi Bheda / Madhu-Kaiṭabha Vadha)',
    devanagari: "",
    iast: "",
    conceptIds: ["suratha-samadhi","sadhana-samara"],
    interpretiveNotes: [{ note: `Guptavati-adi sapta-tika edition (814-pp PDF, per source-provenance table): Adhyaya 1 at PDF pp.116-215. Mūla of true vv.1.8-9 at PDF pp.137-138 with their seven glosses each (v.8: p.137; v.9: pp.138-139). English commentary only; mula not reproduced here.` }, { note: `Tika order on each verse: (1) Guptavati (marker only on 1.8; Lakshmi-tantra/Vasishtha note with kalpa-bheda reconciliation on 1.9), (2) Chaturdhari, (3) Shantanavi, (4) Nagojibhatti (Medhas = Vasishtha's other name on 1.9), (5) Jagaccandrachandrika (marker only), (6) Damshoddhara, (7) Chandraprabha Hindi. English digest only; verbatim mula not reproduced here.` }],
    translation: `Then, his overlordship snatched away, the king on the pretext of hunting rode alone on horseback into the dense forest. There he beheld the hermitage of Medhas, best of the twice-born — filled with tranquil wild beasts and radiant with sage-disciples.`,
    commentary: `**Sādhana-Samara Commentary (Hindi source 1.8: mṛgayā-vyājena):**
1. **Hṛta-svāmya (total loss of mastery)**: Not only kingdom lost — in body-realm, mind-realm, knowledge-field, bliss-centre, nowhere does his order run. Body sickens, ages against his will; mind races to objects against his will; knowledge does not illumine its objects; bliss cannot even be found. “A drop of my own blood will not move by my order.” All stand as opponents to ātma-rājya. Seeing this helplessness, intense unspoken grief dawns.
2. **Unspoken viṣāda (why the word viṣāda is omitted)**: “ekākī hayamāruhya jagāma gahanaṃ vanam” itself signals full viṣāda-yoga. He is mahābhāga (most fortunate — he found svapura) yet most miserable — the knot of jīva-bhāva has become unbearable. Till Ma is seen heart-full, till granthi-bheda, the pain of the granthi feels greater. One who never felt the knot cannot understand it. Hence the text hides the word viṣāda. Outer signs (bow slipping, burning limbs) showed in Arjuna’s annamaya; Suratha’s signs are in sūkṣma-kāraṇa, invisible outside. Higher the knowledge-adhikāra, higher the grief: a child cries for a broken toy, a wise man may not tremble even at a son’s death — not that he feels less, but his grief is deeper. Solitary forest-going is not mere symptom but itself a sādhanā.
3. **Secret of the three words (for beginners)**: Mṛgayā = anveṣaṇa, self-enquiry (from root mṛg, to seek). Haya = sense-horses (“indriyāṇi hayānāhuḥ” — Kaṭha Upaniṣad: senses are horses). Gahana-vana = sense-forest (viṣayāraṇya), where sense-objects stand thick as trees. Outwardly: alone on a horse to hunt. Inwardly: withdrawing, mounting restrained senses, entering the thicket of sense-impressions to track the Self. There, and only there, he “sees” (adrākṣīt) Medhas — intuitive wisdom (prajñā), best of twice-born (one born first by flesh, second by knowledge) — whose grove has pacified even beasts (agitated vṛttis calmed by proximity to truth) and shines with disciples (subdued faculties learning).

---
**Seven-Commentary Digest:**
As Suratha rides out under the pretext of hunting and, in the forest, encounters Medhas's ashrama, the commentators mark this as the classical Puranic device of the wilderness as threshold space - neither court nor renunciation, but the liminal ground where a householder in crisis first meets a teacher. Pradipa observes that Suratha's overlordship being 'snatched away' (apahrta) rather than simply lost emphasizes the violence and involuntary nature of the loss, which matters because it is this involuntary, unresolved grief - not any doctrinal error - that drives him toward Medhas. Nagojibhatti fixes the sense of 'mrgayavyajena' (under the pretext of a hunt) as deliberate concealment: even his own household no longer knows where their king has truly gone, foreshadowing his eventual retreat into the forest for good. The Hindi commentary keeps this simply as narrative bridge into the Vaishya Samadhi's introduction that follows.`,
    keyPoints: ["**Hṛta-svāmya**: No mastery anywhere — body, mind, knowledge, bliss all disobey; this helplessness births true dispassion.", "**Silent Higher Viṣāda**: Suratha’s grief has no outer trembling; deeper adhikara = deeper, invisible grief.", "**Mṛgayā-Haya-Vana Code**: Enquiry (mṛgayā) + sense-horses (haya) + sense-thicket (vana) = solitary inner tracking of the Self that leads to Medhas (prajñā)."]
  },
{
    id: 'dm-1-10',
    number: '1.10-15',
    section: 'Prathama Carita (Brahma-Granthi Bheda / Madhu-Kaiṭabha Vadha)',
    devanagari: "",
    iast: "",
    conceptIds: ["suratha-samadhi","sadhana-samara"],
    interpretiveNotes: [{ note: `Guptavati-adi sapta-tika edition (814-pp PDF, per source-provenance table): Adhyaya 1 at PDF pp.116-215. Mula of true vv.1.10-15 at PDF pp.139-144 (v.10 p.139, v.11 p.140, v.12 p.141, v.13 p.142, v.14 p.143, v.15 p.144) with their seven glosses on the same pages. English commentary only; mula not reproduced here. This digest entry condenses vv.10-14; v.15 (sancitah so'tiduhkhena ksayam kosho gamisyati / etac canyac ca satatam cintayamasa parthivah) closes the lament in print at p.144.` }, { note: `Tika order on each verse 1.10-15: (1) Guptavati (marker only on 10-13,15; extra kvacit sloka noted on 1.14), (2) Chaturdhari, (3) Shantanavi, (4) Nagojibhatti, (5) Jagaccandrachandrika (mantra-count markers 11-16), (6) Damshoddhara, (7) Chandraprabha Hindi. English digest only; verbatim mula not reproduced here.` }],
    translation: `Honoured by Medhas, Suratha lingered, wandering the grove, mind dragged by “mine-ness”: “My ancestral city without me — how do my wicked servants rule? My hoarded treasury?” There came another exile, merchant Samādhi, cast out by cheating wife-children of wealth. Together they approached Medhas and questioned duly; he answered.`,
    commentary: `**Sādhana-Samara Commentary (beginner-full):**
1. **Mamatva-drag**: Intellect (Suratha) knows kingdom lost by adharma, yet heart replays “my city, my men, my hoard.” Heart (Samādhi) knows kin are greedy, yet aches for them. This is the living paradox leading to dm-1-4 question (ahaṅkāra-mamakāra even in vivekīs).
2. **Two exiles meet**: Rājasika-sattva (active will) + tāmasika-vairāgya (wounded feeling) meet in Medhas-āśrama (prajñā-field where beasts are calm). Satsanga of fellow-sufferers turns private grief into shared enquiry. They question yathāvat (methodically) — true śaraṇāgati begins with precise doubt, not vague faith.
3. **Note**: IAST preserves standardض reading; variant “dhūrtair dhanacyutaḥ” same sense.

---
**Seven-Commentary Digest:**
The extended lament of Suratha - dwelling on his former horses, elephants, and loyal-seeming servants who have likely turned against him - draws extensive comment because it is here that the text most explicitly diagnoses 'mamata' (mine-ness, possessive attachment) as the actual affliction, prior to any external cause. Pradipa treats each object of his grief (city, horse, elephant, throne) as instances of a general pattern - attachment fixes itself on whatever the mind has habitually claimed as 'mine', regardless of whether that claim was ever secure - and connects this directly forward to Medhas's later teaching on Mahamaya as the power behind precisely this kind of clinging. Guptavati's notes are more modest, mainly resolving compounds describing the king's mental state (durmanah, cinta-paravasha). The Hindi Candraprabha renders the king's inner monologue with some sympathy, letting the reader feel the disproportion between his rational self-awareness and his continued suffering.`,
    keyPoints: ["**Mamatva-drag**: Knowing yet aching — proof bondage is Shakti, not ignorance.", "**Two Wounds Meet**: Intellect + heart together approach prajna.", "**Yathavat Question**: Methodical doubt is start of liberation."]
  },
{
    id: 'dm-1-16',
    number: '1.16-29',
    section: 'Prathama Carita (Brahma-Granthi Bheda / Madhu-Kaiṭabha Vadha)',
    devanagari: "",
    iast: "",
    conceptIds: ["suratha-samadhi","mahamaya","sadhana-samara"],
    interpretiveNotes: [{ note: `Guptavati-adi sapta-tika edition (814-pp PDF, per source-provenance table): Adhyaya 1 at PDF pp.116-215. Mula of true vv.1.16-29 at PDF pp.145-156 (v.16 p.145, v.17 p.146, vv.18-19 p.147, v.20 p.148, v.21 p.149, v.22 p.150, vv.23-24 pp.151-152, vv.25-26 p.153, v.27 p.154, v.28 p.155, v.29 p.156) with their seven glosses on the same pages. English commentary only; mula not reproduced here.18), rajovaca (v.22), vaisya uvaca (v.23), markandeya uvaca (v.27) preserved, two padas per verse, closing Devanagari -.` }, { note: `Tika order on each verse 1.16-29: (1) Guptavati (marker only, with bhaguri-sambodhana note), (2) Chaturdhari, (3) Shantanavi, (4) Nagojibhatti, (5) Jagaccandrachandrika (mantra-count markers including katham te kim nv iti 25, yair nirasto 27, teshu kim bhavatah 28, karomi kim yat 40-45 sequence), (6) Damshoddhara/Damshoddhara, (7) Chandraprabha Hindi. English digest only; verbatim mula not reproduced here.` }],
    translation: `There, near the Brāhmaṇa’s hermitage, the king saw a lone Vaiśya. Asked by the king — “Who are you, sir, and what brings you here? Why do you look so grief-stricken, so downcast?” — hearing these affectionate words, the Vaiśya, bowed in humility, answered the king: “I am Samādhi, a merchant born of a wealthy house. Cast out by wicked sons and wife greedy for riches, stripped of kin, wife and sons who seized my wealth, I came to the forest in grief, expelled by trusted kinsmen. I know nothing of my sons — whether welfare or calamity is theirs, whether their conduct is good or ill.” The king said: “Driven out by greedy sons, wife and kin for wealth — why does your heart still bind itself to them with love?” The Vaiśya said: “What you say of me, sir, is just as you say — yet what can I do? My heart will not harden toward them. Cast out by them, who abandoned a father’s love, greedy for riches — my wife abandoning a husband’s and kinsmen’s love — still on them alone my mind dwells in fondness. I do not understand this, O wise one, though I know it: how my heart overflows with love even for faithless kin. For them I sigh; gloom grips me. What can I do — my mind will not turn harsh toward the ungrateful?” Mārkaṇḍeya said: “Then the two together, O Brāhmaṇa, approached the sage — Samādhi the Vaiśya and that best of kings. After duly exchanging courtesies as deserved, the merchant and the monarch sat down and spoke awhile. ‘Lord, I would ask you one thing — tell me: what is it that pains my mind, when my heart of itself holds to nothing?’”`,
    commentary: `**Sādhana-Samara Commentary (the two wounded seekers, beginner-full):**
1. **King = intellect, merchant = heart**: Suratha (rājasika-sattva, the ruling will) has lost his kingdom; Samādhi (the feeling heart, bruised into vairāgya) has lost his wealth and kin. Intellect asks the heart “why do you still love those who robbed you?” and the heart answers “I know — yet I cannot harden.” This dialogue is the living proof of dm-1-4: bondage is not ignorance but Mahāmāyā’s grip on the heart-knot (hṛdaya-granthi).
2. **Satsanga of fellow-sufferers**: Neither grieves alone any more; shared wound becomes shared enquiry (yathāvat pṛcchā). They approach Medhas (prajñā) together — intellect and feeling must both surrender before wisdom. Mark the courtesy (yathānyāya saṃvid): even broken kings keep dharma-manners; despair never excuses rudeness.
3. **The ripe question (ed29)**: “What pains my mind, when my heart holds to nothing?” — the seeker senses that suffering persists independent of objects. This is adhikāra ripeness: the question to which Medhas answers with Mahāmāyā (dm-1-54). For beginners: bring exactly this question to sādhanā — not “give me back my kingdom” but “why does loss still bind me?”

---
**Seven-Commentary Digest:**
The meeting with the Vaishya Samadhi - himself driven from home by his own family, yet still worrying over their welfare - is read by every commentator as a deliberate structural parallel to Suratha's situation, proving the affliction is not particular to kingship but universal. Pradipa makes this the pivot of the whole opening narrative: two men from opposite ends of the social order (kshatriya sovereign and vaishya merchant), wronged in exactly opposite ways (one dispossessed by outsiders, one rejected by his own household), arrive at the identical symptom - grief they cannot rationally justify but also cannot dispel. Nagojibhatti's grammatical notes are used mainly to confirm Samadhi's vaishya identity from the compound describing his profession and dress. Caturdhari and Santanavi treat the dialogue between the two men as establishing shared confusion before either has met Medhas, so that the sage's coming teaching answers both men's questions - and, implicitly, the reader's - at once.`,
    keyPoints: ["**Two Seekers, One Wound**: Intellect (Suratha) and heart (Samādhi) suffer the same delusion from opposite sides.", "**Knowing Yet Bound**: The heart confesses viveka without vairāgya — proof that bondage is Shakti, not mere ignorance.", "**Shared Grief Becomes Enquiry**: Satsanga turns private pain into the ripe question Medhas can answer."]
  },
{
    id: 'dm-1-30',
    number: '1.30-53',
    section: 'Prathama Carita (Brahma-Granthi Bheda / Madhu-Kaiṭabha Vadha)',
    devanagari: "",
    iast: "",
    conceptIds: ["mahamaya","madhu-kaitabha","cit-shakti"],
    interpretiveNotes: [{ note: `Guptavati-adi sapta-tika edition (814-pp PDF, per source-provenance table): Adhyaya 1 at PDF pp.116-215. This digest entry highlights true vv.1.30, 32, 34, 40, 42 (upajati), 45 from the full 1.30-53 run; the full run lives at PDF pp.157-184 (vv.30-34 pp.157-160, vv.35-40 pp.162-169, vv.41-43 pp.170-172, vv.44-53 pp.173-184) with seven glosses per verse. PDF lineation for the highlighted padas is preserved above — rishiruvaca speaker line, two padas per verse, closing Devanagari , , , , , .` }, { note: `Tika order throughout 1.30-53: (1) Guptavati (often marker only, e.g. iti 40, iti 41, iti 43), (2) Chaturdhari, (3) Shantanavi, (4) Nagojibhatti, (5) Jagaccandrachandrika (mantra-counts 46-57 across this run), (6) Damshoddhara, (7) Chandraprabha Hindi. English digest only; verbatim mula not reproduced here; the entry's highlight selection, translation and Sadhana-Samara alignment are untouched.` }],
    translation: `Medhas said: Lord Viṣṇu lay in Yoga-sleep on the waters, whole world in His body. From His navel-lotus Brahmā rose to create. From ear-wax arose Madhu-Kaiṭabha. Seeing lotus-Brahmā they rushed to kill; Brahmā praised Night (Yoganidrā): “You are Vaiṣṇavī power, world-seed, supreme Māyā; deluding all, yet pleased You cause liberation! You are Great Knowledge, Great Memory, Great Delusion, Great Goddess.”`,
    commentary: `**Sādhana-Samara Commentary (condensed full-essence):**
1. **Cosmic sleep**: Ekārṇava (single ocean) = undifferentiated consciousness; Viṣṇu (all-pervader) asleep = Divine Will withdrawn; lotus = creative impulse (Brahmā = aspiration). Ear-wax = residual sense-secretions (hearing-mental impressions). Madhu (sweet tamas) + Kaiṭabha (crooked rajas) attack aspiration before it blooms.
2. **Why praise Night, not Vishnu?** Brahmā knows Vishnu cannot wake till Yoganidrā withdraws from His senses. So he praises Mahāmāyā directly as Vaiṣṇavī-śakti (Viṣṇu’s own power), viśva-bīja (seed), sammohinī + mukti-hetu (same power binds/liberates — preview of dm-1-54). Lists Mahāvidyā/Medhā/Smṛti/Mohā: knowledge-memory-delusion are one Mother’s faces.
3. **For beginners**: When higher will sleeps, don’t fight inertia directly; pray to the Sleep itself to lift. This is śaraṇāgati logic of whole Caṇḍī.

---
**Seven-Commentary Digest:**
Medhas's cosmological answer - Vishnu asleep in yoga-nidra on the causal waters, Brahma emerging from the navel-lotus, Madhu and Kaitabha born from ear-wax - receives the heaviest doctrinal commentary in the chapter, since it is here the text first names Yoganidra as Mahamaya, identifying the 'sleep' itself as the Goddess. Pradipa treats this identification as the chapter's real thesis: the same power that puts the cosmic Vishnu to sleep also keeps ordinary beings 'asleep' to their true nature, so cosmology and psychology are one continuous teaching, not two separate topics. Guptavati, closer to its tantric roots, cross-references this Yoganidra directly with the Mahakali form invoked later in the Kavaca and Ratri-sukta, building an explicit continuity across the text's different layers. Nagojibhatti works through the compound descriptions of Madhu-Kaitabha's demonic birth with grammatical precision, while the Hindi Candraprabha simplifies the whole passage into a clear creation narrative for readers unfamiliar with the underlying Puranic cosmology.`,
    keyPoints: ["**Sleeping Will**: Vishnu asleep = will withdrawn; demons = sense-residues.", "**Praise the Veil**: To wake God, pray to His veiling power to withdraw.", "**One Power, Two Jobs**: Same Maya deludes and liberates."]
  },
{
    id: 'dm-1-33',
    number: '1.33',
    section: 'Prathama Carita (Brahma-Granthi Bheda / Madhu-Kaiṭabha Vadha)',
    devanagari: "",
    iast: "",
    conceptIds: ['sadhana-samara', 'suratha-samadhi'],
    interpretiveNotes: [{ note: `Guptavati-adi sapta-tika edition (814-pp PDF, per source-provenance table): Adhyaya 1 at PDF pp.116-215. Mula of true v.1.33 at PDF pp.159-160 (tat kim etan mahabhaga yan moho jnaninor api / mamasya ca bhavaty esha vivekandhasya mudhata, iti 33) with its seven glosses at pp.159-160. PDF lineation preserved above — no speaker line (Suratha's question continues), two padas, closing in print.` }, { note: `Tika order on 1.33: (1) Guptavati (vivekandhasya = viveka-cakshusha hinasya va; jnana-ajnanayoh samanadhikaranyam katham iti prashnarthah), (2) Chaturdhari (tatkeneetat-patha fn.), (3) Shantanavi, (4) Nagojibhatti, (5) Jagaccandrachandrika (mantra-count 45: mamasya ca bhavaty esha vivekandhasya mudhata svaha), (6) Damshoddhara, (7) Chandraprabha Hindi. English digest only; verbatim mula not reproduced here.` }],
    translation: `Suratha said: O most fortunate one, what is this — that delusion grips even the two of us, who understand it as delusion? This blindness to our own discrimination — mine and this man's — what could it possibly be?`,
    commentary: `**Sādhana-Samara Commentary:**
Suratha's question sharpens here into its most precise form: not "why do people grieve" in the abstract, but "why do *we*, who can name our own confusion as confusion, remain caught inside it anyway." This is the exact gap between intellectual and embodied knowledge that Medhas's coming teaching on Mahāmāyā will address — the text refuses to let the aspirant believe that correct information alone dissolves attachment.

---
**Seven-Commentary Digest:**
Guptavati's brief note glosses "vivekandhasya" (of one blinded despite discrimination) as the verse's key compound, underscoring that the paradox — knowing and still not-escaping — is being named explicitly rather than left implicit. The commentators broadly agree this verse functions as the direct pivot into Medhas's forthcoming discourse on Mahamaya: everything Suratha and Samadhi have observed about themselves and, in the following verses, about animal behavior, converges on the single question this verse poses.`,
    keyPoints: ["**Knowing Without Escaping**: Naming confusion as confusion still leaves one inside it — information is not transformation.", "**The Precise Gap**: Intellect versus embodiment; Medhas's coming Mahāmāyā teaching addresses exactly this interval.", "**Vivekāndha**: Blindness despite discrimination — the verse coins the seeker's condition as its key compound."]
  },
{
    id: 'dm-1-35',
    number: '1.35-39',
    section: 'Prathama Carita (Brahma-Granthi Bheda / Madhu-Kaiṭabha Vadha)',
    devanagari: "",
    iast: "",
    conceptIds: ['sadhana-samara', 'suratha-samadhi', 'mahamaya'],
    interpretiveNotes: [{ note: `Guptavati-adi sapta-tika edition (814-pp PDF, per source-provenance table): Adhyaya 1 at PDF pp.116-215. Mula of true vv.1.35-39 at PDF pp.162-168 (v.35 pp.162-163, v.36 p.164, v.37 p.165, v.38 p.166, v.39 pp.167-168) with their seven glosses on the same pages. English commentary only; mula not reproduced here.` }, { note: `Tika order on each verse 1.35-39: (1) Guptavati, (2) Chaturdhari, (3) Shantanavi, (4) Nagojibhatti, (5) Jagaccandrachandrika (lobhat pratyupakarayeti 53 on v.39), (6) Damshoddhara, (7) Chandraprabha Hindi. English digest only; verbatim mula not reproduced here.` }],
    translation: `Medhas said: Some creatures are blind by day, others blind by night, and some see equally well both by day and by night. Is it true, then, that among these, only human beings possess knowledge — is that not so? For all creatures — beasts, birds, and deer alike — possess knowledge too. The knowledge that belongs to human beings belongs also to deer and birds; and whatever else is shared between the two kinds is likewise the same in both. Even where such knowledge is present, look at these birds: driven by delusion, though themselves tormented by hunger, they still busy themselves dropping grains of food into the beaks of their young. Human beings too, O tiger among men, feel this same longing toward their children — out of attachment, hoping for some return-benefit. Do you not see this?`,
    commentary: `**Sādhana-Samara Commentary:**
This is Medhas's first move before naming Mahāmāyā directly: he refuses to let Suratha treat human attachment as a uniquely human failing correctable by uniquely human intelligence.
1. **Knowledge Is Not the Cure**: By pointing out that birds and beasts possess their own form of *jñāna* (knowledge) — sight, discrimination, competence in their own domain — and are *still* driven by attachment (feeding starving young at their own expense), Medhas dismantles the assumption that more information or sharper intellect would solve Suratha's grief. If knowledge alone sufficed, animals — who arguably act with less self-deceiving rationalization than humans — would be exempt.
2. **The Starving Bird as Diagnostic Image**: A parent bird, itself hungry, feeding a chick anyway is offered without moral judgment — it is neither praised as virtuous nor condemned as irrational. It is presented as *mechanism*: a universal pattern of attachment-driven action that operates beneath and prior to reasoning, in human and animal alike.
3. **Setting Up Mahāmāyā**: These verses are the necessary groundwork for verse 41's answer — if the pattern is universal across species, it cannot be explained by individual failure of reason; it requires a cosmic-scale explanatory power, which is exactly what Mahāmāyā will be shown to be.

---
**Seven-Commentary Digest:**
Guptavati's notes across this stretch stay close to the letter, mainly confirming that "divandhah" and "ratrav andhah" describe creatures such as certain birds proverbially blind by day or night respectively (a natural-history commonplace the commentary treats as needing no further gloss). The commentators as a group read verses 36-37 as building a formal syllogism: animals possess knowledge; animals still act from attachment; therefore knowledge and freedom-from-attachment are not the same capacity — a structure several of the seven note explicitly prepares the reader for Medhas's forthcoming identification of Mahamaya as the operative cause. The image of birds feeding their young despite their own hunger (v.38) receives comment mainly on the term "kanamokshadritan" (intent on releasing/dropping grains), confirmed by more than one commentator as describing ordinary parental feeding-behavior rather than any more exotic reading.`,
    keyPoints: ["**Knowledge Is Universal**: Beasts, birds and deer all know — human beings hold no monopoly on awareness.", "**Day-Blind, Night-Blind**: Every creature sees in its own element and is blind outside it; standpoint governs sight.", "**Same Hunger, Same Bond**: Care for young driven by hunger binds animal and human alike — one mohā, different scales."]
  },
{
    id: 'dm-1-41',
    number: '1.41',
    section: 'Prathama Carita (Brahma-Granthi Bheda / Madhu-Kaiṭabha Vadha)',
    devanagari: "",
    iast: "",
    conceptIds: ['sadhana-samara', 'mahamaya'],
    interpretiveNotes: [{ note: `Guptavati-adi sapta-tika edition (814-pp PDF, per source-provenance table): Adhyaya 1 at PDF pp.116-215. Mula of true v.1.41 at PDF p.170 (tan natra vismayah karyo yoganidra jagatpateh / mahamaya haresh caitat taya sammohyate jagat, iti 41) with its seven glosses at PDF pp.170-171. PDF lineation preserved above — no speaker line, two padas, closing in print.` }, { note: `Tika order on 1.41: (1) Guptavati (marker only, iti 41), (2) Chaturdhari (yoganidra = paramanandamayi shaktih; jagatpati = mohya-koti-bahirbhava-sucakam), (3) Shantanavi (ca-shabdo hetau; yoga = nishprapancatma-avagama), (4) Nagojibhatti (yoganidra tamah-pradhana shaktih), (5) Jagaccandrachandrika (mahamaya harer iti 55), (6) Damshoddhara, (7) Chandraprabha Hindi. Patha note: haresh caitat (print) = haresh caisha taya (Shantanavi-sammata). English digest only; verbatim mula not reproduced here.` }],
    translation: `So no wonder need be made of this — this pattern is itself the Yoganidrā of the Lord of the world; She is the very Mahāmāyā of Hari, and by Her the universe is deluded.`,
    commentary: `**Sādhana-Samara Commentary:**
The naming happens here, plainly: what has just been demonstrated across birds, beasts, and both grieving men is not scattered coincidence but the single operation of one power — Mahāmāyā, Hari's own Yoganidrā. This verse retroactively reframes everything since verse 30: Viṣṇu's cosmic sleep and Suratha's inexplicable grief are shown to be the very same force, operating at different scales, cosmic and personal, without any real distinction between them.`,
    keyPoints: ["**No Wonder Needed**: The pattern itself is Her — Yoganidrā, the Mahāmāyā of Hari, by whom the universe is deluded.", "**Sleep as Goddess**: Cosmic sleep is not absence but a Person — the first naming of the veil as divine.", "**Cause Located**: Suratha's 'what is this?' receives its single source before the battle-narrative resumes."]
  },
{
    id: 'dm-1-43',
    number: '1.43',
    section: 'Prathama Carita (Brahma-Granthi Bheda / Madhu-Kaiṭabha Vadha)',
    devanagari: "",
    iast: "",
    conceptIds: ['sadhana-samara', 'mahamaya'],
    interpretiveNotes: [{ note: `Guptavati-adi sapta-tika edition (814-pp PDF, per source-provenance table): Adhyaya 1 at PDF pp.116-215. Mula of true v.1.43 at PDF pp.171-172 (taya visrijyate vishvam trailokyam sacaracaram / saisha prasanna varada nrinam bhavati muktaye, iti 43) with its seven glosses at PDF pp.171-172. PDF lineation preserved above — no speaker line, two padas, closing in print.` }, { note: `Tika order on 1.43: (1) Guptavati (marker only, iti 43), (2) Chaturdhari (mulaprakriti-rupa; bandha-karana api prasanna sati muktaye), (3) Shantanavi (akara-prashlesha: taya avisrijyate na tyajyate kintu rakshyate; cara-acara viveka with Rudrakosha), (4) Nagojibhatti (mohan-karanam api upasanadibhih prasanna mokshaya varada), (5) Jagaccandrachandrika (saisha prasanneti 57), (6) Damshoddhara (akara-prashlesha; amanona pratishedhe), (7) Chandraprabha Hindi. Patha note: jagad etac caracaram iti kvacit-pathah. English digest only; verbatim mula not reproduced here.` }],
    translation: `By Her, this universe — the triple world together with all that moves and does not move — is brought forth; and this very Goddess, when gracious, becomes the bestower of boons and the cause of liberation for human beings.`,
    commentary: `**Sādhana-Samara Commentary:**
The same power that binds (v.41) is here shown, without contradiction, to also liberate. This is the verse's real weight: Mahāmāyā is not one force among two — a binding power balanced by a separate liberating one — but a single power whose direction (bondage or freedom) depends entirely on Her own grace (*prasannā*) rather than on any technique the aspirant alone can force. This is the theological seed that the whole rest of the *Devī Māhātmya* — six more chapters of praise, request, and surrender — will spend itself elaborating.`,
    keyPoints: ["**One Power, Two Jobs**: The same Goddess brings forth the triple world and, when gracious, becomes the cause of liberation.", "**Grace as Causality**: Bondage and freedom share one author — fortune turns on Her favour, not on technique alone.", "**Bhoga and Mokṣa, One Hand**: Boons and liberation both hers — enjoyment and freedom from the same giver."]
  },
{
    id: 'dm-1-44',
    number: '1.44-52',
    section: 'Prathama Carita (Brahma-Granthi Bheda / Madhu-Kaiṭabha Vadha)',
    devanagari: "",
    iast: "",
    conceptIds: ["mahamaya","cit-shakti","madhu-kaitabha","sadhana-samara"],
    interpretiveNotes: [{ note: `Guptavati-adi sapta-tika edition (814-pp PDF, per source-provenance table): Adhyaya 1 at PDF pp.116-215. Mula of true vv.1.44-52 at PDF pp.173-184 (v.44 p.173, v.45 p.174, v.46 p.175, v.47 p.176, v.48 p.177, v.49 pp.178-179, v.50 p.180, v.51 pp.180-181, v.52 p.182) with their seven glosses on the same pages. PDF lineation preserved above — no speaker line on 44, then Suratha's five questions (vv.45-46) and Medhas's nitya-yet-utpanna resolution (vv.47-48) and eka-arnava narrative (vv.49-52), two padas per verse, closing Devanagari -.` }, { note: `Tika order on each verse 1.44-52: (1) Guptavati (marker only on 44), (2) Chaturdhari (vidya = brahma-jnana-lakshana; avidyavidya-vasaya-nitya-ashuci), (3) Shantanavi (avidya = a-vit sansarika; apara-ma = moksha-lakshmi; chandra iti kim kurmo gatanugatikam jagat fn. on 48), (4) Nagojibhatti, (5) Jagaccandrachandrika (mantra-counts 58-66 across this run), (6) Damshoddhara, (7) Chandraprabha Hindi. English digest only; verbatim mula not reproduced here.` }],
    translation: `Medhas said: “She is Knowledge itself — the eternal, unsurpassed ground of liberation — and She alone is also the ground of worldly bondage, the Empress of all lords. Lord, who indeed is this Goddess whom you call Mahāmāyā? How was She born, what are Her deeds, O twice-born? What is Her power, what Her nature, what Her origin — all that I wish to hear from you, O best of Brahman-knowers. She is eternal, the very form of the world, by whom all this is pervaded — yet hear from me Her manifold birth. Whenever, to accomplish the gods’ purpose, She manifests — though eternal — She is then said in the world to be ‘born.’ When, at the aeon’s end, Lord Viṣṇu embraced sleep as Yoga-nidrā, spreading His serpent-couch upon the world turned into a single ocean — then two dread demons, famed as Madhu and Kaiṭabha, born of Viṣṇu’s ear-wax, rose to slay Brahmā. Brahmā Prajāpati, seated on Viṣṇu’s navel-lotus, seeing those fierce demons and Janārdana sunk in sleep — with one-pointed heart he praised Yoganidrā, Her who dwells in Hari’s very eyes, so that (Viṣṇu) would wake.”`,
    commentary: `**Sādhana-Samara Commentary (Vidyā and avidyā are one Mother, beginner-full):**
1. **The whole Śākta creed in one verse (ed44)**: sā vidyā — She is liberating Knowledge; saṃsāra-bandha-hetu — She is also binding ignorance. One Cit-Śakti wears both faces (dm-1-54’s avidyā/vidyā-rūpa drawn out). Nāgojī and Guptavatī stress: She is sarveśvareśvarī — even Brahmā-Viṣṇu-Śiva are Her instruments, not Her masters.
2. **The disciple’s five questions (ed45-46)**: who is She? how born? what deeds? what power? what nature? what origin? Worldly curiosity asks for stories; adhikāra asks for tattva. Note the paradox Medhas will resolve (ed47-48): nityā (eternal) yet utpannā (born) — birth means manifestation for the gods’ work (avatāra-līlā), as Candraprabhā explains: the eternal sun is “born” each dawn for the seer’s eyes.
3. **Cosmic sleep and ear-wax demons (ed49-51)**: ekārṇava (single ocean) = consciousness undifferentiated; Viṣṇu (all-pervading Will) asleep = divine activity withdrawn; lotus-Brahmā = creative aspiration just sprouting; karṇa-mala (ear-wax) = stale hearing-habits, unexamined mental secretions. Madhu (sweet inertia) and Kaiṭabha (crooked obstinacy) attack aspiration at birth — the first battle every meditator knows: sleepiness and self-will strangling a fresh resolve.
4. **Praise, not fight (ed52)**: Brahmā cannot fight or wake Viṣṇu by force; with one-pointed heart (ekāgra — the whole sādhanā in one word) he praises the Sleep Herself dwelling in Hari’s eyes. Rule for beginners: when higher will sleeps, worship the veiling power to withdraw — śaraṇāgati, not struggle. Next (dm-1-66 existing): the great Brahma-stuti.

---
**Seven-Commentary Digest:**
The celebrated 'Ya devi sarva-bhuteshu... nidra-rupena samsthita' formula begins to take shape around this point, and here Medhas defines the Goddess philosophically as Vidya (true knowledge) who is simultaneously the cause of liberation and, in her other aspect, the cause of bondage - a paradox every commentator treats with real care since it forecloses any reading of Devi as simply benevolent in a narrow sense. Pradipa insists the two aspects (bandha and moksha) are not contradictory but sequential expressions of the same undivided power, comparable to how a single fire both burns and cooks depending on how it is used. Nagojibhatti's notes work through the precise philosophical vocabulary (mahamaya, avidya, vidya) to keep the passage consistent with Vedantic usage elsewhere in the commentarial tradition, while Guptavati links the passage forward to the Devi-sukta's more famous enumeration of the Goddess as the many faculties residing within all beings. The Hindi rendering keeps the paradox intact rather than softening it, true to the source.`,
    keyPoints: ["**One Mother, Two Works**: The same Mahamaya liberates as Vidya and binds as ignorance.", "**Eternal Yet Born**: Nitya-Mother “takes birth” as avatara whenever the gods’ (faculties’) work demands.", "**Ear-wax Demons**: Stale sense-habits attack fresh aspiration; praise — not force — wakes the sleeping Will."]
  },
{
    id: 'dm-1-54',
    number: '1.42-43 (numbered 1.54-55 in some vulgate editions)',
    section: 'Prathama Carita (Brahma-Granthi Bheda / Madhu-Kaiṭabha Vadha)',
    devanagari: "",
    iast: "",
    conceptIds: ["mahamaya","cit-shakti"],
    interpretiveNotes: [{ note: `Guptavati-adi sapta-tika edition (814-pp PDF, per source-provenance table): Adhyaya 1 at PDF pp.116-215. This entry preserves the vulgate mantra-ganana numbering 1.54-55 for what the print counts as true vv.1.42-43 (jnaninam api cetamsi ... baladakrishya ... / taya visrijyate vishvam ... saisha prasanna ...); true mula at PDF pp.171-172 with seven glosses pp.171-172. PDF lineation preserved above — no speaker line, two padas per verse. The 42-43 vs 54-55 variance is manuscript-tradition numbering (uvaca counted as mantras), not a different text; translation and Sadhana-Samara alignment are untouched.` }, { note: `Tika order on true vv.1.42-43: (1) Guptavati (jnaninam api = kevalinam api), (2) Chaturdhari, (3) Shantanavi, (4) Nagojibhatti (apakva-kashayanam yoginam api sa mohika), (5) Jagaccandrachandrika (baladakrishyeti 56; saisha prasanneti 57), (6) Damshoddhara, (7) Chandraprabha Hindi. English digest only; verbatim mula not reproduced here.` }],
    translation: `Sage Medhas replied: "She, the blessed Goddess Mahāmāyā, forcibly draws even the minds of the wise and casts them into delusion! By Her this entire moving and unmoving universe is projected. And She alone, when propitiated with devotion, becomes the bestower of boons and grants supreme liberation!"`,
    commentary: `**Sādhana-Samara Commentary:**
This is the foundational aphorism of the Śākta worldview. *Mahāmāyā* is not an accidental blemish, nor is She inert illusion (*Mithyā* in the sense of an absolute void). She is *Bhagavatī*—the conscious sovereign power (*Cit-Śakti*) of the Supreme Divine. 
Her power operates in two modes:
1. *Avidyā-Rūpa* (The Veiling Power): Forcibly drawing even contemplative minds outward into the cosmic drama (*Balād-ākṛṣya*).
2. *Vidyā-Rūpa* (The Unveiling Grace): When worshipped not as external world-matter but as the Mother-Consciousness, She turns Her gaze (*Prasannā*) and dissolves all bondages, granting *Mukti*. 
Hence, the spiritual aspirant must not combat Nature as an enemy, but propitiate Her as the affectionate Divine Mother who holds the keys to liberation.

---
**Seven-Commentary Digest:**
This verse describes Mahamaya's power to overwhelm even the minds of the wise, and Pradipa uses it to address a natural objection: if even sages and gods can be deluded, what use is spiritual effort at all? Its answer is that delusion here is not permanent defeat but a recurring condition that makes grace, not self-effort alone, necessary - precisely the argument that justifies the entire Saptashati as a text of supplication rather than pure philosophy. Caturdhari and Santanavi note the verse's placement immediately before Brahma's request that the gods together approach the sleeping Vishnu, reading verses 42-55 as a single connected unit rather than isolated statements. The editorial note in this edition on the verse-numbering discrepancy (some vulgate texts count these as 1.42-43, others as 1.54-55) is itself flagged by the editor as a manuscript-tradition variance worth noting for readers cross-referencing other printed editions.`,
    keyPoints: ["**Forceful Cosmic Delusion (*Balādākṛṣya*)**: Maya is a cosmic sovereign law, impossible to overcome by individual egoic will alone.", "**Dual Function of Mahamaya**: She who binds the universe is the exact same Supreme Power who liberates."]
  },
{
    id: 'dm-1-55',
    number: '1.55-58',
    section: 'Prathama Carita (Brahma-Granthi Bheda / Madhu-Kaiṭabha Vadha)',
    devanagari: "",
    iast: "",
    conceptIds: ["cit-shakti","madhu-kaitabha","sadhana-samara"],
    interpretiveNotes: [{ note: `Guptavati-adi sapta-tika edition (814-pp PDF, per source-provenance table): Adhyaya 1 at PDF pp.116-215. Mula of true vv.1.53-58 Brahma-stuti opening at PDF pp.182-192 (v.53 pp.182-183 Vishveshvari, v.54 pp.184-186 Svaha-Svadha, v.55 pp.187-189 Ardhamatra-Savitri, vv.56-57 p.190 Dharyate-Srijyate, v.58 p.192 Mahavidya). This digest entry highlights vv.55-58; PDF lineation for the highlighted padas is preserved above — brahmovaca speaker line into the hymn, two padas per verse.` }, { note: `Tika order on each verse 1.53-58: (1) Guptavati, (2) Chaturdhari, (3) Shantanavi (ardhamatra = avyakta turiya; yato vaco nivartante; gandhari-gandhara-svara), (4) Nagojibhatti, (5) Jagaccandrachandrika (mantra-counts 67-80 across this hymn opening), (6) Damshoddhara, (7) Chandraprabha Hindi. English digest only; verbatim mula not reproduced here; the entry's highlight selection, translation and Sadhana-Samara alignment are untouched.` }],
    translation: `You are the eternal half-measure that cannot be uttered even by those who know its special nature; You alone are the Sāvitrī, and You, O Goddess, are the supreme Mother. By You this universe is held, by You this world is brought forth, by You, O Goddess, it is sustained, and always, at the end, You consume it. In emanation You are the form of creation, in maintenance the form of preservation, and likewise, at the end of this world, the form of dissolution, O You who pervade the universe. You are Mahāvidyā, Mahāmāyā, Mahāmedhā, Mahāsmṛti; You are Mahāmoha, and You are Mahādevī, the great demoness (to the demonic) and the great Goddess (to the divine).`,
    commentary: `**Sādhana-Samara Commentary:**
Having named Herself through the mantra-syllables in the previous verse, the Goddess now names Herself through cosmic *function*. This is the transition from Her identity as sound (śabda-tattva) to Her identity as world-process (jagat-tattva).
1. **The Unutterable Half-Measure (Ardhamātrā)**: Beyond the three audible mātrās of AUM (A-U-M) lies a fourth, silent half-measure — the *turīya*, the witness-state underlying waking, dream, and deep sleep. Devī is identified with precisely this silence beyond speech: the substratum that no mantra can fully capture, because it is what listens even to the mantra.
2. **The Threefold Verb (Dhāryate/Sṛjyate/Pālyate/Atsi)**: Four verbs — held, created, sustained, consumed — collapse the entire cosmic cycle into a single breath. This is deliberately economical: where earlier verses distributed creation-preservation-dissolution across Brahmā-Viṣṇu-Rudra, here all three collapse back into the single undivided Devī who was always their common ground.
3. **The Four Mahā-Names**: Mahāvidyā (great knowledge), Mahāmāyā (great illusion), Mahāmedhā (great intellect), Mahāsmṛti (great memory), and Mahāmoha (great delusion) are given in one breath without contradiction. The text refuses to let the sādhaka settle into an easy division between Devī's "good" liberating powers and Her "bad" binding ones — both are named Mahā (great), both are Her, and spiritual maturity is precisely the capacity to see this without flinching.

---
**Seven-Commentary Digest:**
On verse 55, Santanavi is unusually expansive, working through several proposed derivations of "ardhamatra" - as the unvoiced half-beat completing the syllable Om, as the fourth, unspoken measure standing for the turiya state itself, and as "that which cannot be reached by words, which turn back from it together with the mind," explicitly invoking the Taittiriya Upanishad's language of the unreachable. Nagojibhatti's note here simply directs the reader back to its own remarks on the previous verse, treating 55 as a continuation of the same argument rather than a fresh topic - a sign the commentators read 54-55 as one philosophical unit. Guptavati keeps to the essentials: Savitri is glossed as the Gayatri mantra's presiding deity, "janani para" as the supreme mother precisely because, unlike ordinary mothers who beget only "this or that" limited offspring, she alone brings forth everything without exception. On verses 56-57, several commentators (Chaturdhari, Nagojibhatti) read the three verbs - dharyate, srjyate, palyate, atsi - as a direct restatement of Brahma-Vishnu-Rudra's three functions now reclaimed by the single Devi who underlies all three, with Santanavi spelling this out explicitly: creation by her Brahmi shakti, protection by her Vaishnavi shakti, dissolution by her Raudri shakti, three names for one undivided power. Verse 58's four "Maha-" names receive comparatively brief individual glosses (mostly grammatical formation notes) from Guptavati and Damsoddhara, with the commentators letting the verse's own accumulating rhythm - vidya, maya, medha, smrti, moha - carry its meaning without heavy interpretive overlay; the Hindi Candraprabha follows this same restrained approach, translating each name plainly in sequence.`,
    keyPoints: ["**Ardhamātrā**: The eternal half-measure even knowers of its nature cannot utter — sound's edge where speech fails.", "**Sāvitrī as Mother**: The Gāyatrī-source named supreme Mother — mantra and maternity are one power.", "**Held, Born, Sustained**: By Her the universe is held, brought forth and maintained — and at the end, reabsorbed."]
  },
{
    id: 'dm-1-59',
    number: '1.59-63',
    section: 'Prathama Carita (Brahma-Granthi Bheda / Madhu-Kaiṭabha Vadha)',
    devanagari: "",
    iast: "",
    conceptIds: ["cit-shakti","madhu-kaitabha","sadhana-samara"],
    interpretiveNotes: [{ note: `Guptavati-adi sapta-tika edition (814-pp PDF, per source-provenance table): Adhyaya 1 at PDF pp.116-215. Mula of true vv.1.59-63 at PDF pp.193-199 (v.59 p.193 Kalaratri, v.60 p.194 Shri-Hri, v.61 pp.195-196 Khadgini weapon catalogue, v.62 pp.197-198 Saumya, v.63 pp.198-199 Sat-asat) with their seven glosses on the same pages. PDF lineation preserved above — Brahmovaca continues, two padas per verse.` }, { note: `Tika order on each verse 1.59-63: (1) Guptavati (para = Brahmadayah, apara = Shakradayah on 62), (2) Chaturdhari, (3) Shantanavi (saumya = soma-daivatika / su-ma-lakshmika / uma-pati; sat = vartamana / nityam akasha-paramanu, asat = atitanagata / anityam prithivyadi), (4) Nagojibhatti (Dashavaktra-Dashabhuja Vaikritika-rahasya quote on 61; sat = Brahma-vargah, asat = jada-vargah on 63), (5) Jagaccandrachandrika (81 on 61, 82 on 62, 83 on 63), (6) Damshoddhara, (7) Chandraprabha Hindi. English digest only; verbatim mula not reproduced here.` }],
    translation: `You are Prakṛti itself, manifesting the three guṇas of everything; You are Kālarātri, Mahārātri, and dreadful Moharātri. You are Śrī, You are sovereignty itself, You are Hrī (modesty as power), You are intellect whose nature is understanding; You are shame, nourishment, contentment, peace, and endurance. Bearing a sword, a trident, terrible, bearing a mace, a discus, a conch, a bow, arrows, a spear, and an iron club as weapons; gentle, and more gentle than all gentle things, exceedingly beautiful beyond compare, You alone are the supreme among the high and low, the Supreme Sovereign. Whatever thing, existent or non-existent, exists anywhere, O all-pervading One, You are the power of all of that — so how, then, could You possibly be praised in full?`,
    commentary: `**Sādhana-Samara Commentary:**
This is the great catalogue-hymn at the philosophical center of the *turīya*-praise: every register of existence — cosmic (Prakṛti), temporal (the three Rātris), ethical (Śrī, Hrī, Lajjā), martial (the nine weapons), aesthetic (saumyā, sundarī), and finally ontological (sat/asat, existent/non-existent) — is named as Her form, before the hymn admits its own impossibility.
1. **The Weapon-List as Interior Map**: Sword, trident, mace, discus, conch, bow, spear, club — nine implements corresponding, in the *sādhanā* reading, to nine faculties of discrimination the aspirant must develop: cutting through doubt (sword), piercing delusion (trident/śūla), and so on. The Goddess is not merely armed for external battle; every weapon is first forged in the practitioner's own inner life.
2. **The Turn to Impossibility**: The final couplet is the hymn's hinge and its humility: having just listed everything nameable, Brahmā concedes that *any* enumeration is structurally incomplete, since Devī is not one item among the list but the very power (*śakti*) by which the list itself, and everything in it — real or unreal — exists at all. This single verse is often cited as the *Devī Māhātmya*'s clearest statement that Devī-praise can never be exhaustive, only gestural.

---
**Seven-Commentary Digest:**
Pradipa gives its fullest attention in this stretch to the weapon-catalogue of verse 61, tracing each named implement to the specific deity said elsewhere in the text to have gifted it - tying this verse forward to the weapon-donation scene of chapter 2 - and reading the accumulation as proof that Devi's martial capacity was never borrowed for a single occasion but is intrinsic to her nature from the very moment of her praise in chapter 1, well before Mahisha's war even begins. Nagojibhatti and Damsoddhara divide their notes mainly between resolving compound formations (guna-traya-vibhavini, sad-asad-vakhilatmike) and confirming variant readings found across manuscript traditions. Santanavi reads the qualities of verse 60 - Sri, Hri, buddhi, lajja, pusti, tusti, shanti, kshanti - as together constituting a complete inventory of what classical thought calls the sattvika endowments of a well-formed mind, so that the verse quietly instructs the sadhaka in what inner qualities to cultivate even while ostensibly describing the Goddess. On the closing verse's rhetorical question "how then are you to be praised," Guptavati and the Hindi Candraprabha agree this is not despair but the hymn's deliberate self-undercutting - a device meant to humble the one praising rather than to diminish the object of praise, consistent with apophatic gestures found elsewhere in Puranic stotra literature.`,
    keyPoints: ["**Prakṛti of the Guṇas**: She manifests the three guṇas of everything — Sāṃkhya's evolute owned as Goddess.", "**Three Nights**: Kālarātri, Mahārātri, dread Moharātri — time's dread faces gathered into Her.", "**Virtues as Powers**: Śrī, Hrī, intellect, shame, nourishment, contentment, peace — excellences are Her, not ornaments."]
  },
{
    id: 'dm-1-64',
    number: '1.64-67',
    section: 'Prathama Carita (Brahma-Granthi Bheda / Madhu-Kaiṭabha Vadha)',
    devanagari: "",
    iast: "",
    conceptIds: ["cit-shakti","madhu-kaitabha","sadhana-samara"],
    interpretiveNotes: [{ note: `Guptavati-adi sapta-tika edition (814-pp PDF, per source-provenance table): Adhyaya 1 at PDF pp.116-215. Mula of true vv.1.64-67 closing petition at PDF pp.199-201 (v.64 p.199 yaya tvaya, v.65 p.199-200 vishnuh sharira-grahanam, v.66 p.200 mohayaitau, v.67 p.201 prabodham ca) with their seven glosses on the same pages. PDF lineation preserved above — Brahmovaca continues, two padas per verse.` }, { note: `Tika order on each verse 1.64-67: (1) Guptavati (marker only on 64), (2) Chaturdhari (jagat-srashta Brahmakarena, jagat-pata Vishnu-rupena, jagad-atti Rudratmana), (3) Shantanavi (trin-anta / lud-anta, jagat-pata iti patha; vasha = iccha-yantranayoh pumsi prabhutve), (4) Nagojibhatti (tamoguna-pradhana-maya-sambandhat), (5) Jagaccandrachandrika (so'pi nidreti 84 on 64; bodhash ca kriyatam madhya-mantra sequence), (6) Damshoddhara, (7) Chandraprabha Hindi. Patha notes: jagat-patyatti / jagat-pata; vishnuh sharira-grahanam karitah causative. English digest only; verbatim mula not reproduced here.` }],
    translation: `He by whom, through You, the universe is created, protected, and consumed — even he has been brought under the sway of sleep by You; who, then, has the power here to praise You? By You, Viṣṇu was made to take on a body, and I, the Lord (Brahmā), likewise — since even we were made so by You, who could possibly be capable of praising You? You who are thus praised, O Goddess, by Your own boundless powers — now delude these two unassailable demons, Madhu and Kaiṭabha. And let the Lord of the universe, unfallen Viṣṇu, be swiftly brought to wakefulness, and let his awareness be roused, so that he may slay these two great demons.`,
    commentary: `**Sādhana-Samara Commentary:**
The hymn closes not with abstraction but with a direct, urgent petition — the *sādhaka*'s truest posture.
1. **Even the Creator Cannot Praise Her**: Brahmā's confession — "even Viṣṇu who sustains and dissolves the universe is himself under Your sway; even I, who was made to exist by You, cannot truly praise You" — is the hymn's final act of humility. Praise (*stuti*) here is revealed as an act performed *within* Devī's power, never one performed *upon* Her from some outside vantage. This dissolves the subject-object structure of ordinary worship: there is no one standing apart from Her from whom praise could originate.
2. **From Philosophy Back to Action**: The final couplet snaps back from metaphysics to the concrete emergency at hand — Madhu and Kaiṭabha must be deluded, and Viṣṇu must wake. This is the hymn's essential teaching for the practitioner: the highest philosophical realization (*jñāna*) does not replace decisive action (*karma*) but must resolve into it. Brahmā does not remain absorbed in awe; he asks, precisely, for the demons' delusion and the Lord's awakening — the necessary next step of the *sādhana*.

---
**Seven-Commentary Digest:**
Pradipa treats verses 64-65 - where Brahma admits that even Vishnu's cosmic function and his own existence as creator were "caused" by Devi - as the hymn's decisive theological claim, since it places Brahma and Vishnu, the two great gods of the earlier cosmology, explicitly downstream of Devi's causal power rather than beside her; several commentators note this is the strongest non-dual statement in chapter 1, anticipating the still bolder declaration Devi herself will make in chapter 10. Nagojibhatti's notes work through the causative constructions (karitah, literally "were made to do") with technical precision, since the grammar itself carries the theological weight - Brahma is not saying Devi assisted him, but that she is the agent behind his very agency. On the closing petition of verses 66-67, Chaturdhari and the Hindi Candraprabha both mark the shift in register from praise to request as the natural and necessary conclusion of any stotra in this tradition - a hymn that only praised without asking would, in the ritual logic these commentators assume throughout, be considered incomplete. Jagaccandracandrika's mantra-count notes conclude their running tally here, marking this as the close of the hymn-unit before the narrative resumes with Devi's answer to Brahma's request in the verses that follow.`,
    keyPoints: ["**Even He Sleeps**: Creator, preserver, consumer move only by Her — Viṣṇu himself lies under the sway of Her sleep.", "**Praise Disarmed**: If the gods are Her instruments, what power has the praiser? — humility itself as method.", "**Office as Gift**: Viṣṇu's embodied form and Brahmā's lordship both made by Her — rank itself is Her doing."]
  },
{
    id: 'dm-1-66',
    number: '1.53-54 (numbered 1.66-67 in some vulgate editions)',
    section: 'Prathama Carita (Brahma-Granthi Bheda / Madhu-Kaiṭabha Vadha)',
    devanagari: "",
    iast: "",
    conceptIds: ["cit-shakti","madhu-kaitabha","sadhana-samara"],
    interpretiveNotes: [{ note: `Guptavati-adi sapta-tika edition (814-pp PDF, per source-provenance table): Adhyaya 1 at PDF pp.116-215. This entry preserves the vulgate mantra-ganana numbering 1.66-67 for what the print counts as true vv.1.53-54 (vishveshvarim jagaddhatrim ... nidram bhagavatim / tvam svaha tvam svadha ... tridha matratmika sthita); true mula at PDF pp.182-186 with seven glosses pp.182-186. PDF lineation preserved above — rishi-vakya into brahmovaca speaker line, two padas per verse. The 53-54 vs 66-67 variance is mantra-ganana numbering (uvaca counted), not a different text; translation and Sadhana-Samara alignment are untouched.` }, { note: `Tika order on true vv.1.53-54: (1) Guptavati, (2) Chaturdhari, (3) Shantanavi (vishveshvari-sukta = ratri-sukta; kalaratrir maharatrir iti ratri-padabhyasat), (4) Nagojibhatti (vishveshvari-padenopakramat vishveshvari-suktam; asya devyah samutpattish caritam stotram iti), (5) Jagaccandrachandrika (mantra-counts 67-70), (6) Damshoddhara, (7) Chandraprabha Hindi. English digest only; verbatim mula not reproduced here.` }],
    translation: `Lord Brahmā praised Her, the Queen of the cosmos, the supporter of the worlds, the cause of preservation and destruction, the peerless Yoga-Nidrā of Lord Viṣṇu: "You are Svāhā, You are Svadhā, You are the sacred Vaṣaṭkāra; You are the imperishable nectar of the Threefold Sacred Syllables (A-U-M)!"`,
    commentary: `**Sādhana-Samara Commentary:**
*Prathama Carita* represents **Brahma-Granthi Bheda** (piercing the knot of inertia and initial cosmic creation).
1. **Relationship to the Bhagavad Gītā**: The Bhagavad Gītā forms the golden foundation (*Akṣaya-bhitti*) of spiritual life, representing the sādhana of the mental sheath (*Manomaya Koṣa*). The *Devī Māhātmya* is the incomparable palace (*Prāsāda*) erected atop it, representing the sādhana of the wisdom sheath (*Vijñānamaya Koṣa*). In the Gītā one bathes in the ocean of Brahman; in Caṇḍī one achieves total, indivisible merger with the Divine Mother.
2. **Madhu and Kaiṭabha**: Emerged from the ear-wax of Viṣṇu (the subtle secretions of auditory and mental sensory impressions). *Madhu* represents the sweet, seductive inertia of the senses (*Tamas* disguised as pleasure). *Kaiṭabha* represents violent, rigid ego-obstinacy (*Rajas*). Together they attempt to devour Brahmā (spiritual aspiration).
3. **Yoga-Nidrā**: Viṣṇu cannot awaken until *Yoga-Nidrā*—the conscious withdrawal of Godhead—is praised and drawn out from His senses. When the Divine Will awakens, the demons are slain upon His thighs (firm spiritual grounding).

---
**Seven-Commentary Digest:**
Brahma's direct hymn of praise to the sleeping Goddess, asking her to release Vishnu from yoga-nidra, is treated by Pradipa as the first instance in the text of a deva addressing Devi as supreme rather than as subordinate consort or shakti of a male deity - a theological move the commentary treats as the Saptashati's foundational claim. Guptavati cross-references the praise-vocabulary here with formulas used later in the great Devi-sukta of chapter 5, suggesting the text is deliberately training the reader's ear for the fuller hymn to come. Nagojibhatti resolves several compound epithets describing the Goddess as simultaneously world-supporter and world-dissolver, insisting the grammar supports reading both functions as literally simultaneous, not sequential. The Hindi Candraprabha keeps the register devotional, letting the hymn read as prayer rather than argument, appropriate to its function within the narrative as an actual invocation Brahma is uttering.`,
    keyPoints: ["**Brahma-Granthi Bheda**: Overcoming the first great knot of primal ignorance and inertia.", "**Gītā and Caṇḍī**: The Gītā prepares the mind; Caṇḍī dissolves individual authorship into the Mother's dynamic power.", "**Madhu and Kaiṭabha**: Slaying sensual sweetness and mental obstinacy."]
  },
{
    id: 'dm-1-85',
    number: '1.85-104',
    section: 'Prathama Carita (Brahma-Granthi Bheda / Madhu-Kaiṭabha Vadha)',
    devanagari: "",
    iast: "",
    conceptIds: ["madhu-kaitabha","mahamaya","sadhana-samara"],
    interpretiveNotes: [{ note: `Guptavati-adi sapta-tika edition (814-pp PDF, per source-provenance table): Adhyaya 1 at PDF pp.116-215. This digest entry highlights the battle close (true vv.1.68-78) from the full close at PDF pp.201-211 (v.68 p.201 vishnoh prabodhanarthaya, vv.69-70 p.203, v.71 p.204 krodha-rakta, v.72 pp.205-206 panca-varsha-sahasrani bahu-praharanah, v.73 p.206 tavapyatibalonmattau, v.74 p.207 bhavetam adya me, v.75 p.208 vancitabhyam, v.76 pp.209-210 avam jahi na yatrovi, v.77 pp.210-211 tathen, v.78 pp.211-212 evam esha samutpanna) with seven glosses per verse, plus Adhyaya-colophons and mantra-vibhaga at pp.212-215. PDF lineation for the highlighted padas is preserved above — rishiruvaca / bhagavanuvaca speaker lines, two padas per verse. The 85-104 numbering is mantra-ganana (78 shlokas + uvaca = 104: shlokanam ashtasaptatyash caturbhir adhikam shatam uvaca-vacanaih sardham, Jagaccandra p.213); translation and Sadhana-Samara alignment are untouched.` }, { note: `Tika order on each verse 1.68-78: (1) Guptavati (bahupraharanottaram dvau shlokau kvacit pathyete fn. on 72; janghane tatra jalabhavat on 77; mantra-vicara with apekshan-anapeksha caturvidha on 78), (2) Chaturdhari, (3) Shantanavi, (4) Nagojibhatti (saptashati-mantra-sankhya-puraniyataya uktih on 77; shuddha-mayikatva on 78 with Lakshmi-tantra Yoganidra quote), (5) Jagaccandrachandrika (mantra-counts 93-104: krodharakta 93, panca-varshe 94, uktavantau 95, bhagavanuvaca 96-98, rishir 99-102, avam jahi 101, tathen 103, evam esha 104; plus vibhaga karikas pp.213-214), (6) Damshoddhara/Damshoddhara, (7) Chandraprabha Hindi. English digest only; verbatim mula not reproduced here.` }],
    translation: `Thus praised, dark Night withdrew from Viṣṇu’s eyes-mouth-nostrils-arms-heart-breast and showed Herself to Brahmā. Freed, the Lord rose, left Yoga-sleep, fought the demons 5000 years arm-to-arm. Drunk with power, deluded by Mahāmāyā, they told Viṣṇu “ask a boon!” Smiling He said “be slain by Me — what other boon?” Seeing world flooded, they said “slay where earth is not flooded.” “So be it,” He placed them on His thighs and beheaded them with discus. Thus was Night born of Brahmā’s praise.`,
    commentary: `**Sādhana-Samara Commentary:**
1. **Withdrawal through senses**: Yoganidrā exits exactly where She entered — eyes (seeing), mouth-nose (tasting-breathing), arms-heart-breast (grasping-feeling). Sādhanā reverses this: withdraw Mother-power from outer sensing to awaken Will.
2. **5000-year arm-fight**: No outer weapon works on deep inertia-obstinacy; only prolonged self-effort (bāhu-yuddha) matures. Deluded by Mahāmāyā they offer a boon to their foe — ego blinded offers its neck. Viṣṇu’s smile (vihasya) = compassion, not mockery.
3. **Thighs (jaghana) trick**: “Not flooded” = firm ground beyond flux. Thighs = grounded tapas, ethical seat. Placing demons on thighs = bringing tamas-rajas onto firm practice-ground, then discus (sudden viveka-chakra) severs heads (ego-centres). Brahma-granthi pierced; tamas lifts; higher awareness stirs. Here ends Prathama Carita (Mahākālī).

---
**Seven-Commentary Digest:**
The climactic verses in which Night personified withdraws from Vishnu's body and Madhu-Kaitabha are finally slain receive close attention for the curious detail that the demons are killed 'on Vishnu's thighs', a detail Pradipa explains through the Puranic account (also referenced earlier in the commentary) that the demons, boon-protected from dying on land or water, are tricked into being slain on ground that is technically neither. Guptavati and Nagojibhatti both linger on this etymological point since it resolves an apparent narrative oddity that a casual reading might miss. The Hindi Candraprabha explains the trick plainly for readers unfamiliar with the boon's exact wording. Every commentator treats this episode as establishing the template the entire text will repeat: an apparently invincible demon is not defeated by superior force alone but by a wisdom that finds the exact condition his own boon left unguarded - a pattern that recurs, in different form, against Mahisha and later Shumbha-Nishumbha.`,
    keyPoints: ["**Sense-withdrawal**: Night leaves eyes-mouth-heart — reverse sensing to wake Will.", "**Long Arm-fight**: Deep inertia needs prolonged self-effort, no shortcut weapon.", "**Thigh-ground**: Firm tapas-ground + sudden discus = Brahma-granthi-bheda."]
  }
];
